### ISSUE TITLE
Identify Mario Based Graphics that Need to be Replaced

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#103]
This is a task to IDENTIFY the set of graphics out there that are too similar to Mario and need to be replaced.

After they are identified, a series of tasks such as Issue #102 can be opened up.
I don't think we should work the actual replacements of images through this task because there will probably be a very large number.

We'll also need to decide what constitutes being "too close" to Mario versus what constitutes "fair use".  Not everything that seems a bit similar necessarily needs to be replaced, though we will want this game to have its own look and feel.

Related Tasks (Both graphics and non-graphics):
#213 - Replace the powerup graphics
#235 - Rolling fruits (follow up to #213)
#81 - Redesign waffle coins
#210 - New HUD coin collection graphics
#203 - New logo (we're eliminating the word "Maryo")
#209 - Jewel collection sound
#205 - Name of the hero
#97 - Removing old Mario-style music from SMC
#238 - Replace level finish song
#77 - Replace turtle boss with something based on army
#219 - Replace stone graphics
#228 - Replace fruit collection sounds
#236 - Hills Replacements
#333 - Vine Replacement
#337 - Pow Switch Replacement

**Comment by Bugsbane** [comment]
It would be good to update this with which items are still outstanding, and which are closed.

From my quick survey, it seems that the only ones left undone are:
#77  - Replace turtle boss with something based on army
#228 - Replace fruit collection sounds (I've posted a possible draft here)
#236 - Hills replacements (although if this is necessary as they've had the eyes removed already, I'm not sure)
#333 Vine replacement - We actually have a good replacement graphics for this. It's still a vine, but a less Mario like one. I posted a screenshot using it on the ticket.
#337 Pow switch replacement - I can have the frames for this done within minutes of knowing how many we need.

As you can see, nearly all of these have at least a partial fix or draft, or are close to being done already. The only big one is the Turtle boss.

**Comment by datahead8888** [comment]
I'm definitely looking forward to the new turtle boss replacement :)

**Comment by datahead8888** [comment]
We probably have identified about everything to be replaced now, and there is nothing to stop us from opening new tickets if we still find something later.  I am closing this.

**Comment by Bugsbane** [comment]
> I'm definitely looking forward to the new turtle boss replacement :)

Yes, sorry for the long delay on this. I'm just swamped lately, especially with school holidays here, but I haven't forgotten about it!

**Comment by datahead8888** [comment]
> Yes, sorry for the long delay on this. I'm just swamped lately, especially with school holidays here, but I haven't forgotten about it!

Thanks, @Bugsbane.  If it's possible to do a simpler version of the Army Boss graphics for now (without too much rework when you do the better quality version later), that would let us get the boss readded for now.

In #77 you had said:
> Hey guys,
I might be able to do something very simplified next weekend (March 7) just with very few frames of animation.
