### ISSUE TITLE
SFML Port (Master Task)

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#105]
This is a task to decide whether to use 3rd party API's for physics and rendering as well as development philosophy for all libraries.

Thoughts on each sub system
* Physics
    * This blog posting discusses some of the pitfalls of using physics API's for a 2D platformer: http://www.learn-cocos2d.com/2013/08/physics-engine-platformer-terrible-idea/
    * Boswer Jr said in a forum posting that one of the reasons he liked Secret Maryo more than Super Tux was because of the physics system.  Thus the existing physics behavior does attract people.
    * API's such as Bullet are widely used by people and presented at top Graphics conferences.  It is improbable we will ever have someone with the level of skill to develop some features in Bullet.  It is also tested by a community.
    * If we use a physics API, I would suggest finding one that alternately supports 2D/3D (see the discussion below for 3D rendering support).
    * For a physics API, hardware acceleration (probably through OpenCL (not OpenGL)) would be good
* Rendering
    * The old OpenGL cannot continue being used because it is deprecated and may cease to function in the future.
    * The new OpenGL API requires use of the Open GL Shading Language
        * Calling the necessary components, in the right order, is difficult in the new Open GL.  It can be viewed as a hardware API in many ways.
        * Debugging is very difficult with GLSL.  People often output color images to represent intermediate data.
        * People often have a lot of difficulty correctly implementing lighting systems in GLSL.  My own 3D lighting system still has an issue.
        * It does, however, give you hardware accelerated access to graphics effects at both the vertex and the fragment (preliminary pixel) levels
    * If we use an API that replaces OpenGL such as Ogre, I think it should have:
        * Direct support for 3D operations.  Having access to z coordinates and other 3D components can still be useful, even in a 2D projection model.  Also, who's to say we will never ever have a partial-3D mode?  It would be better not to be relatively constrained later by a 2D API.
        * All calls to the API should be translated to OpenGL (DirectX is fine too as long as OpenGL is supported).  This allows hardware acceleration.
        * It would be good if OpenGL can be embedded within it.  If it cannot, the API needs to be abstract all major OpenGL features (including lighting).
    * In the short term it's questionable how much time I can invest in major OpenGL conversions or features.

There are 3 basic philosophies on how to apply them:
1) 100% - Use 3rd Party API's for everything
2) Complement the 3rd party API's with some custom code where necessary or reasonable
3) Continue using custom systems for these components.

If we take option # 1 for one subsystem, I think that policy should be consistent across all subsystems.  In regards to complementing physics systems, I do not mean to run out and start reimplementing dozens of Bullet features.  I mean that we might consider extending a physics API for an additional physics feature or implementation.  In such a case, we would normally interface with the API (perhaps adding a custom module) unless we had a good reason not to.

There are things I like about option # 3, but given the goals of SMC and views of the developers, I am beginning to believe option # 2 is worth considering.  Please do read the article link, though.

**Comment by Quintus** [comment]
@Luiji @datahead8888 @brianvanderburg2 Currently, TSC uses SMC’s old SDL1 + OpenGL2 combination (because SDL1 was horribly unperformant on itself). I am under the impression that given the discussion in #10, everyone is fine if we switch to SFML. Note this does _not_ imply SFGUI, which is a separate topic. CEGUI can still be used with SFML as well.

Is everyone fine with switching to SFML as the main rendering framework then?

Valete,
Quintus

**Comment by sauer2** [comment]
I'm not a TSC dev so in the end it's your decision anyway.

The time I used SFML (2.1) it worked out nice, but from what I heard on reddit you might run in two problems:

1. OpenGL Core Context support, apparently it's still pending: https://github.com/LaurentGomila/SFML/issues/654
2. SFML devs assume you create your own rendering method as their methods don't do batch drawing.

Also, compile times might get worse. That's the price you pay for a modern C++ API.

**Comment by Quintus** [comment]
> OpenGL Core Context support, apparently it's still pending: LaurentGomila/SFML#654 EDIT: 

The 2.3 release is not too far in the future as far as I can see. The guys in `#sfml` talked about 2.3 when I was there and it appeared nearly ready to me.

> SFML devs assume you create your own rendering method as their methods don't do batch drawing.

Are you referring to this? http://www.sfml-dev.org/tutorials/2.2/graphics-vertex-array.php To this? http://www.sfml-dev.org/tutorials/2.2/window-opengl.php

SFML works just fine without having to write a renderer. If you want, you can drop to bare OpenGL for performance, but it is not required. However, I’m new too all this, so I’m going to wait for a comment by @Luiji on that topic who said he has worked with it.

Vale,
Quintus

**Comment by sauer2** [comment]
>Are you referring to this?

Yes.

Good to see those two issues won't be a problem.

**Comment by datahead8888** [comment]
I would like to pause a moment and discuss both of sauer2's 2 new points a little more before finalizing this decision.

> OpenGL Core Context support, apparently it's still pending

From what Quintus said, it may not be a problem, but I'd be curious if Luiji has any concerns.  I'd like to read the SFML team's discussion some more when I get time.

> SFML devs assume you create your own rendering method as their methods don't do batch drawing.

Many higher level API's akin to SFML allow you to override a draw() method (if object oriented), in which you write the logic to draw everything to the screen.  I would like to understand this point a little more before making a decision if possible.

Also, we have a second ticket that also talks about the OpenGL upgrade.  Can we close it as a duplicate, or do 2 tickets still make sense?

**Comment by Quintus** [comment]
I have experimented a bit with this due to your suggestion and found that it’s really easy to use. I have implemented an ungly and simple example of creating an object that consists of several sub-images that are handed to the graphics card at once as one single blob:

* [`Scenery` class that represents all the static scenery in a level](https://github.com/Quintus/sfml-minitsc/blob/master/src/scenery.hpp)
* [Implementation of that class](https://github.com/Quintus/sfml-minitsc/blob/master/src/scenery.cpp)
* [Here’s how the `LevelScene` uses it](https://github.com/Quintus/sfml-minitsc/blob/master/src/scenes/level_scene.cpp#L16-L20).

It is possible to add as many elements as necessary to the Scenery instance, they will all be thrown onto the GPU in one step as one single large `sf::VertexArray`, which should be super-performant. Additionally, I still allow collision detection with this by maintaining the bounding boxes separately (but note that the collision detection itself is performed not really performant, just all boxes are iterated and checked).

Even me who never touched a line of OpenGL code can understand how this works <3.

Vale,
Quintus

**Comment by Quintus** [comment]
> Also, we have a second ticket that also talks about the OpenGL upgrade. Can we close it as a duplicate, or do 2 tickets still make sense?

Yes, this is probably duplicate then.

Vale,
Quintus

**Comment by datahead8888** [comment]
> I have implemented an ungly and simple example of creating an object that consists of several sub-images that are handed to the graphics card at once as one single blob

Yes, I realized afterwards I misread sauer2's point.  He's not talking about implementing your own draw method.

**Comment by Luiji** [comment]
The only thing I'm concerned about is this "OpenGL Core Context" thing, but I honestly have no idea what you guys are talking about in that regard. I doubt compile times will be effected in a way that's detectable to a human being. Rendering can definitely be done efficiently.

The main thing we should do to reduce compile times is reduce the code base. Switching from CEGUI to a less complex environment would help in that regard, so long as the target is actually less complex. That's for a different discussion, however.

**Comment by Quintus** [comment]
> The only thing I'm concerned about is this "OpenGL Core Context" thing, but I honestly have no idea what you guys are talking about in that regard. [...] Rendering can definitely be done efficiently.

Ok. You are the experienced game dev, so if you say it is not relevant then I will not doubt your judgement.

> The main thing we should do to reduce compile times is reduce the code base

As in "remove all the backward compatibility" ;-). Honestly, the compilation time is something I do not worry too much about. `cmake` tries best to instruct `make` to only compile the files that are affected by a change, and I have to say this usually works nice for me. I rarely have to recompile the entire thing.

I’ve never seen a suggestion to optimise compilation time before. One never has seen everything I guess... So, here’s the [obligatory XKCD](https://xkcd.com/303/) (© Randall Monroe, CC-BY-NC 2.5):

![Compiling](http://imgs.xkcd.com/comics/compiling.png)

Vale,
Quintus

**Comment by sauer2** [comment]
> I’ve never seen a suggestion to optimise compilation time before. One 
> never has seen everything I guess...
In the C++ world this has been a topic as soon as many compiler passes 
were required by templates.

Approaches are ranging from better languages (basically every modern 
compiled language compiles faster, even those that use C as intermediate 
code, alone for not having the retarded header/implementation system), 
replacements for ancient build systems like make (I'll try if ninja 
works easily and faster on the next complete compilation) and even 
better linkers, like Valves gold linker.

That's not to say I'm a professional C++ dev, I just watched some talks.

Unrelated: Want a pro-tip for guelkerdev? Make the text panels opaque, 
transparent backgrounds stress the eyes and may even impede visually 
impaired people.

@Luiji: Out of interest,  are there plans to drop the boost libraries, 
now that you were planning to migrate the base to C++11?

**Comment by Quintus** [comment]
> That's not to say I'm a professional C++ dev, I just watched some talks.

Talks are great :-). Except all the talks I have viewed were Ruby talks... :elephant:

> Unrelated: Want a pro-tip for guelkerdev? Make the text panels opaque, transparent backgrounds stress the eyes and may even impede visually impaired people.

Errm, sauer2, this is nice that you make recommendations on my (more or less) commercial site, but I think this is not the place to do so.

> Out of interest, are there plans to drop the boost libraries, now that you were planning to migrate the base to C++11?

I was actively looking for a rendering library that does not depend on boost, so the short answer is: yes. The long answer is: Not right now, wiring out all the boost stuff will take time.

Vale,
Quintus

**Comment by Quintus** [comment]
I take it then that I can start with SFML porting now? :-)

...yes I know I am pressing with this... I just want to start :-)

Vale,
Quintus

**Comment by sauer2** [comment]
>     That's not to say I'm a professional C++ dev, I just watched some
>     talks.
>
> Talks are great :-). Except all the talks I have viewed were Ruby 
> talks... :elephant:
>
>
I guessed you had an origin in web dev and that is how I stumbled over 
your page. Didn't mean to be intrusive, sorry.
>
>     Out of interest, are there plans to drop the boost libraries, now
>     that you were planning to migrate the base to C++11?
>
> I was actively looking for a rendering library that does not depend on 
> boost, so the short answer is: yes. The long answer is: Not right now, 
> wiring out all the boost stuff will take time.
>
Nice. With Boost and CEGUI gone in long terms that's a real cut.

**Comment by brianvanderburg2** [comment]
> I take it then that I can start with SFML porting now? :-)

I like how SFML is C++ based unlike SDL.  Does it have decent support for all Linux/Windows/Mac, and is it future-stable?  SDL looks like it is here to stay, but I've only recently heard of SFML.

**Comment by sauer2** [comment]
It isn't backed by a company, but...

SFML has been there quite some time now and Laurent Gomila has 
handed/opened development to a community based team, so it's not a 
one-man show anymore.

If that's what you mean by future-stable.

It runs on Linux/Win/Mac, support for IOS and Android is in the makings.

Am 23.03.2015 um 23:46 schrieb Brian Allen Vanderburg II:

**Comment by datahead8888** [comment]
This task has morphed into the SFML Port's master task.  I have changed the title to be more meaningful.  #55 (the OpenGL upgrade) and #11 (The SDL upgrade) have both been superceded by this task.

**Comment by Quintus** [comment]
Following @datahead8888’s more sensible approach to porting TSC to SFML, the main work on this task (and its subtasks) has now shifted to the `feature-sfml-port2` branch. I have closed the tickets related to the old approach and left only those open that have a meaning in the new approach as well.

Valete,
Quintus

**Comment by Quintus** [comment]
Porting is nearly done. Remaining is solely issue #516; once that is implemented I will merge `feature-sfml-port2` into `devel` and close this ticket. Bugs are then normal game bugs and can be worked on in `devel`.

Valete,
Quintus
