### ISSUE TITLE
Enhance Mountain Trials Level to Use Scripting...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#115]
This is a task to enhance Bowser Junior's Mountain Trials level with scripting for its objectives.  If Bowser Jr comes around again, we can try to convince him to upgrade it; otherwise we might consider doing it ourselves.

I think they added a Furball boss to the level.  If we decide to include the revised level as one of the official world levels, we may need to consider removing that boss.

If you complete an objective, it would print something such as,
"Objective 1: Complete"
...just like Goldeneye on the N64 :)

**Comment by Quintus** [comment]
What’s the state on this? /cc @SonOfBowser

Vale,
Quintus

**Comment by SonOfBowser** [comment]
Basically done, but I ran into an issue with sublevel state handling 
which means some of the objectives can't be completed.

**Comment by datahead8888** [comment]
> Basically done, but I ran into an issue with sublevel state handling
which means some of the objectives can't be completed.

Thanks, SonOfBowser.  I really appreciate your following up on our request to upgrade this level.
I know Quintus assigned himself to the ticket for this issue (#335), but he's gotten slowed down a bit while he finishes his university exams.

We've just about got enough levels for a new world!

SonOfBowser's Mountain Trials level would make an excellent finishing touch to the campaign - it's a different kind of level.
I've been making more progress on my Desert Fortress level, the sequel to the Desert Break In level.  This could be placed after the former level.
Quintus has 3 levels or so that we could try and put in this last world.  Honestly, I still need to spend more time reviewing them, so it's probably best I don't offer suggestions yet.  I know they are more challenging, which would fit a final world well.

I'd need space for a desert region and a castle at the end of that desert region on the map.  SonOfBower's level would require a mountain.  The mountain can also work for any type of ice level we need, since will have higher altitude regions.

@sauer2, how hard do you think it might be to rig together a map for this for this last set of levels?  It'd be a great way to bring in release 2.0.

**Comment by sauer2** [comment]
@datahead8888:

I'll try to do that later. However, I'm not aware of special flags and 
editor bugs and stuff like that.

**Comment by sauer2** [comment]
@datahead8888: While playing around with the map editor I discovered some issues:

* most overworld sprites look plain ugly
* when creating waypoints, they always are below the way sprites (tl:dr, z-layering is probably broken somehow)
* about that level of yours, desert_break_in: you really should fix the rope endings

So technically, it's quite doable and I think, there are more than enough levels to include.

**Comment by Quintus** [comment]
Cf. #367 for a fix for the sublevel scripting problems.

----------

> most overworld sprites look plain ugly

Yes. Definitely yes.

> when creating waypoints, they always are below the way sprites (tl:dr, z-layering is probably broken somehow)

Grrml. The waypoints have been showing Z layer problems twice already which have been fixed in turn. It seems they don’t want to be fixed.

> So technically, it's quite doable and I think, there are more than enough levels to include.

Each new world is accepted gladly. Looking forward to it! :-)

Valete,
Quintus

**Comment by sauer2** [comment]
> Each new world is accepted gladly. Looking forward to it! :-)
>
>
However, like datahead said, I'd rather wait until the levels (in 
particular the desert levels) are ready.

BTW: Is it possible to set a different background color?

BTW2: What is the mysterious "packages" tab?

**Comment by SonOfBowser** [comment]
This has got a little off topic. Do we need new issues for anything discussed here?

I'll tidy up and send out patches this weekend.

**Comment by sauer2** [comment]
Maybe one for overworld sprites and one for the not working drawing 
order in the overworld.
Am 12.02.2015 um 21:16 schrieb Robert W:
>
> This has got a little off topic. Do we need new issues for anything 
> discussed here?
>
>

**Comment by Quintus** [comment]
> This has got a little off topic. Do we need new issues for anything discussed here?

No, because the OT stuff is no issue stuff :-). @sauer2 could we switch this discussion to the forums?

Vale,
Quintus

**Comment by datahead8888** [comment]
> No, because the OT stuff is no issue stuff

The waypoint Z layer problem needs a bug ticket if it's an issue.  The graphics clean up could be a ticket, unless we feel it's way too broad in scope (there are other tickets just as broad, though).  Opening tickets for the other level and world would allow us to track them against the release more easily if needed later.

**Comment by Bugsbane** [comment]
To me "overworld graphics" is a bit too big for a single ticket. That's a bunch of different art assets (and yes, they're some of the ugliest in the game - baring Maryo / Alex by yours truly, if I say so myself.). I don't think we need a ticket for every asset, but maybe one for each class of image assets (eg hills, flowers, pipes etc).

I've actually been looking forward to redoing these for ages, but prioritized in game assets.
