### ISSUE TITLE
Timers do not Pause With Game

### ISSUE THREAD

**Issue by DarkAceZ** [Secretchronicles/TSC#118]
Clicking/focusing on another window will pause the game window, but because the script's timers are on a separate thread, they will not pause with the game.
(If you've set a "Timer.every" and un-focus from the game window, the timer will keep repeating and heaping up code, which will all be executed right when the game un-pauses.)

**Comment by Quintus** [comment]
Timers also do not pause when you are in a sublevel. When you return from the sublevel, all the accumulated ticks are executed at once.

Vale,
Quintus

**Comment by datahead8888** [comment]
How does scripting.cpp make use of the cTimer class generally (mrb_timer.cpp)?  I was reading through it, and I'm guessing I was missing an abstraction or configuration earlier.

**Comment by Quintus** [comment]
datahead8888 <notifications@github.com> writes:

> How does scripting.cpp make use of the cTimer class generally
> (mrb_timer.cpp)?  I was reading through it, and I'm guessing I was
> missing an abstraction or configuration earlier.

There’s a large comment in mrb_timer.cpp starting at line 102 (in
“devel”) that explains the entire mechanism. If this leaves open any
questions, please ask. Beware the comment might not be entirely
up-to-date, but the general mechanism shouldn’t have changed. Fix
outdated info when you come over it.

The important methods in scripting.cpp are
cMRuby_Interpeter::Register_Callback(), which is used by the timer to
inject an mruby callback into the regular mainloop from another thread,
and cMRuby_Interpreter::Evaluate_Timer_Callbacks(), which executes all
the callbacks registered, and which is called from the main loop once
per frame.

Also, on interpreter shutdown all timers must be destroyed. You’ll find
that in cMRuby_Interpreter’s destructor.

Vale,
Quintus
