### ISSUE TITLE
Bug: particle emitter not getting loaded

### ISSUE THREAD

**Issue by sauer2** [Secretchronicles/TSC#131]
In sauer2_10, at the end, there is a particle emittern near the door. It doesn't get loaded into the level editor and the game.

**Comment by datahead8888** [comment]
Not sure why this one didn't auto close.  If it looks good in devel, @SonOfBowser, we can close it.

**Comment by datahead8888** [comment]
Disregard the last post -- I forgot that PR isn't merged into release 2.0 yet.  I will delete these posts in github to keep it from being cluttered.

**Comment by SonOfBowser** [comment]
There are definitely some levels which have been updated incorrectly before this fix which may need to be corrected or re-imported; most notable of which is menu_brown_1.smclvl

**Comment by datahead8888** [comment]
I could open a new ticket to track this other fix you want.
