### ISSUE TITLE
Kid-friendly File Selector

### ISSUE THREAD

**Issue by DarkAceZ** [Secretchronicles/TSC#14]
We need a file selector that's much easier for people who are not quite familiar with computer mechanics, as opposed to the filename/here "selector".

**Comment by datahead8888** [comment]
As referenced in other duplicate tickets:
* We need to allow level creators to browse available music tracks in the settings pages.
* We need to allow level creators to browser available background images in the settings pages.

Both of these could be done through drop downs or through a file selector using the file system.

If anyone knows of more file selectors that this need this, please list them in this ticket.
