### ISSUE TITLE
Idea: level editor object property tabs

### ISSUE THREAD

**Issue by brianvanderburg2** [Secretchronicles/TSC#141]
The properties of some objects in the level editor are rather numerous, making it where the controls take a lot of space and sometimes even require scrolling to view some of the properties.  One example is the particle emitter.  I think it could be nice if tabs could be used to show the properties, placing related properties under their own tabs.

Actually creating the tabs/layout for editing the properties of a level object may be easier using CEGUI layout files instead of coding the construction of each item. (though I can't seem to get the layout editor working on my system so edit them by hand manually anyway)

**Comment by Quintus** [comment]
This has already been implemented, though a little differently with a panel on the right side.
