### ISSUE TITLE
Updating Level Format

### ISSUE THREAD

**Issue by Luiji** [Secretchronicles/TSC#143]
The old level formats were very verbose due to the nature of the CEGUI XML handler. For example:

```xml
<object>
  <property name="key1" value="value1" />
  <property name="key1" value="value2" />
</object>
```

With the update to our XML handling code, we are now able to discuss cleaning up the level format and significantly reducing on-disk size.

My basic proposal would be something like this:

```xml
<object key1="value1" key2="value2" />
```

**Comment by Quintus** [comment]
Superseded by #354. Discussion continues there please.

Valete,
Quintus
