### ISSUE TITLE
Background preview now shown in editor

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#156]
In the settings editor, on the page where one can set the level background gradient and add background images, the background preview is not shown as it was in version 1.9. Right next to the gradient textfields there should be a little box that contains a minified preview of the background gradient and the background images.

Vale,
Quintus

**Comment by datahead8888** [comment]
Might this one be good/possible to put in 2.1?  If we have Fluxy's old code as reference, that could guide us in implementing it.  Also, the Cegui upgrade is done now, so that is no longer an impediment.

**Comment by Quintus** [comment]
> Might this one be good/possible to put in 2.1?

I'll add it to the milestone. We can always remove it later on if we don't come around to do it.

>  If we have Fluxy's old code as a reference, that could guide us in implementing it.

Someone up for digging it out of Git?

Valete,
Quintus

**Comment by datahead8888** [comment]
You had referenced commit id df54a35623469a0a7672df905cb4f114d8d78e54 earlier, which makes a reference to removing a preview view.  I would guess this is something to check out.
