### ISSUE TITLE
boost filesystem path string conversion issues (devel branch only)...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#157]
It seems the packaging changes in devel change the way boost::filesytem::path is converted to std::string.  This showed up as a compilation error for the CEGUI editbox -> setText method.  @Quintus has patched the call that was preventing compilation but has pointed out that some of the other instances of the problem could cause garbage file names on Windows.

Long term, we probably need to change all instances of this in the code so that they work seamlessly on both Windows and Linux.

I know when changing some printf's to couts, I took out some .c_str()'s myself, but as far as I know they were for instances of std::string only.  I remember devel being broken before my changes went in, but feel free to correct me if I'm wrong.

Does it seem feasible to use a script, in Ruby/Python/Perl to fix the instances in the code?

Discussion: http://smc.quintilianus.eu/topics/50
See also: PR #106 

@brianvanderburg2 and @dlpenguinlover - I am keeping you in the loop on this discussion.

**Comment by Quintus** [comment]
Just a quick heads-up. We should watch how TSC behaves with non-ASCII pathnames after the 2.0.0 release. If everything goes well, we ought to close this.

Valete,
Quintus

**Comment by Quintus** [comment]
Appearently, no problems exist. Closing this.
