### ISSUE TITLE
Hold down button to stream new characters in script editor...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#158]
It would be useful if we could hold down keys such as space, delete, or backspace to repeatedly type a character in the script editor.  It would use timed intervals between these registered keypresses as about any standard editor does.

Also, it would be useful to define behavior for the tab key.  It could map to 4 spaces.

**Comment by Quintus** [comment]
I don't know when, but this has appearently been implemented meanwhile. At least it works for me. I thus close this. If it still does not work for you, please speak up.
