### ISSUE TITLE
Replace 0.000001f by cSprite::m_pos_z_delta

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#198]
The code frequently uses the value `0.000001f` when it wants to increase/decrease the Z position of some sprite. However, it is generally known that magic numbers are bad, and if you look at the code and don’t recognize `0.000001f` as the minimum possible Z step, you are at a loss where the number comes from and what it means. Hence, all uses of that number should be replaced with the new constant `cSprite::m_pos_z_delta` which was introduced in commit d1f651ea9437b04bd07e945e69a96e1f13a1d692 and has been set to exactly that value.

Vale,
Quintus

**Comment by lambda-11235** [comment]
There are a two other places where this number appears that is not directly related to sprite position. renderer.cpp lines 540 and 570, and sprite.cpp line 743. They're still used as minimum numbers, but in a different context.

**Comment by Quintus** [comment]
@lambda-11235 if you give line numbers, please link to them on the repository with a permanent link, i.e. one that includes a specific commit hash or tag. Because otherwise the line numbers are subject to change and it’s unnecessary work to find out to which commit your line numbers correspond after some months.

Otherwise, thanks for the info :-)

Vale,
Quintus
