### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#203]
With ticket #92 being decided, it is time for a new logo. A delicate task, and I would appreciate suggestions from multiple people we can then vote on.

Valete,
Quintus

**Comment by Bugsbane** [comment]
I think we could simplify in the direction of BodhiPeace's design somewhat, although I'd strip out the background behind Alex / the monsters on the left, and remove Alex and the monsters under the text. They're all over on the left, so there's no need to have them in the banner twice. That would also make more room for the text.

Re: The text, the font works well (my text was a bit too jumled and multicolored), although I'd remove the white background and maybe add a touch of color (possible make the text medium brown, with a dark brown outline?)

**Comment by Quintus** [comment]
Currently, @DarkAceZ’s [variant](https://github.com/Secretchronicles/TSC/issues/203#issuecomment-64441359) is in the game and I personally like it. If we could have something like that as SVG that would be really nice. Should be similar to what you were describing.

Vale,
Quintus

**Comment by Bugsbane** [comment]
> If we could have something like that as SVG that would be really nice

I think s/he just pulled out a piece from [my SVG](https://github.com/Secretchronicles/TSC/issues/203#issuecomment-57741015), so if I can just find that, we're good to go.
