### ISSUE TITLE
Villain Name...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#206]
In #92 we established that the name of the villain is Dr. M (abbreviated), and we have also decided he will be a librarian.

What will his full name be?  We had looked at naming him Dr. Maximus, but we need to finalize the name.

@tristanheaven @Luiji @brianvanderburg2 @carstene1ns @default0 @DarkAceZ @dlpenguinlover @Bugsbane @kirbyfan64 @xet7 @giby @Quintus @ciro589m @sydneyjd -- feel free to share your thoughts.

We'll also need to eventually decide his backstory, but I was interested in playing around with this in the story draft before starting up a discussion thread on it.  We can see what works, however.

The art design may be related to his backstory.  For the style, I'd be interested in something slightly "realistic" though still looking cartoonish (ie. no overly exaggerated features, etc) in order to work with some of the themes we've been discussing.  We can discuss all of this, too, though.

**Comment by Quintus** [comment]
As the naming of Alex has been decided a good while ago, I would now like to finish up with this one. Is everybody fine with Dr. Malus now?

Valete,
Quintus

**Comment by sydneyjd** [comment]
Sure, that would work and it sounds odd enough to not have any mario 
resemblance.

**Comment by Bugsbane** [comment]
Sounds fine by me.

**Comment by datahead8888** [comment]
Dr. Malus works.

**Comment by Quintus** [comment]
@Luiji, fine with you also?

Vale,
Quintus

**Comment by Luiji** [comment]
@Quintus Sounds fine.

**Comment by Quintus** [comment]
Great! We finally found something where we all agree upon :-)

Valete,
Quintus
