### ISSUE TITLE
Replace "stone" graphics from SMB

### ISSUE THREAD

**Issue by Bugsbane** [Secretchronicles/TSC#219]
Under "stuff" in the level editor

Specifically:
Stone turtle shell
Stone moon
Stone mushroom
Stone fireplant

Really, this is mainly about finding the righrt combo of filters that can be put on any of our assets to produce a "stone" version.

Needs to be added to the first post in #103

**Comment by datahead8888** [comment]
I found some information on the stone filter that was used before:
http://forum.secretchronicles.de/topics/189

Who knows, maybe this will get knocked out in release 2.0 :)
If it's just a filter, anyone may be able to look into it a bit.

**Comment by datahead8888** [comment]
I converted the image to gray scale with:
~~~~~~~~~~~~~~~~~~~~~~~~~
inkscape -f stone_fruit.svg --verb=org.inkscape.color.grayscale --verb=FileSave --verb=FileClose
~~~~~~~~~~~~~~~~~~~~~~~~~

...then applied the stone filter to the interior.  You have to be careful to move the outlines out of the way while doing this, or a stone filtered outline will look strange.

![stone_size_berry](https://cloud.githubusercontent.com/assets/6478551/5692001/494b74ae-98b0-11e4-9e21-a3ea4618ba43.png)

**Comment by datahead8888** [comment]
Also, here's a second version that has the "blur object" to the left of the fruit removed.  That blur object may/may not work as well with stone versions of fruit:
![no_blur](https://cloud.githubusercontent.com/assets/6478551/5692030/b645054c-98b1-11e4-944a-5c27319abbee.png)

**Comment by datahead8888** [comment]
Redid it again:

With blur object (from original fruit SVG) still in place:
![stone_fruit_new_try_with_blur](https://cloud.githubusercontent.com/assets/6478551/5694625/ce723744-993c-11e4-8870-5aedb710d874.png)

Without blur object in place:
![stone_fruit_new_try_no_blur](https://cloud.githubusercontent.com/assets/6478551/5694626/efccf834-993c-11e4-81b9-e759919ecb0f.png)

**Comment by datahead8888** [comment]
I just did the replacement for the stone fire flower - the stone fire berry:
![stone_fire_berry](https://cloud.githubusercontent.com/assets/6478551/5695384/61080bca-996e-11e4-9163-64e3dd12ab6a.png)

**Comment by datahead8888** [comment]
Replacement for the stone turtle shell - the stone army shell:
![stone_army_shell](https://cloud.githubusercontent.com/assets/6478551/5695397/6d3e91f6-996f-11e4-9e7d-0e41782c5b15.png)

**Comment by datahead8888** [comment]
These are the images I'm replacing for your reference:
![fireplant](https://cloud.githubusercontent.com/assets/6478551/5695411/c07d8cdc-996f-11e4-9e85-37aa66ab77d1.png)
![mushroom](https://cloud.githubusercontent.com/assets/6478551/5695409/c079bb5c-996f-11e4-96ca-6c47c0fd8108.png)
![shell](https://cloud.githubusercontent.com/assets/6478551/5695410/c07cf3bc-996f-11e4-983f-f3a0a867d613.png)

You can view the full set of images at:
https://github.com/Secretchronicles/TSC/tree/release-2.0.0/tsc/data/pixmaps/ground/castle_1/statue/objects

We cannot replace the stone moon until we work the task to find a general moon replacement.

**Comment by DarkAceZ** [comment]
Just going to pop in here to say that I like these stone statues, and whoever thought of making them.

**Comment by datahead8888** [comment]
@DarkAceZ, do you mean you liked the originals?  The problem there is that they are clear references to a Mario game.

**Comment by DarkAceZ** [comment]
No, just the idea in general.

**Comment by datahead8888** [comment]
There actually is a way in which we could get rid of the stone moon now.  We could just replace it with a stone version of some other object.  We would probably want it to be an item or something else "friendly" (and not dangerous like an enemy).  We could either add another stone fruit or add a stone jewel (with an increased size).  Thus if someone used a stone moon in a level, it would be replaced with a stone fruit/jewel automatically.  We will still need to find a replacement for the moon itself, but there's no reason we can't annihilate the stone moon now...

Also, I'd be interested in adding some brand new stone images.  A stone Larry would be a *great* way to rake in TSC 2.0, especially if we put one in the first level.  A stone army (not in its shell) would compliment the stone army shell well.  We might throw other ideas around, though we probably should stop after 2/3 new stone images to avoid an overly large select box.

**Comment by datahead8888** [comment]
@sydneyjd -- how to you export an SVG to a png of size 256X256 and make the graphic fill up the whole space (or line up with the edges of the png graphic)?  No matter what I do, Inkscape seems to pad blank space around some sides of the size berry such that the actual object (within the 256X256 png) is less than 256X256.

Also, I could not find a way to export to 256X256 within Inkscape user interface.  If I changed the width, it changed the height and vice versa -- thus it would not allow me to set it to this size.  I finally started using this instead:
~~~~~~~~~~~~~~~~~~~~
inkscape stone_fruit_RESIZED.svg --export-png=out.png -w256 -h256 --export-area-drawing
~~~~~~~~~~~~~~~~~~~~

**Comment by Quintus** [comment]
> how to you export an SVG to a png of size 256X256 and make the graphic fill up the whole space (or line up with the edges of the png graphic)?

You need to set the canonical page size (i.e. the default export size in pixels) in the document’s settings (should be under the File menu), and on export, select "export page" (NOT "export drawing").

Don’t forget to add your SVGs to the `drafts/` folder. Also, you know, it would be good if you stated "I license these SVG and PNG files as CC-BY 4.0" and post some link :-). If you feel like it, you can also add this information the SVG metadata (File → Document Metadata), but that is only secondary because it’s too easy to forge.

Vale,
Quintus

**Comment by sydneyjd** [comment]
These look awesome @datahead8888 . :D

**Comment by datahead8888** [comment]
> You need to set the canonical page size (i.e. the default export size in pixels) in the document’s settings (should be under the File menu), and on export, select "export page" (NOT "export drawing").

That worked; thank you.

**Comment by datahead8888** [comment]
The mushroom and fireplant statue objects should be renamed (both the png files and the translations in the level editor menus).

I somehow ended up using "Size Berry" for the name of the mushroom replacement.  Do we want to call it something like "Power Berry" (I thought I saw that somewhere but am not sure), or what do we want to call it.

Speak now, or be stuck with with the consequences of whatever I end up doing......

**Comment by datahead8888** [comment]
I had not posted before and after pictures of these statued changes in a level.

Before:
![before_stone_upgrades](https://cloud.githubusercontent.com/assets/6478551/5855911/8b062010-a20b-11e4-97de-01dbc38add60.png)

After:
![stone objects after upgrade](https://cloud.githubusercontent.com/assets/6478551/5855913/9d3d3214-a20b-11e4-9818-86ee6fafed8f.png)

**Comment by sydneyjd** [comment]
Wow! I like them! Looks great!

**Comment by datahead8888** [comment]
I redid the screenshot for the second one so that it doesn't have the rest of my desktop in the picture.
I was trying to think if the lone piece of flame to the top left looks too disconnected from the rest of the stone object.  If I look in Inkscape, I can see clearly it is connected, but after the image is shrunk a bit in a level, I'm not sure if maybe it looks disconnected too much.  Maybe, maybe not...

**Comment by datahead8888** [comment]
I license the stone graphic SVG's and PNG's in the PR for this task as GPLv3+.  I am also fine with them being CC-BY-SA-4.0, but I don't think I can just license them this way because the graphics on which I based them appear to default to the GPLv3+ license.

**Comment by datahead8888** [comment]
Quintus has merged the PR with replacements for 3/4 of the Mario graphics here.
The remaining item is the stone moon replacement.
We can't do a direct replacement yet because we don't have a replacement for the moon itself.
Another option might be to replace it with a stone jewel.  The research item for this, though, is how to export SVG's from the Blender file for this.  It needs to be done, but it could take some time.
I'm not working on this now, so I have unassigned myself.

**Comment by Quintus** [comment]
For anyone wondering why nothing happens in this ticket, there has some more or less heated discussion started on the mailinglist: http://lists.secretchronicles.de/tsc-devel/2015/02/0000003.html

Vale,
Quintus

**Comment by datahead8888** [comment]
See also: http://lists.secretchronicles.de/tsc-devel/2015/02/0000014.html

(It split when I accidentally only emailed Quintus and then forwarded it to tsc-devel).

**Comment by Quintus** [comment]
Cf. #356

**Comment by datahead8888** [comment]
Bugsbane licensed his graphics under the Creative Commons CC-BY 4.0 license, so I will follow suit with these stone fruit graphics (derived from his fruit graphics).

I license these stone fruit graphics (the stone fire berry and the stone berry) under the Creative Commons CC-BY 4.0 license.

I think the army shell originated from secretmaryo.org; if it's possible I license the stone army shell under the Creative Commons CC-BY 4.0 license; otherwise they are licensed under GPLv3+.  We will probably have to mark it as the latter in the settings file.

**Comment by Bugsbane** [comment]
> I think the army shell originated from secretmaryo.org

The original drawings of Aarmy were by me, which were then traced by someone else, so there's an argument for it being a derivative of my work anyway. If there's a problem, I could recreate the army shell image in about 10 minutes.

**Comment by datahead8888** [comment]
@Quintus, what is the legal argument here?  If Bugsbane redoes the the army SVG, we technically have to redo the stone one, too.  It just seems like rework over a legal technicality...

**Comment by Quintus** [comment]
>  what is the legal argument here?

IMO, none. GPLv3 is not an ideal license for graphics, but it works for us. So just that doesn’t do as an argument for redoing this work.

What might be a more interesting argument to consider is whether we should strive for one license for all graphics. That would probably be CC-BY 4.0 then, and for that, redoing the graphic would be required. Given we still have an overwhelming number of original SMC graphics in the game, we shouldn’t start redoing newly introduced graphics just for licensing from GPL to CC-BY 4.0. On the long term, we can do that, but for now it’s overkill I guess.

That being said, if Bugsbane feels he can do it in such a short amount of time, I would be glad to accept that for the way to a uniform graphics licensing.

Valete,
Quintus

**Comment by datahead8888** [comment]
Honestly, if we redo graphics because they can be a higher quality, don't have SVG's, or because we want to do something different for our fork -- that makes sense.  Replacing assets across the project to attain CC-BY-4.0 removes contributions from people just for the sake of a license.

**Comment by Bugsbane** [comment]
Draft of a new rolled up Aarmy. The shading is currently off, and I still need to copy the colors from the original, and I haven't compared the scale at all, but it's enough to give you the general idea, and I have the SVG to license as we wish. :)

![aarmy-ball](https://cloud.githubusercontent.com/assets/401733/6222106/3a1d2be2-b61c-11e4-8aea-01f09f5d29ea.png)

**Comment by Quintus** [comment]
I just got the impression of steel army. Might make a nice version for factory levels.

Vale,
Quintus

**Comment by datahead8888** [comment]
> I just got the impression of steel army. Might make a nice version for factory levels. Could be immune to fire and ice.

We were talking about using the graphics discussed in #199 as a mechanical version of Army.  More versions of enemies never hurts, though if Bugsbane colorizes this for the normal Army enemy, we might want to make more than just color changes for a steel army.

The image posted above might work better for the stonified version, if we rerun the stone filter on the final version.  People may have trouble recognizing the current stone Army shell as Army.

**Comment by Bugsbane** [comment]
> we might want to make more than just color changes for a steel army

Yes, I would make considerably more changes for a mecha-Aarmy. ie screws, bolts, more angular, maybe even camera lenses instead of eyes (I'd have to do some sketches and see how that one actually looked), possibly an antenna.

**Comment by datahead8888** [comment]
The antenna sounds a little too 50's-ish to me, but the screws and bolts make sense.  The camera lenses for eyes might work, too.

**Comment by Quintus** [comment]
Do we have all the stone fruits in now or are some still missing?

Vale,
Quintus

**Comment by datahead8888** [comment]
> Do we have all the stone fruits in now or are some still missing?

No, we still have a stone moon.  Now that we have a moon replacement, it is possible to create stone version.  If no one has time, though, we will have to remove the stone moon outright for release 2.0.

I propose we mark this task as "Blocker", just like the other obvious Mario tasks.  Seeing a Super Mario World moon in the level editor menu is a clear Mario clone item.

**Comment by sydneyjd** [comment]
Testing... 
![moon_stone](https://cloud.githubusercontent.com/assets/8949851/6794547/790bcc8e-d1a9-11e4-86a2-ebd499ca85c8.png)

**Comment by sydneyjd** [comment]
here is the SVG. If its ready to go.

https://cloud.openmailbox.org/public.php?service=files&t=606492d7c34ae4cb3075207caf73f6eb

@Quintus @datahead8888

**Comment by datahead8888** [comment]
Wow...you're fast!  Thanks, Sydney!  I'm sorry I haven't been able to do this task :)

**Comment by sydneyjd** [comment]
@datahead8888 @Quintus here is a screenshot of it using the same config as original moon.
![16](https://cloud.githubusercontent.com/assets/8949851/6795126/0e03ab2e-d1b2-11e4-8db3-4558458d1869.png)

**Comment by sydneyjd** [comment]
I never touched the config, but it looks like the moon could be made slight bigger than 54x54 or whatever.

**Comment by datahead8888** [comment]
We might consider adding a black outline around the stone moon cookie.  In this case, not having an outline stands out more than normal because the stone moon cookie is in front of gray bricks.

I haven't looked closely at the style guidelines in the wiki; I know there was some material being discussed about outlines are usually used.

**Comment by datahead8888** [comment]
I found the style guide (WIP version) link:
http://wiki.secretchronicles.de/StyleGuide

Sydney, you also might see if you have any suggestions for the style guide itself.  Since you're an artist, you might be able to offer some good feedback to help drive its development.

**Comment by sydneyjd** [comment]
@datahead8888 I have gone to the older SMC wiki style guide for help before. Here is  updaed cookie with outline. 

https://cloud.openmailbox.org/public.php?service=files&t=8b700a82637c835811505f8bd813a240

SVG^

![moon](https://cloud.githubusercontent.com/assets/8949851/6795536/afbfea18-d1b7-11e4-9dd8-0a7416e33996.png)

**Comment by Quintus** [comment]
The moon cookie is hovering over the plinth rather than standing on it. Might be a slight sizing issue, though. Thank you, sydney! I’m confident we’ll get that in quickly.

Vale,
Quintus

**Comment by datahead8888** [comment]
> @datahead8888 I have gone to the older SMC wiki style guide for help before.

Sorry, as much as you've done in the wiki and with art there's no way you would have not looked into those guidelines by now.

> The moon cookie is hovering over the plinth rather than standing on it. Might be a slight sizing issue, though.

I think it just needed to be moved down a little bit in the level, but it would be good to try this in the level and be sure.
