### ISSUE TITLE
Dr. M Theme Song...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#222]
We ought to consider requesting a custom theme song for the Dr. M character.  We can then request some remixes of it for some different points in the game (especially cinema scenes).  This is another one of those items we will want to review carefully, since we want it to be iconic.

Themes can do a lot for a game . . . just think about the impact they had in the classic Star Wars movies.

This would probably NOT be the same song used on the title screen.

**Comment by kirbyfan64** [comment]
What ever happened to this?

**Comment by datahead8888** [comment]
The discussion went dead, and nothing was submitted.  You're welcome to take a shot at it; you might try to come up with something thematic that can be remixed into other songs easily.  Movies often reuse themes, and it would be cool if we did the same.

The title and credit themes are the ones we wanted to run a contest for.  Once we get some budget questions answered, hopefully we can run a contest with prizes.

**Comment by kirbyfan64** [comment]
@datahead8888 What exactly did you have in mind for the "style" of it? I was thinking something sort-of-sinister-sounding, but with some more lighter-ish parts to interrupt the intensity. Just to give the sound like, "This is a guy that's bad but kind of cool".

**Comment by kirbyfan64** [comment]
Maybe with some more "grand-ish" sounds or something, for the Shakespere part. :)

**Comment by datahead8888** [comment]
Ideally, the music would correspond to components of his character, as you hinted:
* Dr. M is a fan of Shakespeare and classical music
* He is very intelligent - the music would ideally have a bit of complexity
* Dr. M commands an army of monsters, with overwhelming power, suggesting a dramatic, cinematic orchestral component might need to be present
* He is not pure evil -- to some extent he becomes over-obsessed and goes down the wrong path.  Eventually, he joins Alex in order to fight a greater evil.  The music might also look for a way to reflect this, alternating between sections of music that emphasize the sinister and good components.

@Quintus - if you have any thoughts on using the story as a guideline for this piece, feel free to chime in.  It sounds like it would be a lot of fun to compose :)

**Comment by datahead8888** [comment]
In my opinion, theme songs for dark sections of a game or villains can be very effective if they alternate between a dramatic, all powering section and a soft, thoughtful section.  The contrast expresses a deep thought.

**Comment by Quintus** [comment]
The really evil villain as we plan it will be Lord Âzdhor. If we can have a different, and strikenly evil theme for him that makes him different from Dr. M. himself that would be cool. In contrast to Dr. M.'s theme it can be a rather sharp music, causing a disgustive effect. In the music for Dr. M., there should also swing some moment of thought, of doubt; a reminder of his personality that is not a black or white shape.

**Comment by datahead8888** [comment]
Shall I create a task for the theme for Lord Âzdhor?
Even Lord Âzdhor can't be pure evil, but he may effectively come close to it.

**Comment by Quintus** [comment]
> Shall I create a task for the theme for Lord Âzdhor?

Probably a good idea.

**Comment by kirbyfan64** [comment]
[Closing](https://github.com/Secretchronicles/TSC/commit/47aaa99f604eb1730a6923b253d923377b33a118).
