### ISSUE TITLE
Investigate Builds Using Emscripten...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#229]
As @Bugsbane  suggested in #105, we should evaluate the possibility of building C++ source to JavaScript/WebGL in order to run the game in a browser.

Considerations:
- We'd need to evaluate getting dependencies to compile to Java Script
- We'd need to add this to our build processes.  This would probably be another kind of crossbuild.
- We'd want to evaluate the performance of the game run in a browser.
- How many data/code files would the web version of TSC download at a time while playing?  How much data should it store in memory?

Running in a browser certainly will increase our audience, as Bugsbane pointed out.  It's easier for a lot of people to run, and some people may hesitate to install an application on their machine for fear of viruses.

**Comment by Quintus** [comment]
I don't think this is a good idea. Transpilers are never going to create high-quality code.

**Comment by datahead8888** [comment]
I don't see any problem with using this as a "build to a platform" type of thing; Unity also has an option to build to Java Script which helps a lot of people.  The quality of the generated Java Script would not be of concern, since it would be analogous to generated assembly code for native compilation.  All we would care about is the quality of the C++ code that we actually maintain and the run time performance of the generated Java Script.

However, none of the programmers are probably interested in implementing this, and there has not been much community interest in this since it was brought up.  If no one really wants this, and if no one really wants to implement this (at some point), we should probably close the ticket.
