### ISSUE TITLE
Review Existing SMC iPhone Port Work

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#233]
In follow up to #232, it turns out there is also a pre-existing iPhone port of SMC.
It is at https://code.google.com/p/smcios/
While the Android port is being actively developed, the iPhone port has had no changes since 2012.

This one actually uses C++ in the code, so it may be a bit easier for us to take advantage of.  We also might see if there's any work we can leverage regarding OpenGL on the iPhone.  Finally, we might try to see if we can contact the former developers for it.  Can anyone figure out the easiest way to contact the developer for this?  This person might be able to help us with both iPhone and Mac desktop support.

There are bug fixes in the commit log.  Obviously, we can't immediately be sure if they are fixes for ioS specific changes are pre-existing bugs that we already have, but they may be worth reading.  We also might see if any new features were added at all.

This seems to be an old discussion on an iPhone port - http://www.secretmaryo.org/phpBB3/viewtopic.php?f=1&t=3704&p=22894#p22894

The author of the one on code.google.com is  Li Jie Jun, who is not listed in the old forum posting's title screen shot.  Thus I would assume this is a different port.

Also of interest is an apparent OpenGL ES change: https://code.google.com/p/smcios/source/detail?r=7

@Quintus / @Luiji - I'm cc'ing you again.
@ciro589m - you may also find this interesting.

**Comment by Quintus** [comment]
Is this still relevant?

Vale,
Quintus

**Comment by datahead8888** [comment]
This may still yield benefits if someone reviewed the iPhone port work for possible feature code, and it could be worthwhile to contact the old team members on that port to see if they are interested in our project.  Thus the task is still valid.  Eventually, if we have not used their code yet, our code will become incompatible with theirs, but this isn't as likely to be a problem until we get to the 3.X series or so, possibly.

I closed the Anrdroid port review task because that one was found to provide no further benefit.

**Comment by datahead8888** [comment]
Given that we are planning on doing a rewrite and that there isn't much interest in investigating the iPhone port now, I propose we close this as something we will not do.  If we change our minds, we can always open a new ticket then.

**Comment by Quintus** [comment]
On Sun, Nov 06, 2016 at 03:27:53PM -0800, Chris Jacobsen wrote:
> Given that we are planning on doing a rewrite and that there isn't
> much interest in investigating the iPhone port now, I propose we close
> this as something we will not do.  If we change our minds, we can
> always open a new ticket then.

Yes, I'm also for closing this.

Vale,
Quintus

-- 
Blog: http://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F
