### ISSUE TITLE
Hills Replacements

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#236]
The green_1 graphics at https://github.com/Secretchronicles/TSC/tree/devel/smc/data/pixmaps/hills/green_1 look a lot like Super Mario Bros 3 hills and need a replacement.  Ideally we'd want a replacement that gives a similar feel to the player but that does not look like a Mario rip.

Some of the other hills in the pixmaps/hills folder might be worth discussing.
If anyone knows of map tiles or other background objects that have this problem, feel free to post them here.

![head](https://cloud.githubusercontent.com/assets/6478551/4784727/fe9da7c4-5d63-11e4-9fcd-65f08765f6f1.png)
![middle](https://cloud.githubusercontent.com/assets/6478551/4784729/03d26ea0-5d64-11e4-9f86-0d79bc59a362.png)

**Comment by Bugsbane** [comment]
Just an idea, for how we could fix a lot of these very quickly:

1. if I come up with a generic selection of mouths - say 6 - which wouldn't take long at all. Most I could rip from things I've already made.
2. We just open up the SVG's for everything with eyes, delete them and paste in one of the mouths. Possibly choose a new color to match.
3. Profit! :D

Yes it wouldn't be perfect, but it would still look better than many graphics we already have in the game, and it would let us remove *all* of the Mario like "things with eyes" in about an hour, if someone can get me a list of the SVG's to edit.

Just sayin'

**Comment by datahead8888** [comment]
We might need to come to a decision on #298 before redoing all the hills.  Whatever gets decided on the hedge ticket is probably going to set a rule or partial rule.

We really need to get a team meeting scheduled soon to discuss stuff like this and bring it all to resolution.  We also need to decide on the story, which means I'm going to need to finish reading danfun64's drafts -- I've just been tired out after meeting a research deadline.

**Comment by Quintus** [comment]
As I indicated, I’m not opposed to the mouths idea. I don’t remember
anything like this in other games, and it looks fairly nice.

Valete,
Quintus
