### ISSUE TITLE
Site Scrape...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#246]
It's pretty obvious secretmaryo.org is on the down trend and is at risk of being shut down (I don't think registration of id's is even turned on any more right now).  This is a task to obtain a site scrape so that we have a copy of the site for personal use.  I've currently been using HTTrack for this.

Items:
* Obtain copy of site scrape, place on Alexandria server
* Expose to Internet via unpublished link
* We can talk about making it available to all contributors by either distributing the private link or by adding a login

I lost my last site scrape accidentally but am currently running it again locally.  I may try to set it up on the Alexandria server later if I actually get enough time to read up on the command line version of HTTrack.

See also: http://forum.secretchronicles.de/topics/72

**Comment by datahead8888** [comment]
I've placed SMCWebSite.tar.gz in /home/datahead/SMC-Website-Backup on the Alexandria server for now.

While testing the website on Ubuntu (rather than Windows as before), Firefox was not recognizing .php files.  I can double check this again in Windows later

**Comment by Quintus** [comment]
datahead8888 <notifications@github.com> writes:

> I've placed SMCWebSite.tar.gz in /home/datahead/SMC-Website-Backup on
> the Alexandria server for now.

Errm, you know that you should better keep permissions on your home
directory restrictive so that others can’t look into it? Also, that
directory will not be found and served by Apache httpd.

> While testing the website on Ubuntu (rather than Windows as before), Firefox was not recognizing .php files.  I can double check this again in Windows later

There is no PHP on the server even installed. But the site scrape can
only have yielded static HTML anyway, so it should just display it
as-is. Place it in /srv/http/users/datahead and we’ll see further.

Vale,
Quintus

**Comment by datahead8888** [comment]
> Errm, you know that you should better keep permissions on your home
directory restrictive so that others can’t look into it?

It's just a site scrape file, but sure, I should look into my home directory permissions.

> Also, that directory will not be found and served by Apache httpd.

I couldn't find the correct directory last night so I dumped it somewhere for now.  I will try again later.

**Comment by datahead8888** [comment]
The site scrape can be viewed at:
http://team.secretchronicles.de/~datahead/MyWebSites/index.html

We will probably want to make a new site scrape, run from the Alexandria server later.  Also note this one may have some dead linkes in it if you look hard enough.

I propose we close this task and open a new one for the Alexandria up-to-date scrape in the website repo.  We can worry about what directory we want this to be in for everyone for the final scrape.
