### ISSUE TITLE
Replace "^" block

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#248]
The last yellow block that still is in the game is the one with the upwards ^ arrows. It is just an alternatively animated box with no specific meaning, though I have seen people use it mostly for the +1 life powerup, but you can place anything in it you want.

Vale,
Quintus

**Comment by Bugsbane** [comment]
Is this still needed?

**Comment by Quintus** [comment]
> Is this still needed?

Yes, the old ^ block is still there:

![3](https://cloud.githubusercontent.com/assets/156358/6158035/c7ba1c00-b246-11e4-8a33-569fd30302d4.png)

Vale,
Quintus

**Comment by Bugsbane** [comment]
Ok. I'll have some time this weekend. I've just got to find where I was saving all my TSC files. I love KDE, but it's search has always sucked, and continues to do so. :(

I'm thinking maybe a crate like the others, with small lightning bolts, about the same size as the arrows here, scrolling upwards.

I could be convinced of another concept, if anyone has one though.

**Comment by Quintus** [comment]
> Ok. I'll have some time this weekend. I've just got to find where I was saving all my TSC files. I love KDE, but it's search has always sucked, and continues to do so. :(

You might want to try the `find` command then. I’ve found it much more powerful than any GUI search I’ve ever come across. `$ find -iname '*tsc*' /home/bugsbane`. (`-iname` makes a case-insensitive search, `*tsc*` is a wildcard pattern that says “everything that somewhere contains ‘tsc‘” (it needs to be quoted with `'` so prevent the shell from thinking it’s a shell glob), `/home/bugsbane` is the directory to recursively search below)

> I'm thinking maybe a crate like the others, with small lightning bolts, about the same size as the arrows here, scrolling upwards.

As long as no confusion results with the ordinary powerup box which also has lightning bolts, this sounds fine.

Vale,
Quintus

**Comment by Quintus** [comment]
@Bugsbane Status of this?

Vale,
Quintus

**Comment by Bugsbane** [comment]
It's basically done. I just need to know how many frames of animation are needed and the file names. I just couldn't find where the original animation frames were to replace.

**Comment by Bugsbane** [comment]
Ok, so I have the frames, but I wasn't able to find the block in the editor, so I haven't been able to check the animation. It's just simple vertical movement so it should be ok.

![power_1](https://cloud.githubusercontent.com/assets/401733/12189032/7d56cec4-b588-11e5-8c96-182f3e528467.png)
![power_2](https://cloud.githubusercontent.com/assets/401733/12189034/7d5ca1aa-b588-11e5-86c4-377412dee01d.png)
![power_3](https://cloud.githubusercontent.com/assets/401733/12189033/7d5c7b08-b588-11e5-8f70-e25554a5eeed.png)
![power_4](https://cloud.githubusercontent.com/assets/401733/12189035/7d601a60-b588-11e5-860e-d58b02d379bd.png)

**Comment by Quintus** [comment]
> but I wasn't able to find the block in the editor

Place any regular box, double-click it, and change the "animation" to "bonus".

> If it's acceptable, just let me know

I think it looks good. @datahead8888, @sydneyjd what do you think?

Vale,
Quintus

**Comment by DarkAceZ** [comment]
Looks nice.

**Comment by Bugsbane** [comment]
Took a look at it in the game. There were some alignment issues in the animation and the lightning bolts were a bit too small. [Here's](powerup-crate.tar.gz) a revised set that look all right in the game, along with the settings files and the original Inkscape SVG source.

![power_4](https://cloud.githubusercontent.com/assets/401733/12212855/06bbe33e-b63d-11e5-961d-c9b099798581.png)
![power_3](https://cloud.githubusercontent.com/assets/401733/12212856/06c2ba88-b63d-11e5-896d-54c5648bce9f.png)
![power_2](https://cloud.githubusercontent.com/assets/401733/12212857/06c421ca-b63d-11e5-9cbd-2322a314217a.png)
![power_1](https://cloud.githubusercontent.com/assets/401733/12212858/06cd6e60-b63d-11e5-8740-f5cccb96f595.png)

**Comment by Quintus** [comment]
> [Here's](https://github.com/Secretchronicles/TSC/issues/powerup-crate.tar.gz) a revised set that look all right in the game

I get a 404 error if I try to access that link.

**Comment by Bugsbane** [comment]
Weird. It seems to have changed the link to a github link. Try [this link](http://xymail.info/downloads/powerup-crate.tar.gz) insead.

**Comment by Quintus** [comment]
Okay thank you! I will add this soon :-)

**Comment by Bugsbane** [comment]
Thanks!

**Comment by Quintus** [comment]
Btw. @Bugsbane, GitHub seems to not associate the email address in the commits to your user account. You should add the gmail address to your GitHub account to fix that.

Vale,
Quintus

**Comment by Bugsbane** [comment]
I don't use an gmail account any more. Is there any way to update things to a more current email address?

**Comment by Quintus** [comment]
Not without rewriting Git history to change the email address of those commits to another one. For future commits, I can use the xy address if I make commits for you then. I just used the gmail one because that was the address of all commits associated with you in TSC.

Vale,
Quintus
