### ISSUE TITLE
Replace the Star Power Up Graphic...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#267]
We need to replace the star power up with a new power up graphic (probably a berry power up like the others).

This is follow up to task #213.

**Comment by datahead8888** [comment]
I found an old power fruit discussion on secretmaryo.org:
http://www.secretmaryo.org/phpBB3/viewtopic.php?f=10&t=987

We don't have to do things the same way at all, but it is an interesting point of reference as to the range of possibilities.

**Comment by sydneyjd** [comment]
I may see what i can do on this yet since i don’t have anything else on my hands.

**Comment by sydneyjd** [comment]
@datahead8888 What do you think? http://gifmaker.cc/PlayFrameAnimation.php?folder=2015012214ZHe4rDXwMetKBBC5di1iGq
![2](https://cloud.githubusercontent.com/assets/8949851/5869653/8bbaae0c-a28a-11e4-9de8-5e73132950f2.png)


This is WIP.

**Comment by datahead8888** [comment]
I really like the animated glowing effect!

I wouldn't go that dark toward the center.  What you could do is implement a bit of shading on the first animation frame, and then make all subsequent frames become a bit brighter throughout the body (coordinated with the light that emanates outward).  Once the emanating light starts retracting, you could then make the whole body start to grow dimmer again each frame.

It also might be interesting to try a texture.  This looks like a technique that might work: http://tutorialgeek.blogspot.com/2010/11/texture-in-inkscape.html.  You would just have to make it yellow instead of gray, but the rough paper texture they use could probably work for a lemon surface.  The only question is how it would look once we shrink the size to make it fit in the game.  We could look into whether it's possible to scale (resize) the texture if this becomes a problem.

**Comment by sydneyjd** [comment]
@datahead8888 Im having trouble figuring out a texture that seems to fit lemon well, and making it fit his shape. Here is a pic.
![3](https://cloud.githubusercontent.com/assets/8949851/5912872/4a9a565e-a5a8-11e4-8413-008474a94995.png)

**Comment by Quintus** [comment]
The rounding isn’t optimal. It looks too flat. Maybe try moving up the radial gradiant? Or even apply two radial gradiants, one for the top, and one for the bottom?

Vale,
Quintus

**Comment by datahead8888** [comment]
@sydneyjd, did you add an additional rectangle and apply the filter to it?  It should be possible to apply a filter just to the lemon.

I'm not sure on the radial gradient at the moment.

Could you post your SVG?

**Comment by sydneyjd** [comment]
I guess i should be working on this more but I’ve been kind of preoccupied the last couple days.
https://cloud.openmailbox.org/public.php?service=files&t=d2abbcfe9aa4f3e2f6faa7a4e42f6a44

**Comment by datahead8888** [comment]
@Bugsbane, do you think you might have any advice on how to use a filter on this lemon?  We were targeting it for the star replacement.  I messed around with the stone filter and played around with some other ones, but I'm not sure offhand what the best advice here is.

**Comment by Bugsbane** [comment]
Sorry. I actually don't have a lot of experience with filters as I tend to do most stuff by hand, beyond basic grains and textures. I don't know that he actually *needs* a filter at all, although I would try and make the glow a color that was a bit different to his fill color to differentiate the two.

**Comment by datahead8888** [comment]
The original idea of the texture was to simulate the surface of a lemon and achieve a high level of detail.

If a texture isn't the best approach, what might be another way to do it?  If a texture or detailed surface isn't needed at all, that is fine, too.  Either way, it'd be great to wrap up this task.  There's really no reason we can't target this for release 2.0 at this point if we come up with a decision/solution to this.

>  I would try and make the glow a color that was a bit different to his fill color to differentiate the two.

@sydneyjd, do you think this might be something to try?  Maybe an orange color for the glow might work?

**Comment by sydneyjd** [comment]
Whats everyone's opinion on this? @DarkAceZ @datahead8888 @Quintus @Bugsbane Should i try for orang'er yet?  
http://gifmaker.cc/PlayFrameAnimation.php?folder=2015021514gFvwyk44pxqhFPfpwW9n6I

**Comment by DarkAceZ** [comment]
The coloring is great, but the lemon looks flat, like a piece of paper. Maybe that'll change if I were to see it in-game, though.
How is it going to move? The same way the star does/did (bouncing)? That's important based on how the end graphic looks.

**Comment by Bugsbane** [comment]
The orange definitely looks better. I'd consider trying white though as it's a bit more of a generic color for light.

**Comment by datahead8888** [comment]
> I'd consider trying white though as it's a bit more of a generic color for light.

Good idea :)

**Comment by Bugsbane** [comment]
> we might consider getting this in the game and maybe playing with the graphic more later.

I'd be fine with this.

**Comment by sydneyjd** [comment]
@datahead8888 @Quintus @Bugsbane @DarkAceZ Here is him with white shading. I tried making him have more of a gradient also.
http://gifmaker.me/PlayVideoAnimation.php?folder=2015021614sP45IWEBWXmVV7MvfpsiSI&file=output_Y21BlE.mp4

**Comment by Bugsbane** [comment]
Cool. For the moment, I think this'll do nicely. Eventually, it would be good to get the eyes and mouth matching the style of eyes / mouths elsewhere in the game, but that can be for a later update.

**Comment by sydneyjd** [comment]
Here is a copy if anyone wants to call it cuts, or wants to play with it. 

I license the following .SVG and .PNG files in this post as CC-BY SA 4.0...

![4](https://cloud.githubusercontent.com/assets/8949851/6223022/040606ee-b62d-11e4-9476-ce9c99247d26.png)
![5](https://cloud.githubusercontent.com/assets/8949851/6223024/04261286-b62d-11e4-8102-5a4f2a335b2b.png)
![6](https://cloud.githubusercontent.com/assets/8949851/6223023/04244b4a-b62d-11e4-8a0f-021cd7d0fe66.png)
https://cloud.openmailbox.org/public.php?service=files&t=aa83bdf6e25628a87895fa932b643305

**Comment by sydneyjd** [comment]
No they are not all the same^. :stuck_out_tongue:

**Comment by datahead8888** [comment]
> I license the following .SVG and .PNG files in this post as CC-BY SA 4.0...

@sydneyjd, I know it's a legal technicality, but Quintus has suggested using CC-BY_4.0 instead for the project for new assets.  It is actually a different license.  To switch to the other license, you'd have to make the license statement again.

**Comment by sydneyjd** [comment]
Oops, i didnt realize that.
I license the following .SVG and .PNG files in this post as CC-BY_4.0... ? 

https://cloud.openmailbox.org/public.php?service=files&t=aa83bdf6e25628a87895fa932b643305
![4](https://cloud.githubusercontent.com/assets/8949851/6233439/d99464a4-b6a0-11e4-9ad6-7cb77e4e73dc.png)
![5](https://cloud.githubusercontent.com/assets/8949851/6233440/d99de75e-b6a0-11e4-8bd2-a5a1fe3b71b6.png)
![6](https://cloud.githubusercontent.com/assets/8949851/6233441/d9a18f9e-b6a0-11e4-8429-3e608e96197a.png)

**Comment by datahead8888** [comment]
This is one of the few tasks marked release 2.0 with graphics ready to commit.  When one of us gets time, we need to get these committed and close this.  Further enhancements to the lemon can be done in a new ticket.  We might as well remove the star and replace it with the lemon in release 2.0 -- it's one less Nintendo similarity.

**Comment by Bugsbane** [comment]
I'd like to make further enhancements (I have some ideas about getting more consistency throughout our assets on eyes and mouths), however I agree that right now it's probably better to just commit and be open to updating later (the familiarity principal notwithstanding).

**Comment by sydneyjd** [comment]
@Bugsbane Feel free to do what you want  with it. Right now i am taking 
a break from TSC graphics for a while.

**Comment by datahead8888** [comment]
I have started working on getting this into the release as I get time.
I committed Sydney's graphics to the LemonReplacement branch.
To do:
* Rename the png files from star.png names to lemon.png names
* Add compatibility code for the new name
* Add animation frames code
* Test in-game

**Comment by datahead8888** [comment]
I worked on it a little tonight.  For some reason, after renaming the star files as lemon files and after adding compatibility code, the lemon option was still not accessible from the level editor menu, and reverse compatibility for stars did not work.  I also tried doing a complete rebuild and clearing cache.  The commit is: https://github.com/Secretchronicles/TSC/commit/fc60a1a2ed5cdc11d4c37ff9cbdb7824e193b0b7

**Comment by Quintus** [comment]
Implemented by 133ac464d41309095bd817f99eb4e81dc27e825b.

Vale,
Quintus

**Comment by datahead8888** [comment]
Does it display all 3 of the lemon frames?  I did not have a chance to test that.

Thanks, Quintus.  Sydney will be glad to see it in the release, I know.

**Comment by Quintus** [comment]
> Does it display all 3 of the lemon frames? I did not have a chance to test that.

Not right now. I overlooked that, thanks. Will implement that later today, probably with the cookie.

Vale,
Quintus
