### ISSUE TITLE
Replace the moon power up graphic...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#269]
We need to replace the moon power up with a new power up graphic .

This is follow up to task #213.

**Comment by Quintus** [comment]
@datahead8888 is very concered that the moon is too much of a Mario resemblance. I share this view, so we should strive to get it out. @Bugsbane, the moon is a simple nonmoving two-frame asset ([PNG1](https://github.com/Secretchronicles/TSC/blob/v2.0.0-beta7/tsc/data/pixmaps/game/items/moon_1.png), [PNG2](https://github.com/Secretchronicles/TSC/blob/v2.0.0-beta7/tsc/data/pixmaps/game/items/moon_2.png), [SVG](https://github.com/Secretchronicles/TSC/blob/v2.0.0-beta7/drafts/game/fluxy/level/items/moon.svg)). Do you think you can come up with something simple to replace it for now? Later improvements are of course very welcome, but for 2.0.0 we should see to get this out of the game.

Vale,
Quintus

**Comment by Bugsbane** [comment]
Sure.

As long as we're on a fruit theme, part of me is tempted to use a durian fruit. It's kind of exotic and not found everywhere (like the star) and is pointy and almost slightly star shaped itself. It will likely give anyone familiar with south east asian culture a chuckle, too.

**Comment by Quintus** [comment]
> As long as we're on a fruit theme, part of me is tempted to use a durian fruit.

I’m fine with that. Note that it’s also possible in later versions to change mechanics of this asset.

Vale,
Quintus

**Comment by sydneyjd** [comment]
@Quintus @datahead8888 @Bugsbane @brianvanderburg2  (and anyone else) @Secretchronicles/artists 

Here is an at least temporary moon replacement.

I licence the following .PNG files in this post as CC-BY SA 4.0... ( if thats correct)

![moon_1](https://cloud.githubusercontent.com/assets/8949851/6767752/c99cc666-d01a-11e4-8974-595aacabfe19.png)

You want the animation with the 18 slides?

**Comment by DarkAceZ** [comment]
Is it just rotating? We can do that in the game code, if so.
But I'm not sure if rotating is what we want... Maybe we could have small cookie crumble particles emit from it, because that's something new. :-P

**Comment by sydneyjd** [comment]
I like the cookie crumble idea! That sounds awesome! Is that too hard to do @Quintus @datahead8888 ?

**Comment by datahead8888** [comment]
> Is that too hard to do @Quintus @datahead8888 ?

I doubt it's hard, but I haven't worked with the particle emitters.  Just please don't add a crunching sound when Alex grabs a cookie :)

**Comment by sydneyjd** [comment]
Even better idea datahead!!! Why not? :P

**Comment by sydneyjd** [comment]
Datahead was saying that they talked of a crunch sound effect when they put waffles in instead of coins. I do agree that it is pushing it a little too much. I would probably nt have a crucnh sound efect with cookie-moon.

**Comment by Quintus** [comment]
@sydneyjd Particle emitters aren’t too hard to use. Can you please post the SVG?

Vale,
Quintus

**Comment by sydneyjd** [comment]
I licence the following file/s in this post as CC-BY SA 4.0.
https://cloud.openmailbox.org/public.php?service=files&t=97c4c6e2463d06f72cfc5321cbda0574&download

**Comment by datahead8888** [comment]
Sydney, I know it's technical, but the license that is compatible with the project is CC-BY_4.0.  If you can remake your license statement, it will cover this.

We probably should talk with Quintus to see if you could make a one time statement like Bugsbane did.  Then you would not have to state the license for every single image you post.

**Comment by sydneyjd** [comment]
Ok, well then

I list my last post in this thread (before this one) and all files in it 
under CC-BY_4.0.

**Comment by Quintus** [comment]
I’ll look into the particle emitter thing.

Vale,
Quintus
