### ISSUE TITLE
Add some new levels

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#276]
We need more levels showing our new facilities. @sauer2, do you think you could create one or two further levels for us? Or adapt existing ones?

Valete,
Quintus

**Comment by Quintus** [comment]
We do have some new levels now. New ones are of course always accepted, but I think we can close this.

Vale,
Quintus

**Comment by datahead8888** [comment]
Not needing more levels or a new world seems to be one thing we agree on for release 2.0 :)

As you said, we don't need a task to add extras if we get them.

Just go ahead and close this...
