### ISSUE TITLE
Some keys don’t work when pressed together

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#278]
It seems that some keys on some keyboards on some systems don’t work if pressed together. For example, I can’t press SPACE and CTRL at the same time, the game will only receive one. But this is only happens with my laptop’s internal keyboard, with an external USB one the problem doesn’t appear. @sauer2 [reported something similar](https://github.com/Secretchronicles/TSC/issues/276#issuecomment-66636391) with the A and S keys. Workaround so far is to change the action keys in TSC to something different.

This may or may not be a hardware issue. It may also be that our input handling is flawed in some subtile way.

Vale,
Quintus

**Comment by datahead8888** [comment]
It looks to me like up and right/left may not work properly together.  It seems that if you hold up and one of these other keys, you stop moving right or left, which makes it more difficult to control Alex.  I am using an XBox 360 controller in my laptop.

**Comment by datahead8888** [comment]
To clarify, the issue with holding directional keys together would be the worst when you are trying to catch a rope hanging over a pit.  This might be one of the reasons people keep having trouble with the Rokko pit in my Desert Break In level.

**Comment by datahead8888** [comment]
I was recently playing the game and found this issue to be hassling me in the first level, when I accidentally held up and another direction at the same time.  I think this is the highest priority bug we have right now, apart from any known SFML bugs.  What does everyone else think?

**Comment by datahead8888** [comment]
I was, however, playing in the devel branch, so we will want to test this again after merging the SFML changes into devel.

**Comment by Quintus** [comment]
When playing STK today and afterwards browsing their website, I came about their FAQ which has an entry for something that looks like the exact same problem: http://supertuxkart.sourceforge.net/FAQ#Some_keyboard_keys_do_not_work_when_pressed_simultaneously

**Comment by Quintus** [comment]
The STK website has been redesigned. One can't link to specific questions anymore, but the question is still on the FAQ page at https://supertuxkart.net/FAQ.

**Comment by datahead8888** [comment]
This is definitely an issue that we should probably try to fix in the current codebase.

**Comment by Quintus** [comment]
> This is definitely an issue that we should probably try to fix in the current codebase.

Read the STK FAQ. It is likely a non-issue (aka hardware limitation), but without further investigation I didn't want to close this.

Vale,
Quintus

**Comment by Quintus** [comment]
Closing as an upstream issue; if at all, this is something SFML has to resolve. Cf. the STK docs mentioned.
