### ISSUE TITLE
InvalidLevelError terminates game if save state file references level that doesn't exist...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#283]
If you load a save state file that loads a level that does not exist, it will terminate the game with an exception.

In this case, we should probably print a user friendly error on screen, while still displaying technical information in the console.

Steps to reproduce:
* Create a new level
* Save your game state in that level
* Rename the level on the file system such that the file name used in the save state file no longer exists
* Load your game state file
* Your game will terminate, and you will get the following exception:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unloaded level: /home/datahead/.local/share/tsc/levels/hiccup.smclvl
Loading savegame file '/home/datahead/.local/share/tsc/savegames/1.smcsav'
Loading savegame file '/home/datahead/.local/share/tsc/savegames/1.smcsav'
terminate called after throwing an instance of 'TSC::InvalidLevelError'
  what():  Empty level filename!

Program received signal SIGABRT, Aborted.
0x00007ffff48c70d5 in raise () from /lib/x86_64-linux-gnu/libc.so.6
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Level (renamed from hiccup to hiccupX): https://drive.google.com/open?id=0B6YSsocq3-cWM0hTNWJaYktnYWc&authuser=0
Save state file: https://drive.google.com/open?id=0B6YSsocq3-cWVGx2ZHlpOTlyNk0&authuser=0

**Comment by datahead8888** [comment]
> Shouldn’t the exception really originate from pSavegame::Load() so that it can more easily be cought in the already existing try/catch block around that call in Update_Load()? It would be good that if it could be avoided to load everything twice, because the game is slow enough already...

Yes, I boxed myself into thinking I had to use the exceptions already thrown and not throw new ones.  Thanks for the suggestion, @Quintus.  I had to catch the exception in more places than I thought, though, because this function gets called in a number of places.

This is fixed with commit id 13cf0d9dcde576a39c2fda8e0ba80728d481bd52 in the release-2.0.0 branch.  I apologize for forgetting to use the closes syntax in the comment for one of the commits.  Thus this issue can be closed once that commit is merged to devel.

**Comment by Quintus** [comment]
Nice. So now not everything is loaded multiple times? Thanks for your work.

Vale,
Quintus

**Comment by datahead8888** [comment]
> Nice. So now not everything is loaded multiple times? Thanks for your work.

You are correct.  I threw those changes out and did it based on save data that's already loaded.  Your suggestion helped me realize I should do this.

We may want to run a test to see if it's possible to create a save state file that references a world that doesn't exist.  That will be a different bug if it crashes the game, though.
