### ISSUE TITLE
Create Brand New Hedge Graphics...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#298]
In task #256, we removed the SMB3 style hedge for now.  On @SonOfBowser's suggestion, we're probably going to make it use a different image that we already have in its place for now.

This task is to create a brand new hedge image to replace the old one directly.  It will need to not be recognizable as a Mario style hedge.

The SMB3 style hedge SVG is at  https://github.com/Secretchronicles/TSC/blob/devel/drafts/game/frostbringer/level/ground/green_2/hedges/small_2.svg

cc @sydneyjd, @DarkAceZ

**Comment by sydneyjd** [comment]
@datahead8888 @Quintus Do we still want this, or is it too late?

**Comment by datahead8888** [comment]
There probably is still some time given that we haven't resolved the music issues and given we still have level editing work to do.  This is probably one of the easier Mario replacement tasks (though it does somewhat depend on how we do it).

@SonOfBowser - the overall shape for the new hedges should probably match the shape for the old hedges that we removed, correct?

**Comment by sydneyjd** [comment]
Hey all. @datahead8888 @Quintus @DarkAceZ @Aakburns WHats your opinions? How can i improve upon this design? 
![2](https://cloud.githubusercontent.com/assets/8949851/5609262/317cc8ea-946a-11e4-8db2-85d5d8d64974.png)

**Comment by datahead8888** [comment]
I was just thinking of the 1 big hill and 1 small hill is still too similar to the SMB3 hills.  I might be wrong here, though.

A couple other options are to to use different shades of black in the eyes and to use three hills, one big and too small.  They're just possible thoughts.

Does anyone else have thoughts on what works best for this?

**Comment by datahead8888** [comment]
cc @brianvanderburg2 (you're probably still online :) )

**Comment by brianvanderburg2** [comment]
What if the hills were replaced with other things.  Imagine background trees with a face, branches as arms.  I'm not an artist, but something like this:  http://picpaste.com/b56958db99057db60542e0fa5ea08649.png

Could also have background mountains, background houses, background books (fit's the library theme)

**Comment by sydneyjd** [comment]
Here. Opinions anyone? @brianvanderburg2 @Quintus @datahead8888 ?
![2](https://cloud.githubusercontent.com/assets/8949851/5624006/7a18ed4c-952b-11e4-941a-c1c1dd9796ac.png)

**Comment by datahead8888** [comment]
Most people probably will not connect this with the old svg, which is good.
We were eliminating eyes on clouds, etc, but since this has a complete face, I think it eliminates the problem.
We probably need to give it a try in a level, post a screenshot, and let everyone offer their thoughts.

**Comment by brianvanderburg2** [comment]
What if you get rid of the outer edges or make it thinner, and give the eyes, nose, and mouth some color and shading?

**Comment by datahead8888** [comment]
> It seems to have lost its "cuteness".

Graphics don't necessarily have to have a cuteness -- we've been going for a new look in TSC.  This graphic is a bit of an exception, since it would be nice to retain the feel of the old graphic.

The size should probably be closer to the size of the original, but we will probably have to do a little digging to get those dimensions if we want to compare.

Giving the eyes a little shading as Brian suggested might also help to make it even more distinct from the SMB3 version.  I'd be curious to see what effect thinner edges has, too.

Good work!

**Comment by datahead8888** [comment]
@sydneyjd - The dimensions for the original hedge you are replacing were:
width 32
height 32

If you use those dimensions, it should avoid compatibility (sizing) issues for old levels that used the SMB3 style hedge.

This is the link the the old settings file:
https://github.com/Secretchronicles/TSC/blob/3d031fe4a692d26b798793de4c1e59771ca87a2e/tsc/data/pixmaps/ground/green_2/hedges/small_2.settings

This is where I got those dimensions from.  In fact, that is the exact settings file I think you should be able to use on your computer when you decide to try out the hedge later.

Switch your hedge settings file to that, then add the png named as small_2.png.  These files go in tsc/data/pixmaps/ground/green_2/hedges

**Comment by datahead8888** [comment]
cc @SonOfBowser

**Comment by sydneyjd** [comment]
@datahead8888 @Quintus Here is a redone one with the hedge 32x32. It looks so small! I shrunk the outer lines and addded some 
![7](https://cloud.githubusercontent.com/assets/8949851/5651384/f526cc26-9674-11e4-928b-9fd9351e3d18.png)
![2](https://cloud.githubusercontent.com/assets/8949851/5651396/0b59fd4c-9675-11e4-9b7d-4185f2c3244c.png)

shading.

**Comment by Quintus** [comment]
I’ll leave it up to you with what you replace it -- create what you find fitting.

Vale,
Quintus

**Comment by datahead8888** [comment]
> It looks so small! I shrunk the outer lines and addded some shading.

@sydneyjd -- do this -- show it to one of your brothers, and ask what he thinks.  Don't show him the big version at first.  After that, go ahead and show him the big one.  This eliminates any subconscious bias.

We could look at making the rightmost sad hill a little larger -- it already is the smallest hill and may need to be larger to compensate for the shrinking.  Once we've tried that, it will probably work at the new size.  The new size is needed of course to maintain level compatibility.  We could add some larger hedges (with other styles) as larger assets if we wish, though.

**Comment by sydneyjd** [comment]
@datahead8888 Is this better? 
![3](https://cloud.githubusercontent.com/assets/8949851/5791278/891e9fc8-9e98-11e4-9feb-07ff51c3638f.png)

**Comment by datahead8888** [comment]
> @datahead8888 Is this better? 

Yes, I think so, but we'll need to try it in a level (where it shrinks) to be sure.

**Comment by sydneyjd** [comment]
@datahead8888 This is in level. 
![12](https://cloud.githubusercontent.com/assets/8949851/5793808/d18e59e2-9f1f-11e4-969b-1cdeda2f4c59.png)

**Comment by datahead8888** [comment]
The sizing looks good.  I'd be curious to try a few color options (with shading) in the mouth / eyes, but it's your call.
If you give me the SVG, I could also play with it later, though I don't know most of the paint options yet. 

     On Sunday, January 18, 2015 2:39 PM, sydneyjd <notifications@github.com> wrote:
   

 @datahead8888 This is in level.

**Comment by sydneyjd** [comment]
@datahead8888 ? How about this? 
![big_3](https://cloud.githubusercontent.com/assets/8949851/5811521/4938340c-a026-11e4-8f01-cacafba4c460.png)
![d18e59e2-9f1f-11e4-969b-1cdeda2f4c59](https://cloud.githubusercontent.com/assets/8949851/5811575/011c3f64-a027-11e4-9245-47da011f4b1a.png)

**Comment by datahead8888** [comment]
It's looking good.  I was thinking if we needed a smaller eye pupil size, but it can't go any smaller given that the image must be shrunken.

We might also see how white eyes look.  This might offer a little more contrast if the white color works.  Alex's eyes are also white pupils on a black eye.  Keep a backup of the last one if you try anything new.

**Comment by sydneyjd** [comment]
@datahead8888 Here is white. 
![1](https://cloud.githubusercontent.com/assets/8949851/5830658/cce902b0-a0f1-11e4-8f5b-ebcabe59f177.png)
![d18e59e2-9f1f-11e4-969b-1cdeda2f4c59](https://cloud.githubusercontent.com/assets/8949851/5830660/d34d80cc-a0f1-11e4-93c8-e04f007c1635.png)

**Comment by datahead8888** [comment]
If we go with white pupils, we might consider making the pupils a little smaller (smaller radius) so that the ratio of pupil to eye feels about right.  If we go with blue pupils, we should probably continue using the same radius, since blue is a bit harder to see on black, necessitating the larger radius.

It'd probably best for me to let you make a judgement call as to which of the options (and sizes work best) and then commit it to git.

I do think having some sort of color (white, blue, etc) on top of the black as we just tried is good, since it differentiates it from the old SMB3 style hedge.

Great work!

**Comment by sydneyjd** [comment]
@datahead8888 Is this any better? I dont think it seems right to go much smaller. 
![1](https://cloud.githubusercontent.com/assets/8949851/5849134/22a7ab80-a1af-11e4-8e74-ec959e64c008.png)

**Comment by datahead8888** [comment]
Yes, I think that's good.  Can you post the SVG?

**Comment by sydneyjd** [comment]
@datahead8888  https://cloud.openmailbox.org/public.php?service=files&t=9449024f2674ebd57f6b5eec1ba37e0c

**Comment by datahead8888** [comment]
@sydneyjd -- is the png graphic you last posted in this ticket the correct png?  If so, I can just upload it when I get a chance (with the SVG).

**Comment by sydneyjd** [comment]
Yes it is.

**Comment by datahead8888** [comment]
Could you confirm the type of license (CC-By-SA-4.0 is what we often use now)?

This has to be confirmed in github (as opposed to the forums) because there is no checkbox to signify acceptance of a default license.  Licensing has also been a major focus for TSC 2.0.

**Comment by sydneyjd** [comment]
How do i do that?

**Comment by datahead8888** [comment]
State something such as, "I license these SVG and PNG files as CC-BY SA 4.0", and give a link to the files again.

This is what Quintus suggested for me to do on my own stone graphics task (though I can't just use this license on them because they are derived from images under a different license).

**Comment by sydneyjd** [comment]
Ok, as @datahead8888 requested...

I license the following .SVG and .PNG files in this post as CC-BY SA 4.0...

![1](https://cloud.githubusercontent.com/assets/8949851/5866433/36eedb12-a25f-11e4-9f08-3011dec18b18.png)

https://cloud.openmailbox.org/public.php?service=files&t=9449024f2674ebd57f6b5eec1ba37e0c&download

**Comment by datahead8888** [comment]
![hedgeville](https://cloud.githubusercontent.com/assets/6478551/5885795/94e05f88-a346-11e4-86c7-a43c11e0f08b.png)

**Comment by datahead8888** [comment]
@SonOfBowser - We finally have a direct replacement for the SMB3 style hedge that we had outright removed before.
@sauer2 - You had said you sometimes saw hedges appear with a red background behind them in levels (and that you were removing them I think).  If you still have a level that displays this red object, could you test again in case this change happened to fix it?  I am curious...

**Comment by sauer2** [comment]
@datahead8888 OK, will do.
@sydneyjd Nice job, but please don't keep the noses. In particular, not the triangle nose.

**Comment by sauer2** [comment]
@datahead8888 That seems to be fixed at the first and second glance.

**Comment by datahead8888** [comment]
> Nice job, but please don't keep the noses. In particular, not the triangle nose.

We've been posting pictures for quite a while :P 

The idea of having a nose is to have a complete face, which is supposed to differentiate it from the old SMB3 style hedge.  The old one only had eyes.  Another option might be coloring it, but I can't think of any way to add color without maybe making it over goofy.  I could be wrong, though.
See:  https://github.com/Secretchronicles/TSC/blob/devel/drafts/game/frostbringer/level/ground/green_2/hedges/small_2.svg

@sydneyjd, what do you think about the nose?

> @datahead8888 That seems to be fixed at the first and second glance.

Great!

**Comment by sydneyjd** [comment]
I like the noses personally, I think it would be weird without them. A
nose-less face? I’ve never heard of such a thing. :P

**Comment by datahead8888** [comment]
>  like the noses personally, I think it would be weird without them. A nose-less face? I’ve never heard of such a thing.

You could go either way in TSC, but I think the noses work.

**Comment by Bugsbane** [comment]
I would definitely suggest avoiding the noses, at the very least. Personally I would also suggest leaving off the eyes, too. Remember, one of the things that made the mario games so enchanting was the feeling that everything was alive, even if it wasn't a character in it's own right. They did this by giving most objects eyes, without giving them full faces.

Now elsewhere, we discussed wanting to get away from putting eyes on everything to distance ourselves from the Mario games (although personally, I see the eye's as being more of just a Japanese manga thing, rather than Mario specific). What I suggested there, which personally I would prefer to be just part of our general style guidelines, is that we use no eyes / noses, but just subtle mouths, as I've already been doing with the crates.

Regardless of this though, I do feel that the noses look a bit strange, and unnecessary to give expression.

**Comment by datahead8888** [comment]
> Personally I would also suggest leaving off the eyes, too. Remember, one of the things that made the mario games so enchanting was the feeling that everything was alive, even if it wasn't a character in it's own right. They did this by giving most objects eyes, without giving them full faces.

Yes, this is what we were originally doing in ticket #236.  In this ticket, we were basically trying to find some way to keep the hills "fun" and not make them just be a bare texture, so as to speak.  Sydney put a glimmer of light in the eyes in order to try and give it a different look than the Super Mario Bros. 3 counterpart.  My thought is that eyes on some objects isn't necessarily a Marioism, depending on the frequency and eye style.

We can continue to discuss this, though.  If eyes really are a problem, they will have to be removed.  I'm fine with or without noses myself.  We could also try triangle noses rather than circle noses if that might work better.  We should probably ask @sydneyjd for his input before anyone touches this image.  He's already edited this image quite a bit, though, so if you're able to try a few edits for evaluation, it will give him a break from this task.

**Comment by sydneyjd** [comment]
If you waht to edit it @Bugsbane To see if you can improve, go right ahead. I personally like them very much as they are, but if you feel otherwise, feel free to say so.

**Comment by Bugsbane** [comment]
I'll try and take a play with it in the next few days to see what I can come up with. Very busy right now, but I'll see what I can do.

**Comment by datahead8888** [comment]
> Now elsewhere, we discussed wanting to get away from putting eyes on everything to distance ourselves from the Mario games (although personally, I see the eye's as being more of just a Japanese manga thing, rather than Mario specific). What I suggested there, which personally I would prefer to be just part of our general style guidelines, is that we use no eyes / noses, but just subtle mouths, as I've already been doing with the crates.

@Bugsbane, if you think a ban on eyes should be put in place for all background objects, this seems reasonable.  Much as I followed a line of logic on the the 1-Up ticket, you are following a line of logic on this style standard.  I do want to respect Sydney's thoughts on this, though, as he put a lot of time into the hedge.

I'm not sure on banning eyes on power up objects such as the lemon, but we can certainly discuss this.

If you make a new version of the hedge, try to incorporate what you can from Sydney's work if you can.

**Comment by Bugsbane** [comment]
I don't think eyes need to be banned outright, but I do think that we need to be consistent and work it into the style guide. The key is think about how things look in the context of the whole game, not just whether we like the look of one asset.

Personally, I love the look of having eyes on everything, and would be happy to keep them throughout. That is clearly a strong SMB reference, which people seemed against elsewhere (thus the discussion of just eyes vs just mouths etc in the first place).

If we're not doing that, my thinking is that we leave eyes off background objects (including massive and half massive ground items), but allow them on interactive items such as enemies, powerups etc. This way, eyes are used as another element that focuses the players attention the most on the key objects in the game.

Either way, I do feel that noses just distract as they're not actually a facial feature that expresses any emotion. As to an example of faces without noses, just look up any smiley. :)

**Comment by Quintus** [comment]
I’ve followed this discussion silently, now I think I want to express my opinion on this. I think we should avoid eyes, because we are aiming for our own style. SMB may be a nice game, but we don’t want to be the eternal clone of it. We should aim to not have more references to SMB than any other platform game (though subtile references to several games can be really cool if used sparingly so they will only be seen by those paying enough attention to the gameplay; I love how later Zelda games tend to make references to OoT).

Vale,
Quintus

**Comment by datahead8888** [comment]
> Personally, I love the look of having eyes on everything, and would be happy to keep them throughout. That is clearly a strong SMB reference, which people seemed against elsewhere (thus the discussion of just eyes vs just mouths etc in the first place).

No, I don't think having strong SMB references (ie lots of eyes on lots of background objects) is a good idea.  We need to heavily diverge from Marioisms in the next few releases in order to break the Mario clone perception and stop suffering the consequences that come with it.

The main question was whether eyes on just a handful of background objects (or with a different style of eyes on these few objects) is too major of a consistency break or if it still gave this Mario impression.

I get the impression people want to enforce the no eyes rule across the board on all background objects, in which case this hill will have the eyes and nose both removed.  I'm not sure a mouth by itself would work on the hill, honestly.  In this case the hill will wind up being fairly bland (which is what we've been doing on some other background objects), but I guess we'll see how things turn out.

If we edit the hill further I propose we reopen the ticket.

**Comment by sydneyjd** [comment]
well, if you all feel it is a must to remove the eyes, we might as well. 
I personally like them on, but i will run up a draft of it with them 
off. I will probably remove the mouth as well then, since only a mouth 
on them would be awkward IMO.

**Comment by datahead8888** [comment]
Just to explicitly ask this question - does everyone feel that having eyes on one object or a few objects but not on most objects breaks style or otherwise looks like a major Mario reference?

**Comment by sydneyjd** [comment]
I don't consider it a major mario reference IMO. 
Here is a pic of the hedge plain. 
![1](https://cloud.githubusercontent.com/assets/8949851/6233839/e702b4f8-b6a3-11e4-85ed-b4c84abae3ed.png)

**Comment by sauer2** [comment]
@datahead8888 
Depends on the expression and style, I think.

**Comment by datahead8888** [comment]
***I meant background objects for this question, though I think that was implied based on the previous discussion.

**Comment by datahead8888** [comment]
Quintus said that his opinion above means he does not think we should have eyes on the hill.

**Comment by Quintus** [comment]
So it appears there are quite some different points of views on this. Let me first clarify to you @sydneyjd that what we’re discussing here is not meant to disvalue your work. You are doing great, and I hope you will continue to support the game. The eye topic is problematic due to the Mario resemblances; not from a copyright site probably, but more from how far we want to depart. It has nothing to do with your hard work on the graphic, which I appreciate and I am sure everyone else involved here appreciates as well. Don’t take this discussion as a matter to bring you down in some way.

@Bugsbane is correct that _we need to find a consistant style for the project_, and I agree with him that eyes should not be used as it is too much of a Mario reference. The style is part of our identity as a project and is what we are recognised with, and to make a good game it is very important to stick to the chosen style. A graphic may be great on itself, but it will look weirdly out of place if it doesn’t fit the surrounding style. Too much derivations from the chosen style will make the entire game look inconsistent and unplanned, even though all the graphics are each of high quality.

I suggest that we have a bit of discussion with more people before we make a decision here. @brianvanderburg2 and @Luiji, could you post your opinion with regard to the amount of eyes we should allow in the game? @sauer2, as a level designer, do you think this asset looks out of place too much with all the other eye assets removed or modified accordingly?

I have outlined my position above again, and please note that I’m not arguing on the quality of the graphic. It’s good. That’s not what we are discussing about. Thus, as a compromise, we could leave the graphic as-is, but do not use it in the official levels, so it is available for anyone in the level editor. If we can’t find a solution on which everyone can agree, we’re going to vote on the subject, but for now we should try to really find something everyone is content with.

Vale,
Quintus

**Comment by Luiji** [comment]
@Quintus calls for the opinions of all, I shall provide my component.

The eyes are, to an extent, a component of the Super Mario World art style. I would recommend avoiding anthromorphising too many inanimate objects for the sake of providing our own, unique art style.

**Comment by brianvanderburg2** [comment]
@Quintus I agree that eyes (and maybe for that matter noses and mouths) should not be used to often for the regular, inanimate objects.  They do reflect SMW quite a bit.

I think the same could possible be said with other graphics and concepts:
* The spinning block resembles SMW even with the new graphics, just looks like a spinning crate instead.  What if instead of spinning it shrinks and disappears for a brief time then reappears, or becomes semi-transparent then fully opaque again.
* The fireball attach resembles SMW and most of other Mario games.  I don't know if any of them had an ice ball attack.  Perhaps the fireball could be replaced with a bouncing mini-bomb that does a small explosion on impact with the enemy.
* Vines (perhaps replace with ladders or stairs of some sort)
* Probably others

**Comment by Quintus** [comment]
Okay, thank you two. So you aren’t against any eyes in the game, but they should be restricted to very few objects? Sounds acceptable to me. The vast majority of objects shouldn’t have any eyes then.

As it stands currently, the topic is on the discussion schedule for our General Discussion on 21st. Which gives me opportunity to mention to @Bugsbane that there is going to be a larger IRC meeting soon, please see [this forum post](http://forum.secretchronicles.de/topics/220). Quite a lot of people have already indicated that they’re going to join. Followup announcement with entire discussion schedule is nearly, I just wait for approval by @Luiji.

I have hopes that we can bring this topic to conclusion without voting by restricting eyes to a limited number of objects. Once this more general question is resolved, we should decide how to proceed with sydney’s hedge graphic.

Valete,
Quintus

**Comment by datahead8888** [comment]
This seems like a reasonable compromise.  We would want to decide what other objects or type of objects can have eyes besides the hedges.

Also, I seem to remember seeing some other hills or other objects with eyes.  Does anyone remember seeing them?  If so, we would want to evaluate them and decide if they pose a problem against our eye style guidelines.

**Comment by Quintus** [comment]
> Also, I seem to remember seeing some other hills or other objects with eyes. Does anyone remember seeing them?

Several background graphics have them, and I have to say that that’s a place where I definitely don’t want them:

* https://github.com/Secretchronicles/TSC/blob/v2.0.0-beta7/tsc/data/pixmaps/game/background/blue_waterhills_1.png
* https://github.com/Secretchronicles/TSC/blob/v2.0.0-beta7/tsc/data/pixmaps/game/background/green_hills_2.png
* https://github.com/Secretchronicles/TSC/blob/v2.0.0-beta7/tsc/data/pixmaps/game/background/green_junglehills.png

There are possibly more objects with eyes, I just don’t remember them right now.

Vale,
Quintus

**Comment by datahead8888** [comment]
Yes, the second image was the one I was remembering -- it was very heavy eye usage in a level.

**Comment by Quintus** [comment]
> Also, would it be useful if maybe we had a "DeMarioization" label or "Legal" label, to make it easy to find all tickets involving Marioisms?

Done.

**Comment by Quintus** [comment]
It was [decided by the Team’s General Discussion](http://www.secretchronicles.de/en/news/2015/03/22/results-of-first-general-discussion/) that the hedge remains in-game for now. The issue is not finally decided on, so I leave it open, but remove it from the 2.0.0 milestone.

Valete,
Quintus

**Comment by datahead8888** [comment]
No one needs to be assigned to this task for now, until we have a general team meeting to make a decision on this.

**Comment by Bugsbane** [comment]
My take on it with "mouths instead of eyes" as I've talked about before to lose to SMB look, while keeping the friendly fun, "everything is alive" feel.

http://duruz.com/smiley-hedges.svg

**Comment by Quintus** [comment]
Okay, I have downloaded it and stored it permanently on alexandria: http://team.secretchronicles.de/~quintus/store/smiley-hedges.svg

Thank you @Bugsbane! It’d be nice if you also answered @ardvark71’s questions over on the forum also: http://forum.secretchronicles.de/topics/256

I like your mouthed hill, but as this issue was a very heated discussion I’d like to see what the other ones participating in it say.

Valete,
Quintus

**Comment by ardvark71** [comment]
Hi all..

http://duruz.com/smiley-hedges.svg <--- I love it, too! You have my vote with this one! :-)

Regards...

**Comment by Bugsbane** [comment]
> I like your mouthed hill, but as this issue was a very heated discussion I’d like to see what the other ones participating in it say.

I totally understand. If you with something else, that's fine. I just had a few minutes to spare - just enough to mock that up, but not enough so read pages of debate, so I thought I'd just post it, and "let the chips fall where they may" to use an English idiom (it means to accept whatever happens afterwards).

I posted a reply in the forum too, although I'm unlikely to see the replies until I next login unless prompted. I check in here more often.

**Comment by datahead8888** [comment]
I'm honestly a little hesitant to put mouths on hills, but I might be able to be convinced to change my mind.  Mouths work really well on the blocks, but I'm not sure on hills.  I'd like to discuss it with Sydney later when there's some time.

**Comment by Bugsbane** [comment]
Sure. I'd say, all we can do is try it, and see if we like how it looks (before committing). Until then, we're just imagining if it would work or not.

**Comment by datahead8888** [comment]
Good point :)

**Comment by Bugsbane** [comment]
Ok, so here's a screenshot for people to look and and decide on:
![1](https://cloud.githubusercontent.com/assets/401733/12460621/9fafc5da-bf82-11e5-93db-875e400da97a.png)

Something to consider is that if Mario had used the eyes on blocks in just one or two places, it would have looked strange and unexpected. Because they consistently used them as a theme though, it feels part of a cohesive world. It's the same situation here.

Anyway, if people want to roll with it, here's the 128x128px version (same resolution as the current hedge pixmap):
![small_2](https://cloud.githubusercontent.com/assets/401733/12460691/fafea316-bf82-11e5-877b-3e5113eb72a2.png)

**Comment by datahead8888** [comment]
This originally caused a lot of disagreement when a hedge graphic was submitted a while back.  I think the only way to go is either to debate and/or vote in the next IRC meeting or to hold a one-off vote by email / Github.

**Comment by Quintus** [comment]
> This originally caused a lot of disagreement when a hedge graphic was submitted a while back. I think the only way to go is either to debate and/or vote in the next IRC meeting or to hold a one-off vote by email / Github.

Not necessaryly. I’m fine with Bugsbane’s suggestion, so it is upon @sydneyjd to tell us how he thinks about Bugsbane’s replacement suggestion (which will then cause his submission to get get in)?

Vale,
Quintus

**Comment by sydneyjd** [comment]
I have mixed feelings over this one. 
But i am OK with it, i don't think they look very mario'y, and they do fit with our game's "glad" style.
They do seem kinda creepy though, no eyeballs. :stuck_out_tongue: Its fine. ;)

**Comment by datahead8888** [comment]
Proceeding with Bugsbane's graphic for the hedge seems reasonable.  I would be curious to see what it looks like  side by side with some other objects that have mouths on them, though.

**Comment by Bugsbane** [comment]
> They do seem kinda creepy though, no eyeballs.

Possibly. It's worth remembering though, that some people found Mario's "eyes on inanimate objects" thing creepy too until they got used to it and it became accepted as a known stylistic thing. Now, wait until you see the blood-red version I did with fangs... ;)

**Comment by datahead8888** [comment]
I think we should target this one for the next release if possible.

**Comment by sydneyjd** [comment]
Yes we should try to get this solved before the next release. We still
need to figure out what we style we are going to chose for our hedges,
even though we have a pretty good idea at the moment.

**Comment by datahead8888** [comment]
> We still need to figure out what we style we are going to chose for our hedges, even though we have a pretty good idea at the moment.

I had thought we were going with Bugsbane's graphic, but if I am wrong please correct me.

I just meant we need to get the decided submission committed and close this ticket.

**Comment by sydneyjd** [comment]
No, i think you are correct, i must not have read everything correctly. It seems everyone is OK with the new hedges, because no one has spoken up against it. ;)  Are we good to commit this then? 

-Sydney

**Comment by datahead8888** [comment]
I see both a png and svg, so it looks committable.
I am going to mark this as version 2.1 so that we don't forget if we don't get to it right away.
