### ISSUE TITLE
Editor - can't modify destination on level exit warps

### ISSUE THREAD

**Issue by SonOfBowser** [Secretchronicles/TSC#304]
Clicking on the field closes the popup. Might be more general broken-ness from CEGUI, but this must have worked at some point.

**Comment by Quintus** [comment]
> Clicking on the field closes the popup. Might be more general broken-ness from CEGUI, but this must have worked at some point.

You first have to set the camera movement to "blink".

Vale,
Quintus

**Comment by SonOfBowser** [comment]
Makes sense; there might be a problem with older levels with the wrong movement type or with the destination name already set, but it's so minor I doubt anyone will care.

**Comment by Quintus** [comment]
> Makes sense; there might be a problem with older levels with the wrong movement type or with the destination name already set, but it's so minor I doubt anyone will care. 

I don’t think there should be any problems. To my knowledge, it has been like that already in 1.9.

Vale,
Quintus
