### ISSUE TITLE
Add pipe tops that only have 2 screws to editor...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#310]
This is a task to adjust the settings files so that we also have pipe tops with 2 screws.

Currently pipe tops can have 0 or 4 screws.
Currently pipe bodies can have 0, 2, or 4 screws.

See also the later discussion in: http://forum.secretchronicles.de/topics/158?page=2
--Sydney has posted SVG's there that he said should work for pipe tops with 2 screws.

Again, @sydneyjd and @Quintus - thank you for all you've done in pipe replacements and for your patience.

**Comment by datahead8888** [comment]
The SVG's, PNG's, and settings files are pushed to github now.
I still need to change the default number of screws to 2.  This way old pipes from old levels will have consistent numbers of screws in the tops and bodies by default.  Level editors will be free to change their pipes as they wish, however.

**Comment by datahead8888** [comment]
So I've had a change of heart :)  @sydneyjd was right - 4 screws usually will work better on the top.
Because it's a thinner piece welded at the top, the 4 screws really make sense.  Thus I'm thinking maybe we should just leave the default at the top as 4.  

It does make sense to still have the 2 screw versions available to the level editors.  That gives level editors complete freedom in customizing their pipes.  Thus if no one disagrees, we can close this task (once in devel).  It we make more changes later we can always use new tickets or just do commits and pushes.

This is a screenshot that gives a side by side comparison of a 2 and 4 screw version of the pipe top:
![2 or 4](https://cloud.githubusercontent.com/assets/6478551/5604975/ccca0a52-93b0-11e4-9a24-2d34ddf1e004.png)

**Comment by DarkAceZ** [comment]
Why is each segment outlined? That looks kind of messy...

**Comment by Quintus** [comment]
> Why is each segment outlined? That looks kind of messy...

It’s intentional. Look at my comment here: https://github.com/Secretchronicles/TSC/commit/1600e22dd15bd2a8b20fca6bcc27e483058b21e3#commitcomment-9147094

You can use the "blank" variant if you don’t want the lines.

Vale,
Quintus

**Comment by Quintus** [comment]
>  Thus if no one disagrees, we can close this task (once in devel).

I agree.

Vale,
Quintus

**Comment by datahead8888** [comment]
> I agree.

We were wrong.  2 screws are not selectable for pipe tops facing left or right, and the naming conventions for those are inconsistent with what we changed it to for the up and down variants (blank is a different convention than plain).  I must have missed some settings files.

Since this ticket is set to autoclose on a merge to devel, I guess we will have to open a new bug ticket...

**Comment by Quintus** [comment]
> Since this ticket is set to autoclose on a merge to devel, I guess we will have to open a new bug ticket...

You can always reopen a ticket after it has/was closed.

Vale,
Quintus

**Comment by datahead8888** [comment]
> You can always reopen a ticket after it has/was closed.

...and the problem is resolved now, so we can just let this ticket autoclose on a devel merge (or close it earlier if we want to again).

**Comment by datahead8888** [comment]
Okay, so I accidentally used Cf instead of fixes / closes.  :)
