### ISSUE TITLE
Pip Can Get Stuck in Walls...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#314]
When hopping on a big pip, it will split in two.  If you are near a wall, these smaller pips can become stuck in the wall.

This is a video of how to reproduce the bug:
https://www.youtube.com/watch?v=qjArPRa1jTA&feature=youtu.be

This is the level I used:
https://drive.google.com/open?id=0B6YSsocq3-cWdFJZTjZibktFMEk&authuser=0

I've also seen god Alex get stuck in a pip and seem to remember 2 pips getting stuck in each other (I think when I hopped on two big pips in a row), but I don't have evidence of these other instances of the bug at the moment.

**Comment by datahead8888** [comment]
> TSC’s collision detection algorithm has some problems generally. If you are moving fast enough, you can get stuck at basically at every massive tile.

If this is known, we probably should open a new bug ticket to track it separately.  We can prioritize it as we have time or knowledge.

> As for the pips, the generation of the small pips just places them at a fixed position relative to the original pip’s position. Changing that to honour massive tiles nearby will blow up a oneliner into a complex collision detection method. I’m not sure if that is worth the effort.

Could we change them not to used a fixed position and instead to shoot upright or upleft with a set velocity?  This will probably change the mechanics, but it would alleviate these issues.  We could file an enhancement task to change the mechanics again with more coding changes later if desired (ie increase the gravity to force them to fall down faster with the new velocity method).

If it's difficult, I think it would make sense to still leave it in the tracker.  There are lots of other tasks that are difficult that haven't gotten done yet (ie #149).  It's all about prioritization.

**Comment by Quintus** [comment]
> What would happen if they did start from the same position? Would they get stuck inside of each other?

Yes.

>  If we did this, could we maybe disable object collision code between the two of them temporarily on a timed basis?

Not without quite some code changes I fear.

Vale,
Quintus

**Comment by datahead8888** [comment]
> Not without quite some code changes I fear.

A complex code fix for this issue probably shouldn't go into release 2.0 unless we end up having a really good idea what to do and don't think it's overly risky.  To your point, it may be some time before this gets fixed.

For now we might consider editing levels so as to make this issue not obvious.  There are 2 pips in a row near the end of the first level that seem very bug prone.  I could try and post a video of the pip overlapping pip bug if needed, but I really think we need to edit the level so that the 2 big pips aren't so close to each other.  (cc @sauer2)

I will probably have to remove the "Pip Puzzle" in my Desert Fortress level - it required you to hop on a small pip to get a "super bounce" to reach a bonus area.  Unfortunately, the pips keep getting stuck in walls, so this just won't work as a puzzle for now.

**Comment by datahead8888** [comment]
So here's a new idea, @Quintus (at least for release-2.0.0): I'm assuming the small pipes are each a distance apart along the X axis currently.  When 2 new pips are spawned after the big pip is spawned, maybe we could place them each at about the same X coordinate as the Big Pip and then a bit of a distance from each other along the Y axis.  This would cut down the risk of a small pip initially cutting into a wall to the left or right.  There is some risk of a cut into a higher massive object, but it's not likely, since Alex has to stomp on the Big Pip.  We could also move Alex up a bit to prevent an overlap with Alex issue.

We could then give the small pips each velocities (speed and direction) such that their movement paths do not overlap with one another.  Finally, if the throwing speed is currently fast enough that they can get stuck in walls due to the object collision test issues, we could try to reduce this speed.

I'm drawing guesses based on what we discussed and what I saw in the game -- feel free to correct me.

Also, for the issue you mentioned in which any object can become stuck in a massive tile -- that certainly will be difficult to fix.  I remember reading about dynamic object collisions a while back (which basically account for the velocity when detecting collisions).  This may be what we need, but I would have to consult a resource again as I read it a long time ago.  The code for this kind of test tends to get cumbersome, so I don't think we should target this object collision issue in release-2.0.0.  I could, however, open a ticket for tracking.

**Comment by datahead8888** [comment]
I was playing around with this.  It looked as if when a big pip is directly converted to a small pip, it appears to "shift left", apparently due to the image size and/or configuration.  Thus if we shift each small pip to the right a little bit (using the image size for small pip), it seems to compensate for this.  I ran some tests, and the spawned small pips seem to have a lot less issues with getting stuck in walls.  They either do not get stuck or just get stuck for a moment and then fall out.

This does not address the pip-stuck-in-another-pipe issue or pip-stuck-in-Alex-issue, but it might be an improvement for now.  I've put this in a new branch so that anyone else who wants can give it a test run.  I'd be curious to hear if others find it to mitigate the problem, too.  You can use the level I provided, though I found it easier to add some extra big pips (and an extra berry to make Alex big more easily).

I'm assigning this to myself for now, but, by all means, don't hesitate to make more code changes to this.

**Comment by sauer2** [comment]
Stucking and displacement may be a general problem. When extending 
menu_brown_1 I noticed that - in the case that many bugs are spawned - 
the bug barrage gets moved or killed. The best we can possibly do in 
such general cases is using careful numbers.


Am 18.01.2015 um 00:58 schrieb datahead8888:

**Comment by datahead8888** [comment]
> Stucking and displacement may be a general problem. When extending menu_brown_1 I noticed that - in the case that many bugs are spawned - the bug barrage gets moved or killed. The best we can possibly do in such general cases is using careful numbers.

We probably need to create a task to look into some of these opportunities in general.  @sauer2 - can you create a video of too many bugs killing the beetle barrage?  This would make this problem really clear.

Two things we might look into (probably in a later release are):
* Dynamic object collision detection -- account for the velocity in object collision detection and maybe prevent objects that move too quickly from getting stuck in walls, etc.  This is a theory at the moment and needs to be substantiated with a source.
* Turn off object collisions against other objects (not massive objects) for a given object for a timed interval - this might fix the pip in pip issue and pip in Alex issue.

**Comment by sauer2** [comment]
@datahead8888: Here:

http://forum.secretchronicles.de/topics/177?page=3#p954

I'm not completely sure it's the bugs, though.

**Comment by datahead8888** [comment]
It's still fairly easy to get Alex stuck in a pip with my current change.  We'll have to evaluate it more and decide whether this is just as likely as with the code beforehand or worse.

**Comment by datahead8888** [comment]
This last commit in PipWallStuckFixB seems to be a bit better approach.  The idea is to spawn both small pips with the same y coordinate as the original big pip and with x coordinates such that they both occupy the original space of the big pip.  They do not have there x or y coordinates changed to force them into any positions.  They do, however, have their velocities set to send them flying in opposite diagonal directions.

I also increased the amount of bounce for Alex for stomping on big pips a bit.  This is to reduce the likelihood of his instantaneously stomping on a small pip that was spawned.

Upsides:
* Seems to prevent pips from going into walls
* May reduce pip in pip bugs (needs more testing)

Downsides
* Alex still sometimes instantaneously stomps on a small pip that was spawned, giving him a very large boost upwards.  I might try shoving Alex's y coordinate up a bit.  This is less risky, since he had to have been falling down to stomp on the big bip.
* Sometimes when a small pip is flung up then falls, right before it hits the ground it seems to "float in the air" for a moment and acts as if it's passive.  Other enemies can walk into this "floating pip" and then get stuck in it "when it becomes massive" again.  I wonder if this is related to our remaining issues for floating crates in #226.  I have not tested the latest crate fix yet, though.

**Comment by datahead8888** [comment]
It turns out the release-2.0.0 version:
* Has the same problem with instantaneously stomping spawned small pips when stomping a big pip
* Rarely has the problem where small pips float above the ground.  This appears to be a new bug in my new version.
* It seems to be much easier to get a pip stuck in a pip in the old version

I guess we will have to look at shoving small pips upwards or somewhere else again.  This is the main thing I got rid of.  It is strange they are floating, though.  A good question, though, is whether the old or new implementation is worse right now.

**Comment by datahead8888** [comment]
* Fixed the bug where pip's were floating in mid air -- the collision boxes for pip's needed to be updated
* Removed extra velocity (bounce) that I originally added for stomping on big pips to try and prevent an instantaneous small pip stomp
* Instead moved Alex's y coordinate up a little to deal with instantaneous small pip stomps.  It's still possible on the edges of the big pip, but this really isn't any different than the original code and makes sense

I think it's working, but some more testing and of course a branch merge are needed.  I marked this release 2.0 to give it visibility.  We'll probably want to include this in the release, since the original pip bugs are noticeable.

**Comment by Quintus** [comment]
> I think it's working, but some more testing and of course a branch merge are needed. I marked this release 2.0 to give it visibility. We'll probably want to include this in the release, since the original pip bugs are noticeable.

Please, file it as PR then and mark the PR 2.0.0.

Vale,
Quintus

**Comment by datahead8888** [comment]
> Please, file it as PR then and mark the PR 2.0.0.

@Quintus, I was just going to merge this myself later, but if you want to review it (since you wrote the pip code) and find a PR more convenient, I can file it.

**Comment by Quintus** [comment]
> @Quintus, I was just going to merge this myself later, but if you want to review it (since you wrote the pip code) and find a PR more convenient, I can file it.

If you are sure it’s ok, then just merge it. I just was under the impression you actually wanted someone to confirm all is well.

Vale,
Quintus

**Comment by datahead8888** [comment]
> If you are sure it’s ok, then just merge it. I just was under the impression you actually wanted someone to confirm all is well.

After looking at it yesterday, it seems I still have more testing.  I may have to ask you to test the existing implementation in the release-2.0.0 branch, with a special level.  release-2.0.0 seems to have inconsistent behavior for me...?  I will have to explain later.

**Comment by datahead8888** [comment]
> After looking at it yesterday, it seems I still have more testing. I may have to ask you to test the existing implementation in the release-2.0.0 branch, with a special level. release-2.0.0 seems to have inconsistent behavior for me...? I will have to explain later.

I think the problem is that I was using a "bad build".  It seems builds are oblivious to changes in the git branch, which means that the build system may decide not to rebuild an object file or redeploy png files.  Do you usually just purge the build directory and rebuild the whole project after switching branches?  This takes some time, but it does eliminate these problems.  It would be interesting if we were able to make our build system be able to work in sync with git branch changes.

**Comment by datahead8888** [comment]
I have created PR #352.  I need help testing this change in order to assess a possible CPU speed anomally.  It seems to behave a bit differently on may laptop depending on whether it is plugged in (higher speed) or not plugged in (lower speed).  See the PR for more details.

**Comment by datahead8888** [comment]
New conclusions:
* The differences on my PC depending on whether it was plugged in or not plugged in may have been due in part due to the choppy animation (when unplugged) making it difficult to see where I landed on pips
* Increasing the vertical displacement for Alex seems to help with the autostomp issues.  I would have pushed a change to the PR, but I forgot about the rebase push issue.  I will probably be better off wiping out the branch locally and redoing the change.

**Comment by datahead8888** [comment]
The change to increase the vertical displacement is now pushed to github and ready for people to test.

**Comment by Quintus** [comment]
> Do you usually just purge the build directory and rebuild the whole project after switching branches?

Yes.

Vale,
Quintus

**Comment by Quintus** [comment]
Fixed by aba33b5ad170c4061439a140fe7d3d0aca6d5c72.

Vale,
Quintus
