### ISSUE TITLE
Ruby Timer documentation is inconsistent

### ISSUE THREAD

**Issue by SonOfBowser** [Secretchronicles/TSC#318]
Specifically, Timer.after claims its value is in seconds, when it gets interpreted as milliseconds (same as Timer.new). Not sure if the intention was milliseconds and the docs are wrong, or the intention was seconds and the implementation's wrong. @Quintus can decide ;)

**Comment by Quintus** [comment]
The documentation of `Timer::after` is wrong. All other explanations of timer intervals use milliseconds, so for consistency in both the documentation and the actual API milliseconds should be used. Thanks for catching this!

Vale,
Quintus
