### ISSUE TITLE
World 3 is broken

### ISSUE THREAD

**Issue by sauer2** [Secretchronicles/TSC#322]
I've been [playing  so far] (http://forum.secretchronicles.de/topics/177) because @datahead8888 wrote something about world 3 being broken. He was right.

In the game, the way points seem to be missing, altough they are there in XML.

**Comment by datahead8888** [comment]
Actually I think Quintus is the one who had said world 3 was broken.  I had assumed we were using #59 to represent this (and other level problems in general).  If we use this to represent the world 3 problem, we'll want to mark it release-2.0.0 and blocker, since it's a very major issue.

**Comment by sauer2** [comment]
Ya, sorry, I lost track about what issue is active and which is not.

**Comment by Quintus** [comment]
Having an extra issue does not hurt if it is more specific. So we can just leave it.

Vale,
Quintus
