### ISSUE TITLE
Pipe Line Glitch...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#323]
This pipe in this video is exhibiting a glitch in which the line dividing the top of the pipe and the section of the body below disappears/appears as Alex moves. I tried playing with it in the level editor, but the only way to prevent the line from appearing/disappearing for this pipe is to overlap different parts of the pipe so that no line ever shows. 

This is in level 3, world 1:
https://www.youtube.com/watch?v=z3nwWyzA5aA&feature=youtu.be

Here's another instance in world 1, level 2:
https://www.youtube.com/watch?v=LYEGyTxNZRE&feature=youtu.be

See also the discussion in this commit: https://github.com/Secretchronicles/TSC/commit/1600e22dd15bd2a8b20fca6bcc27e483058b21e3#commitcomment-9164378

cc @sydneyjd

**Comment by sydneyjd** [comment]
Haha, thanks :) cool.

**Comment by datahead8888** [comment]
I've started working on committing this.  I will have to finish it a little later, though...

**Comment by datahead8888** [comment]
The png's added address the line glitch for the most common pipes (pretty much any pipe in the old levels), but it seems to still have the issue when some of the newer pipe pieces we added are still used.  I went ahead and committed the png's since it certainly fixes the issue in a lot of places, but we will need to continue to look into this.

This level demonstrates the issue:
https://drive.google.com/open?id=0B6YSsocq3-cWOEJTdHBfZjBNYjg&authuser=0

In that level go here to see the issue:
![new line glitch](https://cloud.githubusercontent.com/assets/6478551/5656167/802eb320-96a6-11e4-95b6-2093e009ed0f.png)

When committing the png's, these files showed as changed:
~~~~~~~~~~~~~~~~~~~~~~~
#	modified:   data/pixmaps/pipes/blue/up_1.png
#	modified:   data/pixmaps/pipes/blue/up_3.png
#	modified:   data/pixmaps/pipes/grey/up_1.png
#	modified:   data/pixmaps/pipes/grey/up_3.png
#	modified:   data/pixmaps/pipes/orange/up_1.png
#	modified:   data/pixmaps/pipes/orange/up_3.png
#	modified:   data/pixmaps/pipes/red/up_1.png
#	modified:   data/pixmaps/pipes/red/up_2.png
#	modified:   data/pixmaps/pipes/red/up_3.png
#	modified:   data/pixmaps/pipes/yellow/up_1.png
#	modified:   data/pixmaps/pipes/yellow/up_3.png
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Thus blue/up_2.png, grey/up_2.png, orange/up2.png, and yellow/up2.png did not change (even though there were files posted for them in the forum).  I would have said we want to check these png's for lines at the bottom, but I think @sydneyjd said he double checked these in IRC.  Perhaps they already had lines before the line addition?

If that doesn't fix the issue, we will need to investigate the types of pipe bodies producing the problem in the demo level.

At least we have it working in most campaign levels for now (with old types of pipe).  May the never ending pipe saga continue...

**Comment by sydneyjd** [comment]
@Quintus @datahead8888 Here is our (me and datahead's conversation on the forum) Any thoughts Quintus? 


23:29 -->datahead8888 entered #secretchronicles.
23:30 datahead8888 | sydney: You could try adding some extra line width to the tops of the body images having problems
23:30 datahead8888 | Otherwise, we could always try just a little thicker line width on the pipe tops and see what happens
23:41 sydney | datahead8888: I havent seen an issue yet with them on my computer.
23:41 sydney | I can do some more testing tonight though.
23:41 sydney | Maybe i was not digging deep enough.
23:41 datahead8888 | Did you try it in the demo level I posted?
23:42 sydney | Oh, no.
23:42 datahead8888 | The campaign levels were working fine for me
23:42 datahead8888 | Only the demo level showed the problem
23:42 datahead8888 | That's why I pushed the current fix - it fixed the issue in most places
23:43 datahead8888 | This problem will come back to haunt us later, though, for the newer pipe body parts / top parts as they get used in new levels
23:44 sydney | Yeah :s
23:44 sydney | I odnt want to see that happen.
23:46 sydney | Oh! I know why now!
23:47 datahead8888 | :)
23:47 sydney | What do you want to do about it? ;)
23:47 sydney | We would have to create another top .png
23:48 datahead8888 | How would it be different?
23:48 sydney | Well, you are using either a top .png or a bottom .png without a line.
23:49 sydney | A blank top has no line, so if you use it on a bottom with screws, only the bottom has the line, creating the issue.
23:49 sydney | If you use a blank top with a blank bottom, or a top with screw and a bottom with screws, you dont have an issue.
23:50 sydney | So, its self-invoking, you might say.
23:51 sydney | So, you either create a blank top that has a line, or you deal with the issue.
23:51 datahead8888 | I see
23:52 sydney | Make sense?
23:52 datahead8888 | If we can't fix it strictly through images, we could create alternate versions of each of the blank images with a line added
23:52 datahead8888 | We would then need C++ glue code to auto swap the images depending on the combination
23:52 datahead8888 | If you could post this finding on the ticket, we can see if Quintus has any other solution or, if we have to add the glue code, where that code should go in the code architecture.
23:53 sydney | Or just add another type in the "pipes" section.
23:53 datahead8888 | There are 2 potential problems with that:
23:53 -->aanderse entered #secretchronicles.
23:53 datahead8888 | 1) A lot of people won't know not to mix a blank piece with a piece with a line and will have issues in levels
23:54 datahead8888 | 2) The number of pipe variants listed is already pretty long, and adding an extra line piece will continue to bloat it
23:54 sydney | yes,  get your point.
23:54 datahead8888 | It's already going to get longer if I go back and add the 2 screw variants of the horizontal pipes
23:54 datahead8888 | We probably need to make a new section in the menus, at least for the small pipes, to break it up into easier menu selections

**Comment by datahead8888** [comment]
@sydneyjd  - Ok, new thought -- Could we eliminate the line on the bottom of all top pipe pieces and only have the line on the top of pipe body pieces?  This Pipe body line would be twice the width of the line we were using on head/body before.

If this ends up looking bad or doesn't work, I think we may have to look at code solutions that add/remove the line on the top pipe pieces based on what pipe body part is used.  Come to think of it, it may be difficult to tell what the adjacent pipe body part is.

**Comment by datahead8888** [comment]
...or...try this:

1. Remove the line from all top pipe images
2. For pipe body parts, add a transparent line 1 pixel high along the very top
3. For pipe body parts, add a black line 1 pixel high directly below the transparent line

The theory for this approach is that the transparent line on the pipe body overlaps the bottom pixels of the pipe top if image resizing occurs.  Thus the pipe tops shows.  Since the black line is further down, it would (hopefully) not conflict.  If a user forgets to add a pipe top, the body will still look as it should, since it has a black line followed by transparency at the very top.

If this still doesn't work, it might be a 1 off issue.  You could try shifting the parts of this solution further down, try the 2 pixel width as described above, etc.  This fix is largely about experimentation.

**Comment by sydneyjd** [comment]
I need to give the pipes a break for a couple days. i feel pooed out
just talking about them. ;)

**Comment by datahead8888** [comment]
> I need to give the pipes a break for a couple days. i feel pooed out just talking about them. ;)

Yes, I may not get the other fix for the horizontal 2 screw pipe tops done for a bit either...

**Comment by sydneyjd** [comment]
No @Quintus. I have it myself.  It happens when we use a blank top ( that doesnt have a line) with a bottom that has a line.
If the bottom doesnt have a line and the top doesnt have a line, or if the top has a line and so does the bottom it works fine.

They rely on each other to make the line work properly.

**Comment by Quintus** [comment]
> They rely on each other to make the line work properly.

So it is not intended to cross-combine these assets from your side? In that case we might just ignore the problem as it’s an unsupported combination...

Vale,
Quintus

**Comment by datahead8888** [comment]
> So it is not intended to cross-combine these assets from your side? In that case we might just ignore the problem as it’s an unsupported combination...

People may try to mix and match them without knowing this and then be surprised when it displays wrong with a line glitch in their levels.  These levels may start cropping up in the game, later.

**Comment by datahead8888** [comment]
> No @Quintus. I have it myself. It happens when we use a blank top ( that doesnt have a line) with a bottom that has a line.
 If the bottom doesnt have a line and the top doesnt have a line, or if the top has a line and so does the bottom it works fine.
They rely on each other to make the line work properly.

The best solution I can think of is to:
* Change pipe tops so that none of them have lines at all.  It may be necessary to try putting a transparent line on the bottom of the pipe top PNG.
* Pipe bodies would only have lines at the top, not the bottom.  Some would have lines; some would have no lines - this would cover the blank and non-blank versions.
    *They too may need to have a transparent line on the bottom.
    *If the line at the top doesn't show up well, it may need to be made twice as thick.  
*It may be necessary to break up the pipes into more SVG files to accomplish the above two points.  This is all dependent on what is needed to export PNG's to meet these requirements.

Thus, with lines only being on the pipe bodies, a conflict between the tops and bottoms would never occur.  This is all theoretical, so it would require experimentation to verify.

The only other solution I can think of is some sort of code solution, but it would become very nasty to test for the joining of pipe parts in the editor.  We would probably be better off marking this as "WONTFIX" than getting into that mess.

**Comment by sydneyjd** [comment]
Huh. :(

**Comment by sydneyjd** [comment]
Arg, i spen the last 2 hours fixing this, and now i have another issue. if you look my shading is not quite the same on the pipes with blank tops or middles. Ugg. Im going to bed ;)
![8](https://cloud.githubusercontent.com/assets/8949851/5791502/da688cf4-9ea7-11e4-8dbc-da1593e3bbca.png)

**Comment by sydneyjd** [comment]
It almost creates a per/section bubble affect.

**Comment by sydneyjd** [comment]
efect* @datahead8888 @Quintus

**Comment by sydneyjd** [comment]
The lines are working good the way you recomended though Datahead. ^

**Comment by datahead8888** [comment]
@sydneyjd  -- thanks for your hard work on this again.  I know everyone has been worn out on pipes - I ended up avoiding them myself for a bit.

> Arg, i spen the last 2 hours fixing this, and now i have another issue. if you look my shading is not quite the same on the pipes with blank tops or middles.

This probably is going to be tedious to correct.  I would guess your two options would be to:
* Recreate the "duplicate SVG" (duplicate in that you didn't have to have these extra SVG's before this fix -- I'm assuming you had to do this), and redo the shading on the SVG from the original SVG from which you clone.  If the new, duplicated SVG's are cloned from this, they would pick up the correct shading.
* Keep trying to correct the shading on each separate object until it's correct.  You might post on an inkscape forum and see if there is a way to do shading by only setting up parameters in the user interface (not clicking and dragging the mouse).  Being done through exact parameter values, it would be done the same way every time on different objects.

> It almost creates a per/section bubble affect.

I can see the red pipe seems to show a bit of a horizontal line in the shading.  Is this what you mean?

> The lines are working good the way you recomended though Datahead.

It does?  That's good to hear :)

If you post your PNG's and settings files I could try it in the level later when I get a chance.  We don't have to have the SVG's until we're about ready to commit it to git.

**Comment by sydneyjd** [comment]
Ok, im having issues. I cleared the cashe, but the images dont seem to show any changes. The pipes are seamless if i put them together manually as shown below.
![1](https://cloud.githubusercontent.com/assets/8949851/5793349/77cc59ba-9f0e-11e4-8571-c9e6a2f93676.png)
![2](https://cloud.githubusercontent.com/assets/8949851/5793350/77cf26fe-9f0e-11e4-9e43-48c41795ae6b.png)

**Comment by sydneyjd** [comment]
Here is the most recent .tar.xz to try @datahead8888. Yes, it is newer than the one i gave you this morning. https://cloud.openmailbox.org/public.php?service=files&t=fef695c0b2b8f377aa53fbc98d0895fd

**Comment by datahead8888** [comment]
> I cleared the cashe, but the images dont seem to show any changes.

There have been times where I had to delete the whole build directory and rebuild the entire project as (and clear the cache, too) in order to get around weird issues like this.  It's annoying but eliminates the question of a bad TSC build install.

> Here is the most recent .tar.xz to try @datahead8888. Yes, it is newer than the one i gave you this morning.

Ok, what change did you make?

**Comment by sydneyjd** [comment]
I made sure that the shading lined up on the .pngs, and re-exported
every one.

**Comment by datahead8888** [comment]
> I made sure that the shading lined up on the .pngs, and re-exported every one.

Oh, I see.  That's really good.

If it's all fixed, we'll just need to get the SVG's, commit it to git, and close out this ticket :)

I look forward to trying it out later.

**Comment by sydneyjd** [comment]
Well, i cleared my build and cache, and now am re-compiling to test it.

**Comment by sydneyjd** [comment]
Yes!!!! Finally!!! If i am correct everthing works now. I did not do much for throughal testing since im still not really allowed to play. ;) That tar.xz up there should fix everything.
![10](https://cloud.githubusercontent.com/assets/8949851/5793793/402d7d2a-9f1f-11e4-86d6-ebb7ec29fc55.png)

**Comment by sydneyjd** [comment]
I just thought of something @datahead8888. With these pipes that only have the lines on the top we wont have a line on the bottom, so if we try to put a top on the bottom of a middle piece we wont be able to have a line there.

**Comment by datahead8888** [comment]
> With these pipes that only have the lines on the top we wont have a line on the bottom, so if we try to put a top on the bottom of a middle piece we wont be able to have a line there.

If I remember correctly there should be a down facing body and down facing pipe top option in the level editor.  When you use these, it actually rotates the whole object, which means the line you drew gets rotated, too.  I doubt it will be an issue.

**Comment by sydneyjd** [comment]
Ok, good.

**Comment by datahead8888** [comment]
Sorry, Sydney.  Some stuff came up, and I may not be able to touch this for a bit/while.

**Comment by sydneyjd** [comment]
Ok, thats fine with me. I will dink with the hedge then.

**Comment by datahead8888** [comment]
I've tested the change Sydney made, which was based on the suggestions I made on how to try and fix it.
It had these issues:
* The line toward the top for all pipes in the game swaps between being 1 and 2 pixels thick (rather than 0 and 1 pixels, which was what we first put a fix in for) when the screen scrolls.
* Since vertical body pieces do not have a line at the bottom with this change in place, this means that you cannot put a pipe top facing down below a vertical body piece and still get the line.  It becomes impossible to put the line there anymore.

I can push these attempted changes to a branch for safe keeping in case anyone wants to play with them later.

Quintus had said:
> So it is not intended to cross-combine these assets from your side? In that case we might just ignore the problem as it’s an unsupported combination...

This is worth considering at this point.  At the very least, we might think if we really want to invest efforts in this for release 2.0, given that in the release branch this bug only happens when you mix a blank piece with a non-blank piece.  We're still free to play with pipe lines later.  I dropped #149 for now for the same reason - there are other release tasks that will yield more gains for now.  If we don't want to give up yet, though, that is fine, too.

This is another possible thing to try I just thought of:
* Change the pipe tops so that none of them have the line at the bottom.  They would then have a transparent line at the bottom.
* The blank pipe bodies would have a transparent line at the top and bottom.
* The non-blank pipe bodies would have a black line at the top and bottom.  We could try this with both 1 and 2 pixels and see which might work better.

This is just a thought -- when I tried something similar, it didn't seem to work for pipe tops, but I did not draw a straight transparent line by hand.

**Comment by datahead8888** [comment]
@sydneyjd - I pushed the change we just tested that had a couple issues to branch SydneyPipeLineTopOnly.  Thus anyone can do a git checkout on it now and play with it if they need to.

**Comment by sydneyjd** [comment]
The only other change we can make that would fix it as far as i know is just to remove the lines completely. @datahead8888 @Quintus Any thoughts?

**Comment by datahead8888** [comment]
We could still try the last theory I posted above, but, as you suggested, it doesn't seem likely it will work.

I really like the lines we have on the pipes because they make them look like sheets of metal.  I would rather have a glitch for people who mismatch a blank pipe piece and non blank pipe piece that sacrifice lines just for the sake of this issue.

It is strange that this is happening, so it might be worth opening a separate ticket to see if there is some sort of issue in the rendering code that is causing this.  If it's a placement issue, we can't just can't just offset all images, or those images would start having off by one pixel issues.  We might have to make it so that only certain images such as the pipe image are dealt with differently.  An issue like this would probably sit out there for a while, since most of the programmers don't know the rendering code very well.

**Comment by Quintus** [comment]
> I really like the lines we have on the pipes because they make them look like sheets of metal.

I’m against removing the lines. I like them to the exact reason @datahead8888 has mentioned.

> It is strange that this is happening, so it might be worth opening a separate ticket

This is what should be done. Try to find more cases where the rendering goes amiss. I’m pretty sure that this problem can also be constructed on other objects than pipes. When you open the new ticket, please close this one and add a "superseded by #xxx" comment.

Vale,
Quintus

**Comment by datahead8888** [comment]
The images are fixed for all practical purposes for pipes for this.

Superseded by #345
