### ISSUE TITLE
French Translations...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#332]
@giby indicated he could to a French Translation of Secret Chronicles.  This is a task to represent that translation.

He asked if we have a make pot script.  If someone could explain this, it would be appreciated.

**Comment by giby** [comment]
a makepot script is just a small script to generate pot files, with all strings to translate…

**Comment by Quintus** [comment]
Please review the translation guide: http://docs.secretchronicles.de/api/devel/md_translating.html

It includes the instructions to create the PO file. The POT file is updated by us developers from time to time.

Vale,
Quintus

**Comment by datahead8888** [comment]
giby said he's started working on this task.

**Comment by datahead8888** [comment]
giby said he is working his French Translations at https://www.transifex.com/projects/p/the-secret-chronicles-of-dr-m-tsc/

Francis Scott Fitzgerald also offered to help with French translations in the posting at http://forum.secretchronicles.de/topics/209

**Comment by datahead8888** [comment]
For now giby's po file can be tested with the branch: https://github.com/Secretchronicles/TSC/tree/FrenchTranslation

This branch will have to be deleted and the commit redone when we're ready because I forgot the git author option.

**Comment by datahead8888** [comment]
@Quintus - @Giby said he thinks the existing French translation is good enough for release-2.0.0
I can pull it from Transifex later when I get a chance.  Let me know if you (or anyone on the team) have any concerns with it going into the release.  He's had French translations out there for a while; he just can't test them himself, since he cannot build the game on his machine.

**Comment by Quintus** [comment]
I’m fine with that. Just be sure to set the copyright notice correctly.

Vale,
Quintus

**Comment by giby** [comment]
Hi, 

So I cannot go further for I would need to play the game to see them in context, and I cannot install on OSX. 
For the copyright, I could make it better… it would actually just need some setup, no time for that curently

**Comment by datahead8888** [comment]
Sorry guys...I may virtually have no time for TSC until Wednesday of next week...

**Comment by datahead8888** [comment]
PR #428 has been filed with the latest changes as of now.
I will see if it's possible to post screenshots of the French text in-game later (if someone can explain how to change the language).  Otherwise we can just merge it into devel and open a new PR if more French changes are made.

**Comment by datahead8888** [comment]
Screenshots are now attached to the PR.

**Comment by Quintus** [comment]
#428 has been merged.

Valete,
Quintus

**Comment by datahead8888** [comment]
@giby had said there was more work to do in the French translation.  We had decided the current file should be merged, since it was an improvement and so that other French speakers would gain visibility too it.  I think we might consider reopening this and leaving it open until giby translates 100% of the file.

**Comment by Quintus** [comment]
datahead8888 <notifications@github.com> writes:

> @giby had said there was more work to do in the French translation.
> We had decided the current file should be merged, since it was an
> improvement and so that other French speakers would gain visibility
> too it.  I think we might consider reopening this and leaving it open
> until giby translates 100% of the file.

Okay, I’m fine with that.

Valete,
Quintus

**Comment by datahead8888** [comment]
I have reopened it.  I will follow up with giby.  He is pretty busy with his PhD, so it will probably take some time before he finishes it.

**Comment by datahead8888** [comment]
@giby, have you had much time to work on the French translation?

**Comment by datahead8888** [comment]
@giby - do you still think you will do any French translations for the game?  Otherwise I will close this ticket, since we don't normally keep tickets open on translations to other languages otherwise.

**Comment by datahead8888** [comment]
Since no one is working more on this, I am going to close this.

We do leave tickets open as to-do's, but we don't have tickets open for Italian, Russian, and Chinese languages.  French is no different this way.
