### ISSUE TITLE
Scripting across sublevels is a bit broken

### ISSUE THREAD

**Issue by SonOfBowser** [Secretchronicles/TSC#335]
Scripting gets reset on returning to the main level, losing global variables e.t.c

Also, event handlers on the level player are taken over to the sublevel

**Comment by Quintus** [comment]
Fixed by f9319726fa4176d55a5243a3eee3b043c569d29e.

Vale,
Quintus

**Comment by datahead8888** [comment]
Apparently there was a rumor going around that TSC is buggy.

Well, not for long... :)

**Comment by Quintus** [comment]
Wouldn’t programming be boring if there weren’t any bugs? :-)

Vale,
Quintus

**Comment by DarkAceZ** [comment]
> Wouldn’t programming be boring if there weren’t any bugs? :-)
That's a very optimistic way of looking at it.

**Comment by datahead8888** [comment]
> Wouldn’t programming be boring if there weren’t any bugs?

I just look forward to proving the rumor wrong :)

**Comment by Bugsbane** [comment]
H heard a rumor that @datahead8888 will be wiring me 10,000 Euro's...

> I just look forward to proving the rumor wrong

:)

**Comment by datahead8888** [comment]
> H heard a rumor that @datahead8888 will be wiring me 10,000 Euro's...

I look forward to proving this rumor wrong as well...
