### ISSUE TITLE
CEGUI *is* provided by a modern distro (wording problem)

### ISSUE THREAD

**Issue by Luiji** [Secretchronicles/TSC#336]
https://github.com/Secretchronicles/TSC/blob/devel/INSTALL.md

> Additionally, TSC needs CEGUI version 0.7.x. However, as this old version is not provided by any modern Linux distribution anymore...

Turns out Gentoo does.

~~~
nnn@oddbox /usr/portage/dev-games/cegui $ ls
cegui-0.6.2b.ebuild    cegui-0.8.3.ebuild  files
cegui-0.7.7-r1.ebuild  cegui-0.8.4.ebuild  Manifest
cegui-0.7.9.ebuild     ChangeLog           metadata.xml
~~~

Should we reword the document ("most modern Linux distributions...")?

**Comment by Quintus** [comment]
If you are going onto the words in such a way, you shall fix it then :-P

Vale,
Quintus
