### ISSUE TITLE
Pow Switch Graphic Replacement

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#337]
The Pow Switch looks just like the P-Switches from some Mario games.  We probably need to replace it with a bit different image (at least with a letter other than P).

**Comment by Quintus** [comment]
Sounds like a nice task for @sydneyjd. Do you want to give it a try?

Vale,
Quintus

**Comment by sydneyjd** [comment]
Sure i can give it a shot. What does the original one look like @datahead8888 ?

Sydney

**Comment by datahead8888** [comment]
> What does the original one look like @datahead8888 ?

These are the images, though they are all the same size in the actual game.

Also, "Pow" itself is a term used in the Mario games.  We might either consider "Switch" or some other name.

![blue](https://cloud.githubusercontent.com/assets/6478551/6159968/ce143e8a-b22a-11e4-8b1d-884d28625a9d.png)
![blue_active](https://cloud.githubusercontent.com/assets/6478551/6159969/ce15005e-b22a-11e4-9073-4304aac46700.png)

![green](https://cloud.githubusercontent.com/assets/6478551/6159973/d4f09ac8-b22a-11e4-899f-85a8ad4cafea.png)
![green_active](https://cloud.githubusercontent.com/assets/6478551/6159975/d4f429f4-b22a-11e4-98d0-c344bb30fec5.png)
![red](https://cloud.githubusercontent.com/assets/6478551/6159976/d4f46702-b22a-11e4-8d77-44521ecaad18.png)
![red_active](https://cloud.githubusercontent.com/assets/6478551/6159974/d4f3ab96-b22a-11e4-85eb-ed4856a04309.png)

**Comment by Quintus** [comment]
Here are the SVGs: https://github.com/Secretchronicles/TSC/tree/v2.0.0-beta7/drafts/game/pipgirl/pow

Valete,
Quintus

**Comment by sydneyjd** [comment]
I know it doesn't look the best (yet) But what do you think of the overall switch idea? @datahead8888 @Quintus @Bugsbane 
![1](https://cloud.githubusercontent.com/assets/8949851/6182275/c85036b8-b30e-11e4-92bc-7a7c9a146e86.png)

**Comment by Quintus** [comment]
Nice. The idea is good. The top part can even be colored differently.

Now apply a gradient to make it look round.

Vale,
Quintus

**Comment by datahead8888** [comment]
Does the red part slide into the black part, sort of like a big button that is pressed down?  I was thinking if we might shape the bottom black part a little differently, but it depends on what we're trying to do.

You also might try a little different color for the very top rectangle (at least another shade of red) so that it stands out against the main body.

Yes, it will need shading, but that will probably come after the initial shape is decided.

**Comment by Quintus** [comment]
> Does the red part slide into the black part, sort of like a big button that is pressed down? 

I would say so.

Vale,
Quintus

**Comment by sydneyjd** [comment]
@Quintus @datahead8888 @Bugsbane Opinions? Any ideas on bottom of switch improvement? 
![1](https://cloud.githubusercontent.com/assets/8949851/6198476/3ee84fb8-b3d2-11e4-88fc-798b703ee718.png)

**Comment by Bugsbane** [comment]
Red and black together, traditionally signifies danger, rather than opportunity.

Currently it looks somewhat like a pipe, especially the black part. Might I suggest we try a switch instead?

**Comment by Quintus** [comment]
> Red and black together, traditionally signifies danger, rather than opportunity.

I was imagining we would have several colours for the top part. The old pow switches are also available in three colours, and depending on the situation, the level designer should be able to pick the switch with the colour he finds to fit best.

Valete,
Quintus

**Comment by sydneyjd** [comment]
@Bugsbane @Quintus @datahead8888 How do i change the bottom to look more "button like"?

**Comment by Bugsbane** [comment]
I'll try and run up a draft tomorrow (Monday)

**Comment by datahead8888** [comment]
I honestly have a little trouble seeing black for the color of the base.  Gray might be an option.

At this point, I'd like to defer further suggestions about the shape and other color choices to Bugsbane.

@Bugsbane, do you think you might be able to draw a quick sketch of your thoughts so that Sydney can see what you had in mind?

**Comment by Bugsbane** [comment]
I'm thinking something a little more along these lines (shading on the base still needs work):

![green-switch](https://cloud.githubusercontent.com/assets/401733/6271601/a7af97ca-b82f-11e4-9d32-66dca32d1b7c.png)

Notable changes include:
* Rounding the very top part of the button instead of a rectangle
* Changing it to green (generally in most games, pushing a button is more likely to do something good than bad)
* Changing shape of the base
* Some misc. details like screws

**Comment by Quintus** [comment]
> Changing it to green (generally in most games, pushing a button is more likely to do something good than bad)

I still think we should have switches with different colors. They can be used where they fit, or a creative level designer could use the color codes for something. You could have blocks of the same color appear/disappear, or red switches generally spawn enemies in the level, etc.

> I also generally favor avoiding letters anywhere given the many different languages spoken by our players.

I agree with this, but where was the suggestion made to use letters?

Valete,
Quintus

**Comment by Bugsbane** [comment]
> I still think we should have switches with different colors

Agreed.

> where was the suggestion made to use letters?

The current original image uses the letter "P". I brought it up in reference to that.

**Comment by Quintus** [comment]
> The current original image uses the letter "P". I brought it up in reference to that.

Ah ok. I think the P was only there because the original Mario switches also had it.

Btw @Bugsbane, why don’t join us in IRC at `#secretchronicles` on chat.freenode.net? datahead and me are hanging around there quite often, and sydney is there all the time. Would be nice to see you there from time to time.

Vale,
Quintus

**Comment by datahead8888** [comment]
Honestly, I immediately mistook it for a Mario pipe when I saw the green color.  It could just be me, though, since we've been talking about pipes recently.  We could also try another shade / color for the very top tip section to differentiate it from the middle section below it.

We also ought to get Sydney's thoughts on this and probably should allow him to make any other changes if they are made.

> Btw @Bugsbane, why don’t join us in IRC at #secretchronicles on chat.freenode.net? datahead and me are hanging around there quite often, and sydney is there all the time. Would be nice to see you there from time to time.

Yes, we'd definitely be up for having you in IRC with us :)
I tend to be in and out of IRC quite a bit myself.

> I still think we should have switches with different colors....

This is a good idea.  The question of level consistency is going to eventually come up.  I'm wanting to publish some thoughts on world/level consistency later.  I don't want to be overbearing with rules on how levels are made, but there are some things that need to thought about across all levels.  Consitsency, consistency, constistency, consistency...

**Comment by sydneyjd** [comment]
@Bugsbane I really like your switch. Are we pushing for this in release in 2.0.0? We culd do the pipe tops fliped over like bugsbane used up there. That would alow them to match with existing pipes.
Any thoughts?

**Comment by Quintus** [comment]
> Honestly, I immediately mistook it for a Mario pipe when I saw the green color. It could just be me, though,

I don’t think that this looks like a Mario pipe, even with the green color.

> Are we pushing for this in release in 2.0.0?

Not without the SVGs and not without a licensing confirmation. We have had this once, that’s enough :-)

Also, we’d need a graphic for the activated state of it.

Vale,
Quintus

**Comment by Bugsbane** [comment]
> there are some things that need to thought about across all levels. Consistency, consistency, consistency, consistency...
This.

> Not without the SVGs
Is there somewhere SVG's can be uploaded more easily than comitting to GIT on a regular basis? GitHub issues are a pain, as they allow uploading of PNG's / JPG's but not SVG. This is what often leads to me uploading png's and then never getting around to sharing the SVG. Git might be easy for dev's, but this kind of thing usually ends up taking me 1/2 an hour to figure out, which is time I'd much rather spend making art. Something like a TSC ownCloud instance with a folder structure mimicing the TSC data/bitmaps folder would be great, as it's super easy to just turn into another folder in the file manager via webdav. If we had something like this I'd save all my drafts in there by default instead of having to hunt around for them, upload them somewhere else etc.

> and not without a licensing confirmation.

Can we save time here and just have me state for the record that:

"I give full permission for the secret Chronicles project, as found at http://GitHub.com/Secretchronicles to use any artwork (png's/jpg's/sketches/.svg files) created by me, that I post on this projects sub pages (issues, files area etc.), past, present and future until further notice, under a creative commons CC-BY 4.0 license."

? Because if that's ok, then I verify the statement above in quotation marks to be accurate and true. :)

**Comment by Quintus** [comment]
> Is there somewhere SVG's can be uploaded more easily than comitting to GIT on a regular basis?

Currently, there are 3 possibilities:

* You can upload SVGs [in our forum](http://forum.secretchronicles.de/forums) as attachments. The forum rules state CC-BY licensing for everything you post there, so that generally ease things very much.
* Alternatively, the same goes for the tsc-devel [mailinglist](http://lists.secretchronicles.de/).
* There is SFTP available which allows you to upload to `http://team.secretchronicles.de/~<username>` everything you like. I use it to dump everything TSC-related somewhere onto the web ([link](http://team.secretchronicles.de/~quintus/)). I’d just have to create an account for you, then you can use any SFTP program like FileZilla to upload files.

> Can we save time here

The forum and mailinglist both have rules that automatically license everything 4.0 that you post there. GitHub doesn’t allow us to enforce people to check an "I accept this" option, so it doesn’t work on GitHub. datahead has pointed out that we could have this when we self-host the tracker after the 2.0.0 release.

> just have me state for the record that:

That’d work for GitHub for now, yes.

Vale,
Quintus

**Comment by datahead8888** [comment]
We still need the SVG from Bugsbane if we use his version and need to be sure everyone is in agreement as to which version we use.  Thus no one needs to be assigned to this task for now.  We should discuss this in our next team meeting, unless we reach Bugsbane before then and come to a decision through the tracker.

**Comment by Bugsbane** [comment]
Sorry I don't have time for much more right now:

"I give full permission for the secret Chronicles project, as found at http://GitHub.com/Secretchronicles to use any artwork (png's/jpg's/sketches/.svg files) created by me (including the SVG file linked to below), that I post on this projects sub pages (issues, files area etc.), past, present and future until further notice, under a creative commons CC-BY 4.0 license."

http://duruz.com/green-button.svg

This is a temporary link. Please download the SVG and add to the git repo.

**Comment by Quintus** [comment]
I stored it on alexandria: http://team.secretchronicles.de/~quintus/store/green-button.svg

Thank you for your hard and patient work for the game. It is great to have a skilled artist like you :-)

Vale,
Quintus

**Comment by Bugsbane** [comment]
Do we need frames for it being pushed down, or will that be done in code? Using frames is probably quicker to do, but you could have it looking a lot smoother is there was code along the lines off "Lower button if it has a weighted object on it, otherwise make it slowly rise again." By "the button" I'm referring to only the green part, not the metal base. I can easily group the button and the base, or separate them into separate PNG's if it will help. This would take all of about 20 seconds.

**Comment by Quintus** [comment]
There’s no C++ code for the switches. They’re entirely controlled by
scripting, including change of the graphic when stumped on. TSC provides
a rudimentary default implementation in the SSL
(<http://www.secretchronicles.de/docs/2.0.0-beta8/ssl/Std/Switch.html>),
but a level writer is free to code all the logic himself instead. Thus,
no changes in C++ code are required. The SSL implementation however can
surely be improved.

Here’s the implementation in the SSL:
<https://github.com/Secretchronicles/TSC/blob/9ad35b29688159edb0250f74e29618dae0106517/tsc/data/scripting/std/switch.rb>

As you can see, rather simple. By employing a quickly executing periodic
timer, it’d be possible to create a smooth animation if desired (again,
without touching the C++ code). Same goes for the button reacting on
objects on it. In any case, the scripter will need frames to display, so
they’re definitely needed :-)

Vale,
Quintus

**Comment by Bugsbane** [comment]
> TSC provides a rudimentary default implementation in the SSL (<http://www.secretchronicles.de/docs/2.0.0-beta8/ssl/Std/Switch.html>), but a level writer is free to code all the logic himself instead. Thus, no changes in C++ code are required. The SSL implementation however can surely be improved. Here’s the implementation in the SSL: <https://github.com/Secretchronicles/TSC/blob/9ad35b29688159edb0250f74e29618dae0106517/tsc/data/scripting/std/switch.rb>

You just made my head explode.

> As you can see, rather simple.
Ahhhh.... no.

> By employing a quickly executing periodic timer, it’d be possible to
Is it possible that my head could have exploded a second time?

> so they’re definitely needed :-)
This part I get. SO how many frames do you need? Just up and down, or multiple inbetween frames (how many)?

**Comment by kirbyfan64** [comment]
@Bugsbane You don't know Ruby, do you? :)

**Comment by Bugsbane** [comment]
@kirbyfan64 Sure! That's those red rocks that come out of the ground, right? Why do you ask? ;P

**Comment by datahead8888** [comment]
> @Bugsbane You don't know Ruby, do you

I'm a programmer, and I don't really know Ruby very well either :)

@Quintus, if we add more frames, yes, it could be done through scripting now, but it might make sense to add some sort of C++ support eventually.

**Comment by Bugsbane** [comment]
Up and down frames as well as the SVG:
At [this](http://duruz.com/power-switch.tar.gz) link.

I give full permission for the secret Chronicles project, as found at http://GitHub.com/Secretchronicles to use any artwork (png's/jpg's/sketches/.svg files) created by me (including the SVG file linked to above), that I post on this projects sub pages (issues, files area etc.), past, present and future until further notice, under a creative commons CC-BY 4.0 license.

**Comment by Quintus** [comment]
Bugsbane <notifications@github.com> writes:

> You just made my head explode.

Fairly enough :-). Okay, from the beginning: TSC comes with a scripting
engine that allows the level author to diverge from the standard TSC
gameplay. datahead used this to create a draw bridge, and I often use it
for switches. If you play the tutorial level, you’ll see sauer2 used it
for showing messages to the user. In one of the new “quintus_*” levels I
dynamically create platforms when all red gems have been collected by
the player. The enemy pit level I posted in the forums generates lots of
enemies dynamically.

Or in short: Any dynamic content in TSC is done by scripting. The
main documentation on scripting is here:

  http://www.secretchronicles.de/docs/2.0.0-beta8/core/

That’ſ the so-called “core” documentation. Any of the things documented
there are implemented in C++, but are accessible to the level writer at
runtime by using Ruby. Additionally, this facility was used to provide a
set of simple Ruby scripts that we ship with the game, the “Standard
Scripting Library”, or SSL for short. This way a level writer doesn’t
have to reinvent everything, but can just use the Ruby code that was
written on top of the Core API. The SSL is documented here:

  http://www.secretchronicles.de/docs/2.0.0-beta8/ssl/

Switches are implemented this way. The “switch” standard library takes
the facilities from the Core API that allow to control the appearance
and collision behaviour of a sprite and uses them for making the switch
work. It first attaches to the static switch sprite by listening for a
“touch” event on its UID. The event handler, when executed, changes the
switch’s sprite to the pressed one and additionally performs some action
the level author defined in his script code.

That is, the current implementation uses two sprites, the normal sprite,
and the sprite for the pressed button. You can supply any amount of
sprites that you deem useful, and it should be easy to adapt the
switch’s implementation by just changing some lines of Ruby code.

>> By employing a quickly executing periodic timer, it’d be possible to
> Is it possible that my head could have exploded a second time?

Forget about the timers, it’s an implementation detail only relevant for
coding. The one who is going to adapt the switch.rb file will appreciate
that I made a recommendation on a possible way to implement it.

> This part I get. SO how many frames do you need? Just up and down, or
> multiple inbetween frames (how many)?

Supply as many as you deem required. Whether we show 3, 4, or 10 does
not really matter as the amount of code needed to make it work is the
same.

Valete,
Quintus

**Comment by Bugsbane** [comment]
Seems to me that if there's no need of any specific number, that two, just like what we already had, is probably simplest. If we don't actually need more, then we can just close this with the two frames I've already posted.

**Comment by Quintus** [comment]
Okay. Then I’ll at your button when I find time again.

Vale,
Quintus

**Comment by datahead8888** [comment]
Quintus, are you still working on this task?  Will it likely be deferred until the SFML port (major priority) is completed?

**Comment by Quintus** [comment]
datahead8888 <notifications@github.com> writes:

> Quintus, are you still working on this task?  Will it likely be
> deferred until the SFML port (major priority) is completed?

It is likely that I focus on the SFML stuff exclusively first. However,
adding this graphic should really not be difficult. Feel free to
unassign me.

Vale,
Quintus

**Comment by Quintus** [comment]
@Bugsbane can we have blue and red versions of the switch as well so we can directly replace all switches in [this directory](https://github.com/Secretchronicles/TSC/tree/devel/tsc/data/pixmaps/ground/underground/pow)?

Vale,
Quintus

**Comment by Quintus** [comment]
Also, please export at a larger size, like 128x128px like the blue pow switch we currently have.

Here’s how it looks in-game, with the old blue switch on the right side:


![5](https://cloud.githubusercontent.com/assets/156358/10331587/d4930752-6cd6-11e5-8d57-0b52513517dc.png)

What does everyone think?

Valete,
Quintus

**Comment by sauer2** [comment]
Looks pretty good! However, are you sure everyone would recognize this 
as switch at once? It doesn't stand out that much...

Am 07.10.2015 um 09:36 schrieb Marvin Gülker:

**Comment by Quintus** [comment]
> It doesn't stand out that much...

In the image above I think this is a result of the green background behind the green switch. You’d probably use another color in that situation; also I think there’s a switch in the tutorial level that makes people familiar with its functionality (if there isn’t, please add one :-)).

Vale,
Quintus

**Comment by sauer2** [comment]
Sounds reasonable.

Unless someone changed the tutorial, the switch should be still in there.

Am 07.10.2015 um 14:07 schrieb Marvin Gülker:

**Comment by Bugsbane** [comment]
> It doesn't stand out that much

>  the image above I think this is a result of the green background behind the green switch.

I agree with both statements. Maybe offering a couple of different colors (red, yellow, blue) may help. It would be quick and easy enough to do.

**Comment by Quintus** [comment]
> Maybe offering a couple of different colors (red, yellow, blue) may help

Take a look at what [I wrote above](https://github.com/Secretchronicles/TSC/issues/337#issuecomment-146098945) — I asked you for exactly these :-)

> Possibly, the "off" switch could be made a bit taller, too...

Beware that it needs to be distinguishable from the "on" switch. You’d then have to make that one taller also (maybe try to match the dimensions of the existing pow switch?).

Vale,
Quintus

**Comment by Bugsbane** [comment]
Yes, I'm just talking about making the taller image, taller again, so it would actually be more distinguishable. Actually, if we wanted to mark junior jobs for artists, making this taller and changing colors would definitely be one, otherwise I can just do it.

**Comment by Quintus** [comment]
> Actually, if we wanted to mark junior jobs for artists, making this taller and changing colors would definitely be one

I’d be fine with this. Sounds like something for @sydneyjd then :-)

Vale,
Quintus

**Comment by JohnTheTreeman** [comment]
Hi, this is my idea of a switch. Colors can be changed. =D

![pow_v03](https://cloud.githubusercontent.com/assets/14848980/10415358/8c8c0396-6ff6-11e5-9657-2850525503a4.png)

**Comment by datahead8888** [comment]
@JohnTheTreeman - the main characteristic of the Nintendo-like switches is the letter P.  I think we'd be best off not having any letter on the switch.  We've gone through enormous efforts to stop being a Mario-NIntendo clone, so I don't think letters are worth the risk.

Multiple types of switches might be an interesting idea to discuss, but if they require programming changes, they will have to wait until the SFML port is done.

**Comment by Quintus** [comment]
datahead8888 <notifications@github.com> writes:
> Multiple types of switches might be an interesting idea to discuss,
> but if they require programming changes, they will have to wait until
> the SFML port is done.

Since all switches are scripted, and script is written by the level
writer, no C++ code changes are necessary.

Vale,
Quintus

**Comment by Bugsbane** [comment]
Love the look of @JohnTheTreeman's switches (better than mine). My only requests would be:

1. Dropping the S, although for different reasons, namely internationalization. Ideally, someone with the language set to Korean / Chinese / Japanese etc, won't be faced with a game full of characters from some foreign language.

2. The standard width non-black, outline as in the style guide.

3. A brighter highlight near the top of the coloured button section, to highlight the shininess (and also draw attention to it as a fairly important interactive item in the level)

Other than those minor things, I think the overall design looks fabulous.

**Comment by sydneyjd** [comment]
Wow, these look nice!

**Comment by datahead8888** [comment]
> Dropping the S, although for different reasons, namely internationalization. Ideally, someone with the language set to Korean / Chinese / Japanese etc, won't be faced with a game full of characters from some foreign language.

@Bugsbane, it's not unusual here in the US to see Asian symbols in either Japanese anime or something like the Matrix movie.  I don't think we should put a ban on all letters in graphics.  In this case, though, I think we should not use the "S" because we need to be significantly different than Nintendo's "P" graphic.

**Comment by Quintus** [comment]
> it's not unusual here in the US to see Asian symbols in either Japanese anime or something like the Matrix movie. I don't think we should put a ban on all letters in graphics. In this case, though, I think we should not use the "S" because we need to be significantly different than Nintendo's "P" graphic.

I completely agree with what datahead outlined here. I don’t think we ought to ban all letters from the game, but in this particular case, I think we are better off without one due to the Nintento Pow switch similarity.

Valete,
Quintus

**Comment by Bugsbane** [comment]
> it's not unusual here in the US to see Asian symbols

How much meaning would it convey in TSC though? How does having non-understandable characters add to TSC's visual identity specifically?

In the Matrix, the entire point of the film was that it was a reality made of code, and the characters were a) fictional an b) showing the key plot point (the underling code) of that reality.

Also it's easy to not feel marginalized as part of a large, dominant culture in a way that it isn't if you're from one of the less influential cultures.

Elements included in visuals are to communicte something. It doesn't communicte well, if it isn't understood.

Anyway, I don't want to turn a fairly minor point into a major debate. If anyone else wants to add anything, by all means do, but I've said my piece and will limit any other comments on this issue to discussion of the actual switch replacement graphics, as we all seem to agree to removing the S in this instance.

**Comment by datahead8888** [comment]
> How much meaning would it convey in TSC though? How does having non-understandable characters add to TSC's visual identity specifically?

If the graphic contains instructions that the player has to read in order to proceed, it needs to be translatable in order to function.  This, with our current features, is probably not feasible.  Otherwise, simple letters/symbols/characters or possibly even words that are not game play instructions can still convey an image and impression.

> Also it's easy to not feel marginalized as part of a large, dominant culture in a way that it isn't if you're from one of the less influential cultures.

Honestly, this is a very subjective argument; we cannot please everyone.  If we strongly disagreed, however, we'd just have to vote on this.  Similar arguments come up with religious similarities, etc.

> as we all seem to agree to removing the S in this instance

We're in agreement, there.  I'm not eager to start a major debate either :)

**Comment by JohnTheTreeman** [comment]
I'll update the switch soon and post some alternatives to the "S" too.

**Comment by kirbyfan64** [comment]
You could always try using a down arrow on the switch or something like that.

**Comment by datahead8888** [comment]
@Bugsbane, there's quite a bit of artwork in the forums you might want to review when you get a chance.  Also, if you get a chance to finish the style guide draft, it will help ensure artists have a common reference.  We can ask JohnTheTreeMan, skarfester, and Sydney for there feedback on it, too.

**Comment by Quintus** [comment]
> we'd just have to vote on this

Please, don’t try to settle all conflicts directly by calling for a vote. I don’t want that votes become our normal measure of action, and this is laid down in the voting rules itself:

> § 4 General Rule of Consent
>
> All decisions are to be made in consent of all team members.
> Only if it is impossible to reach a consent even by means of
> compromises, a voting shall be held.

There must be discussion and serious attempts of finding compromises before we resort to voting. Voting is not a measure to escape from the need of discussion, but the last resort in ending a discussion that does not lead to definitive results. We have not really started discussion here.

> You could always try using a down arrow on the switch or something like that.

Agreed, I think that’s best.

Valete,
Quintus

**Comment by datahead8888** [comment]
> Please, don’t try to settle all conflicts directly by calling for a vote.

I did not mean to say we should vote as of yet for this issue but just meant to say that we may disagree in a manner similar to the god mode ticket.  Votes for issues are not normally preferable.

**Comment by sydneyjd** [comment]
Im fine with Omega mode also.

**Comment by kirbyfan64** [comment]
@sydneyjd Wrong issue. :)

**Comment by sydneyjd** [comment]
LOL, shoot. Clicked the wrong email to respond to. :p

**Comment by datahead8888** [comment]
Would everyone be fine if I removed the last 3 omega mode comments (and this one or answers to this question?)

**Comment by Bugsbane** [comment]
> Would everyone be fine if I removed the last 3 omega mode comments

Maybe we should put it to  vote? ;P Seriously though, please do, assuming @kirbyfan64 and @sydneyjd are ok with it.

**Comment by Quintus** [comment]
> Maybe we should put it to vote?

No, no! We need to vote first whether we want to vote on the topic!

SCNR

**Comment by kirbyfan64** [comment]
You can vote on whether or not you can vote on whether or not you can vote on...

**Comment by datahead8888** [comment]
@JohnTheTreeman, have you had any time to look at this one?  Knocking off a major Mario-ism will be a big win for us.

**Comment by Quintus** [comment]
Okay everyone. Status of this? I want to remove the Mario pow switch for the next release, so it’d be nice if we came to a conclusion here. Looking at the issue it appears to me there’s not too much work left.

Valete,
Quintus

**Comment by Bugsbane** [comment]
Seems to me that while there was some disagreement on why, that there was general consensus on @JohnTheTreeman's version just with the S removed, and possibly with the outline and extra shine (although these items weren't further discussed after I suggested them). The main thing that we need at this point are the SVG's.

**Comment by Bugsbane** [comment]
@JohnTheTreeman Any chance of an SVG? *hint* *hint* :D

**Comment by datahead8888** [comment]
@JohnTheTreeman, if we don't get an SVG, it is possible the graphic may have to be redone in order to keep moving.

**Comment by Quintus** [comment]
Suggestion: If @JohnTheTreeman doesn’t respond within a week now, we’ll give up on waiting for his SVGs and simply do a new graphic.

**Comment by Bugsbane** [comment]
Sure. If we want to go with his design, I can replicate it. I do think it looks good, although it is fairly tech looking, so it may be a little out of place in the more natural levels (eg jungle). That said, my design is a bit more generic, but a bit overly simplistic. Of course the benefit of my one is that we already have the SVG. I'm not personally attached to either, so I'm happy to go whichever way. Possibly we could do something like use my design until I get a chance to replicate his and then switch to that. It wouldn't take me that long to do, however I want to finish Aarmy Snr (the boss) first, which requires me to learn some new stuff in Synfig first.

**Comment by Quintus** [comment]
@Bugsbane @datahead8888 JohnTheTreeMan has emailed the SVG to me, I uploaded it to the forum: http://forum.secretchronicles.de/topics/335/posts/1885

**Comment by Bugsbane** [comment]
OK, so I got the SVG, adapted it to the style guidelines (mainly just outlines), removed the "S" as we all seemed to agree on, and did green and blue versions. Here's how they look ingame:
![5](https://cloud.githubusercontent.com/assets/401733/12535510/ac222d16-c253-11e5-9fa5-94970d92ca7a.png)

Unfortunately, a lot of the nice details are lost at that size, but overall I think they look good. If everyone else agrees, then I'll move to complete the settings files and post the SVG and PNG's.

They sure as heck look better than what we have now, though!

**Comment by Quintus** [comment]
Wantz! <3

**Comment by sauer2** [comment]
Yeah, looks pretty good!

**Comment by Bugsbane** [comment]
Ok, [here's a tgz](http://duruz.com/power-switches.tar.gz) with the PNG's and source SVG. Settings files to follow.

**Comment by Quintus** [comment]
> whoever coded the settings editor!

Me, as a quick weekend hack if I remember correctly :-). It must be horribly buggy. Maybe I will work on it again a little bit when the SFML stuff is done.

I’ll add your graphics soon.

Vale,
Quintus

**Comment by Quintus** [comment]
I knew it is buggy. @Bugsbane, the width/height of the graphics is set to 64px which is fairly large compared to the original pow switch, and larger than what you showed in your screenshot. Also the `editor_tags` and `type` keys were missing, and the `name` key didn’t fit the file name always.

Other than that, the graphics and settings files have beended with commit 4a6862fb7fa4837ddab51389887bf561206b5a1d. We’ll have to discuss on the sizing a little before we close this ticket, though.

Valete,
Quintus

**Comment by Quintus** [comment]
Screenshot:

![10](https://cloud.githubusercontent.com/assets/156358/12537296/b07ea714-c2bb-11e5-9dd9-983bfb751870.png)

**Comment by sydneyjd** [comment]
These look awesome!!

**Comment by Bugsbane** [comment]
I think we should make them the same width as the blocks...

**Comment by datahead8888** [comment]
They look well done and do not look like Mario objects.

They look a little sci-fi'sh -- I think this could work well if we stick with the monster factory theme or have Dr. M build other machines in the game.

**Comment by datahead8888** [comment]
They do look a little tall at first glance -- we might think a little more, then make a decision.
