### ISSUE TITLE
Update man page

### ISSUE THREAD

**Issue by akien-mga** [Secretchronicles/TSC#338]
There is a man page in tsc/docs/man/smc.6, but it seems to be outdated.
It's name should be changed to tsc.6, and the content should be revised to fit TSC 2.0.0.

Ideally the man page should describe the available switches listed by ```tsc --help```.

Once the man page is complete, a CMake instruction should probably be added to get the man page installed in $(PREFIX)/man/man6/tsc.6 on Linux systems.

**Comment by Luiji** [comment]
There's also `smc.pod`. I'll update them.

**Comment by Luiji** [comment]
I've cherry-picked this into the release as well.
