### ISSUE TITLE
FIXED_DATA_DIR works fine but should also be used by CMake for the install step

### ISSUE THREAD

**Issue by akien-mga** [Secretchronicles/TSC#341]
Since it was fixed in #240, the FIXED_DATA_DIR option works fine to tell TSC to search for its data in a given directory.

On Linux, this variable is not used in the CMake script to change the data install path, so the data ends up in $(PREFIX)/share/tsc instead of $(FIXED_DATA_DIR).

There should probably be a test to see if FIXED_DATA_DIR was defined by the user, and if so, override the $(PREFIX)/share/tsc path.

Another partly related feature request would be to give packagers the possibility to override the binary installation path without having to patch the CMakeLists.txt. Mageia and Debian put game data in /usr/share/games (FIXED_DATA_DIR partly caters for that), and binaries in /usr/games (and not $(PREFIX)/bin as currently hardcoded in the CMakeLists.txt).

**Comment by Quintus** [comment]
Fixed by commits 8a41792396ff243b702c0660290faa238237bb95 + dfbc6723f2833848d69e957430b6d2b3e0f333a4 + 4620137ef516970a727a9968b63d4b3608cd92f4.

And give a thankyou to `git rebase` which erased the branch merge commit when I rebased with the remote git repository. :-(

Vale,
Quintus

**Comment by Quintus** [comment]
I was told on Twitter the commit isn’t erased. It’s still there. The commit ID was 78ca30ce2a5dc3629614d5056ddd9bfcd71cf29e and it still shows up in `git reflog`, a command I’ve never used before but that appearently is quite useful.

Though I guess the commit is not in the remote repository on GitHub, but only in my local Git history.

Vale,
Quintus
