### ISSUE TITLE
Optimize PNGs

### ISSUE THREAD

**Issue by Luiji** [Secretchronicles/TSC#343]
This is a note that we should run the `optipng.sh` before release. It is not necessary before then, but should be done to ensure the minimal size of our distribution.

Additionally, I would like to propose we add `advpng`, the AdvanceCOMP recompression tool to the PNG optimization pipeline. It pairs well with optipng, where optipng will remove unnecessary information and convert files to indexed format where it reduces size, advpng optimizes the DEFLATE-compressed chunks.

If we agree to the later point I'll update the `optipng.sh` script. Either way, I may update it to include some friendlier messages when the depended-upon utilities are not available, such as "optipng is not installed or could not be found; it's available here..."

**Comment by Quintus** [comment]
> If we agree to the later point I'll update the optipng.sh script.

I would suggest removing it alltogether and instead create a task in the `Rakefile` that runs the `optipng` program.

Vale,
Quintus

**Comment by Luiji** [comment]
@Quintus I'd be fine with that as well. Merging scripts into the `Rakefile` will keep things nice and clean.

**Comment by Quintus** [comment]
@Luiji With the [most recent commit](https://github.com/Secretchronicles/TSC/commit/1500eb590b6e4cebd606b1a3c4d48822a8391aa4) all graphics changes for the 2.0.0 release have been added. Would be nice if you could run `rake optipng` now, commit the result, and close this ticket :-)

Vale,
Quintus

**Comment by Quintus** [comment]
Nevermind, I’ll just do it myself then.

Vale,
Quintus

**Comment by Quintus** [comment]
~~~~~~~~~~~~~~~~~
Old total size of all PNGs: 74 MiB 192 kB 341 B
New total size of all PNGs: 68 MiB 540 kB 462 B
Reduction in size thus is:  5 MiB 675 kB 903 B
~~~~~~~~~~~~~~~~~

Vale,
Quintus
