### ISSUE TITLE
Package Builder User Interface...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#348]
This is a task to create a package builder user interface for users who do not know XML or are otherwise untechnical.

@brianvanderburg2  suggested the following in #106:

> A package editor should not be to complex as a package doesn't have a lot of data.
>     package name, using a dotted notation "simpletoon.levelset1" or "simpletoon.respack1"
>     package description, user overrides game
>     hidden or not hidden, false overrides true (a checkbox would be needed in the menu to show hidden packages)
>     the menu level to use for the package, user overrides game
>     package dependencies, user first then game
> Editing a package does not edit any packages from the game data directory, so while the menu would show the correct description based on user/game package, an editor should only show the data from the user package.
> - Create new package - prompt for name, make sure it doesn't exist, then create a new directory under USERDATADIR/packages with .smcpkg extension, create initial package.xml file with name
> - Edit a package - Determine user data directory, if not set then create directory and initial xml file with name.
> 
> There are some issues with the code though, so you can't change packages in the middle of game play. I initially tried some weird hacks to work around this, but if any levels are open, if any sprite managers are up, they may end up caching the wrong images during a switch. Also, since the worlds and levels would get completely reloaded, the current loaded levels list get completely discarded, etc, (Currently the level manage seems to try to always keep one level around to hold onto the sprite manager) you can't switch in the middle of playing a level or world. I experienced crashes that are quite difficult to trace and fix and settled on the only currently reasonable solution being to set the current package at program start-up. Changing the package doesn't take affect until restarting the program.

Yes, XML is less difficult than something like programming (or even scripting), but we're dealing a bit more with psychology and time investment from users.

**Comment by Quintus** [comment]
With the package system being on hold indefinitely, there is no point in leaving this open.
