### ISSUE TITLE
Settings Files Editors for Graphical Editing / Viewing...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#351]
In #319, we talked about creating GUI components to edit settings files or view data from them.  A ticket like this is obviously the best place to discuss this rather than cluttering the code discussion for issue 319.

These are some items that have been suggested:
* A graphical tool to edit / add images to an animation sequence.
* A graphical tool to view the images in sequence for an animation
* A graphical tool to edit collision boxes for an image

These allow visual editing and allow the user to view/make changes without firing up TSC every time.

As discussed in issue #319, we do not have the programmer bandwidth to create a settings file editor for every single settings file.  Thus we would only create tools for settings files that yield benefits (ie visual editing/viewing).

We would also want to maintain the same settings file format and not switch to something like XML.  This way programmers can continue to use scripts on the command line as desired to mass manipulate settings files.

cc @Quintus, @Luiji, @brianvanderburg2

**Comment by Bugsbane** [comment]
This would have saved me a ridiculous amount of time when I was working on the boxes / crates.

**Comment by datahead8888** [comment]
> This would have saved me a ridiculous amount of time when I was working on the boxes / crates.

Which settings files might this tool help you with?  Would you want to use it just for certain types or all settings files?  If people find it useful for all types of settings files, this would give us good reason to make it more generic.

**Comment by Bugsbane** [comment]
WHen I was working with the crates, and with the diamonds. I had to go and tweak multiple files multiple times, each time, saving, clearing the cache and resetarting the game to see 1-2px changes, before editing. Being able to easily see animations would be a huge help as well. Currently, Inkscape doesn't support animations, meaning you have to go through a similar process of making many changes, deleting the cache, restarting, and trying to pick where you need to make changes. If there was even just a tool that could be pointed at a folder of png's+settings files, and showed a looping animation of them, with a reload button, it would be a huge help.

**Comment by Quintus** [comment]
Creating such a tool is possible. I will look into it when I find the time. For now, quick dump of my thoughts so I don’t forget it:

* It must scale the graphics live according to the dimensions in the settings file
* Beware stacked settings files which depend on one another
* Define a naming scheme for animation image files so multiple image files are automatically recognised as an animation
* GTK has a canvas widget that should be able to do what is needed
* Probably make a toggleable hatch
* Allow defining the borders by drag’n’drop and with a widget for 1px movements of the borders
* Add an option to have a border definition affect all settings files of an animation set at once

Valete,
Quintus

**Comment by datahead8888** [comment]
My suggestion for this tool is to architect it so that it's easy to add new features (whether viewing or modifying other settings files later).  Even if we start out with just a settings file animation viewer, there's no reason we can't extend it later if an interest in such features develops.  We would then prioritize features based on actual demand from users.

**Comment by Quintus** [comment]
I’m working on this.

Vale,
Quintus

**Comment by Quintus** [comment]
So. I wrote it: https://github.com/Secretchronicles/Settingseditor

It’s currently very raw, but the basics work. It’s written in wxWidgets, so it should be cross-platform. I’ve only tested it on ArchLinux, though.

Please open tickets related to the editor on the editor’s repository from now on. General discussion can continue here of course.

Vale,
Quintus

**Comment by Bugsbane** [comment]
> I’ve only tested it on ArchLinux, though.
My main distro of choice, so that works for me. ;) Eventually it would be nice to see an AUR.
