### ISSUE TITLE
Level Selector does not display .smclvls (or smc campaigns)...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#353]
As discussed in ddcb87434df4f8b38e56caf44de896faef07c16e, Secret Chronicles currently does not list .smclvls as playable levels in a user's directory.

We definitely need to move towards using .tsclvl as the new extension in order to establish ourselves as a fork and stick with our new name of the game, but if .smclvl does not list as a valid level, the game is essentially not reverse compatible with old levels that users may copy into their directories (because the file must be renamed to be played).  My personal feeling is that this defeats the purpose of maintaining reverse compatibility for release 2.0 (and subsequent 2.X versions).

Once we reach version 3.0, we certainly will want to strip out compatibility code and support for .smclvl reading.  For now, if a .smclvl is edited, we could save it as a .tsclvl instead.

Old campaigns and old save state files are also affected.

cc @Luiji, @Quintus

**Comment by Luiji** [comment]
My opinion in this regard is that "smclvl"s should essentially be considered a separate, incompatible format. The two primary ways we can handle their support are to provide a separate read-only "compatibility loader" module (which allows us to move all the backwards-compatibility code into their own little sub-module) or to implement an import tool. In only the former case do I consider supporting smclvl files in the loader necessary.

I also do not consider the current behavior a bug as much as the lack of a feature.

**Comment by datahead8888** [comment]
> I also do not consider the current behavior a bug as much as the lack of a feature.

The reason I marked it as a bug was because the plan had been to maintain reverse compatibility (without a separate converter application) through the 2.X series and then to strip out all compatibility code in version 3.0.  The game in the release-2.0.0 branch is no longer reverse compatible.  This sort of thing is more likely to be noticed in release 2.0 than in any other version that follows.
See: #169

We can certainly discuss this plan again, but my concern is that it is very close to the release for us to be changing it.  We've also invested a lot of time in maintaining compatibility for release 2.0 already.  I also view direct reverse compatibility as good for the 2.X series because in a way it fulfills the original intent of the old SMC series; after the 2.X series all the mechanics will change.

> provide a separate read-only "compatibility loader" module (which allows us to move all the backwards-compatibility code into their own little sub-module)

This is a good idea, but it probably cannot be done in release-2.0.0 because of the risk of errors.  We could look at having a class with a series of callable methods for each step of the conversion process.  This would make it easier to strip out when compatibility support is dropped.  This could be put in the next minor release.

> implement an import tool

In the long term, once we finally drop compatibility support, this is how we could deal with legacy formats.  We had discussed waiting until version 3.0 to add the conversion tool.  This would give us a little more time to iron out how that tool will be built.  This is also discussed in #169.

@Luiji, I think your ideas are very good; it's just a disagreement about when to do this.

cc @Quintus

**Comment by Quintus** [comment]
We are to far into the release process to introduce a breaking change like not supporting `.smclvl`, etc. I agree with @Luiji that we should drop support as soon as possible, but we can’t do so for 2.0.0 right now. I do also agree with him that the support has to be read-only, i.e. when an `.smclvl` file is encountered, it should just be read in and when it gets saved out, it’s saved as a modern `.tsclvl` (removing the `.smclvl`). We have an even older format in the compatibility code that does exactly this, and I think adding `.smclvl` to that is nothing too complicated. If @datahead8888 hadn’t assigned the issue to himself I’d have implemented it over the next week sometime.

On the long term I agree with @datahead8888 we need an importer tool so we can clearly separate the backward compatibility code from the actual current format code.

Vale,
Quintus

**Comment by datahead8888** [comment]
> If @datahead8888 hadn’t assigned the issue to himself I’d have implemented it over the next week sometime.

I could post changes to a branch.  If it becomes beneficial, we could both contribute to it (as long as we clearly communicate who is doing what).  At the very least, I will ask if you and Luiji can look it over when I'm done, since it will be easy to make a mistake with legacy code like this.

Once release 2.0 is done, format discussions, story discussions, and mechanics discussions will become a big priority :)  We at least need to start figuring out what we want to do going forward.

**Comment by datahead8888** [comment]
Is there a way to edit campaigns?  If not, I don't really see a point in adding conversion code for these -- they will have been converted through Luiji's renaming of the prepackaged campaign files.

There is no button to create a New World right now, but since the use is able to edit existing worlds, I think it makes sense to add conversion code for world file names.

**Comment by Quintus** [comment]
> Is there a way to edit campaigns?

No. You have to edit the XML by hand currently.

> There is no button to create a New World right now, but since the use is able to edit existing worlds

Yes. You can edit an existing world by pressing F8 and then save it under a different name.

Thus, I think you are correct with your conclusion.

Vale,
Quintus

**Comment by datahead8888** [comment]
> Yes. You can edit an existing world by pressing F8 and then save it under a different name.
Thus, I think you are correct with your conclusion.

It turns out world xml files and their directories have no reference to smc or tsc.  Thus there is nothing to make compatible for them.  I can't complain about this :)

**Comment by Quintus** [comment]
Awww, you are right. The worlds are just saved by world name, and the files have an `.xml` extension.

Vale,
Quintus
