### ISSUE TITLE
New Tutorial Music...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#355]
We removed the old Mario based tutorial music when @sauer2 created a new tutorial level for us and went ahead and assigned it to a different song.

This is a task to created brand new tutorial music.  It would probably need to have an action-adventure theme, to fit with the lava filled adventurous (somewhat like an Indiana Jones theme?) tutorial level.  This also may work well with our new story.

**Comment by kirbyfan64** [comment]
If this isn't being worked on yet, I can try to do it tomorrow (I know you guys are releasing soon...).

**Comment by datahead8888** [comment]
I think something adventurous, kind of like from a motion picture might work for this.  You might look again through the drafts that Danfun64 and I published in #68.  Hopefully once I'm finished with school, I'll have time to follow up on the story again.

**Comment by kirbyfan64** [comment]
*sigh* Unfortunately, due to FL Studio/VST-related issues, as well as my brain not working correctly right now, this will *not* be ready today. Sorry... :(

**Comment by datahead8888** [comment]
No problem - take as long as you need.

**Comment by datahead8888** [comment]
@kirbyfan64 - would you still be up for this?  This would make a nice addition to release 2.1 and would be noticeable from the beginning.

**Comment by datahead8888** [comment]
We have a submission at http://forum.secretchronicles.de/topics/461

Thanks, @kirbyfan64!

**Comment by Quintus** [comment]
I'm for committing it.

**Comment by datahead8888** [comment]
I'm marking this as version 2.1, so we can make sure we get it into the release.
