### ISSUE TITLE
Level exit/entry wrong position

### ISSUE THREAD

**Issue by brianvanderburg2** [Secretchronicles/TSC#357]
When a level exit goes to an entry in the same level (and maybe a different level but not yet tested), the animation sometimes places the player at the wrong position before placing him at the correct position.  I've noticed this seems to happen both with blink and fly mode.

**Comment by Quintus** [comment]
I have never seen this. Can you provide a detailed step-by-step reproduction guide?

**Comment by Quintus** [comment]
Closed due to inactivity.
