### ISSUE TITLE
Low level warp down may kill player.

### ISSUE THREAD

**Issue by brianvanderburg2** [Secretchronicles/TSC#358]
If a level warp down is placed to low to the bottom (kill) zone, when the player goes through the warp and thus drops below the zone, the player appears at the destination but immediately dies.

**Comment by Quintus** [comment]
I remember seeing this issue in old SMC 1.9 already, so it’s nothing that was newly introduced. Thank you for opening a ticket on this.

Next week’s sunday (i.e. not the day after tomorrow) I will be done with my exams and can return to game development. I fear if I look into the `devel` branch then I will find @brianvanderburg2 has silently renamed the game to “Dr. M. Invader” and made it a space shooter :-)

Vale,
Quintus

**Comment by brianvanderburg2** [comment]
Lol.  Nah I haven't made any major changes.  The only major feature I've worked on is the Animations feature, and I haven't committed it to devel yet, first I want other to check it out some.  I might make a small test level to demonstrate it and upload it to the forums.
