### ISSUE TITLE
Option to disable image cache

### ISSUE THREAD

**Issue by brianvanderburg2** [Secretchronicles/TSC#359]
I think it could be useful if there is an option to disable using and creating the image cache.  This is particularly useful from a development standpoint where each git checkout of a different branch may end up attempting to recreate the cache.

Something like:
```
tsc --disable-cache
```
Would be good I think.

**Comment by datahead8888** [comment]
This is a great idea!  This would make life so much easier, especially when running TSC from a shell script.

**Comment by Quintus** [comment]
There *is* an option for disabling the image cache. Simply set

~~~~ xml
<property name="image_cache_enabled" value="0"/>
~~~~

in your TSC configuration file (this value is `1` by default).

Valete,
Quintus

**Comment by Bugsbane** [comment]
The number of hours I could have been saved, if I knew this... X-|
