### ISSUE TITLE
World Save State - Finished Levels Do Not Save...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#360]
This bug currently happens in the release-2.0.0 branch.  If you save your state in world 1 then load it, your progress points are lost, and you will be unable to backtrack to those levels.  I have only tested this in world 1.

I have made a video of the glitch:
https://www.youtube.com/watch?v=UsOVkMoGX-w&feature=youtu.be

I think this is probably impacting enough that it needs to be marked for the release-2.0.0 milestone, but I'll see if everyone agrees.  I'm sad to have found another major bug, but it's good we're aware of it.

I also tried purging all save state files and rerunning the test.  The problem still happened.

cc @Quintus, @Luiji.

**Comment by Quintus** [comment]
You don’t have to CC us all the time for new tickets. We check the tracker anyway. Please only use that if you want a quick reply so the feature doesn’t get overused. I’ve got 100 GitHub notification emails that are marked as unread, and getting more will not result in more attention.

Before marking this for 2.0.0, I want to find out more about the circumstances why this happens.

Vale,
Quintus

**Comment by datahead8888** [comment]
> You don’t have to CC us all the time for new tickets.

I had done this because I figured it might be impacting to the release, but I can try to use the feature less often in general.

> Before marking this for 2.0.0, I want to find out more about the circumstances why this happens.

I had figured it should be a release 2.0 task because it impacts a player's level progress; most players won't be very happy if they save on the world map, move backwards, and have to repeat old levels.  The release 2.0 marker reminds us that something needs to be researched or fixed in the release; it can always be removed later.

Regardless of how we mark it, I think someone will at least need to look at this more before release 2.0 and draw conclusions.

**Comment by Quintus** [comment]
@datahead8888 I can’t reproduce. See this video, which is made from current `release-2.0.0`:

http://team.secretchronicles.de/~quintus/stuff/overworld-bug.ogv

Vale,
Quintus

**Comment by Quintus** [comment]
Btw. the video also shows the invocation of `recordmydesktop` and how to redirect sound in PulseAudio for it. That might be useful for you :-)

Vale,
Quintus

**Comment by datahead8888** [comment]
> I can’t reproduce

In this case, I need to test for a corrupted profile or other user data.  Where it the TSC data stored for a user profile in Linux?  I could then move it somewhere else and simulate "a fresh install".

**Comment by Quintus** [comment]
> In this case, I need to test for a corrupted profile or other user data. Where it the TSC data stored for a user profile in Linux? I could then move it somewhere else and simulate "a fresh install".

* `~/.local/share/tsc`
* `~/.cache/tsc`

Beware if you delete the first directory your custom levels will be gone.

Vale,
Quintus

**Comment by datahead8888** [comment]
Wiping out these directories (actually I renamed each instance of tsc as tsc2 to avoid losing data) fixed the problem.  This suggests my user data was corrupted.

If there is interest (and if I know what files to use), I could upload the user files to the forum for review.  Does it sound useful to see what data could cause all world saves going forward to be messed up?  Could this be a robustness issue?

Figuring out what caused the profile to be written like this would be much more difficult - that's probably not something to pursue unless this happens again.  In-development-code could have been what corrupted my user data.

I am glad this is not an issue for the release.

**Comment by Quintus** [comment]
> Does it sound useful to see what data could cause all world saves going forward to be messed up?

Feel free to do so, but I guess it has something to do with your savegame fixes. Maybe you had a corrupt savegame (from your work on the savegame handler) that you loaded, then played the world, then saved again, thus keeping the corrupt state?

> Figuring out what caused the profile

What profile are talking about? TSC makes no profiles.

> that's probably not something to pursue unless this happens again. In-development-code could have been what corrupted my user data.

That’s what I personally think given I wasn’t able to reproduce. I’ll close this, but feel free to reopen if you find something that suggests this isn’t related to corrupt data.

Vale,
Quintus

**Comment by datahead8888** [comment]
> Maybe you had a corrupt savegame (from your work on the savegame handler) that you loaded, then played the world, then saved again, thus keeping the corrupt state?

In the video, I create a brand new save then load it.  This could not have been an old save file.

> TSC makes no profiles.

If it wasn't a save state, something had to have caused it.  This is very interesting...

To your point, we don't really need a ticket for this unless we find clear evidence that user data is able to break the game when it should not.  In that case, we could look into the robustness of the code.  What produced the data would probably be irrelevant, as long as it wasn't an old save state causing the problem.

**Comment by Quintus** [comment]
> In the video, I create a brand new save then load it. This could not have been an old save file.

You could have loaded a previous savegame before the video even starts.

> If it wasn't a save state, something had to have caused it. This is very interesting...

To be clear, ALL stuff TSC saves is in the `.tscsav` file. Nothing else is stored from in-game state.

Vale,
Quintus
