### ISSUE TITLE
1-Up Berry Name...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#365]
We currently have references to a "1-Up Berry" in the level editor (maybe elsewhere - this would have to be checked).

This sounds a lot like "1-Up Mushroom" from the Mario games.

We might consider renaming it to something like "Life Berry", which I seem to remember seeing somewhere.

If this isn't just a settings file change, we will also need to update translations.

**Comment by Quintus** [comment]
I’m OK with “life berry”. Or do we want to be a bit more interesting and call it the “magic berry” or something like that?

Vale,
Quintus

**Comment by datahead8888** [comment]
Life berry is a very self descriptive name.  Most players will quickly learn a new name once introduced to it, though.

**Comment by Bugsbane** [comment]
Personally I like Life Berry. No confusion there.

**Comment by datahead8888** [comment]
> Personally I like Life Berry, although I have no problem with "1 Up Berry". No confusion there.

This is my general thought, but I'm open to other ideas.

**Comment by sydneyjd** [comment]
Life berry is ok by me, even though for some reason it doesn't quite fit as well as 1 up berry. Too much mario gunk in my noggin. :P

**Comment by datahead8888** [comment]
Sorry, I misread Bugsbane's suggestion.  I like life berry more than magic berry.  I don't think we should use 1-Up berry because Mario games are the only games I can think of that use that term.

**Comment by Bugsbane** [comment]
Seems to me everyone's happy enough with Life Berry...

**Comment by Quintus** [comment]
> Seems to me everyone's happy enough with Life Berry...

Yeah. I’ll change it when I find the time :-)

Vale,
Quintus
