### ISSUE TITLE
Final Music Assignment Review...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#366]
Before finishing release 2.0, we need to review the final assignments of replacements for Mario music and decide if we still need to swap any songs around again.  We also should verify that the music in each level works well (ie does the volume fit).  

Lastly, we might think if there are any levels we want to assign to other music.  We've added a number of songs that are not used yet in official levels.  Not all of the songs are appropriate to use (ie if we don't have a certain level type yet), but we might be able to put them to good use.

**Comment by Quintus** [comment]
I don’t think we have to do this for the 2.0.0 release. If you know levels which now have a totally wrong music, tell us so we can correct this; otherwise I’d just regard that as "general game improvement" and close this issue as levels are improved over time anyway.

Vale,
Quintus

**Comment by datahead8888** [comment]
I agree.  Problems in Mario replacements can be discussed in #97.  I also am fine with leaving the Vanilla Dome replacement where it is, at least for release 2.0.  We increased the volume for that song, which is a reasonable improvement.  We can always continue to discuss this later.
