### ISSUE TITLE
Z Layer Waypoints Issue...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#370]
In ticket #115 it was mentioned that there is a Z layer problem with world way points:

sauer2 said:

> when creating waypoints, they always are below the way sprites (tl:dr, z-layering is probably broken somehow)

Quintus said:

> The waypoints have been showing Z layer problems twice already which have been fixed in turn. It seems they don’t want to be fixed.

How impacting is this issue?

**Comment by datahead8888** [comment]
Sauer2 recently said it is difficult to add new worlds due to a bug in the world editor.  Is this the bug?
Does it require rewriting the code for it to fix it?  We've talked about adding a world or two for an upcoming 2.X release, so this is a task to talk about.

**Comment by Quintus** [comment]
> Sauer2 recently said it is difficult to add new worlds due to a bug in the world editor. Is this the bug?

No. The disfunctional world editor is an unported piece of CEGUI code most likely. I extensively focused on the level editor, but barely touched the world editor at all.

Vale,
Quintus

**Comment by datahead8888** [comment]
> No. The disfunctional world editor is an unported piece of CEGUI code most likely.

Do you mean it (mostly) worked before the Cegui upgrade but was left broken afterwards?
We should open a ticket if it is a different issue.  We can decide what to do with it from there.

**Comment by Quintus** [comment]
> Do you mean it (mostly) worked before the Cegui upgrade but was left broken afterwards?

Yes.

> We should open a ticket if it is a different issue. We can decide what to do with it from there.

Yeah, probably.

Vale,
Quintus

**Comment by Quintus** [comment]
>> We should open a ticket if it is a different issue. We can decide what to do with it from there.

> Yeah, probably.

I revoke that statement. There *is* already a ticket for that: #555.

Vale,
Quintus
