### ISSUE TITLE
Save games not loading correctly.

### ISSUE THREAD

**Issue by brianvanderburg2** [Secretchronicles/TSC#378]
Some objects in save games do not get loaded.  I haven't be able to trace the exact problem, but have found out a few things.

**Spika**
I added the following code:

``` c++
cSpika::cSpika(XmlAttributes& attributes, cSprite_Manager* sprite_manager)
    : cEnemy(sprite_manager)
{
    cSpika::Init();

    // position
    Set_Pos(string_to_float(attributes["posx"]), string_to_float(attributes["posy"]), true);
    cerr << "I AM SPIKA" << endl;
    cerr << m_start_pos_x << ":" << m_pos_x << endl;
    cerr << m_start_pos_y << ":" << m_pos_y << endl;

    // color
    Set_Color(static_cast<DefaultColor>(Get_Color_Id(attributes.fetch("color", Get_Color_Name(m_color_type)))));
    cerr << "I AM SPIKA" << endl;
    cerr << m_start_pos_x << ":" << m_pos_x << endl;
    cerr << m_start_pos_y << ":" << m_pos_y << endl;
}
```

When loading the savegame, I get the following results:

```
Loading savegame file '/home/allen/.local/share/tsc/savegames/3.tscsav'
I AM SPIKA
6508:6508
-541:-541
I AM SPIKA
6508:6499
-541:-550
Loaded level: /home/allen/Downloads/versioned/SMC3/build-devel/testinstall/share/tsc/levels/bad_evening.tsclvl
```

After calling Set_Color, the position has changed.

Apparently, what happens is:
- Set color adds the image set of the correct images
- Set color calls Set_Image_Set("main")
- This calls cMovingSprite::Set_Image
- If there is a collision point change, it calls Move
- Move moves the code, and then the m_pos_x/m_pos_y is no longer equal to m_start_pos_x/m_start_pos_y

**Comment by datahead8888** [comment]
Do you know if this just happens in just devel or also release-2.0?

**Comment by brianvanderburg2** [comment]
Debugged using nemiver.  I set a breakpoint at cSpika::cSpika.  After Set_Pos, m_pos_x is 6508, after calling Set_Color, it is 6499.

**Comment by datahead8888** [comment]
If the position checking we discussed is causing it not to save, there is a boolean field for "exceptions" to the normal saving rules you can define.  You would just check if it's a Spika and then set that boolean field if so.  It's a bit hacky, but it would get the Spika saving if this is the cause.  I can't look into it right now, though.

**Comment by brianvanderburg2** [comment]
It's saving fine, just not loading right.  Also, it seems this issue could affect anything that uses cMovingSprite, since it is within the call to cMovingSprite::Set_Image that makes the move if collision rectangle of the previous and current image differ.

I added the following to savegame.cpp:
```c++
                /*The Get_from_Position method below searches for the saved object in the level definition using its original position information.
                Loose shells will slightly have their current position offset based on their image during the initialization process during level loading
                Only require the original position field be checked for them.*/
                if (save_object->m_type == TYPE_SHELL || save_object->m_type == 31) {
                    checkPosition = 0;
                }
```

and now spika loads in the correct position.  I understand this what this does is requires only that the start position match for the save item to load, and not both the start position and current position.  But this seems a little bit hacky.

This seems to be the problem:
* Initially there is no "current" image
* cSpika::cSpika calls cSpika::Init -> Set_Color(COL_ORANGE), which eventually calls Set_Image
* SInce there is no current image, there is no collision rectangle difference.
* cSpika::cSpika then calls Set_Color(attributes), which eventually calls Set_Image
* Now the list of images is cleared, but there is still a current image
* Set_Image will now have a collision rectangle different from the old (orange) and new (grey) images, and will change m_pos_x and m_pos_y

I see two possible solutions:

* For cSpika, remove Set_Color from Init, and instead put it in both constructors.  That way, it doesn't get called twice with the second constructor (once from the second ctor calling Init, then again directly).  This solution would only fix the issue for cSpika. Other cMovingSprites may still have the issue
* During Clear_Images, reset the current image to NULL (m_image = NULL)  This way there is no current image, and the next call to Set_Image will not have a collision difference.  This should be optional and default to false:  cAnimateSprite::Clear_Images(bool reset=false) (release) cImage_Set::Clear_Images(bool reset=false) (devel)

**Comment by brianvanderburg2** [comment]
I have confirmed that the second solution seems to works.  I've pushed a small animation change to devel allowing Clear_Images to clear the current image. The branch VanderburgLoadFix1 uses this change, currently only for Spika, and it seems to work.

**Comment by datahead8888** [comment]
Do you think it would be risky to put this change in the release branch (since we're close to a release date)?  If not, it'd easily be one less bug for the users.

Thanks for taking on this issue :)

**Comment by brianvanderburg2** [comment]
I don't know.  I don't think it would break any compatibility though as no formats change, just what happens when an animated sprite's image list is cleared.

I've just pushed another commit to that branch for powerups.  It turns out to be the same:  Initially the powerup starts as one image, but then gets switched to another image with different collision rectangle, resulting in cMovingSprite::Set_Image to call Move.

Because of this, I wonder if the default for Clear_Images should be true (m_image=NULL) instead of false.  I compiled a test where Clear_Images always resets the current image to NULL, and it doesn't seem to be causing any problems.

**Comment by brianvanderburg2** [comment]
It may create a small issue.  Not moving the sprite when load it means some items initial collision rectangles may start a little different than what they were.  However, these items were also not initially saved due to bug so it may not be a problem.  For instance, the spika when setting to color grey moved by 9 pixels from what it was loaded as.

Also, care needs to be taken when editing.  When doing anything that "changes" the images, the current image should be reset, so that calling Set_Image doesn't adjust m_pos_x/m_pos_y.  Otherwise you get an issue were the start position is one thing, but changing the image causes the current position to move a little.  After saving to file, it saves the start position, but the loading code shouldn't doesn't move it again, so the loaded position isn't visually the same as the saved position. This means:
* Edit operations should either call Clear_Images(true) when changing an image, such as editing the moving platform's left image or static enemy image.
* Loading from level should also do the same.
Normally, both of these are achieved by having a single function that does the work, and that function gets called both by the editing event handler and by the loading code.  During actual game play, switching from one image to another will still perform the move if the collision rectangles are different.

**Comment by datahead8888** [comment]
> I don't know. I don't think it would break any compatibility though as no formats change, just what happens when an animated sprite's image list is cleared.

I just meant that if it's essentially an architectural change, it might be too risky (bug wise) for release 2.0.  Does the fix require image sets (the .imgset changes) to work?  Otherwise it would be good for the release if we can put it there.  This decision also might be dependent on how many bugs this change is expected to fix.

**Comment by brianvanderburg2** [comment]
No, it doesn't.  It can also be done with release-2.0 code.  It's basically the exact same code in all the other files, and just change cAnimated_Sprite::Clear_Image to do the same thing.

**Comment by datahead8888** [comment]
> No, it doesn't.

If it's not an architectural change it'd be useful for the release, if anyone can get it ported over.

> Also, should the static enemy save the current rotation? 

Yes, I think it should.  There was a lot of stuff that didn't used to save; it's usually better to err on the side of saving data.  We'll probably be finding stuff like this for a while...

**Comment by datahead8888** [comment]
Is this still a bug in the devel branch?  I know Quintus and Brian Vanderburg implemented an overhaul (with bug fixes) for saving.  Much of the discussion was about whether this could be moved to release-2.0, but now devel is all we care about.

**Comment by Quintus** [comment]
No response from OP, closing.
