### ISSUE TITLE
You can't play unless you install.

### ISSUE THREAD

**Issue by Danfun64** [Secretchronicles/TSC#386]
Whenever I play a game that uses svn or git, and which can change at any moment, I prefer not sudo make install ing. However, it appears that the game refuses to work unless it detects a share folder or whatever. Maybe you can "fix" this issue to make the game more portable?

**Comment by Quintus** [comment]
>  I prefer not sudo make install

Don’t do it. You don’t have to install to a root-only location. Compile TSC like this and be fine:

~~~~~~~~~~~~~~~
$ cmake -DCMAKE_INSTALL_PREFIX=whereeveryouwantit ..
$ make
$ make install
~~~~~~~~~~~~~~~

Vale,
Quintus

**Comment by Danfun64** [comment]
I don't understand why you don't like games not being installed. Most open source games that I've seen, including you main "competitor", supertux, can run just fine on their own if one wishes it.

However, you're one of the developers, I'm not. If you think the game *has* to be installed in order to work properly, that is up to you.

**Comment by datahead8888** [comment]
@Danfun64 - could you explain a little more what you're saying?  It works properly if you use the DCMAKE_INSTALL_PREFIX to build it in a chosen directory, and you can then play it out of that directory.  Alternatively, we have an installer utility that does install it on the system with an icon, etc.  This installer gets used for each of the beta releases our team has put out so far.  How else could we make the game installation work?

**Comment by Danfun64** [comment]
Let me explain what I mean by not installing using Supertux as an example. Both games require using cmake and make to compile. However, Supertux places the binary in the folder where the game is, and makes installing optional from that point. Most other open source games follow the philosophy of not requiring "make install" to occur. However, TSC places the binary in the build folder. Even if you do "cmake .", the game will refuse to run unless it is "installed".

**Comment by sydneyjd** [comment]
I personally don't care that TSC uses the DCMAKE_INSTALL_PREFIX command, as long as i only hve to use it the first time i build. So once i do it im fine with it.
But ad Danfun64 stated, supertux just does cmake .. and make and it creates a nice little executable in ~/Supertux/build and it is a little easier.
@Quintus Is it possible for you to explain why we have to chose the build directory that we want in TSC vs just dumping an executable in a normal premade folder?

-Sydney

Also, welcome to TSC @Danfun64 !!

**Comment by Quintus** [comment]
> @Quintus Is it possible for you to explain why we have to chose the build directory that we want in TSC vs just dumping an executable in a normal premade folder?

Windows. This way we have easy handling of the resources to be loaded that looks the same on each platform and allows you to have multiple installations of TSC even on Windows while still keeping the code the same and simple.

Vale,
Quintus

**Comment by Danfun64** [comment]
For Windows this problem is even worse. Have you ever heard of portableapps? Such a setup would be impossible for TSC as long as installation is required.

**Comment by Quintus** [comment]
> For Windows this problem is even worse. Have you ever heard of portableapps? Such a setup would be impossible for TSC as long as installation is required.

Exactly _not_. TSC’s setup is ultra-portable, because it looks up its pathes relative to its main executable. You do not understand what the install step means. It has nothing to do with fixed pathes.

Vale,
Quintus
