### ISSUE TITLE
Alex still has "Maryo" symbols.

### ISSUE THREAD

**Issue by Danfun64** [Secretchronicles/TSC#387]
The "M" motif still remains in Alex's clothing. Are the "m"'s to be removed or no?

**Comment by datahead8888** [comment]
@Danfun64 - we were talking about removing the M's at https://github.com/Secretchronicles/TSC/issues/264

One of our artists, Bugsbane, was interested in using a paint tool to remove them.  We would normally use Inkscape, but we do not have SVG vector graphic files for the Alex graphics, unfortunately.  Thus we really need to redo the Alex graphics entirely.

**Comment by Danfun64** [comment]
Being a duplicate issue...I will close this.
