### ISSUE TITLE
More Hills Replacements...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#390]
As discussed in #298, there are more hills that probably need to have eyes removed as part of our de-Marioization efforts.   Since we have discussed having eyes on a limited number of objects, this point also needs to be considered.

These are the hills that Quintus found:
*  https://github.com/Secretchronicles/TSC/blob/v2.0.0-beta7/tsc/data/pixmaps/game/background/blue_waterhills_1.png
* https://github.com/Secretchronicles/TSC/blob/v2.0.0-beta7/tsc/data/pixmaps/game/background/green_hills_2.png
* https://github.com/Secretchronicles/TSC/blob/v2.0.0-beta7/tsc/data/pixmaps/game/background/green_junglehills.png

@Bugsbane - you will probably find our new De-Marioization label useful when looking for this kind of task.  Of course, tasks that block the release for any reason will continue to be marked "Blocker".

@DarkAceZ - feel free to play with these and post any drafts.

**Comment by sydneyjd** [comment]
I could maybe give one of the hills a shot.  The only one i've seen in use is the one in the last link. I wonder if we just pulled the other two. My thought. But that may cause more issues then swapping it out with diferent graphics.

**Comment by datahead8888** [comment]
We originally tried removing the hedge, which raised concerns with some team members that it impacts old levels by removing well designed scenery.  This will be even more true for background images like hills.  We also tried changing the settings file for the hedge to point to a different image.  That ended up causing bugs in some places.

If these hills are not used in levels it would be fine to remove them outright.  Otherwise, I think we need to do a direct replacement.  We probably can get away with just editing out the eyes for now.

**Comment by sydneyjd** [comment]
@Quintus @datahead8888 @Secretchronicles/artists 

Opinions on these?

![green_hills_2](https://cloud.githubusercontent.com/assets/8949851/6789069/f5128858-d173-11e4-8028-47db9efeda2c.png)
![green_junglehills](https://cloud.githubusercontent.com/assets/8949851/6789070/f5142550-d173-11e4-9b01-cd79368f0c02.png)

**Comment by sydneyjd** [comment]
SVGs

https://cloud.openmailbox.org/public.php?service=files&t=98a945797c3b74036e423493d3c59b5a

https://cloud.openmailbox.org/public.php?service=files&t=65977eaf374c35a3fe60390c7ba2b507

**Comment by datahead8888** [comment]
@sydneyjd, we still need a license statement.

**Comment by Quintus** [comment]
@datahead8888 No, we don’t :-): http://forum.secretchronicles.de/topics/227/posts/1083

Vale,
Quintus

**Comment by sydneyjd** [comment]
@Quintus @datahead8888 Hows this look? Thanks for the tip datahead. ;)

![blue_waterhills_1](https://cloud.githubusercontent.com/assets/8949851/6795210/6b23d1d4-d1b3-11e4-8b67-b831df90f104.png)

**Comment by datahead8888** [comment]
These look perfect!  Did you use a clone tool?

**Comment by sydneyjd** [comment]
Yes! :)

**Comment by Quintus** [comment]
@sydneyjd Is this correct that the size of this image is so much smaller than the size of the other ones you posted?

Vale,
Quintus

**Comment by sydneyjd** [comment]
@Quintus It is the same sizw PNG as the original in game, i just tweaked it. I didn't touch the Rezolution.Yes, it is alot smaller than the others.
