### ISSUE TITLE
No automatic uninstallation using make

### ISSUE THREAD

**Issue by Danfun64** [Secretchronicles/TSC#391]
On many linux programs that have been compiled by hand, there is a feature that goes "sudo make uninstall", which would automatically remove everything inside the program. Cmake doesn't provide this functionality by default, so it's up to the developers of programs using cmake to implement it themselves. Could you do this before 2.0.0?

**Comment by xet7** [comment]
Currently I compile TSC git directory to my home directory like this, and then start the game:
```bash
cd ~/TSC/tsc/build
make clean
rm -rf ~/tsc && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=~/tsc .. && make && make install
cd ~/tsc
./bin/tsc
```
So to remove tsc, it's only:
```bash
rm -rf ~/tsc
```
But if installing with sudo creates menu options (does it?) this would need something more complicated.

**Comment by Luiji** [comment]
With the power of `install_manifest.txt` this is a pretty easy thing to do (and one I've done myself in the past). My only question is: shell script (`uninstall.sh`), Rakefile rule (`rake uninstall`), or something else? Adding `make uninstall` would require CMake'ing it up, which I'm not particularly knowledgeable in, but I'll look into it. Looks kind of like [1] is relevant, but I'm not sure how to make it a `PHONY` target (which is *technically* not necessary as long as a file named `uninstall` doesn't exist, but it's really unhealthy to depend on the user not creating that file).

[1] http://www.cmake.org/cmake/help/v3.0/command/add_custom_command.html

**Comment by Quintus** [comment]
@Luiji status of this?

Vale,
Quintus

**Comment by Quintus** [comment]
Unassigning, Luiji doesn’t have time for this.
