### ISSUE TITLE
What is the license of the game going to be?

### ISSUE THREAD

**Issue by Danfun64** [Secretchronicles/TSC#392]
If it's going to be DFSG-complient and/or FLOSS, reunion_1.ogg will have to go, due to using a nonfree license (CC-BY-NC-SA 3.0).

**Comment by Quintus** [comment]
> If it's going to be DFSG-complient and/or FLOSS, reunion_1.ogg will have to go, due to using a nonfree license (CC-BY-NC-SA 3.0).

Our assets currently have several different licenses (see note at the end of the README). We are not commercial, so an NC license is not a problem for us to use.

As far as the future is concerned, we ideally want to license all of our assets as CC-BY, but that’s a long way to go still. Don’t expect this to happen in short time.

Vale,
Quintus

**Comment by Danfun64** [comment]
Well, you should at least *try* to avoid non-free licenses.

**Comment by datahead8888** [comment]
> We are not commercial, so an NC license is not a problem for us to use.

If we try to raise funds by selling a soundtrack later, this may cause a problem.  We will probably just have to strip out all songs with unacceptable licenses from the sold soundtrack.  I do not think we need to permanently remove songs from the game, at least not now.

I understand CC-BY-SA 4.0 is just as much of a problem as the one Danfun64 asked about, correct?

> and once the de-marioization process is completed, it won't at all

Yeah, the Mario references have been a major problem, since a lawyer could have gotten us on being a derivative Mario work.  The fear of legal action has caused many more problems for us.

**Comment by Danfun64** [comment]
How is CC-BY-SA a problem? As far as I know, it is a free license.

**Comment by datahead8888** [comment]
> How is CC-BY-SA a problem? As far as I know, it is a free license.

I know Quintus said it's technically incompatible with the other licensing we have.  I may have been wrong on the commercial aspect.

**Comment by Danfun64** [comment]
You might be confusing it with CC BY-NC-SA, which *is* non-free.

**Comment by Quintus** [comment]
I have outlined the CC-BY-SA incompatibility in lengths and lengths and will not repeat it again. GPLv3 and CC-BY-SA have conflicting copyleft clauses, you can’t use it in one work. See the long discussion with simpletoon on the forum: http://forum.secretchronicles.de/topics/221

Vale,
Quintus

**Comment by Quintus** [comment]
The decision was made for CC-BY as the goal license, but we can’t accelerate the process of people contributing new assets. In the meantime, the old assets will be kept. If people contribute properly licensed replacements, we’ll have to decide on whether an existing assets should be removed in favour of the new asset.

Valete,
Quintus

**Comment by Bugsbane** [comment]
> The decision was made for CC-BY as the goal license

Is this referring to the code, the media assets (sprites, music etc) or both?

**Comment by Quintus** [comment]
> Is this referring to the code, the media assets (sprites, music etc) or both?

Only assets. The decision I refer to is the same we have been discussing since very long, so nothing changed in this regard. We can’t change the code license anyway, because we are bound by FluXy’s GPL license as long as we have code fragments by him (which are still many).

Vale,
Quintus
