### ISSUE TITLE
New Massive Type "Physics"

### ISSUE THREAD

**Issue by DarkAceZ** [Secretchronicles/TSC#395]
If any tile/normal object could have the physics that the crate currently has, it would open all kinds of designs in TSC levels.

I originally thought of the idea when I was making a level. I wanted to have a pow block drop out of a secret area, but then realized that the pow blocks, like all other blocks, do not have the option to have physics like enemies, or the crate.
Not to be confused with #41.

**Comment by Quintus** [comment]
In this generality, this is too difficult to implement with the current state of the codebase. However, the good news is, you can do this with scripting now. Thus, closing this.
