### ISSUE TITLE
Publish your TSC team membership status

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#396]
Hi everyone,

this issue is targetted towards the people of the TSC team who have not yet published their status. As it was determined yesterday in IRC that voting right has who is listed as a member of the _Secretchronicles_ organisation on GitHub, please go to this page:

https://github.com/orgs/Secretchronicles/people

and set your membership status to “public”. This allows everyone to view that list. By default only organisation members can see you otherwise, which is bad for public votings.

This affects the following people: @Aakburns @Bugsbane @datahead8888 @Luiji @sydneyjd @tristanheaven @xet7 

Please do as described above. Thank you.

Valete,
Quintus

**Comment by xet7** [comment]
Done for my part. Currently missing only @Luiji and @tristanheaven .

**Comment by Luiji** [comment]
I'm set. @tristanheaven seems to be the only person with two-factor authentication, BTW. ;P

**Comment by xet7** [comment]
Ok it seems that everybody has published their status. Closing #396.
