### ISSUE TITLE
Wipe or convert XAR files

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#398]
We currently have a lot of Xara vector source files in the repository. The thing is, we currently have no way to convert them to SVG and thus they’re basically worthless for us. If anyone finds a way to convert them to SVG, that’d be great, otherwise we have to remove them, because carrying around useless files is... well, useless. They can always be acquired from the Git history if some conversion tool shows up.

Here’s the list of XAR files we have:

```
% find -iname '*.xar'
./game/fluxy/level/blocks/stone/2.xar
./game/fluxy/level/blocks/stone/1.xar
./game/fluxy/level/apple_green.xar
./game/fluxy/level/mushroom.xar
./game/fluxy/level/hills/blue_1/big.xar
./game/fluxy/level/hills/blue_1/medium.xar
./game/fluxy/level/hills/green_2/big_1.xar
./game/fluxy/level/hills/green_2/medium_1.xar
./game/fluxy/level/hills/very_light_blue_1/big.xar
./game/fluxy/level/hills/very_light_blue_1/medium.xar
./game/fluxy/level/items/egg.xar
./game/fluxy/level/pipes/green_top.xar
./game/fluxy/level/pipes/green_small_ver.xar
./game/fluxy/level/pipes/green_ver.xar
./game/fluxy/level/pipes/green_small_top.xar
./game/fluxy/level/apple_red.xar
./game/fluxy/level/backgrounds/hills/blue_hills_1.xar
./game/fluxy/level/backgrounds/hills/blue_waterhills.xar
./game/fluxy/level/backgrounds/hills/sand_hill.xar
./game/fluxy/core/gui/itembox.xar
./game/fluxy/core/gui/menu/text/game.xar
./game/fluxy/core/gui/menu/text/save.xar
./game/fluxy/core/gui/menu/text/audio.xar
./game/fluxy/core/gui/menu/text/options.xar
./game/fluxy/core/gui/menu/text/quit.xar
./game/fluxy/core/gui/menu/text/load.xar
./game/fluxy/core/gui/menu/text/the end.xar
./game/fluxy/core/gui/menu/text/game_over.xar
./game/fluxy/core/gui/menu/text/video.xar
./game/fluxy/core/gui/menu/text/controls.xar
./game/fluxy/core/gui/menu/text/start.xar
./game/fluxy/core/gui/unknown.xar
./game/fluxy/core/gui/special.xar
./game/fluxy/particles/rain_2.xar
./game/yuki/level/window/2.xar
./game/yuki/level/window/1.xar
./game/yuki/level/window/3.xar
./website/fluxy/clock.xar
```

Valete,
Quintus

**Comment by sauer2** [comment]
> We currently have a lot of Xara vector source files in the repository. 
> The thing is, we currently have no way to convert them to SVG and thus 
> they’re basically worthless for us. If anyone finds a way to convert 
> them to SVG, that’d be great, otherwise we have to remove them, 
> because carrying around useless files is... well, useless. They can 
> always be acquired from the Git history if some conversion tool shows up.
>

In theory it's possible...

Not sure if that can be automated.

http://wiki.ubuntuusers.de/Xara_Xtreme (german link, describing that 
there is a svg export plugin)

**Comment by Quintus** [comment]
> http://wiki.ubuntuusers.de/Xara_Xtreme (german link, describing that there is a svg export plugin)

Luiji has already taken a look at that one: https://github.com/Secretchronicles/TSC/issues/102#issuecomment-64998475

Vale,
Quintus
