### ISSUE TITLE
Rendering optimisation (affects scripting)

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#401]
Hi everyone,

with my recent learning of SFML, I learned that rendering all the sprites one by one (as is done by TSC currently) is much slower than rendering all the static unmovable objects as one single entity from a tileset. See [here](http://www.sfml-dev.org/tutorials/2.2/graphics-vertex-array.php) for the SFML page I am referring to.

This makes sense to me, and I think it should be applied to TSC as well. That is, all the ground sprites (the type “massive” objects that do not move), should be combined into one single entity. Maybe the same for the other massive types for all objects that do not move. This should speed up things noticably, and with rendering from a single tileset (or a limited number of them) level loading should drastically speed up as well (which has been noticed as a problem already). If you want a simple naïve example, I have experimented with this (and other things) in [this repository](https://github.com/Quintus/sfml-minitsc).

The drawback of this is that you can’t use scripting to modify entities inside this large entity. Once loaded, it stays the way it is. In other words: If you want to affect a ground object via scripting, you’ll have to specifically mark it in the level editor accordingly. I’m not completely sure how I’d implement this, but there are solutions to this I guess. Movable stuff like enemies or platforms or so are not affected by this drawback and will stay affectable by scripting because they have to be rendered each on their own anyway (because they move all the time).

Another drawback is that the level designer has to associate the level with the “tilesets” he wants to use, because the speedup results from the possibility to render parts of one single texture rather than lots of textures on its own. Given a level should best stay in a little number of themes anyway, I don’t see this as a large problem.

Vale,
Quintus

**Comment by sauer2** [comment]
@Quintus, @Luiji:

Reminds me to ask you to optimize the particle emitter.

I might be wrong, but from a first glance it looks to me like the 
emitter is creating new particle objects in memory and deletes them 
every time they are outlived which is horribly ineffective for managing 
thousands of objects in realtime.

**Comment by Quintus** [comment]
That should probably be a separate issue.

Vale,
Quintus

**Comment by datahead8888** [comment]
TSC currently uses one texture per rendered object, correct?  This is the impression I got looking at texture id's while debugging the menu icon rotation issue.

When I was in the #opengl room, they told me, "Friends don't let friends use glBegin()" (My friend's code had this).  This will be very good to fix.  They also specifically said higher level API's should be used instead of the old OpenGL when you want to write code faster (which is what we're doing with SFML).

Yes, this should speed up runtime while playing the level and also loading the level (because of the reduced texture calls to the graphics card).

> The drawback of this is that you can’t use scripting to modify entities inside this large entity. Once loaded, it stays the way it is. In other words: If you want to affect a ground object via scripting, you’ll have to specifically mark it in the level editor accordingly. I’m not completely sure how I’d implement this, but there are solutions to this I guess. Movable stuff like enemies or platforms or so are not affected by this drawback and will stay affectable by scripting because they have to be rendered each on their own anyway (because they move all the time).

Could you explain - how does scripting modify the sprites currently?  It is possible to build a new texture at run time and send that to the card.  You can generate a sprite sheet for all the letters of a font, for example.  There would, however be overhead in assembling this and sending it to the card, so an intelligent strategy would still be required.

**Comment by Quintus** [comment]
> Could you explain - how does scripting modify the sprites currently?

Simple. Each sprite is an instance of `cSprite` or a subclass, and has an UID. All sprites are contained in a level’s `cSprite_Manager` instance. You use the UID to wire the sprite out of the sprite manager, and then script it. As each sprite has its own texture, this simply works as expected.

If you look at the [implementation of my `Scenery` class in my SFML example](https://github.com/Quintus/sfml-minitsc/blob/master/src/scenery.cpp), you will notice that this is not as easy anymore. To simplify, each ground object is not a separate object anymore. All ground tiles are dissolved in one large ground sprite. Though with a more complex implementation building on a similar technique as the `m_bounding_boxes` member of the `Scenery` class it might be possible to overcome that restriction. The only hard requirement that remains is that you can’t change the object’s texture to a texture of a different tileset.

>  It is possible to build a new texture at run time and use that on the card.

We are doing that all the time and that’s not what I’m referring to. I would doubt it is possible to construct a texture on compilation time, where you might not even have a graphics card.

Vale,
Quintus

**Comment by Luiji** [comment]
Quick thing: in the past I've experimented with these optimizations a bit and I've found that using vertex arrays massively improves performance, using texture atlases massively improves performance, but once you have one the other isn't as noticeable. So as long as you get one, the other can be deprioritized (but can still be done with no damage).

**Comment by sauer2** [comment]
> Quick thing: in the past I've experimented with these optimizations a 
> bit and I've found that using vertex arrays massively improves 
> performance, using texture atlases massively improves performance, but 
> once you have one the other isn't as noticeable. So as long as you get 
> one, the other can be deprioritized (but can still be done with no 
> damage).
>
>
Maybe you can still texture atlases to improve texture loading 
performance if needed.

**Comment by Quintus** [comment]
The vertex array approach has been taken in the rewrite for TSC3. This ticket can be closed now.
