### ISSUE TITLE
Wiki build instructions not up to date?

### ISSUE THREAD

**Issue by sauer2** [Secretchronicles/TSC#408]
Following the instructions in wiki, I ended up without make files.

Is the wiki entry out of date?

If not, don't hesitate to clear this issue.

**Comment by datahead8888** [comment]
@sauer2 - post your console output so that everyone can see what happened in your build process.

**Comment by sauer2** [comment]
@datahead8888 Just the usual 'No targets specified and no makefile found' error, nothing suspicious.

The devel branch seems to work fine, though.

**Comment by sauer2** [comment]
The devel branch works for me, unlike the release-2.0.0 branch.

FYI: It also builds with ninja, but the install command fails with:

user@user-SVE1513A1ESI ~/T/tsc> ninja install
[1/1] Install the project...
FAILED: cd /home/user/TSC/tsc && /usr/bin/cmake -P cmake_install.cmake
-- Install configuration: ""
CMake Error at cmake_install.cmake:36 (FILE):
  file INSTALL cannot find
  "/home/user/TSC/tsc/CMakeFiles/CMakeRelink.dir/tsc".
ninja: build stopped: subcommand failed.

But that may be due to the version of ninja.

**Comment by Quintus** [comment]
The official build instructions are in the [INSTALL.md](https://github.com/Secretchronicles/TSC/blob/release-2.0.0/INSTALL.md) file in the repository. If building with that instructions doesn’t work, it’s a bug that needs to be fixed.

Vale,
Quintus

**Comment by Quintus** [comment]
No response from OP, closing. Please reopen if this issue is still present in some form.

Vale,
Quintus
