### ISSUE TITLE
Entering tower_1 in world 1 freezes the game...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#410]
It seems we removed tower_1 but failed to account for the fact that it is used in world 1.

Steps to reproduce:
* Start the normal campaign
* Press g+o+d at the same time to enter god mode on the map and walk past all levels
* Walk until you see a level with the title "tower_1"
* Attempt to enter that level.  It freezes the game.

The solution is probably pretty simple - we'd just need to swap it out with another one.

I am marking this with "Blocker" and release-2.0.0, since the game is unplayable with this bug.

On another note: We should change the level loader so that entering a level that does not exist gives some sort of error and does not just freeze the game.  This can be filed in a separate ticket and done in a later release.

**Comment by Quintus** [comment]
`tower_1` has been removed on request of @sauer2. I’ll just set it to some different level.

Vale,
Quintus
