### ISSUE TITLE
Segfault after the first level in world 2 finishes

### ISSUE THREAD

**Issue by kirbyfan64** [Secretchronicles/TSC#415]
I'm on HEAD. When I play level 2 and complete it, I get a segfault. Not sure if in affects anything, but I had *just* grabbed the ice berry (not quite sure what it's called) hidden in the windows at the end of the level.

**Comment by Quintus** [comment]
Hmmm. I’m mainly working on the SFML stuff currently, but this might be something to look into. Can anyone try to reproduce?

Vale,
Quintus

**Comment by sauer2** [comment]
I can't reproduce it.

**Comment by Quintus** [comment]
Between major releases SFML should be stable. Have a look at the
Changelog for version 2.3:

  http://www.sfml-dev.org/changelog.php#sfml-2.3

Version 2.3 brings some new features and a number of bugfixes. SFML also
dropped a dependency (libsndfile), which is always something nice.

Updating thus should be flawless.

Vale,
Quintus

**Comment by datahead8888** [comment]
This was a bug in the devel branch (and not the release-2.0.0 branch), correct?

**Comment by Quintus** [comment]
We don’t know. @kirbyfan64, please add some more info!

Valete,
Quintus

**Comment by kirbyfan64** [comment]
@Quintus Sorry! Haven't been playing games lately. Too busy fixing segfaults in my own programs...

I'm on the `release-2.0.0` branch, but I don't know if I was when this issue came up. I need to try again.

**Comment by datahead8888** [comment]
@kirbyfan64 - okay, let us know.

Also, let us know if you'd like to try a coding task or two some time :)  We're always looking for programmers.

**Comment by Quintus** [comment]
@kirbyfan64 Is this issue still present in RC1?

Vale,
Quintus

**Comment by Quintus** [comment]
No reply from OP, closing.

Vale,
Quintus

**Comment by kirbyfan64** [comment]
Sorry. I don't know what I did, but I can't figure out how to do it again.
