### ISSUE TITLE
Ideas for improvements to image sets.

### ISSUE THREAD

**Issue by brianvanderburg2** [Secretchronicles/TSC#425]
I have also been having some optimizing questions with my image set code.  It stores the sets by name, which means each change has to do string comparisons to look up, which can be costly.  I thought about a change where Add_Image_Set would return an index, and Set_Image_Set would take an index.  It would internally use a std::vector instead of std::map.  In order to preserve compatibility, overloads could be provided that take a name, call the vector version, and store a name to index in a std::map until all instances of the name-based versions are replaced to use the index based versions.

Name based:
- Pro: Easy to use a meaningful name
- Con: Move overhead to look up a std::map
- Con: No compile time error if a name is misspelled (Add_Image_Set("player_walk", ...); Set_Image_Set("playr_walk");)

Index based:
- Pro: Constant time to look up an indexed offset
- Con: Must have variables to keep track of each offset

Another issue is, regardless of name based or index based, that after clearing the image set, there be invalid data, especially if after a clear and reload, certain sets from the last time aren't loaded this time. (Perhaps the last time has a flying image set but this time doesn't).  Using index based, the last time will set the index of m_fly_imgset to maybe 2, but when the image set is cleared, and other sets are added, index 2 may still exist but be a different image set (maybe jump or duck).

One idea, instead of storing the data internally and returning an index, would be to store the data in data structures that are returned, and using a weak reference system to invalidate those data structures when the images are cleared.

``` c++
// info has read-only start, end, valid, and imgset*, friend classed to imgset which can write to valid and imgset*;
// if(info) invokes operator bool() { return valid; }
// if image set is cleared, it invalidates all infos
// if image set is destroyed, it invalidates all infos and sets the imgset* to null
// if info is destroyed, it removes itself from the image set.
// not thread safe, code that uses add_image_set, clear_images
// creates or destroys the info or image set should all be in the same thread

cImage_Set::Info info = Add_Image_Set(stuff); // no need for start and end anymore, it is also stored in the info
// We could also eliminate Set_Image_Set, simply use Set_Animation_Range(info.start, info.end);

Clear_Images(); // This will invalidate all cImage_Set::Info structures

```

The frame information is still stored internally in m_images, such as frame time, branching information, etc.

**Comment by brianvanderburg2** [comment]
An example code may look like this:

```c++

// header file
class MySomething : public cMovingSprite
{
...

// Would use a better name than Info
cImage_Set::Info m_walk[2];
cImage_Set::Info m_fly[2];
...
}

// Source file
MySomething::SetState(int state)
{
  if(m_state == state) return;

  Clear_Images(); // Invalidate all previous image set information
  if(m_state == 1)
  {
      // only have walk information
      // no need to set m_fly_left or m_fly_right, Clear_Images invalidated them.
      m_walk[0] = Add_Image_Set("player/small/walk_left.imgset");
      m_walk[1] = Add_Image_Set("player/small/walk_right.imgset");
  }
 else
  {
      // have walk and fly
      // only have walk information
      m_walk[0] = Add_Image_Set("player/small/walk_left.imgset");
      m_walk[1] = Add_Image_Set("player/small/walk_right.imgset");
      m_fly[0] = Add_Image_Set("player/small/fly_left.imgset");
      m_fly[1] = Add_Image_Set("player/small/fly_right.imgset");
  }

  if(m_walk[m_direction].valid)
  {
    Set_Animation_Range(m_walk[m_direction].start, m_walk[m_direction].end);
    // Proably should keep Set_Image_Set for simplicity
    // Set_Image_Set(m_walk[m_direction]);
  }
}

**Comment by Quintus** [comment]
It is unlikely anybody ever undertakes implementing this. Closing.
