### ISSUE TITLE
Port Music system to SFML

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#435]
The music system needs to be ported from SDL_music to SFML’s Audio module.

Cf. http://www.sfml-dev.org/tutorials/2.3/audio-sounds.php

Valete,
Quintus

**Comment by datahead8888** [comment]
Can this task be closed, or does it need to be in devel first?

**Comment by Quintus** [comment]
datahead8888 <notifications@github.com> writes:

> Can this task be closed, or does it need to be in devel first?

The ticket is on autoclose if you look closely :-). As soon as the SFML
port branch gets merged into devel, this issue (and a number of other
issues) will automatically close.

Vale,
Quintus

-- 
#!/sbin/quintus
Blog: http://www.guelkerdev.de

GnuPG key: F1D8799FBCC8BC4F
