### ISSUE TITLE
Make Crates be Destroyed by Exploding Larries...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#443]
I discussed this with Quintus in IRC.  The idea is to allow crates to be destroyed when Larries explode.  This could also make chain reactions more interesting.  Quintus suggested using a wood particle effect when a crate is destroyed.

I may or may not get this done with my Doom Larry changes, so I am creating a task.

**Comment by Quintus** [comment]
Related note: Larry's explosion already makes spinboxes start spinning. I've used this in one level for a secret area: I placed spinboxes at the bottom so there's no way to jump against them. If Larry explodes nearby however, they start spinning and Alex can pass the spinboxes downwards.
