### ISSUE TITLE
conflict with system installed ogre

### ISSUE THREAD

**Issue by sss123next** [Secretchronicles/TSC#451]
cmake --no-warn-unused-cli -C /var/tmp/paludis/games-arcade-tsc-scm/work/tsc-scm_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_INSTALL_DO_STRIP=OFF -DCMAKE_USER_MAKE_RULES_OVERRIDE=/var/tmp/paludis/games-arcade-tsc-scm/work/tsc-scm_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/var/tmp/paludis/games-arcade-tsc-scm/work/tsc-scm_build/gentoo_toolchain.cmake  /var/tmp/paludis/games-arcade-tsc-scm/work/tsc-scm/tsc
Not searching for unused variables given on the command line.
loading initial cache file /var/tmp/paludis/games-arcade-tsc-scm/work/tsc-scm_build/gentoo_common_config.cmake
-- The CXX compiler identification is GNU 4.9.3
-- Check for working CXX compiler: /usr/lib/ccache/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/lib/ccache/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- The C compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/lib/ccache/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/lib/ccache/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found PkgConfig: /usr/bin/x86_64-pc-linux-gnu-pkg-config (found version "0.28") 
-- Could NOT find CEGUI (missing:  CEGUI_LIBRARY) 
Could not located CEGUI.h
Could not located CEGUIOpenGLRenderer.h
Looking for lib: CEGUIOpenGLRenderer
Could not located CEGUIOpenGLRenderer
Could not located CEGUIBase
Could not located CEGUIFalagardWRBase
Could not located CEGUITinyXMLParser
Could not located CEGUIDevILImageCodec
CEGUI 0.7.x was not found. It will be downloaded and compiled during the build process.
-- Found rake: /usr/bin/rake
-- Found gperf: /usr/bin/gperf
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found OpenGL: /usr/lib64/libGL.so  
-- Found GLEW: /usr/include  
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.5.1") 
-- Found BISON: /usr/bin/bison (found version "3.0.4") 
-- Found Freetype: /usr/lib64/libfreetype.so (found version "2.6.0") 
-- Found IL: /usr/lib64/libIL.so  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   chrono
--   thread
--   system
-- checking for module 'libpng'
--   found libpng, version 1.6.18
-- checking for module 'sdl'
--   found sdl, version 1.2.15
-- checking for module 'SDL_image'
--   found SDL_image, version 1.2.12
-- checking for module 'SDL_mixer'
--   found SDL_mixer, version 1.2.12
-- checking for module 'SDL_ttf'
--   found SDL_ttf, version 2.0.11
-- checking for module 'libpcre'
--   found libpcre, version 8.37
-- checking for module 'libxml++-2.6'
--   found libxml++-2.6, version 2.38.1
-- ----- Path configuration -----
-- Install prefix:   /usr
-- Data directory:   share/tsc
-- Binary directory: bin
-- (relative pathes are relative to the install prefix)
-- ------------------------------
-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C               -march=bdver2 -maes -mpclmul -mpopcnt -mabm -mlwp -mfma -mfma4 -mxop -mbmi -mcx16 -msahf -mtbm -mavx -msse4a -msse4.1 -msse4.2 -mlzcnt -mfxsr -mf16c -mprfchw  -mxsave -mtune=bdver2 -O2 -mprefer-avx128 -mvzeroupper -pipe -Wno-error 
C++             -march=bdver2 -maes -mpclmul -mpopcnt -mabm -mlwp -mfma -mfma4 -mxop -mbmi -mcx16 -msahf -mtbm -mavx -msse4a -msse4.1 -msse4.2 -mlzcnt -mfxsr -mf16c -mprfchw  -mxsave -mtune=bdver2 -O2 -mprefer-avx128 -mvzeroupper -pipe -Wno-error -fpermissive 
Linker flags:
Executable       -Wl,-O1 -Wl,--as-needed
Module           -Wl,-O1 -Wl,--as-needed
Shared           -Wl,-O1 -Wl,--as-needed

-- Configuring done
-- Generating done
-- Build files have been written to: /var/tmp/paludis/games-arcade-tsc-scm/work/tsc-scm_build

--------

28 -mvzeroupper -pipe -Wno-error -fpermissive -MT libCEGUIOgreRenderer_la-CEGUIOgreTexture.lo -MD -MP -MF .deps/libCEGUIOgreRenderer_la-CEGUIOgreTexture.Tpo -c CEGUIOgreTexture.cpp -o libCEGUIOgreRenderer_la-CEGUIOgreTexture.o
Makefile:450: recipe for target 'libCEGUIOgreRenderer_la-CEGUIOgreGeometryBuffer.lo' failed
In file included from /usr/include/OGRE/OgreMatrix4.h:32:0,
                 from ../../../../cegui/include/RendererModules/Ogre/CEGUIOgreGeometryBuffer.h:35,
                 from CEGUIOgreGeometryBuffer.cpp:28:
/usr/include/OGRE/OgrePrerequisites.h:319:32: error: conflicting declaration 'typedef class Ogre::SharedPtr<Ogre::Texture> Ogre::TexturePtr'
     typedef SharedPtr<Texture> TexturePtr;
                                ^
In file included from ../../../../cegui/include/RendererModules/Ogre/CEGUIOgreGeometryBuffer.h:32:0,
                 from CEGUIOgreGeometryBuffer.cpp:28:
../../../../cegui/include/RendererModules/Ogre/CEGUIOgreRenderer.h:57:7: note: previous declaration as 'class Ogre::TexturePtr'
 class TexturePtr;
       ^
In file included from CEGUIOgreGeometryBuffer.cpp:29:0:
../../../../cegui/include/RendererModules/Ogre/CEGUIOgreTexture.h:86:22: error: field 'd_texture' has incomplete type 'Ogre::TexturePtr'
     Ogre::TexturePtr d_texture;
                      ^
In file included from /usr/include/OGRE/OgreRenderTarget.h:34:0,
                 from /usr/include/OGRE/OgreRenderSystem.h:42,
                 from CEGUIOgreGeometryBuffer.cpp:33:
/usr/include/OGRE/OgreTextureManager.h: In member function 'Ogre::TexturePtr Ogre::TextureManager::createManual(const String&, const String&, Ogre::TextureType, Ogre::uint, Ogre::uint, int, Ogre::PixelFormat, int, Ogre::ManualResourceLoader*, bool, Ogre::uint, const String&)':
/usr/include/OGRE/OgreTextureManager.h:352:3: error: return type 'class Ogre::TexturePtr' is incomplete
   {
   ^
/usr/include/OGRE/OgreTextureManager.h:354:73: error: invalid use of incomplete type 'class Ogre::TexturePtr'
     numMipmaps, format, usage, loader, hwGammaCorrection, fsaa, fsaaHint);
                                                                         ^
In file included from ../../../../cegui/include/RendererModules/Ogre/CEGUIOgreGeometryBuffer.h:32:0,
                 from CEGUIOgreGeometryBuffer.cpp:28:
../../../../cegui/include/RendererModules/Ogre/CEGUIOgreRenderer.h:57:7: error: forward declaration of 'class Ogre::TexturePtr'
 class TexturePtr;
       ^
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_algobase.h:64:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/char_traits.h:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/string:40,
                 from ../../../../cegui/include/RendererModules/Ogre/../../CEGUIBase.h:87,
                 from ../../../../cegui/include/RendererModules/Ogre/../../CEGUIGeometryBuffer.h:31,
                 from ../../../../cegui/include/RendererModules/Ogre/CEGUIOgreGeometryBuffer.h:31,
                 from CEGUIOgreGeometryBuffer.cpp:28:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_pair.h: In instantiation of 'struct std::pair<Ogre::TexturePtr, unsigned int>':
CEGUIOgreGeometryBuffer.cpp:156:36:   required from here
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_pair.h:101:11: error: 'std::pair<_T1, _T2>::first' has incomplete type
       _T1 first;                 /// @c first is a copy of the first object
           ^
In file included from ../../../../cegui/include/RendererModules/Ogre/CEGUIOgreGeometryBuffer.h:32:0,
                 from CEGUIOgreGeometryBuffer.cpp:28:
../../../../cegui/include/RendererModules/Ogre/CEGUIOgreRenderer.h:57:7: error: forward declaration of 'class Ogre::TexturePtr'
 class TexturePtr;
       ^
CEGUIOgreGeometryBuffer.cpp: In member function 'virtual void CEGUI::OgreGeometryBuffer::appendGeometry(const CEGUI::Vertex*, CEGUI::uint)':
CEGUIOgreGeometryBuffer.cpp:213:22: error: aggregate 'Ogre::TexturePtr t' has incomplete type and cannot be defined
     Ogre::TexturePtr t;
                      ^
CEGUIOgreGeometryBuffer.cpp:215:45: error: invalid use of incomplete type 'class Ogre::TexturePtr'
         t = d_activeTexture->getOgreTexture();
                                             ^
In file included from ../../../../cegui/include/RendererModules/Ogre/CEGUIOgreGeometryBuffer.h:32:0,
                 from CEGUIOgreGeometryBuffer.cpp:28:
../../../../cegui/include/RendererModules/Ogre/CEGUIOgreRenderer.h:57:7: error: forward declaration of 'class Ogre::TexturePtr'
 class TexturePtr;
       ^
make[7]: *** [libCEGUIOgreRenderer_la-CEGUIOgreGeometryBuffer.lo] Error 1
make[7]: *** Waiting for unfinished jobs....
In file included from /usr/include/OGRE/OgreArchiveManager.h:31:0,
                 from CEGUIOgreResourceProvider.cpp:33:
/usr/include/OGRE/OgrePrerequisites.h:319:32: error: conflicting declaration 'typedef class Ogre::SharedPtr<Ogre::Texture

**Comment by Quintus** [comment]
This is an issue with the CEGUI subcompilation task; the error is not thrown by our compilation process, but by CEGUI’s. There are two possibilities for you:

1. Complain to the CEGUI devs at https://bitbucket.org/cegui/cegui/; but note that this may have been fixed in newer versions of CEGUI, which we can’t use yet (but plan to in the future).
2. Compile CEGUI 0.7.9 by hand prior to installing TSC and ensure it can be detected by CMake. When the build system detects it, there will be no attempt made to compile it from source, but the existing library is used.

Also, please use code tags for your output.

Vale,
Quintus
