### ISSUE TITLE
Force UTF-8 encoding in gem files

### ISSUE THREAD

**Issue by akien-mga** [Secretchronicles/TSC#457]
When trying to build 2.0.0 on Mageia's buildsystem, I ran into this issue:
```
[ 12%] Generating credits.cpp
rake aborted!
ArgumentError: invalid byte sequence in US-ASCII
/home/iurt/rpmbuild/BUILD/TSC-2.0.0/tsc/Rakefile:23:in `match'
/home/iurt/rpmbuild/BUILD/TSC-2.0.0/tsc/Rakefile:23:in `match'
/home/iurt/rpmbuild/BUILD/TSC-2.0.0/tsc/Rakefile:23:in `<top (required)>'
(See full trace by running task with --trace)
CMakeFiles/tsc.dir/build.make:61: recipe for target 'credits.cpp' failed
```

Full build log: http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20150927093845.akien.valstar.31482/log/tsc-2.0.0-1.mga6/build.0.20150927093906.log

According to this stackoverflow topic [1], it could be fixed either on my side by forcing en_US.UTF-8 on Mageia's buildsystem (I guess right now it might be simply "C"), or on your side by forcing UTF-8 encoding in the gem files. I guess the second solution is probably cleaner since you do want to enforce UTF-8 anyway.

[1] http://stackoverflow.com/questions/17031651/invalid-byte-sequence-in-us-ascii-argument-error-when-i-run-rake-dbseed-in-ra

**Comment by akien-mga** [comment]
Actually my title might be wrong as I don't see any "gem" file in the source; I'm not familiar with ruby at all so :p

For the reference, the error was with:
ruby-2.0.0.p645
ruby-rake-10.3.1

**Comment by Quintus** [comment]
This looks weird. The rakefile is explicitely set up to use UTF-8, and should do that independently from your environment. @akien-mga, could you please apply this patch to the Rakefile and then try again?

~~~~~~~~~~~~ diff
diff --git a/tsc/Rakefile b/tsc/Rakefile
index 248de16..9b6ff75 100644
--- a/tsc/Rakefile
+++ b/tsc/Rakefile
@@ -19,7 +19,7 @@ require "pathname"
 
 CLOBBER.include("build", "crossbuild", "docs/scripting/html", "docs/scripting/rdoc", "docs/api")
 
-str = File.read("CMakeLists.txt", :encoding => "utf-8")
+str = File.open("CMakeLists.txt", "r:UTF-8"){|f| f.read}
 TSC_VERSION_MAJOR = str.match(/^set\(TSC_VERSION_MAJOR (\d+)\)/)[1]
 TSC_VERSION_MINOR = str.match(/^set\(TSC_VERSION_MINOR (\d+)\)/)[1]
 TSC_VERSION_PATCH = str.match(/^set\(TSC_VERSION_PATCH (\d+)\)/)[1]
~~~~~~~~~~~~ 

There shouldn’t be any difference, but I want to be sure.

Vale,
Quintus

**Comment by akien-mga** [comment]
The patch does not apply, and I guess that gives us the culprit: tsc/Rakefile in 2.0.0 does not specify the encoding.
https://github.com/Secretchronicles/TSC/blob/c3106816c6d07e70bd3689acb69d40a75e0f7f55/tsc/Rakefile#L22

**Comment by akien-mga** [comment]
Actually even after patching tsc/Rakefile to force the encoding as in the devel branch, I still get an error at the same place (the actually error being slightly different, but I don't know if it's due to the patch or just that the build job was run on a node with a different number of CPUs): http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20151006180613.akien.valstar.24994/log/tsc-2.0.0-1.mga6/build.0.20151006180710.log

**Comment by Quintus** [comment]
Ah yes. The patch was against `devel`, apologies.

For the second issue, it is very similar. Try this patch additionally:

~~~~~ diff
--- a/tsc/Rakefile
+++ b/tsc/Rakefile
@@ -39,7 +39,7 @@ namespace TSC {
 
 	const std::string g_credits = "\\\n!)
 
-    File.open("docs/authors.txt") do |f2|
+    File.open("docs/authors.txt", "r:UTF-8") do |f2|
       # Skip to real content
       loop do
         line = f2.gets
~~~~~

Vale,
Quintus

**Comment by akien-mga** [comment]
Thanks, to be on the safe side I patched all File.open(), and it works: http://svnweb.mageia.org/packages/cauldron/tsc/current/SOURCES/tsc-2.0.0-issue457-utf8-rakefile.patch?revision=886619&view=markup

**Comment by akien-mga** [comment]
Now it seems to be failing because somehow -std=c++11 is not specified, but that's a separate issue :)

**Comment by Quintus** [comment]
Okay thanks, I will apply your patch to `devel` then.

Vale,
Quintus

**Comment by Quintus** [comment]
Actually it appears `devel` has this completely resolved already by commit 405f866991409eddda1d90a092957b34e7b19b8d. So there is no need to apply your patch. Thank you anyway :-)

Vale,
Quintus

**Comment by Quintus** [comment]
@akien-mga For completeness: #417 is very closely related.

Vale,
Quintus

**Comment by akien-mga** [comment]
Indeed, thanks. Hijacking this issue for a small unrelated question (I don't feel it's worth opening a new ticket): TSC did not build for me against gcc 5.2.1 and threw tons of errors about the need to specify -std=c++11. Is this something that would be relevant to do directly in your CMakeLists.txt?

**Comment by Quintus** [comment]
> Is this something that would be relevant to do directly in your CMakeLists.txt?

2.0.0 should not require C++11. Other than that, this would be done in the CMakeLists.txt by setting

~~~~
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
~~~~

, yes.

Vale,
Quintus

**Comment by akien-mga** [comment]
> 2.0.0 should not require C++11

Ok, then it's a problem specific to the buildsystem I'm using where all libs have been updated to the new gcc 5 ABI and built with C++11, so some low-level dependencies of TSC seem to complain (note: heavy!): http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20151006182145.akien.valstar.27056/log/tsc-2.0.0-1.mga6/build.0.20151006182207.log

**Comment by akien-mga** [comment]
Nothing to change on your side though, as you said. I just fixed it for me by passing -DCMAKE_CXX_FLAGS="-std=c++11" to the cmake call.
