### ISSUE TITLE
Virtual File System

### ISSUE THREAD

**Issue by Luiji** [Secretchronicles/TSC#47]
When I get time and we've dealt with our other problems, I would like to write a small C++ library similar to PhysicsFS [1] that would provide a simple virtual file system. The advantage of this would be the ability to prevent file name collision. For instance, Package A might add an image called `cherry.png`, and Package B might provide the same image. The virtual file system only mounts relevant data to a given level, so a level in Package A would just mount Package A and the core file set.

Additionally, if we ever add new images to the core file set, we don't have to worry about the packages overwriting them, since they just override them in the virtual file system. If the maintainer of one of the packages wants access to that, than they can voluntarily, and without much trouble, edit their own file name so they can see the file they override. If they have no want to access that overridden image, they have no need to update the package.

This would function just well with resource packs. I like the idea that people can create resource packages that level editors can add without the mainline having to add them manually. With this mechanism, resource pack collisions wouldn't be nearly as much of an issue, and different level packs could use different versions of the same resource pack without any collision problems.

One of the features I want to add to the C++ library is the ability to support transparent reads from archives (the same as C++), so that we can change the package format we designed with SMC-GET to simple ZIP files (required instead of tarballs for better random access) or 7Z files that people can easily create and just drop into SMC without having to extract anything. It would also help save disk space by compressing the level and script files.

The reason I would like to write a custom C++ library instead of using PhysicsFS is for ease of integration into SMC. I'd write it as an external system that we could include similarly to mruby so it wouldn't much count as an external library. Plus, I've been interested in writing my own virtual file system library for awhile. ;)

[1] http://icculus.org/physfs/

**Comment by Quintus** [comment]
Unassigning, Luiji doesn’t have time to work on this.

**Comment by Quintus** [comment]
With the consensus currently being that the package feature will not further be developed, I think this should be closed.

**Comment by datahead8888** [comment]
If this feature is only for the packages that Brian Vanderburg introduced, I agree with Quintus.

However, I'd like to hear @Luiji  's thoughts on this before we close the ticket, in case we misunderstood him or in case he has any thoughts about dropping package support.

**Comment by datahead8888** [comment]
No feedback - closing.
