### ISSUE TITLE
Remove cVideo::Downscale_Image() in its current form

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#489]
TSC is not an image processing library. [This function](https://github.com/Secretchronicles/TSC/blob/6a476461703c62d684a0e097a8e915f21af7d627/tsc/src/video/video.cpp#L1580-L1643) thus should be removed and replaced by a call to libPNG or a similar library. Implementing image pixel processing ourselves is definitely out of scope for TSC.

Valete,
Quintus

**Comment by datahead8888** [comment]
Would this increase our dependency count?  A lot of people have complained already about how tough it is to build TSC.  The code is borrowed from Jonathan Dummer anyways, so it's not like anyone wrote this from scratch in the first place.

**Comment by Quintus** [comment]
datahead8888 <notifications@github.com> writes:

> Would this increase our dependency count?

No. We already depend on libPNG.

Vale,
Quintus

-- 
#!/sbin/quintus
Blog: http://www.guelkerdev.de

GnuPG key: F1D8799FBCC8BC4F

**Comment by datahead8888** [comment]
> No. We already depend on libPNG.

Then I would agree here.

> Implementing image pixel processing ourselves is definitely out of scope for TSC.

I don't think we should make a blanket policy.  For things commonly dealt with by libPNG, yes, but it is possible someone may come along eventually and want to do something cutting edge.  It should be evaluated on a case by case basis.  This applies to a lot of algorithms beyond image processing.

**Comment by Quintus** [comment]
I took a look on possible alternatives. libPNG does not support image
manipulation, but DevIL does (iluScale() function). We use DevIL
currently only as a dependency of CEGUI. If our goal is to remove CEGUI
eventually, we'd then keep DevIL around just for the scaling
functionality...

It's possible to do the scaling with SFML itself. That's a little
complicated, but it works as follows: load the image file as an
sf::Image, upload into a sf::Texture, construct an sf::Sprite with it,
transform the sprite with sf::setScale() to the desired size, draw the
sprite onto a temporary sf::RenderTexture, retrieve the transformed
texture with sf::RenderTexture::getTexture(), download that into an
sf::Image and finally save that into a file.

-- 
Blog: https://mg.guelker.eu

**Comment by refi64** [comment]
I mean if CEGUI is sticking around in the near-ish future using DevIL could be plausible, but the sfml version doesn't sound that bad tbh.

**Comment by Quintus** [comment]
Because you assigned the ticket to yourself: please note that the
Downscale_Image() function is only used during cache generation. If the
cache is removed, this ticket becomes obsolete. For the cache removal,
I'd suggest we wait for further opinions on the mailing list first.

-- 
Blog: https://mg.guelker.eu

**Comment by Quintus** [comment]
The image cache is going to be [removed](https://lists.secretchronicles.org/hyperkitty/list/tsc-devel@lists.secretchronicles.org/thread/3NNZM5DPLCBOOLUGW5R5FBWUVOT4TKJI/) after 2.1.0, so this ticket is obsolete now.
