### ISSUE TITLE
Port preferences to SFML

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#492]
SFML uses different keyboard and joystick settings, so a slight adaption of TSC’s preferences handling in `preferences.cpp` is required. Some work has already been done on this.

**Comment by lambda-11235** [comment]
The print screen key is currently unsupported in SFML. A different key may need to be used for printing. F12 is a commonly used alternative.

**Comment by Quintus** [comment]
For reference, the SFML team appearently knows about the problem: https://github.com/SFML/SFML/issues/7

Vale,
Quintus

**Comment by Quintus** [comment]
Preferences are ported over now with commit f1a7838e6265ac2fb154ec24cfeaf778dd39c561.
