### ISSUE TITLE
README links to coding conventions and style guide are broken

### ISSUE THREAD

**Issue by lambda-11235** [Secretchronicles/TSC#496]
The style guide link needs a .html appended to the address. The coding conventions link refers to a non-existent page.

**Comment by xet7** [comment]
https://github.com/Secretchronicles/main-website/commit/c02c7a3c0dd7a8194ac0e3a7ad8b251669fd4d5e

**Comment by xet7** [comment]
@Quintus I have translated documentation page, and fixed StyleGuide link in README.md. You can now fix coding conventions etc docs links.
