### ISSUE TITLE
Mouse cursor is set off in SFML port

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#505]
At certain places, the mouse cursor is set off in the SFML port. In ticket #502 there are some screenshots and investigations, namely finding that the offset does not apply to CEGUI GUI elements, but only where TSC handles mouse cursor input itself.

/cc @lambda-11235

Valete,
Quintus

**Comment by lambda-11235** [comment]
I noticed a problem that I think is related to this in mover mode. If sf::Mouse::getPosition is used, then the  position is relative to the desktop screen.  This is what cMouseCursor uses for m_x and m_y. sf::Event::MouseMoveEvent gives coordinates relative to the game window.

Initial tests indicate that this, or something similar, might be the case. My evidence is that the mouse input and icon offset is relative to the position of the window. Putting the window so its corner touches the upper left part of the screen causes the input and icon to overlap. In any case beware using MouseMoveEvent.

**Comment by lambda-11235** [comment]
Actually, it might be best to store all mouse positions relative to the TSC window. This would mean giving getPosition a sf::Window argument. The problem is getting the window argument in cMouseCursor. For reference the problem appears to be on line 205 of menu.cpp. I think m_col_rect is measured relative to the window, while pMouseCursor is relative to the desktop.

I think a good course of action might be to change cMouseCursor to have coordinates relative to the window. However, I don't know how to get these positions without passing the SFML window down from main, any suggestions?

A fix to getPosition will also mean changing PR #504.

**Comment by Quintus** [comment]
Taran Lynn <notifications@github.com> writes:

> The problem is getting the window argument in cMouseCursor.

TSC maintains pVideo as a global pointer for exactly this purpose. You
can retrieve the sf::Window instance of the main window at any time
everywhere in the code with

  pVideo->mp_window

.

> For reference the problem appears to be on line 205 of
> menu.cpp. I think m_col_rect is measured relative to the window, while
> pMouseCursor is relative to the desktop.

I agree with your finding. The coordinates are retrieved and set in
cMouseCursor::Update_Position() which needs to be modified then.

> I don't know how to get these positions without passing the SFML
> window down from main, any suggestions?

Use the pVideo global variable as outlined above.

> In any case beware using MouseMoveEvent.

With this I don’t agree. MouseMoved event always contains relative
coordinates according to the documentation, which means they are exactly
the way we want them. From this it is explainable why the CEGUI elements
work correctly: Their receive their mouse cursor position information in
reaction to the MouseMoved event.

Maybe it would be even more useful if the menu code did not query global
state from SFML, but instead react to the mouse move event? I know TSC
currently queries global state at a lot of places, but this doesn’t mean
this has to stay like that. In my opinion, reacting to events is much
more elegant (and performant, since it doesn’t need to be done in every
frame). This however should probably be resolved separately from this
issue as it is an architectural change as opposed to a simple bugfix. We
should however keep this in mind.

Vale,
Quintus

-- 
#!/sbin/quintus
Blog: http://www.guelkerdev.de

GnuPG key: F1D8799FBCC8BC4F

**Comment by Quintus** [comment]
Fixed with merge of #509. Closing.
