### ISSUE TITLE
Change key combination for Omega mode

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#511]
As a followup to #481, we should probably change the key combination for activating Omega mode. The old G-O-D doesn’t fit the name anymore now.

Suggestions?

Valete,
Quintus

**Comment by lambda-11235** [comment]
OMeGa
O M G
Easy to remember. :smiley:

**Comment by Quintus** [comment]
+1 for OMG :-P

**Comment by Bugsbane** [comment]
"OMG" Love it!

**Comment by datahead8888** [comment]
Not that I want to start another controversy about what is and isn't offensive, but "OMG" actually is an abbreviation that can offend some people.  We should at least discuss this a little before making a decision.  Granted, our new context is different, but the old name was god mode.

**Comment by Bugsbane** [comment]
Actually, yeah... @datahead8888 has a point.

**Comment by lambda-11235** [comment]
@datahead8888 good point. The binding doesn't need to be three letters either. "OM" for "Omega Mode" might be a less controversial abbreviation.

**Comment by Quintus** [comment]
Okay. “OM” is also fine for me.

/cc @Luiji 

Valete,
Quintus

**Comment by datahead8888** [comment]
"OM" kind of sounds like Omega Mode, so I think it could work.

**Comment by Bugsbane** [comment]
Agreed

**Comment by lambda-11235** [comment]
Actually, I just realized that "O M E G A" could be a possibility. However, it is a lot of buttons to press, but is still fairly comfortable to press. I end up using my left hand on "A E G" and my right on "M O".

**Comment by datahead8888** [comment]
I think pressing five keys at once is a little too complicated for a cheat code.  I realize some old games had complex key combinations for cheats, but it really was a royal pain with some of those games.

I think it's unlikely most players will stumble on O + M accidentally, but we could require it to be held down for a number of seconds if we want to play it safe.

**Comment by Bugsbane** [comment]
Here's the thing, even if they *do* stumble across it accidentally, is that really a problem? If I was a user who accidentally stumbled across this while keyboard mashing or something, I'd just think it was really cool. Seems like a good thing, to me.

**Comment by datahead8888** [comment]
I think there is also a "Kid" mode that can be accessed with K + I + D if I remember correctly.  Should we leave that one as is or consider changing it to K + M?

**Comment by Bugsbane** [comment]
I'd leave it. I don't see any overriding need to modify anything.

**Comment by Quintus** [comment]
Bugsbane <notifications@github.com> writes:

> I'd leave it. I don't see any overriding need to modify anything.

Kid “mode” really just downgrades you to small Alex immediately. I think
it can stay as it is.

OMEGA is a little hard to press. Currently, it is possible to play TSC
with a single hand if you choose your action keys carefully, and such a
long combination would break this (just try to do that combination with
one hand, it won’t work out). OM doesn’t look like something one comes
over accidentally, but one never knows all the keyboard layouts
everywhere on this world. I think this risk is acceptable, and OM is
still fine to me. I sympathesize with datahead’s suggestion of having to
press those keys for, say, two seconds, before Omega mode gets
activated. It is a cheat after all, mostly intended for easing level
design (testing).

Valete,
Quintus

-- 
#!/sbin/quintus
Blog: http://www.guelkerdev.de

GnuPG key: F1D8799FBCC8BC4F

**Comment by sydneyjd** [comment]
How about "OME"? For the first 3 letters of OMEGA. But thats just it. Im fine with OM though. The idea of having to hold the keys for a couple seconds is a good idea IMHO.

**Comment by datahead8888** [comment]
> How about "OME"?

On QWERTY keyboards, this will require two hands, though I like that you are maintaining three letters.  "KID" cannot be done with one hand, though it is not used very often.

**Comment by Quintus** [comment]
So everybody is fine with "OM" and a delay of 1-2 seconds?

Valete,
Quintus

**Comment by datahead8888** [comment]
If we use a delay of 1-2 seconds for "OM", shouldn't we maybe do this for "KID" as well?

**Comment by Quintus** [comment]
> If we use a delay of 1-2 seconds for "OM", shouldn't we maybe do this for "KID" as well?

Agreed. Or remove the KID cheat altogether. I’ve never found myself in need of it.

Vale,
Quintus

**Comment by Bugsbane** [comment]
> So everybody is fine with "OM" and a delay of 1-2 seconds?

Yup. Or at least I am.

**Comment by datahead8888** [comment]
Technical Note: this must be changed both in level.cpp and overworld.cpp, since God mode can be used both within levels and the overworld.
