### ISSUE TITLE
Implement the debug window as a real GUI window

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#514]
In old OpenGL/SDL TSC, the debug window was rendered completely manually by our own code. Rendering an entire Window is what we have a GUI library for (CEGUI currently), so the debug window should be implemented on top of that GUI library instead.

In the SFML port the debug window has been temporayly removed to faciliate work, because porting it to SFML would mean to rewrite it, and rewriting would also be required when porting it to the GUI system. Rewriting twice is not what we want, so it was disabled. The old code can be recovered from Git, e.g. from [here](https://github.com/Secretchronicles/TSC/blob/9faa744e671d37ed5eca7c81331fd1369dc18914/tsc/src/gui/hud.hpp#L245-L281) and [here](https://github.com/Secretchronicles/TSC/blob/9faa744e671d37ed5eca7c81331fd1369dc18914/tsc/src/gui/hud.cpp#L881).

Valete,
Quintus

**Comment by datahead8888** [comment]
Quintus, might this be good to combine with your text offset fix work, since you are rewriting a lot of other pieces in Cegui?  If people find the debug window useful, it's good to get it back when we have a chance.

**Comment by Quintus** [comment]
> Quintus, might this be good to combine with your text offset fix work,

Probably. I'll mark it for 2.1.0 and assign myself.

Vale,
quintus
