### ISSUE TITLE
ALT+F4 doesn’t work in SFML port

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#517]
I just found that pressing the ALT+F4 key combination does not quit the game as it does in the SDL version of TSC. That should be fixed.

/cc @lambda-11235

Valete,
Quintus

**Comment by lambda-11235** [comment]
ALT+F4 quits the game as expected on my computer.

**Comment by Quintus** [comment]
For me it doesn’t. It freezes for a short moment, then gameplay continues. This happens both on the title screen and in levels. Hm.

Vale,
Quintus

**Comment by lambda-11235** [comment]
@Quintus Does the fullscreen key combo (Alt+Enter) work? What about other function keys, F6 for example?

**Comment by Quintus** [comment]
Alt+Enter works, and F6 also works.

**Comment by Quintus** [comment]
@lambda-11235 I just noticed I also can’t input anything into the "new level" box that appears when clicking the "New" button on the level tab (the box for the new level’s name). Does that work for you?

Vale,
Quintus

**Comment by Quintus** [comment]
Actually I can’t input any text into any CEGUI text box... O_o

**Comment by lambda-11235** [comment]
I can't get any CEGUI input to work either.

**Comment by Quintus** [comment]
CEGUI stuff has been fixed with commit cb4cdc0606f6b83b2335e0702e37acd5e75a7eb5. The ALT-F4 question remains. I think I’m going to debug this myself as I seem to be the only one affected O_o

Vale,
Quintus
