### ISSUE TITLE
TSC Game Console...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#518]
This is a task to create an in-game console (probably created with SFML and/or CEGUI).  It would offer a number of commands for both scripting debugging and activating cheat or debug modes.  We might try to think of additional use cases for this feature.

**Comment by DarkAceZ** [comment]
Like Valve's Source Engines? I like it.

**Comment by datahead8888** [comment]
Have you implemented a command history such that you can hit up / down to shuffle through prior commands?  I was just thinking that would be fun to add to your branch if I get time and if it is not done yet.

We could even add game controller support for command shuffling :P

**Comment by Quintus** [comment]
On Wed, Dec 07, 2016 at 05:40:29PM -0800, Chris Jacobsen wrote:
> Have you implemented a command history such that you can hit up / down
> to shuffle through prior commands?  I was just thinking that would be
> fun to add to your branch if I get time and if it is not done yet.

This is one of the next things I was wanting to target, i.e. that
functionality is not there yet. If you want to test the current state,
you can activate the console with [F7] while you're in a level (close it
again with [F7]).

Also, I want to redirect the output of "puts" and similar commands in
scripts to the game console rather than the program's stdout. Likewise,
exception messages and backtraces should show there. mruby allows to
exchange the I/O at the lowlevel, so this might be easily possible; I
have to take a closer look on the topic.

> We could even add game controller support for command shuffling :P

While possible, this doesn't resolve the problem of how you would want
to enter text commands not in the history into the console.

Vale,
Quintus

-- 
Blog: http://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by datahead8888** [comment]
> If you want to test the current state, you can activate the console with [F7] while you're in a level (close it again with [F7]).

Okay.  It would probably make sense to add a Cegui menu option to open the console, too.

> Also, I want to redirect the output of "puts" and similar commands in scripts to the game console rather than the program's stdout.

We could have them go to both stdout and the console or make it configurable.

> While possible, this doesn't resolve the problem of how you would want to enter text commands not in the history into the console.

I was mostly joking.  I don't see any harm in making this accessible, though you are correct people need a keyboard to use the console properly.  It does not seem worthwhile right now to create a virtual keyboard and mouse-like interface for analog joysticks or directional pads.

**Comment by datahead8888** [comment]
As noted above it also might be useful to have a family of "cheat" commands, sort of like:
* Inv on/off
* Restart level
* Skip/Exit level
* Restart world
* Upgrade fire
* Upgrade ice
* Upgrade size
* Increase lives {n}
* Increase score {n}

If the commands are too powerful, we could require entering omega mode to enable them.  Such commands could be invaluable while troubleshooting and will make us seem like a true game console :)

We'd have to spend more time debating the syntax for these commands as well as building a fuller list.

**Comment by Quintus** [comment]
On Thu, Dec 08, 2016 at 06:07:23PM -0800, Chris Jacobsen wrote:
> It would probably make sense to add a Cegui menu option to open the
> console, too.

The console is tied to the mruby instance, which in turn is tied to a
level. It is thus not possible to have a game console outside a level;
therefore, an option in the main menu does not work. One could probably
add one into the level editor's panel, though as of now the game console
and editor are exclusive, i.e. you cannot have both the editor and the
game console open at once. This can be changed, but I am not entirely
sure whether this does or does not cause conflicts especially when
saving a level. It might lead to unexpected results. On the other hand,
allowing console in the editor would open possibilities for
editor-specific commands.

>> Also, I want to redirect the output of "puts" and similar commands in
>> scripts to the game console rather than the program's stdout.
> We could have them go to both stdout and the console or make it
> configurable.

I don't think these belong to stdout. That's not where it is
expected. My most recent commits thus map it exclusively to the console;
you however do have a point in that one could log the console output to
a logfile in ~/.cache/tsc. This would simplify it to copy the console
output for users when they file bug reports.

> I was mostly joking.  I don't see any harm in making this accessible,
> though you are correct people need a keyboard to use the console
> properly.  It does not seem worthwhile right now to create a virtual
> keyboard and mouse-like interface for analog joysticks or directional
> pads.

I agree. I don't think we should implement this currently.

Vale,
Quintus

-- 
Blog: http://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by Quintus** [comment]
The game console is now implemented. Further development on it can happen in the regular `devel` branch, where I merged it into now.

Here's a screenshot for the hungry:

![out](https://cloud.githubusercontent.com/assets/156358/21047730/d12a24ba-be0b-11e6-9685-b651d72fa244.png)

What do you happens next when I accept that command? :-P

Valete,
Quintus
