### ISSUE TITLE
IRC Team Meeting - Looking at April 9th...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#527]
We have been talking about scheduling an IRC meeting to decide on story questions, tools used by the team, some game mechanics, and administrative issues.
We are looking at a date of April 9th for the meeting.  If you think you would be able to make this date, please respond to this message confirming it; otherwise please suggest other possibilities for the date.
We need responses in order to confirm we will have people able to attend the meeting.

We would allow two weeks for creating documents expressing views on issues  and two weeks for reading those documents.  This leads to the following cumulative list of dates:
* March 12th - Last Day to Suggest addition/removal of topics for discussion
* March 26th - Due Date for All Documents Expressing Views on Topics
* April 9th - IRC Team Meeting - Channel #secretchronicles on freenode.net

A tentative list of topics for the meeting has been discussed at forum.secretchronicles.de/topics/387.  Feel free to add new topics, either by that forum entry or the mailing list.
Only official members at https://github.com/orgs/Secretchronicles/people will be able to decide on issues during the meeting; however, feedback from everyone in the community is welcome -- we want to take your opinions into account.

cc @Bugsbane, @Aakburns, @DarkAceZ, @brianvanderburg2, @Quintus, @sydneyjd, @xet7, @Luiji, @sauer2, @kirbyfan64

**Comment by DarkAceZ** [comment]
It's quite a bit away, but so far, my calendar is clear.
Suits me fine.

**Comment by Bugsbane** [comment]
What time would it be? I'll be looking after my kids then, who tend to need me constantly, but if it's at some time that they're asleep....

**Comment by xet7** [comment]
It's OK for me.
I tried to reply by email, but it did not work, so I reply here directly at GitHub.

**Comment by sauer2** [comment]
@datahead8888 Works for me, but like @Bugsbane asked: What time did you have in mind?

**Comment by datahead8888** [comment]
> What time would it be? I'll be looking after my kids then, who tend to need me constantly, but if it's at some time that they're asleep....

@Bugsbane, at what time do your children go to sleep?  The potential problem with having a meeting really late in US/Canada time is that this will be at odd hours of the morning for anyone in German time.

**Comment by Quintus** [comment]
Would everybody please be so kind and post the UTC offset he lives in (or will live in in April)? Otherwise it’s hard to suggest a useful time.

Valete,
Quintus

**Comment by Quintus** [comment]
Parallel discussion on the ML: http://lists.secretchronicles.de/tsc-devel/2016/03/0000002.html

**Comment by kirbyfan64** [comment]
UTC -6

**Comment by xet7** [comment]
UTC+3

**Comment by lambda-11235** [comment]
UTC-8

**Comment by sydneyjd** [comment]
My time is UTC-05:00.

**Comment by Quintus** [comment]
UTC+1, will be UTC+2 in April.

**Comment by DarkAceZ** [comment]
UTC-5

**Comment by sauer2** [comment]
same as Quintus'

**Comment by datahead8888** [comment]
UTC-5

**Comment by Quintus** [comment]
Okay. I have the following suggestions on time. I have tried to find times that I hope are acceptable to everyone, though it obviously is impossible to reach a satisfactory result for everyone. Someone of us is going to have to get up early.

1. 04:00 UTC
2. 05:00 UTC
3. 11:00 UTC
4. 12:00 UTC
5. 14:00 UTC
6. 17:00 UTC
7. 19:00 UTC

All of these are okay to me if required. I think option 5 fits best, but I am open to other suggestions.

Valete,
Quintus

**Comment by xet7** [comment]
Hi,
for me, others are ok, but option 7 starts to be too late, I can reconsider if needed.

BR,
xet7

**Comment by kirbyfan64** [comment]
5 *might* be too late for me, but anything at all before that works.

**Comment by lambda-11235** [comment]
Options 3/4 might be to early/late for me, as it corresponds to 3/4 in the morning. 5 may also be pushing it, but I think I could get up that early..

**Comment by brianvanderburg2** [comment]
I'm in EDT right now (UTC-4) Options 4/5 would be 8/9 AM Sunday and probably doable.  Options 6/7 probably better.

**Comment by datahead8888** [comment]
Option 1 (12:00 AM EDT), or options 5/6/7 (each after 10:00 AM EDT) are possible.
Option 4 is possible if needed, though it is 8:00 AM UDT, so I'd prefer not to use that option.

Basically, I subtract 4 hours from UTC times to get the EDT time.

**Comment by kirbyfan64** [comment]
Wait, I'm an idiot. I was calculating my local time the wrong way.

5, 6, and 7 would all work for me.

**Comment by sydneyjd** [comment]
I'd have to go with 5 and 6 for my options. I *should* be able to do
that almost no matter what.

-Sydney

**Comment by DarkAceZ** [comment]
Assuming that I have the Saturday free, any of the selections will be okay.

**Comment by sauer2** [comment]
I'd rather go with one of the earlier options, but in theory I'm off the whole day.

**Comment by Quintus** [comment]
This looks currently as if we can narrow the set of available options down to options 5 and 6, with preferance probably towards option 6.

Since some people here spoke of sunday, and others of saturday. The meeting is on 2016-04-09, which is a *Saturday*.

@Bugsbane what about you? @Luiji?

**Comment by Bugsbane** [comment]
1,2,5,6,7 should work for me. My kids would be in bed for 1 or 2. 5,6,7 I can do, but I may have to leave sporadically to look after my kids.

**Comment by Luiji** [comment]
Options 5 through 7 are the closest to good for me here in `/usr/share/zoneinfo/America/New_York` (UTC-5).

**Comment by lambda-11235** [comment]
Turns out daylight saving time means I'm at -7 UTC, and not -8 UTC. Anyone living in the U.S. might want to consider this, if you haven't already. This now means only option 3 is bad for me, with option 4 being unpreferable. Option 5 is now perfectly fine.

**Comment by Quintus** [comment]
Okay, it still looks to me as if option 6 is causing the least inconvenience for everyone. So, is anybody inherently _against_ option 6 (17:00 UTC)?

Valete,
Quintus

**Comment by Bugsbane** [comment]
> it still looks to me as if option 6 is causing the least inconvenience for everyone.

I'm fine with that

**Comment by kirbyfan64** [comment]
:+1:

**Comment by xet7** [comment]
:+1:

**Comment by sauer2** [comment]
As well.

Am 01.04.2016 um 17:00 schrieb Lauri Ojansivu:

**Comment by lambda-11235** [comment]
:+1:

**Comment by Luiji** [comment]
:+1:

**Comment by DarkAceZ** [comment]
:+1:

**Comment by Quintus** [comment]
Now that looks good. Then the meeting is set for

2016-04-09 17:00 UTC

to be held in the `#secretchronicles` chatroom on the Freenode network.

Valete,
Quintus

**Comment by Quintus** [comment]
ML Announcement: http://lists.secretchronicles.de/tsc-devel/2016/04/0000004.html

**Comment by Luiji** [comment]
I'll do everything I can to remember to turn on IRC! =D

**Comment by Quintus** [comment]
> I'll do everything I can to remember to turn on IRC! =D

Cron? :-?

Vale,
Quintus

**Comment by Quintus** [comment]
@Luiji @kirbyfan64 @Bugsbane mind you, we are waiting ;-)

**Comment by kirbyfan64** [comment]
Huh? I put a thumbs up...

**Comment by Quintus** [comment]
@kirbyfan64 The meeting is happening RIGHT NOW! Come join the channel!

**Comment by Quintus** [comment]
@kirbyfan64 We are still discussion, please come!

**Comment by Quintus** [comment]
@kirbyfan64 We are in a 15-minute break now. @Luiji @Bugsbane We miss you!

**Comment by kirbyfan64** [comment]
Holy ****, it's today! 1 moment!

**Comment by Bugsbane** [comment]
Dang! I miscalculated the time. I thought it was happening a few hours from now. :(

**Comment by Bugsbane** [comment]
Ah, I just realized I got my am/PM mixed. *sigh* I'll try to read the logs.

**Comment by datahead8888** [comment]
> Ah, I just realized I got my am/PM mixed. sigh I'll try to read the logs.

I compare the UTC time posted for a meeting against the UTC time shown on our main web page.  I find that useful for seeing how many hours are left till a meeting on a given day.

We'll need to get your input in a story discussion in order to make decisions on the story discussion topics.  We need your representation as an artist.  We could either schedule another IRC discussion or look at using the mailing list and/or GitHub; it's up to the team as to what works.

**Comment by Bugsbane** [comment]
Ok. I read the logs, although I still need to find time to read the story draft. Here's my feedback from what I can remember of it all.

1. For translation, I'd vote for option 5, so we can accept direct po files, be open source and have an accessible web interface to encourage new translators.

2. I like the rayman, checkpoints but no lives model.

3. I feel like my views on the target audience were misrepresented, which I'll admit is largely my fault for not being there. I am *not* arguing in favor of making the game only for kids (or even primarily for kids) or "dumbing stuff down". I am looking at how Mario games manage to successfully appeal to a wide range of audiences ranging from my 4 year old, through to me, a 40 year old. In the tickets I've raised previously, they were items which I felt would make a big difference to supporting kids, while having very little impact on older audiences.

Personally I feel that if we avoid the controversial subjects that people already seem to agree on avoiding (graphic violence, sex, religion, politics etc) then it's only about giving kids the ability to miss the minor parts that don't suit, ie having to read all the text, watch all of the cut scenes etc. Interestingly, most of those same things, many adults would want to skip anyway. I love the idea of having an engaging story. At the same time, I don't want to have to repeatedly watch the same cut scenes over and over, or to have to read slabs of text in the middle of gameplay (I strongly agree with the push to eliminate numbers for things like health etc, and instead represent them visually).

Personally, I believe that kids grow up in an adult world, and that as long as the story isn't graphically violent, sexual etc then I'm perfectly fine with a rich and complex story. If you look at the highest quality stories they typically work at many levels, so different people still get something from them.  Adults can enjoy a complex story and kids can either skip/ignore it, or learn from the simpler layers and be intrigued to try and learn from the more complex ones. The old fairy tales are classic examples of this. To kids, the story of Scrooge is a fun ghost story. To adults it's a lesson about gratitude, generosity, relationships and choosing our path through life. 

Anyway, what I would actually suggest is that we don't make this a strawman, false dichotomy like "Is this going to be a rich, complex game with a story or something dumbed down that's only for 4 year olds?" but instead look at creating a game that is *primarily* for adults, with a rich story that makes allowances for a wider range of players, such as kids, where changes are minor and don't heavily conflict with our primary target group. 

I'm pretty sure there are other subjects that were discussed and voted on that I've forgotten to mention here (I agree with both team member additions) so feel free to ask about anything I've missed.

**Comment by Bugsbane** [comment]
PS. A great example, outside of Mario, of a game working on multiple levels, is double fines "Psychonaughts". It goes into adult ideas ranging from PTSD , parental abandonment, mental institutions etc, but to kids playing, it's just a fun 3D platformer with unique graphics and cut scenes that can be skipped.

**Comment by Bugsbane** [comment]
As to the bug tracker, I love GitHubs interaction flow, but totally, strongly support moving to an open source platform. While I was hoping it would be GitLab/GOGS as they have similar easy collaboration interfaces, I'm not that familiar with Redmine, so it may well be just as good. I'm just grateful that we're not going to TRAC or *shudder* Mantis/Bugzilla.

**Comment by sauer2** [comment]
> Anyway, what I would actually suggest is that we don't make this a strawman, false dichotomy like "Is this going to be a rich, complex game with a story or something dumbed down that's only for 4 year olds?" but instead look at creating a game that is primarily for adults, with a rich story that makes allowances for a wider range of players, such as kids, where changes are minor and don't heavily conflict with our primary target group. 

That's a relief.

Any thoughts about SFGUI vs CEGUI?

**Comment by datahead8888** [comment]
> Anyway, what I would actually suggest is that we don't make this a strawman, false dichotomy like "Is this going to be a rich, complex game with a story or something dumbed down that's only for 4 year olds?" but instead look at creating a game that is primarily for adults, with a rich story that makes allowances for a wider range of players, such as kids, where changes are minor and don't heavily conflict with our primary target group. 

@Bugsbane - what do you mean by allowances for a wider range of players or by minor changes?

We still need to discuss the other story topics with the team.  These were skipped in the meeting.

What we might to do is:
1) Let Quintus and me spend some more time with the draft(s) we've been writing.  I had stopped writing a draft under the assumption that we needed to decide story guidelines first, while I think Quintus may have rushed a little on the one he wrote before the meeting.  Quintus and I also could spend some time talking to each other and the team.
2) Hold another IRC meeting, exclusively focusing on all the story decisions to get it done with.

I'd be a bit hesitant to set a date on the next meeting, since I don't want to rush our stories, though obviously we'll want to get going on them.

Our other option is to hold the IRC meeting immediately and not discuss drafts at all.  Drafts can then be made and discussed after that.

**Comment by datahead8888** [comment]
I edited my last post so that I could revise my suggestion for the story meeting.  This is my new suggestion:
1) Hold another IRC meeting, exclusively focusing on all the story decisions, as soon as possible with scheduling.  We would stick with the original story topics we had last time, meaning that story drafts do not need to be finished or improved by this date.  If an IRC meeting does not work, the only other option is a combination of GitHub and mailing list discussions.
2) Let Quintus and me spend some more time with the draft(s) we've been writing.  I had stopped writing a draft under the assumption that we needed to decide story guidelines first, while I think Quintus may have rushed a little on the one he wrote before the meeting.  Quintus and I also could spend some time talking to each other and the team.

We can then hold another meeting if needed to decide on more of the story draft(s).

**Comment by Quintus** [comment]
> For translation, I'd vote for option 5, so we can accept direct po files, be open source and have an accessible web interface to encourage new translators.

@Bugsbane Please go to https://github.com/orgs/Secretchronicles/people and set your membership to "public". Otherwise, formally, you are in conflict with the voting rules and aren’t allowed to vote. As for the rest, datahead has requested and I have started the long voting procedure, see ticket #196. That is, in two weeks we are going to vote on the topic again, then hopefully with a higher participation.

Likewise, @kirbyfan64, please accept the invitation you were sent and set your membership to "public" as described above as well.

> I like the rayman, checkpoints but no lives model.

Nice, then we really have something to work on.

> I feel like my views on the target audience were misrepresented

I apologise if I didn’t repeat your views correctly, however, after all all I wanted was to prevent the team from making a decision without your word being heard before.

> As to the bug tracker, I love GitHubs interaction flow, but totally, strongly support moving to an open source platform. While I was hoping it would be GitLab/GOGS as they have similar easy collaboration interfaces, I'm not that familiar with Redmine

Redmine is GPL’ed software, so from the FLOSS point of view there’s nothing to complain about. I don’t know how long @xet7 is going to take to set up things, so for the meantime we will simply continue using GitHub.

> Hold another IRC meeting, exclusively focusing on all the story decisions

Since it is incredibly difficult to get all of the team members onto the same time, not to mention finding a time where everybody actually _does_ have time, I would like to talk this over in the tracker, which might even come to a faster result than planning and helding another meeting, because it has to be announced weeks in advance so that everybody can mark it in his calendar beforehand. If you want a soon subsequent meeting, then I think you should also organise it. I’ve organised this GD, which was quite a lot of work, and I’d like to take a pause from organising IRC meetings for a moment.

-------------

Since the 2nd GD is over now, I close this issue. Please continue with the story discussion in the ticket it belongs to: #68.

Valete,
Quintus

**Comment by datahead8888** [comment]
> Since it is incredibly difficult to get all of the team members onto the same time, not to mention finding a time where everybody actually does have time, I would like to talk this over in the tracker, which might even come to a faster result than planning and helding another meeting, because it has to be announced weeks in advance so that everybody can mark it in his calendar beforehand.

Sometimes it's hard to get people to participate in the tracker in discussions like this, though we could @ them; people will have to participate if they want to have input.  It probably does make sense to see where this goes before starting another IRC meeting.

Thank you for all the work you did in this IRC meeting.
