### ISSUE TITLE
Scandinavian characters as boxes after SFML branch to devel merge

### ISSUE THREAD

**Issue by xet7** [Secretchronicles/TSC#528]
Hi,
I compiled newest SFML master and TSC devel branch today 2016-03-06.
Scandinavian characters are shown as boxes:

![screenshot at 2016-03-06 02 01 03](https://cloud.githubusercontent.com/assets/15545/13551363/fa39d140-e33f-11e5-8b65-204c47432969.png)

![screenshot at 2016-03-06 02 00 38](https://cloud.githubusercontent.com/assets/15545/13551366/133192dc-e340-11e5-874d-50532c9f988e.png)

**Comment by xet7** [comment]
@lambda-11235
Your pull request https://github.com/Secretchronicles/TSC/pull/529 fixes this issue for me.

Screenshots:
![utf1](https://cloud.githubusercontent.com/assets/15545/13553695/fab3daf8-e399-11e5-864a-3fbad00c0e53.png)

![utf2](https://cloud.githubusercontent.com/assets/15545/13553701/16683438-e39a-11e5-8b37-a928fa6fa369.png)

@Quintus 
Could you test German version how it works?
Also, I yesterday updated potfile and fi_FI.po, but not the German de.po file.

**Comment by xet7** [comment]
This seems to be happening again on latest devel branch, latest commit of 2017-08-26 "Rename directory path pow to switch".

![kuvakaappaus - 2017-08-27 20-38-01](https://user-images.githubusercontent.com/15545/29752546-deb888bc-8b68-11e7-9495-14545c9aabba.png)

![kuvakaappaus - 2017-08-27 20-36-51](https://user-images.githubusercontent.com/15545/29752549-ec4ecb80-8b68-11e7-9f85-ec9c74eaeebc.png)

**Comment by lambda-11235** [comment]
The code for text seems to have changed from using the SFML api to the CEGUI api. Looks like it's partially due to missing `UTF_` calls when setting CEGUI text in src/gui/menu_data.cpp.
