### ISSUE TITLE
Please port to CEGUI 0.8.5

### ISSUE THREAD

**Issue by coldtobi** [Secretchronicles/TSC#537]
Currently TSC does not compile with CEGUI 0.8.x. 

There were some efforts for smc @ Debian, see https://bugs.debian.org/812096 , (but the patch is not complete.)

Many thanks!

**Comment by kirbyfan64** [comment]
Hello! This has already been reported: see issue #10.

**Comment by kirbyfan64** [comment]
[And this comment](https://github.com/Secretchronicles/TSC/issues/10#issuecomment-206397715), which mentions that the port is for CEGUI 0.8.5.
