### ISSUE TITLE
Link to assets licence in README is broken

### ISSUE THREAD

**Issue by pedja1** [Secretchronicles/TSC#538]
Im curious to know how are assets (png-s and audio files) licenced.

I know that all assets mentioned in issues labeled "De-Marioization" are probably not ok, but can i use other assets and under which terms?

Im creating a game based on SMC/TSC for android, but from scratch(code base), but i want to use assets from "SMC/TSC", and i want to know if that is ok (I actually already used all assets, i just want to know if that is ok or not)?
I would maybe eventually publish game for free in Google Play Store

This is the game im working on
https://github.com/pedja1/SMC-Android

**Comment by Quintus** [comment]
There is a license statement at the bottom of the README which should answer your question. It is *below* the GPL statement in case you stopped looking when you read GPL :-)

In a nutshell: The old SMC graphics we inherited have an [undefinable license](https://github.com/Secretchronicles/TSC/blob/devel/tsc/docs/pages/old_smc_contribution_license.md) nobody really knows what it is. The new assets we added always have a `license` tag in the `.settings` file accompanying an asset, and we generally use CC-BY licensing for those.

Vale,
Quintus

**Comment by pedja1** [comment]
I actually did read it, but link(path) in README is wrong: `docs/old_smc_contribution_license.md`, it should be `docs/pages/old_smc_contribution_license.md`. :) My bad for not looking harder.

Anyway, thanks for clarification.

**Comment by Quintus** [comment]
> I actually did read it, but link(path) in README is wrong

Oops. That needs to be fixed. Thanks for reporting!

Vale,
Quintus

**Comment by pedja1** [comment]
No problem :)
