### ISSUE TITLE
Building with the Ninja generator fails if tinyclipboard isn't already installed

### ISSUE THREAD

**Issue by kirbyfan64** [Secretchronicles/TSC#540]
```cmake
ExternalProject_Add(tinyclipboard
    PREFIX "${TSC_BINARY_DIR}/tinyclipboard"
    SOURCE_DIR "${TSC_SOURCE_DIR}/../tinyclipboard"
    BUILD_IN_SOURCE 1
    CONFIGURE_COMMAND ""
    BUILD_COMMAND ${CMAKE_MAKE_PROGRAM} CC=${CMAKE_C_COMPILER} AR=${CMAKE_AR}
    INSTALL_COMMAND "")
```

This code won't work if you configure CMake to use the Ninja build system. I had to build and install tinyclipboard separately and then enable `USE_SYSTEM_TINYCLIPBOARD`.

**Comment by Quintus** [comment]
Do you have an error message for us? What’s ninja?

Vale,
Quintus

**Comment by kirbyfan64** [comment]
@Quintus Sorry, sometimes I forgot that most people aren't as build system obsessed as I am. :)

Normally, people use the GNU makefile generator that comes with CMake. However, you can also do:

```
$ cmake -G Ninja
```

[Ninja](https://ninja-build.org) is a build system that's quite a bit faster than make...which is why I use it!

The problem: the code I showed uses `${CMAKE_MAKE_PROGRAM}`, which is defined to `ninja` when using the Ninja generator for CMake. As a result, tinyclipboard is built using Ninja...

...except tinyclipboard doesn't have a Ninja build script, so the build fails.

A simple fix would just be for TSC to build tinyclipboard manually through CMake; after all, tinyclipboard's Makefile is rather short.

**Comment by Quintus** [comment]
> A simple fix would just be for TSC to build tinyclipboard manually through CMake; after all, tinyclipboard's Makefile is rather short.

I see. Should be doable. I’ll look into that.

Vale,
Quintus

**Comment by Quintus** [comment]
@kirbyfan64 The last commit incorporates tinyclipboard into the regular CMake build process by means of `add_library()`. Does this fix your problem?

Vale,
Quintus

**Comment by kirbyfan64** [comment]
Well, I'm 1000 miles away from my computer, so I'll take your word for it. :)

**Comment by HybridDog** [comment]
lt doesn't compile for me:
```
Scanning dependencies of target tsc
CMake Error: Directory Information file not found
[ 16%] Building CXX object CMakeFiles/tsc.dir/src/input/mouse.cpp.o
TSC/tsc/src/input/mouse.cpp: In member function ‘bool TSC::cMouseCursor::Handle_Event(const sf::Event&)’:
TSC/tsc/src/input/mouse.cpp:164:10: error: ‘MouseWheelScrolled’ is not a member of ‘sf::Event’
     case sf::Event::MouseWheelScrolled: {
          ^
TSC/tsc/src/input/mouse.cpp:165:16: error: ‘const class sf::Event’ has no member named ‘mouseWheelScroll’
         if (ev.mouseWheelScroll.wheel == sf::Mouse::VerticalWheel &&
                ^
TSC/tsc/src/input/mouse.cpp:165:42: error: ‘VerticalWheel’ is not a member of ‘sf::Mouse’
         if (ev.mouseWheelScroll.wheel == sf::Mouse::VerticalWheel &&
                                          ^
TSC/tsc/src/input/mouse.cpp:166:35: error: ‘const class sf::Event’ has no member named ‘mouseWheelScroll’
             Handle_Mouse_Wheel(ev.mouseWheelScroll.delta)) {
                                   ^
make[2]: *** [CMakeFiles/tsc.dir/src/input/mouse.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/tsc.dir/all] Fehler 2
make: *** [all] Fehler 2
