### ISSUE TITLE
Segfault when touched by a monster

### ISSUE THREAD

**Issue by Boiethios** [Secretchronicles/TSC#545]
When I have the fire bonus (and only in that case, as far as I know) and I touch a monster, the game segfault.

**Comment by lambda-11235** [comment]
I'm having trouble reproducing the bug. Which level was this on? Which monster? Which version of the game (given on lower right in the title screen)?

**Comment by Quintus** [comment]
Given the [forum discussion](http://forum.secretchronicles.de/topics/437), this was on `feature-cegui-0.8`. Would be nice of the OP could retry on current `devel`.

Vale,
Quintus

**Comment by Boiethios** [comment]
What is the current development branch? I will test again with the latest version.

**Comment by Quintus** [comment]
On Tue, Jul 26, 2016 at 12:56:25AM -0700, Boiethios wrote:
> What is the current development branch? I will test again with the latest version.

With CEGUI 0.8.x merged, the main development branch is `devel` (again).

Vale,
Quintus

-- 
Blog: http://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by Boiethios** [comment]
There are a **lot** of compilation errors when compiling without `ENABLE_EDITOR`.

I think every `mp_*` variable initialization must be in a `#if` block, like the declaration.

**Comment by Quintus** [comment]
On Tue, Jul 26, 2016 at 03:55:21AM -0700, Boiethios wrote:
> There are a **lot** of compilation errors when compiling without `ENABLE_EDITOR`.

I have not yet tried compiling without ENABLE_EDITOR set. The
compilation errors qualify for a new ticket, but are irrelevant for
this ticket. ENABLE_EDITOR is enabled by default, and if you had left
it in its default state, you wouldn't have run into compilation errors
here.

If ENABLE_EDITOR was not set by default for you, you should clean your
build directory as its default value was changed somewhere shortly
before the merge (when switching branches, cleaning the build
directory is recommended anyway).

Also note that you shouldn't disable ENABLE_MRUBY. It is likely that
this will also result in quite a lot of compilaton errors.

Vale,
Quintus

-- 
Blog: http://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by datahead8888** [comment]
Has anyone reproduced this recently in devel?  I remember seeing something like this when I touched a monster a while back.  I may have linked to a back trace on pastebin.com in IRC, but I would need to grep the logs to see if I can find this, if it still exists.

**Comment by datahead8888** [comment]
I remember seeing something like this a few months ago or so when I touched a monster.  I have not seen it in a while.  I'd be interested in at least keeping this open a little longer to try and ask @Boiethios to retest or see if anyone else on the team can reproduce this.  If a bug like this exists, it is very serious.

**Comment by datahead8888** [comment]
Quintus has a point.  If no one can reproduce this, it should be closed.  No one has been able to in a while, so I am closing this.

**Comment by Boiethios** [comment]
Sorry, I forgot this opened issue. Indeed, I could not reproduce this.
