### ISSUE TITLE
Segfault when selecting menu item on Linux Mint 18

### ISSUE THREAD

**Issue by xet7** [Secretchronicles/TSC#547]
@Quintus @kirbyfan64 

Hi,
today at this commit on devel branch:

```
commit 8a2d356749867631e3b842b1dedc02075df1932e
Author: Quintus
Date:   Tue Jul 19 21:41:44 2016 +0200
```

when I compiled with this command

``` bash
rm -rf /home/USERNAME/tsc && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/USERNAME/tsc .. && make && make install
```

TSC does start and main theme sound is playing, but when I select some menu like Options with my keyboard arrow keys down and enter, TSC segfaults. This log is from selecting Options, and also selecting Start does segfault TSC, I did not try others from main menu yet.

Logs:
[compile.txt](https://github.com/Secretchronicles/TSC/files/380200/compile.txt)
[gdb.txt](https://github.com/Secretchronicles/TSC/files/380201/gdb.txt)

**Comment by Quintus** [comment]
I cannot reproduce this. Maybe it has to do with the Finnish translation? Can you try setting `LANG` to the locale-agnostic `C` locale before running TSC? You can do it like this:

~~~~~
$ export LANG=C
~~~~~

Please report if the issue persists.

Vale,
Quintus

**Comment by xet7** [comment]
@Quintus @kirbyfan64 

I updated pot and po files.

Main menu loads in all cases: running TSC, under GDB, and under Valgrind.

![mainmenu](https://cloud.githubusercontent.com/assets/15545/17271604/eb43f3ac-5688-11e6-9ac9-bfa16317b052.png)

Without and with GDB, after selecting some menu option from main menu, TSC segfaults. 

[gdb-lang-c.txt](https://github.com/Secretchronicles/TSC/files/391971/gdb-lang-c.txt)

[gdb-lang-en_US.txt](https://github.com/Secretchronicles/TSC/files/391972/gdb-lang-en_US.txt)

[gdb-lang-fi.txt](https://github.com/Secretchronicles/TSC/files/391974/gdb-lang-fi.txt)

Probably at some point I had low available RAM, so I rebooted and tried again.

[gdb-lang-fi-AFTER-REBOOT.txt](https://github.com/Secretchronicles/TSC/files/391975/gdb-lang-fi-AFTER-REBOOT.txt)

Running under Valgrind prevents TSC from segfaulting, I can guess menu options and even slowly play the game.

![start](https://cloud.githubusercontent.com/assets/15545/17271627/8a7c5aae-5689-11e6-986a-478cb41904ca.png)

![gameplay](https://cloud.githubusercontent.com/assets/15545/17271625/74ee5d72-5689-11e6-990c-02af836a936f.png)

![options](https://cloud.githubusercontent.com/assets/15545/17271626/7d9c60b8-5689-11e6-8f7f-1cf71e79e028.png)

![load](https://cloud.githubusercontent.com/assets/15545/17271628/9605c630-5689-11e6-9761-4d0fc5df5a4d.png)

![save](https://cloud.githubusercontent.com/assets/15545/17271630/9e89809e-5689-11e6-9033-63b700523cac.png)

[valgrind.txt](https://github.com/Secretchronicles/TSC/files/391979/valgrind.txt)

[valgrind-supressed.txt](https://github.com/Secretchronicles/TSC/files/391980/valgrind-supressed.txt)

**Comment by datahead8888** [comment]
I, too, had a segfault, though I did not get to the menu screen.
It happened on a malloc call (through new), which suggests there may be heap corruption.
@xet7, could you post a backtrace for your segfault from gdb?

What I have found is documented here: http://forum.secretchronicles.de/topics/448

**Comment by xet7** [comment]
@datahead8888 

I to menu screen only with older buggy cegui and using valgrind.

After compiling newer cegui I did not get to main menu, segfault in all cases, also with valgrind.

But currently on Linux Mint 18 I have broken compile of cegui, so I can't add backtrace yet, maybe sometime later when I compile cegui again.

Currently I'm happy that TSC works easily on Lubuntu 16.10, see:
http://forum.secretchronicles.de/topics/449
https://github.com/Secretchronicles/TSC/blob/devel/INSTALL-2016-08-01.md

**Comment by Quintus** [comment]
@datahead8888 try deleting `~/.cache/tsc`. When  adding new graphics, sometimes this happens. I have not exactly found out why yet.

Valete,
Quintus

**Comment by xet7** [comment]
During game Start and Options menu show this bug (screenshot above) as pointed out by @Quintus 
https://bitbucket.org/cegui/cegui/issues/1063/openglrenderer-on-linux-renders-cegui

The CEGUI bug is in all Ubuntu based distros that are older that Ubuntu 16.10.

On Lubuntu 16.10 Start and Options menu shows correctly:

![lubuntu1610start](https://cloud.githubusercontent.com/assets/15545/17304484/741a626e-582e-11e6-8e4c-2a4b8f0a128f.png)

![lubuntu1610options](https://cloud.githubusercontent.com/assets/15545/17304518/9cf23040-582e-11e6-9e74-b6ee49db8dde.png)

I have added request for updating or backporting bugfix to older Ubuntu versions to Launchpad:
https://bugs.launchpad.net/ubuntu/+source/cegui-mk2/+bug/1608114

**Comment by Quintus** [comment]
@xet7 I suspect the original problem is a duplicate of #560. Can you confirm that this the case so that this ticket can be closed?

**Comment by xet7** [comment]
@Quintus 

I today compiled CEGUI from these sources:
https://launchpad.net/ubuntu/+source/cegui-mk2/0.8.7-1.2

And also TSC latest from devel branch:

```
commit 1429329dcd95c459c24615113cefe8ddedcb74d1
Author: Quintus
Date:   Mon Aug 22 17:48:57 2016 +0200

    Handle libxml++'s header and linking dependencies in its CMake Find module.
```

On Linux Mint 18 still when from main game menu when I select Start, then TSC stopped to some errors.

Log attached.

[gdb.txt](https://github.com/Secretchronicles/TSC/files/432897/gdb.txt)

**Comment by Quintus** [comment]
@xet7 Please delete the cache directory `~/.cache/tsc` and retry.

**Comment by xet7** [comment]
Ok, after clearing cache directory I got following errors.

[gdb2.txt](https://github.com/Secretchronicles/TSC/files/433178/gdb2.txt)

**Comment by Quintus** [comment]
Hm. Something is wrong with the destructors. This appears to be some new error we have not seen yet. I don't have time to look at it right now, but we should keep it on the agenda.

**Comment by Quintus** [comment]
Is this still relevant? If yes, please give a detailed step-by-step guide on how to reproduce this crash.

**Comment by xet7** [comment]
@Quintus

No, current TSC does not run on Mint 18 because of too old libraries, minimum requirement is Ubuntu 16.10 based distro.
