### ISSUE TITLE
Deprecated Open GL Research and Code Changes...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#55]
The fixed function pipeline in Open GL is deprecated.
Programs are supposed to use the newer Open GL, which requires GLSL (a shading language to write Open GL code snippets that run on the GPU).

Prior Forum Discussions:
* http://secretmaryo.org/phpBB3/viewtopic.php?f=6&t=2885&p=17575#p17575 and
* http://secretmaryo.org/phpBB3/viewtopic.php?f=1&t=9929&p=44619#p44619 (toward bottom)

These are the major things that are deprecated in the old Open GL and that must be changed if they're in use in order not to have deprecated code:

* All matrix transformations must be done with GLSL (ie do not use glRotate3f or glTranslatef)
* Lighting must be done through GLSL (ie do not use glLightfv)
* Textures must be done through GLSL (ie do not use glEnable(GL_TEXTURE_2D); )
* All drawing calls must be done using vertex buffer objects and not immediate mode (ie do not use glBegin or glEnd function calls)

Tasks:
- [ ] Verify - are there any Open GL categories of importance other than the ones I listed above?
- [ ] Research support for fixed function pipeline on newer graphics cards versus support of GLSL on older graphics cards (as possible - forum posts might be a good avenue)
  * Professor Han Wei Shen at Ohio State University said that after a certain point, support for the old Open GL will be dropped, and a lot of programs will break.  Many other people think it will be a long time before this, however.
- [ ] Identify a list of all major Open GL function calls or constants that are deprecated
- [ ] Run text searches through the Secret Maryo source code to identify all usage of deprecated items
- [ ] Identify 3rd party library to replace some of the matrix/vector functionality that is no longer handled by Open GL
  * GLM seems to work pretty well - http://glm.g-truc.net/0.9.5/index.html
- [ ] Analyze logic and structure of Open GL relevant code
- [ ] Write code for changes
- [ ] Unit Test Changes
- [ ] Regression Test all of Secret Maryo Chronicles (anything that displays must be tested)
- [ ] Write documentation for Open GL rendering

NOTE: Not slated for upcoming release

**Comment by Quintus** [comment]
Superseded by #105.
