### ISSUE TITLE
TSC image manager optimisation

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#550]
TSC hickups basically every time something graphically more complex happens. I poked around the code a bit and finally ran it through Valgrind's `cachegrind`. The result shows that TSC spends most of its execution time in `std::string::find_first_of()`. To be honest, this is definitely not where a game should spend most of its execution time. Debugging with GDB reveals that these calls stem from `cImage_Manager::Get_Pointer()`, so this is where to start optimising things.

Valgrind cachegrind report:

~~~~~~
--------------------------------------------------------------------------------
I1 cache:         65536 B, 64 B, 2-way associative
D1 cache:         65536 B, 64 B, 2-way associative
LL cache:         524288 B, 64 B, 16-way associative
Command:          ./TESTINSTALL/bin/tsc -l A
Data file:        cachegrind.out.10905
Events recorded:  Ir I1mr ILmr Dr D1mr DLmr Dw D1mw DLmw
Events shown:     Ir I1mr ILmr Dr D1mr DLmr Dw D1mw DLmw
Event sort order: Ir I1mr ILmr Dr D1mr DLmr Dw D1mw DLmw
Thresholds:       0.1 100 100 100 100 100 100 100 100
Include dirs:     
User annotated:   
Auto-annotation:  off

--------------------------------------------------------------------------------
             Ir       I1mr       ILmr             Dr        D1mr        DLmr             Dw       D1mw       DLmw 
--------------------------------------------------------------------------------
162,748,592,194 55,347,476 10,854,764 40,340,167,133 262,898,184 142,098,514 18,732,292,982 78,755,516 57,828,907  PROGRAM TOTALS

--------------------------------------------------------------------------------
            Ir       I1mr      ILmr             Dr        D1mr       DLmr            Dw       D1mw       DLmw  file:function
--------------------------------------------------------------------------------
70,724,385,785 26,979,440 5,580,144 16,669,248,519 107,494,430 36,961,669 6,099,289,129 65,757,434 50,234,010  ???:???
11,232,862,687     85,394    13,365  1,154,425,876      13,285      2,702             0          0          0  ???:memchr
10,786,072,281     98,919    17,076  3,089,789,670     113,424        873 2,078,837,019     48,985        255  ???:std::string::_M_mutate(unsigned long, unsigned long, unsigned long)
 8,347,787,535     58,130    15,204  3,283,668,809   3,821,717    445,528 1,070,974,507        726          7  ???:boost::filesystem::path::m_path_iterator_increment(boost::filesystem::path::iterator&)
 6,993,087,380     20,231     3,622  1,298,528,230   3,290,801    985,497 1,027,728,433      2,011          8  ???:std::string::find_first_of(char const*, unsigned long, unsigned long) const
 5,913,610,783    116,854     9,890  1,761,499,962     284,508     37,111   377,464,676    154,135      6,433  ???:malloc
 4,802,901,714     14,083     8,623  1,666,309,678     375,394     88,685 1,274,163,852     53,895      2,387  ???:__dynamic_cast
 4,220,220,192     37,822     5,295  1,066,671,155       7,000          7   678,790,735         25          6  ???:std::string::replace(unsigned long, unsigned long, char const*, unsigned long)
 3,531,921,957     41,458     9,774  1,114,315,627     351,621     28,747   910,320,151     60,292      1,516  ???:__cxxabiv1::__si_class_type_info::__do_dyncast(long, __cxxabiv1::__class_type_info::__sub_kind, __cxxabiv1::__class_type_info const*, void const*, __cxxabiv1::__class_type_info const*, void const*, __cxxabiv1::__class_type_info::__dyncast_result&) const
 3,494,970,555      4,144     4,144    712,955,260   4,144,196  2,799,698   237,653,924  3,884,456  3,629,325  ???:ilCopyPixels2D
 3,189,165,280     17,558     6,906    491,608,967      11,901      2,194   776,253,904      7,583         37  ???:char* std::string::_S_construct<char*>(char*, char*, std::allocator<char> const&, std::forward_iterator_tag)
 3,104,925,088     41,641     4,961    776,231,272       1,723         14   485,144,545      6,116         70  ???:std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&, unsigned long, unsigned long)
 2,812,366,533     68,832    10,854    749,610,580     381,277         39   350,961,048    105,107         16  ???:boost::filesystem::detail::lex_compare(boost::filesystem::path::iterator, boost::filesystem::path::iterator, boost::filesystem::path::iterator, boost::filesystem::path::iterator)
 2,779,460,428     18,807     4,926    633,428,531      53,454          8   620,543,718        150          1  ???:std::string::_M_replace_safe(unsigned long, unsigned long, char const*, unsigned long)
 2,469,314,228     22,165     4,927    247,089,130         795          0   494,178,260    102,706      1,866  ???:std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&)
 1,888,810,439     70,191     7,708    377,914,286     599,691    268,517            16          0          0  ???:free
 1,842,363,006     32,142     2,786    872,698,266   1,054,025      6,961   290,899,422          8          2  ???:std::codecvt<wchar_t, char, __mbstate_t> const& std::use_facet<std::codecvt<wchar_t, char, __mbstate_t> >(std::locale const&)
 1,379,886,552     30,981     6,397    250,888,464         184          4   250,888,464     17,429        490  ???:operator new(unsigned long)
   863,520,488     16,285     5,382    215,957,471  39,767,136 34,544,381   185,027,310          0          0  ???:CEGUI::Event::unsubscribe(CEGUI::BoundSlot const&)
   826,595,398     12,652     7,556    312,273,159       1,999          2    31,431,746         52          0  ???:adler32
   757,220,929      2,669     1,755    336,320,270       1,050          5    84,294,491          5          0  ???:std::string::_M_leak_hard()
   562,003,030     46,168    45,984    112,195,797     124,101      2,533    78,494,895     29,170      4,498  ???:inflate
   512,689,124     61,377    12,408    154,642,516     854,578    249,823    93,107,400      3,474         51  ???:boost::filesystem::path::begin() const
   501,763,640     28,955    24,120     87,324,728     734,923     20,783    21,835,732  1,384,702  1,001,961  ???:snd_pcm_lfloat_convert_float_integer
   488,196,654     49,725     4,055    195,278,656      52,438      4,747            28          0          0  ???:std::locale::id::_M_id() const
   387,865,911        803       583     96,966,476       4,484        772             5          0          0  ???:boost::filesystem::path::codecvt()
   377,114,642     15,481     3,051    161,691,643  32,745,647 28,213,743             0          0          0  ???:std::_Rb_tree_increment(std::_Rb_tree_node_base*)
   350,580,112      1,776     1,776     87,680,631     349,802    284,384    21,982,463    257,673     41,813  ???:iReadLump
   272,467,152     55,619    10,915     73,100,464      21,334         21    49,841,672         43          1  ???:boost::filesystem::path::compare(boost::filesystem::path const&) const
   223,646,437     11,229     4,374     48,190,947       1,510         53    41,306,526         15          0  ???:std::string::compare(char const*) const
   188,636,865      2,442     1,978     70,553,040     419,675     10,762    28,875,240    134,812     13,893  ???:mdct_backward
   174,016,956        280       280     63,582,768      52,232     32,624    10,039,856    157,034    156,855  ???:iConvertPalette
~~~~~~

Full cachegrind profile file: http://team.secretchronicles.de/~quintus/stuff/cachegrind.txt.gz

Running TSC through Valgrind takes more than 15 minutes, so think about doing this. Also it is nearly unplayable slow.

Vale,
Quintus

**Comment by Quintus** [comment]
A large part of these calls seem to come from creating particle emitters.

**Comment by Quintus** [comment]
I think have to correct this statement. Appearently the most calls come from changing image sets (but the particle emitters do have a role, still).

This is a confusing topic.

**Comment by kirbyfan64** [comment]
Dang, that code loops through every surface to find the image:

```c++
cGL_Surface* cImage_Manager::Get_Pointer(const fs::path& path) const
{
    for (GL_Surface_List::const_iterator itr = objects.begin(); itr != objects.end(); ++itr) {
        cGL_Surface* obj = (*itr);

        // return first match
        if (obj->m_path.compare(path) == 0) {
            return obj;
        }
    }

    // not found
    return NULL;
}
```

No wonder it's so slow...

A simple change would be to have a hash table of paths -> indexes into the `objects` vector.

**Comment by Quintus** [comment]
> A simple change would be to have a hash table of paths -> indexes into the objects vector.

Yes, and that's probably what we'll do. The correct solution, however, would be to not use string comparisons at all, but instead index the surfaces. For the rewrite in 3.0.0, we should generally reconsider how to deal with things.

Vale,
Quintus

**Comment by datahead8888** [comment]
> The correct solution, however, would be to not use string comparisons at all, but instead index the surfaces.

What did you have in mind for this?

**Comment by Quintus** [comment]
On Sat, Jul 30, 2016 at 09:18:35PM -0700, Chris Jacobsen wrote:
> > The correct solution, however, would be to not use string comparisons at all, but instead index the surfaces.
> 
> What did you have in mind for this?

String comparisons are expensive since a string must be compared
letter by letter; if you use a hash table, you still have to hash the
string and then compare the hash value. If each surface got an
integral index instead, that'd be quicker I imagine. From what I
learned in this OpenGL tutorial that's what we'd get from OpenGL
anyway each time we upload a surface to the graphics card. So, at
least for the rewrite, we should simply upload all surfaces used in a
level to the graphics card and then use the indices we get from OpenGL
to reference them. For 2.1.x, the hashtable solution is good enough
if it performs okay, as it does not need so much code rewriting.

Greetings
Marvin

-- 
Blog: http://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by Quintus** [comment]
Wow. Optimising `cImage_Manager::Get_Pointer()` doubled TSC's framerate and killed off the long wait phase on level loading. Even the monster level `quintus_5` now loads within seconds. @kirbyfan64 please try current `devel` now and tell me the performance difference it makes on your machine!

Anyone: If you want to see a really cool performance boost, compile `devel` before commit aa2685c899352e57614290a21ba6cb1dbb7be9ed and after. :tada:

Valete,
Quintus

**Comment by sauer2** [comment]
>Anyone: If you want to see a really cool performance boost, compile devel before commit aa2685c and after. :tada:

Sounds good. BTW: How can I compile this? The usual building instructions fail to work, since CEGUI is somehow missing. Can I install that from the package manager, and which version do I need?

Anything else I need to know? Is this the version using SFML already?

**Comment by Quintus** [comment]
The speed difference to 2.0.0 stable won't be too high I guess. When we updated to SFML, things got slower. But the function I optimised was probably already there in 2.0.0, so there will be a speed difference still.

**Comment by sauer2** [comment]
@Quintus Could you tell me how to compile CEGUI the way it works together with the make script of the devel branch?

I downloaded CEGUI 8.7 in source and tried to make + make install it, but the TSC make file still outputs something like

`fatal error: CEGUI/RendererModules/OpenGL/GLRenderer.h: file or dir not found`

**Comment by Quintus** [comment]
> Could you tell me how to compile CEGUI the way it works together with the make script of the devel branch?

CMake's default config works just fine for me, so it's hard to give any advice. I haven't had any problem with it on native use. Better ask @datahead8888 and @xet7 who both went through a more problematic CEGUI compilation yesterday.

I have just downloaded CEGUI, then run

~~~~
$ mkdir build
$ cd build
$ cmake ..
$ make -j4
$ make install
~~~~

And everything worked as it should. If not, you should check if CEGUI doesn't find its prerequisites for the OpenGLRenderer (dev packages!).

Greetings
Marvin

**Comment by sauer2** [comment]
>If not, you should check if CEGUI doesn't find its prerequisites for the OpenGLRenderer (dev packages!).

Seems like it, at least the RendererModules folder is missing in the installed headers. Thanks for the hint. Guess, I'll ask datahead and xet7...

**Comment by datahead8888** [comment]
> Could you tell me how to compile CEGUI the way it works together with the make script of the devel branch?

I pulled Cegui from Bitbucket and then checked out the v0-8 branch, the latest stable branch.  I would definitely make sure you are not using an unstable branch.

Apart from that, there shouldn't be many dependencies at all (one if I remember right).  Check the FAQ section in the Readme.txt file included with the source -- it has some useful information on this.
