### ISSUE TITLE
Texts are offset

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#551]
Texts are not always where they should be. @xet7 has seen this earlier (though I don't find his message currently) and it is easily noticable in the level editor, where the X/Y/UID text is shoved to the bottom of the screen instead of below the mouse cursor.

I suspect there's a problem with `global_upscalex` and `global_upscaley` not being applied correctly.

Greetings
Marvin

**Comment by Quintus** [comment]
The coordinates offset in the editor appears to be a different issue at its root, but is affected by the general text offset as well (i.e. is caused by two problems in conjunction).

**Comment by datahead8888** [comment]
Did the "Pin editor object info to the screen" and Hud reimplementation commits fix the two problems, or is more work still left on this?

Great job for addressing the root of the issue :)

**Comment by Quintus** [comment]
On Sun, Oct 16, 2016 at 02:46:55PM -0700, Chris Jacobsen wrote:
> Did the "Pin editor object info to the screen" and Hud
> reimplementation commits fix the two problems, or is more work still
> left on this?

The commit touching the editor object info only fixes half of the
problem with the editor coordinates. They are now pinned to the screen,
but they still do not appear next to the cursor.

All text offset problems with the HUD texts on the other hand are fixed
now.

The Credits menu item is also still affected by this bug.

> Great job for addressing the root of the issue :)

Thanks.

Vale,
Quintus

-- 
Blog: http://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by datahead8888** [comment]
@Quintus, tooltips do not show up in the options menu when you mouse over items.  Could this be related to your issue, or do you think it is a brand new issue?

**Comment by Quintus** [comment]
Tooltips not shown is something different, but you are right. Actually, no tooltips are shown anywhere. This ticket specifically deals with items originally *not* drawn with CEGUI, but with raw SFML. The tooltips have always been governed by CEGUI, so they cannot be affected by this ticket's problem at all.

The last item drawn with raw SFML in TSC is the "Credits" menu item on the main menu as far as I can see. Everything else is a different problem. Look for `Prepare_SFML_Text()` calls in the code, which is the origin of this bug.

Vale,
Quintus

**Comment by Quintus** [comment]
I found more places affected.

* Load savegame menu
* Save savegame menu
* "Back" button in credits menu

I.e., everywhere text is drawn directly with SFML instead with CEGUI. This means fixing this will take a little longer than expected. The Credits menu item is now fixed with my most recent commit.

Vale,
Quintus
