### ISSUE TITLE
Unable to create items in the overworld editor

### ISSUE THREAD

**Issue by sauer2** [Secretchronicles/TSC#555]
Neither clicking at nor dragging the labels or images seems to have any effect.

**Comment by datahead8888** [comment]
It might be a good idea to put out a call for level editor testers to try to find any other bugs in the level editor (in addition to a call for testing the main game menus).

**Comment by datahead8888** [comment]
I seem to have found the cause of this issue.

At these lines, it is only programmed to make icon clicking work for level editing.  Logic is missing for the world editor.  This code is called both by the world and level editors:
https://github.com/Secretchronicles/TSC/blob/c949de7346e87839e2b9b679e57344b465c88f92/tsc/src/core/editor/editor.cpp#L1218-L1219

It would need an if statement to detect whether the editing mode is in level editing or world editing and accordingly set up the sprite managers for this.

I should have a fix soon for this.

Once we fix this and any other major world editing blockers, we can make a list of levels we want to package in a new world and ask sauer2 if he would still be able to put them together.

On another note, it's terrible that there are not "New" and "Edit" buttons on the start up menu for world editing, and the world editor itself needs a "Save As" option.  Version 2.1 would be a great opportunity to clean this up; I think we filed tickets for this a while back.
