### ISSUE TITLE
Full Screen Issues...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#557]
I have found that if I use full screen mode, I see a subwindow within a larger white window.
Also, when this happens, mouse clicks usually fail for the menus, though this is probably due to the incorrect sizing.
I am running Ubuntu 14.04.4 LTS.

![messedupfullscreen](https://cloud.githubusercontent.com/assets/6478551/17385927/85ebc5c2-59ab-11e6-956a-f555887dd0cd.png)

**Comment by datahead8888** [comment]
This seems similar to ticket #331.

**Comment by Quintus** [comment]
I cannot reproduce this.

**Comment by datahead8888** [comment]
My code is slightly out of date, but I can still reproduce this issue.

**Comment by Quintus** [comment]
On Sat, Jan 21, 2017 at 03:33:30PM -0800, Chris Jacobsen wrote:
> My code is slightly out of date, but I can still reproduce this issue.

Could you post a step-by-step guide on how to create this effect?

Vale,
Quintus

-- 
Blog: http://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by datahead8888** [comment]
* Start the game
* Go to Options -> Video
* I had resolution 1024x768 (default after using the reset option on a previous game execution) when I first came into this screen.  Full screen was turned off.
* I set full screen to on.
* I clicked Apply
* I then saw a smaller game screen surrounded by a white area, and mouse clicking for menu options was off.  The second time I reproduced this, mouse clicking for options was not off.

I have now tested this with the most recent code.

**Comment by datahead8888** [comment]
I did a little debugging to see what I found.
I did not find any discrepancy between the width/height used for SFML window creation and for setup of the OpenGL viewport.  However, I did notice this line displayed a warning:

https://github.com/Secretchronicles/TSC/blob/cff128326bcc7744a01254477edbe2020cae1692/tsc/src/video/video.cpp#L195

It prints this warning message:
> Failed to set new screen configuration

That warning message is cited in the discussion this SFML bug that was fixed:
https://github.com/SFML/SFML/issues/921

They fixed their bug in this commit:
https://github.com/SFML/SFML/commit/81fdc96c135ecb54def973ed42deeb3af3d4f5c1

Whether an upgrade would fix it is an interesting question.  I'm using version 2.3.2 right now (/usr/local/lib).

Apparently SFML 2.4 is out now.  If that version turns out to fix this, we might think about what version we recommend using.

@xet7, does the full screen mode work for you now?

**Comment by kirbyfan64** [comment]
@datahead8888 Did the upgrade fix the issue?

**Comment by datahead8888** [comment]
I haven't tried an upgrade as of yet.

It might be worthwhile to attempt to reproduce the problem in a minimally complete working example.

The problem definitely should be researched - it happens very consistently for me, and I seem to remember xet7 having the issue at one point.

**Comment by datahead8888** [comment]
Self assigning for now, but this will probably move slowly.  I need to finish that PR merge first, too.

**Comment by datahead8888** [comment]
I wish I had time to work on this, but I have a lot of other things going on I need to focus on.
If anyone has questions on how to reproduce this, I can try to assist as possible.
I do consistently see the bug in my current build and remember @xet7 getting the bug a while back.  I assume we'd at least want to be sure it's not likely to impact users if they build with the most recent version of SFML.

**Comment by kirbyfan64** [comment]
I'm curious on how reproduce the bug, considering I've previously run TSC under Ubuntu 14.04 and never encountered this...

**Comment by xet7** [comment]
My testing was long time ago, TSC frameworks have changed since. I'll test how this works in current version.

**Comment by xet7** [comment]
Full screen works for me on Ubuntu 17.10 installed from daily iso.
