### ISSUE TITLE
Sound Becomes Disabled After Turning Music Off then On

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#564]
Steps to reproduce:
- Enter level 1 of world 1
- Make sure the sound is on and has full volume
- Turn the music off then on
- Play through the level.  You will find that there is no sound.

**Comment by datahead8888** [comment]
This will need to be retested after PR #563 is merged.

**Comment by datahead8888** [comment]
I just retested this, and it is still an issue.

**Comment by kirbyfan64** [comment]
Huh, I could've sworn that fixed it... Probably didn't reproduce the test case correctly...

**Comment by datahead8888** [comment]
I just tested this and found it to work.
