### ISSUE TITLE
Saving causes short pauses

### ISSUE THREAD

**Issue by default0** [Secretchronicles/TSC#566]
I found that when editing even relatively small levels (few hundred kb of file-size) hitting Ctrl+S to save takes something like 500ms up to 2s (Intel Xeon 3.4GHz, saving to an SSD).
It's a bit annoying to have the game "hiccup" everytime you save.

Without having run the numbers or checked anything, it might be worthwhile to hand a snapshot-copy of the level off to a worker thread that then does all the xml generation and file I/O in the background so as a user the save feels "instant" (naturally care must be taking against spamming Ctrl+S etc). Either that, or maybe show some quick save-progress-bar while it does its work.

**Comment by Quintus** [comment]
Which version of TSC are you running? If compiled from `devel`, please give the commit ID.

**Comment by default0** [comment]
The Release 2.0 available through the homepage. I didn't build a recent version.

**Comment by Quintus** [comment]
Not necessaryly. We'll see how it manifests with the upcoming 2.1.0 :-)

Thanks for reporting anyway.

**Comment by Quintus** [comment]
Doesn't appear to be still a problem in `devel`.
