### ISSUE TITLE
No Repeated Input on Key hold

### ISSUE THREAD

**Issue by default0** [Secretchronicles/TSC#567]
In any textbox, if I hold down a key, I would normally expect the held input to be repeated quickly after a short delay.
This does not work in textboxes of TSC.
It makes deleting parts of a longer line with backspace in the script editor awkward and it makes navigation using the arrow keys on the keyboard more awkward.

**Comment by Quintus** [comment]
I know this problem and can confirm it exists. Actually this should be handled by CEGUI automatically; we'll have to check why it doesn't do that.

Vale,
Quintus

**Comment by datahead8888** [comment]
I think this was seen before the Cegui upgrade - #158.
I agree that is would make sense to do in version 2.1, though I suspect this should be marked as a feature rather than a bug.  We also only keep one of these two tickets open.

**Comment by Quintus** [comment]
Oops. You are right, this is a dup.
