### ISSUE TITLE
Page up/down key functionality in level editor

### ISSUE THREAD

**Issue by ghost** [Secretchronicles/TSC#568]
Apparently, Pos1 and End are currently used to go to the player start and first level exit.

Page up/down keys have no function at the moment.

A possible use can be to go to the top/bottom of a level and - in combination with the shift key to go to the left/right.
Other suggestions?

Also, is it possible to extend the End key functionality to toggle to all exits?

**Comment by Quintus** [comment]
I've implemented this now. As a slight deviance from the original suggestion, PageUp/PageDown move to the left/right level edges; hold Shift to move to the top/bottom edges. It is most probably more likely people want to the left and right level edges than to the top and bottom ones, so this should be more accessible.

I've also implemented the End key cycling through all level exits.
