### ISSUE TITLE
joy_axis_threshold preferences XML value read incorrectly - Can Freeze Game...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#573]
Steps to Reproduce:
* Run the game, built from devel
* Turn off both sound and music in the options menu
* Quit the game with the "Quit" option in the the main menu from the title screen
* Start the game (and notice the theme music playing)
* Look in the options menu - both sound and music are turned on again

Can anyone else reproduce this?

--Update: The above test is invalid, as I had an rm statement in my shell script used to invoke TSC, but 4 posts down I describe an issue in preferences loading and the joy_axis_threshold preferences value

**Comment by datahead8888** [comment]
Actually, it does not save any preferences for me it all.  It is not just music and sound settings.

**Comment by datahead8888** [comment]
My preferences in /home/datahead/.config/tsc/config.xml save; they do not seem to load correctly however when I start the game again.

**Comment by Quintus** [comment]
I cannot reproduce. Maybe try removing your config.xml and then try again?

Vale,
Quintus

**Comment by sydneyjd** [comment]
I cannot successfully reproduce this either, on any of the settings i changed.

-Sydney

**Comment by datahead8888** [comment]
It turns out I had an rm statement for the config file in the shell script I use to invoke TSC....HOWEVER...

After removing this rm statement, I found that running the game with the preferences config file present froze the menu start up screen.

It was getting stuck in this loop:
https://github.com/Secretchronicles/TSC/blob/50a7482edd39b4b4eca61c1f0c496e5e1e9156f8/tsc/src/core/main.cpp#L525-L533

After some debugging, I finally tracked it down to this section of code in the preferences loading.  It is reading the joy_axis_threshold XML value as an int, when it should be a float for SFML:
https://github.com/Secretchronicles/TSC/blob/50a7482edd39b4b4eca61c1f0c496e5e1e9156f8/tsc/src/user/preferences_loader.cpp#L307-L311

I have coded a preliminary fix locally.  I should be able to commit it later when I get some more time.

It seems very unusual that it could get stuck waiting on an lost focus event because of a joystick threshold value.  I guess we could try to create a minimally working example for the SFML team to look at, though I may not get to it for a bit.

With this fixed, I will no longer be blocked in coding and testing the removal of the analog joystick preference as part of the analog joystick removal work.

**Comment by datahead8888** [comment]
Typo - should have been analog jump removal - fixed above

**Comment by Quintus** [comment]
> It seems very unusual that it could get stuck waiting on an lost focus event because of a joystick threshold value. I guess we could try to create a minimally working example for the SFML team to look at, though I may not get to it for a bit.

This is probably not a problem with SFML. TSC explicitely subscribes to the focus/unfocus events to halt the game loop while the window is not active. It does this by creating a mini event loop that does nothing else than looking for the GainedFocus event after the LostFocus event was received: https://github.com/Secretchronicles/TSC/blob/70b14a24cbf0086f8a8e2bc01b860404791d149f/tsc/src/core/main.cpp#L517-L540

Vale,
Quintus

**Comment by datahead8888** [comment]
> This is probably not a problem with SFML. TSC explicitely subscribes to the focus/unfocus events to halt the game loop while the window is not active. It does this by creating a mini event loop that does nothing else than looking for the GainedFocus event after the LostFocus event was received:

Fixing the joystick reading code made the game quit freezing for me.  If it's not an SFML/Cegui bug, we probably have another bug in our TSC code.  Something had to have caused this; somehow focus was permanently lost.
