### ISSUE TITLE
Automatic Core Dump Generation

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#575]
As best as I can tell, TSC does not seem to generate core dumps automatically when it crashes with something like a seg fault.  Can we configure it to geneate these automatically?  It would be very useful for tracking down causes of crashes.

A core dump can be loaded in gdb with:
~~~~~~~~~~~~~~~~~~~c++
gdb -c coreFileName pathToExecutable
~~~~~~~~~~~~~~~~~~~~~~

General Info: https://en.wikipedia.org/wiki/Core_dump

**Comment by kirbyfan64** [comment]
IIRC an app can't create a core dump; you just have to run `ulimit -c unlimited` before running TSC.

**Comment by Quintus** [comment]
> IIRC an app can't create a core dump

This is correct. Core dumping is a facility of the operating system; some have it enabled by default, others disable it by default. This even varies between Linux distributions.
