### ISSUE TITLE
All Tooltips No Longer Display...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#577]
Tooltips no longer display in menus when items are moused over.  See the discussion in #551 for additional info on this:

> Tooltips not shown is something different, but you are right. Actually, no tooltips are shown anywhere. This ticket specifically deals with items originally not drawn with CEGUI, but with raw SFML. The tooltips have always been governed by CEGUI, so they cannot be affected by this ticket's problem at all.

> The last item drawn with raw SFML in TSC is the "Credits" menu item on the main menu as far as I can see. Everything else is a different problem. Look for Prepare_SFML_Text() calls in the code, which is the origin of this bug.

**Comment by Quintus** [comment]
Came over a CEGUI documentation error while working on this. Reported: https://bitbucket.org/cegui/cegui/issues/1145/broken-reference-in-tooltip-class
