### ISSUE TITLE
Incorrect Music Track Played After Invincibility...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#580]
Steps to reproduce:
* Play a level individually from the level tab.  Choose one with a lemon power up.
* Grab a lemon power up in the level.
* Wait for the invincibility music to finish.  It will then start playing the title theme music, rather than the level music.

**Comment by Quintus** [comment]
The title theme music is kind of a fallback music. Whenever a music file is not found by the audio system, it will play the title music. That might be the reason why it's specifically _that_ music that gets played.

Vale,
Quintus

**Comment by kirbyfan64** [comment]
@datahead8888 Could you mention a level? I've literally been grepping for the words "lemon", "star", "invin", and "powerup" for 30 minutes, and I can't find a thing. :(

**Comment by kirbyfan64** [comment]
Also, the fix for #574 *might* have also fixed this.

**Comment by datahead8888** [comment]
I usually just use the level editor (F8) and place a box with a lemon in it in a level to test this.  I'm not in Linux at the moment, but I could check later if you need an existing level in TSC.

**Comment by datahead8888** [comment]
Sorry to be the bearer of bad news, but it still seems to be broken for this ticket.
The level I used to reproduce this issue is desert_break_in.  This level can be played from the "Level" tab in the game; it's not currently part of a campaign.  You will find the star about a third into the level if you jump up the platforms toward an upper ledge.  If you have trouble finding it, just hunt around with god mode turned on or peek in the level editor.
