### ISSUE TITLE
Analog Jump Broken...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#581]
Turning analog jump on in the options menu, then pressing up on an analog joystick while in a level, does not make Alex jump.

This doesn't appear to work in version 2.0, either, which probably says a lot about how many people are using this feature...

**Comment by datahead8888** [comment]
I have a tentative solution started for this.  The original issue was that the jump processing code that checks for analog upward presses was never called in the first place when up is pressed.

If analog jump is turned on in a level and if up is pressed on the analog stick, I am wanting it to:
* If Alex is not touching a climbable surface, he will jump
* If Alex is touching a climbable surface:
    * If he is not already climbing, he will start climbing
    * If he is already climbing:
        * If he is not at the top, he will climb upwards without jumping
        * If he is at the top:
            * If he has been continually holding up on the analog stick, he will just stay at the top until he releases and presses it again
            * If this is a new "press" of the analog joystick upwards, he will jump

Not dealing with these situations seems to make it a little unpredictable whether Alex will jump or climb when touching a climbable object (I found different behavior climbing while standing on the ground or trying to climb during a jump before).

Related: #570 

Furthermore, analog jumping will not be applied for the directional pad.  It will only be used for the analog stick.

**Comment by datahead8888** [comment]
I'm currently thinking the analog jump option should just be removed:
* It was broken in version 2.0 already and is not a break due to the SFML/Cegui ports.  The code that does the checks wasn't even invoked through the proper type of input.
* No one noticed that is was broken for multiple years.  It may not even have worked in older SMC versions.
* In our last IRC discussion, no one seemed interested in using it.  I am one of the developers who uses game pads the most frequently, and I use buttons for jumping.  I find the analog jump difficult to use in Super Smash Brothers Melee, and that game doesn't even have climbing.
* It is not easy to address the question of whether the player should climb up objects or jump with analog jump in a consistent manner
* The code solution to make analog jump will be a bit qwirky, both due to the way the joystick architecture is written and the fact that analog jump requires one axis while everything else works with two axes (analog joystick and directional pad).

It's not impossible I could be convinced to give this a try and discuss it again, but for now, I am just going to remove it.  There are other features I would rather focus on than this.

**Comment by Quintus** [comment]
Yes, remove it. It is such a niche feature causing so much confusion that it is not worth it.

Vale,
Quintus

**Comment by Quintus** [comment]
Oh, if you close this, please mark it was WONTFIX so the state is clear from the labels.

**Comment by datahead8888** [comment]
> please mark it was WONTFIX so the state is clear from the labels

Whenever I see "WONTFIX" I assume no action was taken in source control.  If we remove the broken feature, that really"is" the fix, so I don't think "WONTFIX" would be appropriate.

**Comment by datahead8888** [comment]
If the state is still not clear, I think we should just update the issue's title.
