### ISSUE TITLE
Raspberry Pi + RetroArch support

### ISSUE THREAD

**Issue by enderandrew** [Secretchronicles/TSC#582]
Can we get a Raspberry Pi port, ideally with RetroArch support so that this can be played on a RetroPie with controller mapping?

http://www.libretro.com/index.php/retroarch-2/

**Comment by Quintus** [comment]
TSC runs everywhere you can run Linux on. Compile it for your hardware of choice and enjoy it. If your box can run Linux, then it can run TSC. It is a totally different question whether your box has powerful enough hardware to run TSC, but that's something we cannot change.

TSC has gamepad support, and with datahead's recent changes it should even work properly again.

Vale,
Quintus

**Comment by enderandrew** [comment]
Not all apps compile on ARM processors without changes/tweaks. I wasn't sure if that would be an issue here or not. It is a completely different architecture.

Libretro/retroarch support will allow the gamepad to be mapped automatically. You map your controller once for Retroarch and then it applies appropriate mappings to every emulator or game called that supports libretro.

**Comment by Quintus** [comment]
> Not all apps compile on ARM processors without changes/tweaks. I wasn't sure if that would be an issue here or not. It is a completely different architecture.

There should be no problems, as TSC does not contain processor-specific tweaks. I think someone in our IRC channel even successfully ran it on an RPi, but it was unbearably slow.

> Libretro/retroarch support will allow the gamepad to be mapped automatically.

I have not used this before and so cannot be of much help here. If someone provides a patch or PR for supporting it, we'll surely look at it, but I don't think any of the devs has the time to support this given the long list of tickets in our tracker already.

Vale,
Quintus

**Comment by datahead8888** [comment]
> There should be no problems, as TSC does not contain processor-specific tweaks.

We do use legacy OpenGL in Secret Chronicles still - most systems can run this, but I don't know about Raspberry Pi's for certain offhand.  We do plan on getting rid of legacy OpenGL, at least through the rewrite that is planned, though this will take a while.

This article talks about "experimental OpenGL support" on raspberry Pi's: http://www.linuxjournal.com/content/raspberry-pi-gets-opengl-support

> Libretro/retroarch support will allow the gamepad to be mapped automatically.

If I read the site correctly, it sounds like libretro may essentially BECOME our platform, much like Unity is a platform  We're currently leaning towards implementing a lot of engine components ourselves, as the developers code for fun.  We were looking at using C++ and possibly even modern OpenGL for this reason in our planned rewrite.

The website says:

> When you choose to use the libretro API, your program gets turned into a single library file (called a ‘libretro core’). A frontend that supports the libretro API can then load that library file and run the app. 

----Now, if it's possible to have a libretro build and still have our regular native builds, this might be fine if someone has time to code this, but we need to understand this a bit better.

We just spent a lot of time porting the current code to SFML and upgrading Cegui, so we must tread carefully with new API's.

**Comment by Quintus** [comment]
> If I read the site correctly, it sounds like libretro may essentially BECOME our platform, much like Unity is a platform. [...] Now, if it's possible to have a libretro build and still have our regular native builds, this might be fine if someone has time to code this, but we need to understand this a bit better.

Does not look possible to me. I am for rejecting this and closing the ticket.

Valete,
Quintus

**Comment by datahead8888** [comment]
> Does not look possible to me.

I don't think it's feasible, either.

It might be good for someone to try out the game on a raspberry Pi and let us know if they think there's anything we can change that would improve the game for lower performance machines in general.

> I am for rejecting this and closing the ticket.

I agree.
