### ISSUE TITLE
Remove/fix levels not properly working anymore

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#59]
SMC ships with some levels that appearently weren’t designed to work with the current version. Some have 1px off errors, some seem to miss graphics. I’ve not played them all, but those levels that are not properly playable anymore should either be fixed or removed from SMC. For those contained in the official worlds, fixing should be favoured over removal.

Vale,
Quintus

**Comment by datahead8888** [comment]
I've been told world 3 is broken (I started playing through the game again but didn't make it that far yet this time).  We've also talked about going ahead and removing some levels that are either mostly broken or very old / non-interesting.  I think it might make sense to make this a release-2.0.0 task again.

**Comment by Quintus** [comment]
>  I think it might make sense to make this a release-2.0.0 task again.

Grmlmlmgnngmnnnrrrmnlngnl

**Comment by sauer2** [comment]
@datahead8888 Makes sense.
I'll try to play the worlds later.

**Comment by sauer2** [comment]
@datahead8888 
@Quintus 
See: http://forum.secretchronicles.de/topics/177

**Comment by datahead8888** [comment]
As discussed in the forum entry, we will probably remove tower_1.
We should look at others as candidates for removal.

The basic idea is to remove really old (and possibly boring) levels that no one wants to update or levels with other problems.  This will go hand in hand with the new levels we are adding.

**Comment by Luiji** [comment]
@datahead8888 If we store older versions of main game maps, I believe we should only do so if the game world is different enough that we can consider making a full "throwback 1.9" package.

**Comment by datahead8888** [comment]
No, I just meant storing the old levels that were outright removed from TSC.  I did not mean world maps.  As you indicated, those would require a corresponding set of levels, in which case you might as well look into a package.

**Comment by datahead8888** [comment]
We already have the world 3 bug fixed, so this really isn't a release 2.0 critical task anymore.  We probably should remove the milestone label.

Removing levels such as tower_1 is a good-to-do item if we're in agreement but not critical.  This should probably go under a new task, however, since that is not a bug.  I propose we close this one.

**Comment by Quintus** [comment]
Mh, I don’t want to close this yet. There are several levels in the level list that are not in the worlds, and have not been tested. We should have one (or multiple) "play the game day" somewhere in the next weeks where everyone from the team tests X levels whether they are playable. Of course we need to properly define who tests what level. As a team effort, I think we can quickly get through the entire list of non-overworld levels and sort bad ones out.

Vale,
Quintus

**Comment by datahead8888** [comment]
We could always remove all non-campaign levels with the exceptions of ones contributed recently like Mountain Trials and Desert Break In then add them if tested in the next release :P

**Comment by datahead8888** [comment]
When everyone reviews these levels, besides noting problems we find in old levels, we might also note the quality of the level.  Thus a level that is not broken but seems really, really old or that has poor design migth be removed in the release.

**Comment by Quintus** [comment]
@DarkAceZ @brianvanderburg2 @sauer2 and maybe @Luiji, do you think we can build up a list of who tests which levels so that we can have all levels tested before the 2.0.0 release? Yes that’s right, I ask you to do some actual playing in the game :-)

There’s a total of 123 levels in the game, with a number of them being recently added so they don’t need testing (most notably the 7 `quintus_*` (ahem) levels, BowserJr’s revised `mountain_trials`, sauer2’s revised `menu_brown_1` and new `sauer2_15`, which leaves us with 123 - 7 - 1 - 2 = 113 levels that need to be played. We are 5 persons, which amounts to... about 22 levels per person. Ugh. better we had more persons. @ciro589m, @xet7, @sydneyjd do you think you can help in this effort? Then we’d be 8 persons, giving about 14 levels to play for everyone. Maybe I can get aanderse from IRC to join us, then we’d reduce the amount to about 12 levels for everyone.

Is everyone of you fine with this? Please post a short yes if so or no if you don’t want to / can’t participate in this effort. Between all people who posted a positive answer in this ticket I’m going to hand each one about the same number of levels; until the release date, you have to test the levels you got by playing them. You don’t have to discover all the secrets or so, just ensure that the level is finishable and isn’t of such a bad quality that it rather shouldn’t be included in the game.

Vale,
Quintus

**Comment by sauer2** [comment]
@Quintus : yes

I'll post the results and potential fixes at the chessboard, if that is ok.

The release date is fixed or up to discussion on the 21th?

**Comment by Quintus** [comment]
> The release date is fixed or up to discussion on the 21th?

It’s on the discussion schedule for the 21th.

Vale,
Quintus

**Comment by sauer2** [comment]
OK.

In that case I'll have to note that I probably won't be able to test all my levels IF it has to happen in the last week of march. Otherwise, that's fine.

**Comment by Luiji** [comment]
@Quintus I semi-regularly test random levels in the latest Git to check for problems. I'd be willing to do a more rigorous run of a specific level set. :)

**Comment by datahead8888** [comment]
You might be able to give me a few levels at a time to test, but, as I said, I can't make promises on getting anything done right now.

We also might ask for help from @Danfun64 and @georgebr -- they seem to be doing a good job at level testing already :)  We'll need to be clear that the testing has to be in the release-2.0.0 branch for this task, though.

**Comment by Quintus** [comment]
@DarkAceZ Please respond. Can you do level testing?

Vale,
Quintus

**Comment by DarkAceZ** [comment]
Working at it.
Cave_1 segfaults the game on load. There's a warning, but I don't think it's related.

<code>Warning : Object Spika did send Collision but doesn't exists in Manager</code>
<code>Segmentation fault (core dumped)</code>

**Comment by DarkAceZ** [comment]
This might deserve its own issue. If level borders are too small, textbox dialogs get cut off.
![Cut]
(https://dl.dropboxusercontent.com/u/22806246/Screencaps/tsc.png)

The screenshot there shows a textbox with three empty lines at the beginning to combat this issue...

**Comment by brianvanderburg2** [comment]
I've fixed the problem with cave_1 crashes, but before committing to devel had some questions about if the changes tests where correct to preserve compatibility.  I've created a pull request here #393

**Comment by datahead8888** [comment]
@DarkAceZ - can you post your fixes to the star background for the desert_break_in level?

**Comment by DarkAceZ** [comment]
@datahead8888 - I'll be posting all my changes at once in a compressed file.
I'm currently ready for flippa, which might take a while.

**Comment by Quintus** [comment]
@DarkAceZ Please post a list of the levels you want to test or I’ll just assign some to you. I want to prevent duplicate effort so that we can get this through quickly prior to the 2.0.0 final release.

Vale,
Quintus

**Comment by Quintus** [comment]
Also, please test on `release-2.0.0` and **not** on `devel`. `devel` has seen several deep changes already and we don’t want to re-check everything against the release branch.

> These two are not used in any campaign, should we just remove them? Who knows where jungle_castle got to.

Yes. cave_1_2 should be removed then.

> This might deserve its own issue. If level borders are too small, textbox dialogs get cut off.

Yes, that should have its own issue.

Vale,
Quintus

**Comment by DarkAceZ** [comment]
> Please post a list of the levels you want to test or I’ll just assign some to you. I want to prevent duplicate effort so that we can get this through quickly prior to the 2.0.0 final release.

Aside from @sauer2 , I don't see anyone else who's planning on helping, and it looks like he's planning on reviewing his own set, so I could just plan on skipping the sauer_* levels.
Will that work?

Also, should I be adding/changing elements in the levels, or just fixing any glitches?

**Comment by Quintus** [comment]
> Aside from @sauer2 , I don't see anyone else who's planning on helping

Ahm, me?

> Will that work?

So you now test all the `flippa` levels. Good. @sauer2 tests all the `sauer` levels. Good. I will now test these:

~~~~~~~~~~~~~~~~~~~
-rw-r--r-- 1 quintus users   81509 20. Mär 14:12 green_grounds.tsclvl
-rw-r--r-- 1 quintus users  214235 20. Mär 14:12 houses.tsclvl
-rw-r--r-- 1 quintus users  103348 20. Mär 14:12 icy_tower.tsclvl
-rw-r--r-- 1 quintus users  456946 20. Mär 14:12 ita_1.tsclvl
-rw-r--r-- 1 quintus users 1074959 20. Mär 14:12 ita_2.tsclvl
-rw-r--r-- 1 quintus users  168418 20. Mär 14:12 jr_cave.tsclvl
-rw-r--r-- 1 quintus users  192441 20. Mär 14:12 jungle_1.tsclvl
-rw-r--r-- 1 quintus users  312747 20. Mär 14:12 jungle_2.tsclvl
-rw-r--r-- 1 quintus users  393313 20. Mär 14:12 jungle_3.tsclvl
-rw-r--r-- 1 quintus users  188486 20. Mär 14:12 keywest_1.tsclvl
-rw-r--r-- 1 quintus users  176133 20. Mär 14:12 lake_shore_paradise.tsclvl
~~~~~~~~~~~~~~~~~~~

All else are free for anyone to take and test. Just please post you are working on it!

@DarkAceZ @sauer2 Is this ok so far?

Vale,
Quintus

**Comment by Quintus** [comment]
Also, @DarkAceZ, please re-try cave1 on the `release-2.0.0` branch as it shouldn’t crash there but it may still be not playable.

Vale,
Quintus

**Comment by Quintus** [comment]
Results so far:

* green_grounds: good
* houses: great level
* ita_1: great level
* ita_2: good, some Z issues
* jr_cave: Poor level, requires jumping on gees on the mainline. Hard, but nothing else. I think this should be removed.

Vale,
Quintus

**Comment by Quintus** [comment]
* jungle_1: good
* jungle_2: Misses level exit
* jungle_3: Some enemy collision problems (armies being set too near to one another)

Vale,
Quintus

**Comment by Quintus** [comment]
* keywest_1: Works, but I think not of too good quality.
* lake_shore_paradise: Works, nice level, but this is appearently a tutorial. It should either be merged with sauer2’s new tutorial or be removed.

Vale,
Quintus

**Comment by sauer2** [comment]
@DarkAceZ 
@Quintus 

>he's planning on reviewing his own set

I wasn't planning that, but am fine with that as well.

**Comment by sauer2** [comment]
Ok, here a first batch (including bad_evening and icy_tower from my brother):

* bad_evening: gameplay meh, smaller visual issues, wouldn't shed a tear for it
* clear_night: ok, if a bit boring
* desert_ruins: graphical inconsistent (however, it looks plausible, imho), but also a lot of rocket dudes in partly unexpected places, like before invisible bonus boxes, your opinion would be appreciated
* furball_hills: I already fixed that when inserting the scripting.
* houses: already tested by @Quintus as I see it...
* icy_tower: works with me pretty great, both gameplay and features wise
* neverland: good, but somehow the global flying dirt particle effect went missing
* sauer2_1: ok

**Comment by sauer2** [comment]
* sauer2_10: ok
* sauer2_11: ok, but an old-style powerup box, see fix http://forum.secretchronicles.de/topics/224
@Quintus : Please upload!
* sauer2_12: ok
* sauer2_13: ok
* sauer2_13_end: ok
* sauer2_14: ok
* sauer2_15: ok, the new level
* sauer2_2: ok

**Comment by sydneyjd** [comment]
whatsnow: Looks ok, the layout should be improved IMO. Never found finish line, got stuck.
wn_01: Ok,perhaps a tad light on the amount of bad guys. Has unused door at very end that seems awkward if you don't move to next level..
wn_02: door from wn_01 shows up at the begining here. everything looks ok. 
wn_03: Looks ok. The maker seems to favor the background with the eyes. Every level so far has them. May want to change that.
Seems plenty hard when i look from god mode.
wn_03-down: part of wn_03.
wn_04: Decent desert level, decent hardness.
wn_05:Seems ok
wn_05-top: seems ok.
wn_06: ok
wn_06-bottom: Ok.
wn_07: turtle boss.
yuki2000: quite hard IMO. Could use more graphics.
yuki_dungeon: very hard. looks decent..

Hopefully this helps. If not i had fun doing it. :)

**Comment by DarkAceZ** [comment]
@sydneyjd - Actually, that helps quite a bit, thanks.

**Comment by datahead8888** [comment]
@DarkAceZ / @sydneyjd  - I'd be curious if either of you think we should remove tower_1.  sauer2 and I had concluded earlier it should be removed because it's not interesting enough for a level.

**Comment by Quintus** [comment]
> whatsnow: Looks ok, the layout should be improved IMO. Never found finish line, got stuck.

I was able to finish it, but the level misses any decoration. I think it should be removed, unless somebody is willing to work on it.

Vale,
Quintus

**Comment by Quintus** [comment]
> yuki2000: quite hard IMO. Could use more graphics.

Indeed, a bit bare, but beatable.

> yuki_dungeon: very hard. looks decent..

Hm, one the enemies are killed, there’s not much left in this level. I also don’t find it hard, I was able to finish it on the first try.

Vale,
Quintus

**Comment by Quintus** [comment]
>  I'd be curious if either of you think we should remove tower_1. sauer2 and I had concluded earlier it should be removed because it's not interesting enough for a level.

If you don’t like `tower_1`, then you will not like `yuki_dungeon` as well. They follow pretty much the same style. I don’t think it needs to be removed, but if you want, we can do that.

Vale,
Quintus

**Comment by datahead8888** [comment]
> If you don’t like tower_1, then you will not like yuki_dungeon as well. They follow pretty much the same style. I don’t think it needs to be removed, but if you want, we can do that.

If there's disagreement, we should probably talk more before removing it.  Our criteria for removing levels should generally be consistent, too.

@sauer2 - what do you think for tower_1?

**Comment by sauer2** [comment]
>@sauer2 - what do you think for tower_1?

Into the trash it goes.

>Our criteria for removing levels should generally be consistent, too.

Right. Levels shouldn't be made of one block type, with a depressing background and an inconsistent, loveless thrown together set of enemies.

Speaking of inconsistencies: Your opinion about desert_ruins and bad_evening? Fix or purge?

**Comment by Quintus** [comment]
@sauer2 is a bit extreme I think :-).

> bad_evening

I think this should be removed. These pipe constructions are not really nice to look at.

> bad_evening

I think this can be improved, but doesn’t have to be removed.

Vale,
Quintus

**Comment by sauer2** [comment]
@Quintus: Given, you mean desert_ruins in the second quote:
I'm on it.

**Comment by Quintus** [comment]
> Given, you mean desert_ruins in the second quote:

Ooops. Yes, of course.

Vale,
Quintus

**Comment by sauer2** [comment]
OK, here is the rest:

* sauer2_3: really inbalanced, removed rocket dudes, most of the spikeballs and retimed falling platforms
* sauer2_4: ok
* sauer2_5: ok
* sauer2_6: again, removed spikeballs. @Quintus This level relies on vertical rocket dudes and it turns out it still uses the horizontal editor box and a wrong collision box.
* sauer2_7: ok
* sauer2_7_boss: ok
* sauer2_8: ok, but relies on vertical rocket dudes
* sauer2_9: removed rocket dude
* sauer2_nolin: changed old-style powerup
* sauer2_nolin_sub: ok
* under_construction: fixed a missing image warning

@Quintus The fixes are in the same forum thread as sauer2_11. Please upload.

**Comment by Quintus** [comment]
Levels still untested:

* allen_1
* all
* david_1
* dj_kirby_1_sub
* dj_kirby_1
* eatomania
* empty
* flan
* All the `flippa` levels (@DarkAceZ?)
* frosty_climber
* game_tutorial
* The `lvl` levels
* menu_blue_1
* menu_green_1
* night_sky
* old_lvl_1_sub
* old_lvl_1
* pasol_1
* pasol_2
* pasol_3
* runaway
* scaley
* space
* speed_test
* The `stephan` levels
* undergroundsurprise
* underground

Please continue with your work, we’ll get through this :-). I will now take on the levels `allen1` - `flan`.

Valete,
Quintus

**Comment by sauer2** [comment]
I could check these:
>
>   * runaway
>   * scaley
>   * space
>   * speed_test
>   * The |stephan| levels
>   * undergroundsurprise
>   * underground
>

**Comment by DarkAceZ** [comment]
I think desert_ruins is fine. The music fits quite nicely, too (but it's a nice track in general).
dj_kirby needs quite a lot of changes, which I'm working on. I already cleaned up the sublevel.
> I will now take on the levels allen1 - flan.
I've already looked through and edited levels A - D...

**Comment by DarkAceZ** [comment]
`empty` is just that - an empty level, aside from some ground tiles. Could very well be removed.

**Comment by sauer2** [comment]
Results so far:

  * runaway: Boring one-block type level, gameplay not appealing as
    well. Ripe for removal.
  * scaley: Nice & hard, but pretty thrown together enemies, your
    opinion would be appreciated!
  * space: It's a nice concept in theory, but I don't think it is
    actually playable, so I pledge for removal. One might pick up that
    idea another time.
  * speed_test: It's a speed test for armadillos. Can be removed. Test
    levels should probably not be included in releases anyway.
  * undergroundsurprise & underground: Great, although it relies much on
    pipes. Is that a marioism if the count is that high?


stephan levels still pending....

**Comment by datahead8888** [comment]
> undergroundsurprise & underground: Great, although it relies much on pipes. Is that a marioism if the count is that high?

I don't see anything wrong with keeping a level with a lot of pipes.  We will eventually have other pipe replacements.  If the level is good (I can't check now), I'd like to keep it.

**Comment by sauer2** [comment]
>     undergroundsurprise & underground: Great, although it relies much
>     on pipes. Is that a marioism if the count is that high?
>
> I don't see anything wrong with keeping a level with a lot of pipes. 
> We will eventually have other pipe replacements. If the level is good 
> (I can't check now), I'd like to keep it.
>
>
It's good.

stephane_1: OK.

stephan_1-n: Mostly ok, but pretty boring to play. May require some 
visual fixes, not sure if it's worth the effort.

I also noticed some bugs when playing the stephan series:

When getting from stephan_4 to 4.1 while being big, you can get stuck. 
The start point looks ok, though.

Getting from 5.1 to 5.2 somehow disables falling to death.

Also, I get a lot of

Error loading image : /home/clemens/tsc_done/share/tsc/pixmaps
Reason : Unsupported image format

Should I be worried?

**Comment by DarkAceZ** [comment]
https://dl.dropboxusercontent.com/u/22806246/TSC/levels/levels%20A%20-%20D.tar.gz
Levels A thru D.

Might want to consider removing `all` and `empty` from the official level list. They're useless.

**Comment by DarkAceZ** [comment]
Currently, game_tutorial is the level opened when selecting the campaign "Tutorial". I think the level is great, but for someone who has just installed TSC for the first time and fires up that campaign, it might be a little too hard for them...
Didn't @Quintus make a new tutorial level a while back?

**Comment by DarkAceZ** [comment]
`allen_1`: Overly difficult and poorly designed in some areas. Could probably be removed. (I did not fix this one up.

**Comment by DarkAceZ** [comment]
`all` useless, remove
`allen_1` overly difficult and poorly designed in some areas. Could probably be removed.
`bad_evening` OK
`cave_1, cave_1_2` fixed up
`cave_1b` OK
`clear_night` OK
`david_1` fixed up
`desert_break_in` fix some z and other background issues
`dj_kirby_1, dj_kirby_1_sub` fixed up, but `dj_kirby_1` has a slight issue with its script. I've had enemies jump up a slope in one place, but I wasn't able to figure out how to not make moving army shells not jump... :-P So you will have a hopping shell if you throw one there, and it's not unlikely that you will. Maybe someone can help me with this.
`eatomania` fixed up
`empty` useless, remove
`flan` short, but OK
`flippa_2` fixed up
`flippa_3` fixed up
`flippa_3_desert` fixed up
`flippa_3_ending` fixed up
`flippa_3_green` fixed up
`flippa_3_mushroom` fixed up
`flippa_3_sky` OK
`frosty_climber` fixed up
`furball_hills` already done by @sauer2 
`game_tutorial` rather hard for a new player's first level...

Updated pack, levels 'A' through 'F': https://dl.dropboxusercontent.com/u/22806246/TSC/levels/levels%20A%20-%20F.tar.gz


I believe we're about done here, then.

**Comment by datahead8888** [comment]
> Didn't @Quintus make a new tutorial level a while back?

sauer2 made the new tutorial level.  We've been talking about changing the engine so that we can define script events so that falling in lava does not kill Alex.  I think it's better to leave the lava pits as is for now so that we can fix this in a later release without giving up our new tutorial level.

**Comment by datahead8888** [comment]
Something else we might do is double check to make sure all menu levels can be exited in one way or another.

**Comment by georgerbr** [comment]
Please change `maryo` to `alex` in line 229 of `levels/menu_blue_1.tsclvl`, line 1948 of `levels/menu_brown_1.tsclvl`, and line 166 of `levels/menu_green_1.tsclvl`.

**Comment by Quintus** [comment]
My findings of the last untested levels:

* `night_sky`: Playable, though not exciting. Misses decoration.
* `menu_blue_1`: Misses exit, I’ll fix that
* `menu_green_1`: Misses exit, I’ll fix that
* `old_lvl_1`: Broken pipe exit, I’ll fix that
* `lvl_1`: <3 Orrm, I made that myself...
* `lvl_2`: ok
* `lvl_3`: ok
* `lvl_4`: ok
* `lvl_5`: ok
* `lvl_6`: ok
* `lvl_7`: ok
* `lvl_8`: ok
* `lvl_9`: ok
* `lvl_10`: ok
* `pasol_1`: hard, but ok
* `pasol_2`: That’s exactly the right type of level to get @sauer2 up to working temperature :-). I say this should be removed.
* `pasol_3`: ok

And that’s it. I’ll fix what I described above, then we’re done.

Vale,
Quintus

**Comment by Quintus** [comment]
Aaaaaand, hey! We are done. All levels tested. All levels that are now still in the game are not broken and are finishable. They may not all be excitingly great, but they are playable and not outstandingly poor. Improvements to levels are of course always accept anyway, but now I close this issue. :heart:

Valete,
Quintus

**Comment by sauer2** [comment]
@Quintus : What about the bugs described in https://github.com/Secretchronicles/TSC/issues/59#issuecomment-85255837 ?
Are they considered a non-blocker for 2.0.0?

**Comment by Quintus** [comment]
Level improvements can be done anytime, they’re no blocking issues; the important thing was that all levels are finishable.

> Error loading image : /home/clemens/tsc_done/share/tsc/pixmaps Reason : Unsupported image format

Can you point me to a level where that happens so I can take a look at it?

> Getting from 5.1 to 5.2 somehow disables falling to death.

This is an issue on its own... I have seen something similar, but have not yet nailed it down to a reproduction guide that always works.

Vale,
Quintus

**Comment by sauer2** [comment]
>     Error loading image : /home/clemens/tsc_done/share/tsc/pixmaps
>     Reason : Unsupported image format
>
> Can you point me to a level where that happens so I can take a look at it?
>
It's in 5.2. I discovered that when I checked the command line for 
errors regarding the falling issue.

**Comment by Quintus** [comment]
> It's in 5.2. I discovered that when I checked the command line for errors regarding the falling issue.

I don’t get these messages for `stephan_5_2`. Try deleting `~/.cache/tsc` and then try again. Maybe related to the recent commits that moved graphics around.

Vale,
Quintus

**Comment by sauer2** [comment]
>     It's in 5.2. I discovered that when I checked the command line for
>     errors regarding the falling issue.
>
> I don’t get these messages for |stephan_5_2|. Try deleting 
> |~/.cache/tsc| and then try again. Maybe related to the recent commits 
> that moved graphics around.
>
That seems likely, but I can't test it now.
