### ISSUE TITLE
Build error: no matching function for call to ‘CEGUI::SubscriberSlot::SubscriberSlot(void (TSC::cMenu_Main::*)(const CEGUI::EventArgs&), TSC::cMenu_Main*)’

### ISSUE THREAD

**Issue by ckorn** [Secretchronicles/TSC#593]
Hi,

having problems to build the current HEAD fc53f2f0550423aea17b177db5609f5c70725ab0 here.
```
/home/korn/packages/mari0/tsc/tsc-0.0.0+git170114/tsc/src/gui/menu_data.cpp:197:133: error: no matching function for call to ‘CEGUI::SubscriberSlot::SubscriberSlot(void (TSC::cMenu_Main::*)(const CEGUI::EventArgs&), TSC::cMenu_Main*)’
     mp_credits_item->subscribeEvent(CEGUI::Window::EventMouseClick, CEGUI::Event::Subscriber(&cMenu_Main::credits_item_clicked, this));
```

This is the full build log:
https://paste.ubuntuusers.de/423513/

**Comment by Quintus** [comment]
Hmm. While it shouldn't happen, it might be that my version of CEGUI (0.8.7) has this method signature while your version (0.8.4) does not have it. I will have to try building TSC with CEGUI 0.8.4.

Are you trying to package TSC for Ubuntu? If so, thank you very much! Please let us know all problems you encounter during that quest. You might want to take note of @muammar's efforts to package it for Debian: #448.

However, please note that there is a fatal bug in CEGUI <= 0.8.5 that causes corrupted graphics at runtime on systems with a too recent version of glm (which is pretty much any modern Linux distro). Info here:

* Upstream bug: https://bitbucket.org/cegui/cegui/issues/1063
* Backport request on the Ubuntu tracker: https://bugs.launchpad.net/ubuntu/+source/cegui-mk2/+bug/1608114
* Where we found the bug: https://github.com/Secretchronicles/TSC/issues/10#issuecomment-170352262
* A duplicate report, but with a screenshot: https://github.com/Secretchronicles/TSC/issues/572

Vale,
Quintus

**Comment by kirbyfan64** [comment]
Out of curiosity, what happens if you update your CEGUI version?

**Comment by kirbyfan64** [comment]
@Quintus You're right; the void overload [didn't exist in 0.8.4](https://bitbucket.org/cegui/cegui/src/5861231e83355f1230a5d3a8e60a18d8dff3b843/cegui/include/CEGUI/SubscriberSlot.h?at=v0-8-4#SubscriberSlot.h-101).

**Comment by kirbyfan64** [comment]
Looks like it was [added in 0.8.5](https://bitbucket.org/cegui/cegui/diff/cegui/include/CEGUI/SubscriberSlot.h?diff2=0bb3a47a176e&at=v0-8).

**Comment by xet7** [comment]
I have not had problems compiling TSC with Ubuntu 16.10 and newer based distros, where is new enough dependencies. I did not get TSC working with older distros.

**Comment by Quintus** [comment]
Thank you, @kirbyfan64. It appears I accidentally used the `void` signature. While it is convenient, it is not required here. I'm going to commit a fix that changes it to the traditional `bool` so that it can compile with CEGUI 0.8.4 as well (looking forward to the backporting of the glm bug).

Valete,
Quintus

**Comment by Quintus** [comment]
@ckorn Please test whether commit 29bc0c6bad5ff49f055ccc083636f1ee9f72e289 fixes your problem and report back here.

**Comment by ckorn** [comment]
This patch makes it compile and run fine on Ubuntu 16.04. However, I also see the bug you mentioned.
So I will switch to just compile it on Ubuntu 16.10.

This package will be published on the Ubuntu gaming site playdeb.net
Will also have a look at the existing debian directory you mentioned.
Thanks.

**Comment by Quintus** [comment]
Thanks!

**Comment by datahead8888** [comment]
> This package will be published on the Ubuntu gaming site playdeb.net

@ckorn - if you are building from our devel branch, it is still an unstable version.  If you post a build on a site, could you note that it is still a development version so that they do not get the wrong impression about it?

You probably can't post the older version 2.0, either, since it has an oudated Cegui version that causes people problems.  There really aren't other options.

**Comment by ckorn** [comment]
Ok, mentioned the development version here in the G+ post:
https://plus.google.com/+playdeb/posts/QKtUXf7bBqB

Also will publish a new revision which has the word "development version" in the desktop file and the short and long description.

**Comment by datahead8888** [comment]
Thanks, @ckorn.  This will help get the game in front of more people.

We are trying to move away from being a game that is very similar to Super Mario World, but it is going to take more time.  The next step is changing game mechanics.
