### ISSUE TITLE
Rebuild world maps

### ISSUE THREAD

**Issue by Skarfester** [Secretchronicles/TSC#594]
I have just installed the **deb** packages for 2.1.0-dev and I found my contributed graphics there, but no world map is using them.  
I propose to update/rebuild the existing world maps including the new artwork.  
And maybe is a good time to rearrange the levels, if needed, or adding new ones, or even new campaigns. I'll open a new issue for that.

**Comment by datahead8888** [comment]
> I propose to update/rebuild the existing world maps including the new artwork.

I agree.  If you are able to help us with some of the level/world editing, we really could use some level editing help.  The main part of the world editor should be fixed now; let us know if you have any issues with it.

**Comment by Quintus** [comment]
On Mon, Jan 16, 2017 at 06:47:49PM -0800, David F. Fernández wrote:
> I have just installed the **deb** packages for 2.1.0-dev

Just curious: are these the packages published on playdeb.net?

> and I found my contributed graphics there, but no world map is using them.
> I propose to update/rebuild the existing world maps including the new
> artwork.

I agree, but please note that I want to get the multiple exits feature
into 2.1.0 as well, though it will take some time (not below a month
most likely).

> And maybe is a good time to rearrange the levels, if needed, or adding
> new ones, or even new campaigns. I'll open a new issue for that.

New levels would be great.

Vale,
Quintus

-- 
Blog: http://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by Skarfester** [comment]
As per bug #596 I can't rebuild the worlds. Anyway, here's the existing layout:

**world_1**
lvl_1
lvl_2
lvl_3
lvl_4
lvl_5
lvl_6
lvl_7
lvl_8
lvl_9
pasol_3
stephane_1
houses
**world_2**
eatomania
lvl_10
pasol_1
flippa_3
dj_kirby_1
jungle_1
keywest_1
underground
clear_night
**world_3**
wn_01
wn_02
wn_03
wn_04
wn_05
wn_06
mountain_trials
**world_4**
sauer2_1
menu_brown_1
sauer2_2
sauer2_3
sauer2_4
sauer2_5
sauer2_6
sauer2_7
sauer2_7_boss

Note that the worlds have 12, 9, 7 and 9 levels respectively, with a boss at the last level.

**Comment by Quintus** [comment]
Suggestions how to re-arrange things? I'm all in for this, but somebody has to restructure.

**Comment by Quintus** [comment]
No reply from OP, closing.
