### ISSUE TITLE
Adding new levels (and campaigns)

### ISSUE THREAD

**Issue by Skarfester** [Secretchronicles/TSC#595]
I miss some levels in 2.1.0-dev, mostly mine: skarfester01-06, marble_zone and quintus_6.  
I don't know the process for being accepted and added upstream, if there is one.  
With these and/or other unused levels we could add another campaign to give players more options, instead of playing levels individually.

**Comment by datahead8888** [comment]
I think we've generally been posting levels in the forums for review, which can then be added to the game if there is agreement.  How many of the levels should be added to the game is a good question, but it sounds like we need to include some more of your levels.

I have a Desert Fortress Level of my own I intend to submit.  I'll have to try to dig it up; I'd like to get some feedback on it.  It is intended to be played after the Desert Break In level.

It would be a lot of fun at least to add one new world to the game.  Quintus plans on adding alternate exits to the game as well, which may create a need for new levels in all of the worlds.

**Comment by datahead8888** [comment]
Also, be sure to join us in the #secretchronicles chat room on freenode.net from time to time.

**Comment by Quintus** [comment]
I added the skarfester levelset with commit 73bfffb79e3c36b28f38febf617d40e7d58ae471.

**Comment by Quintus** [comment]
Closing, because the level set has already been merged.
