### ISSUE TITLE
Green shells became armadillos at level start

### ISSUE THREAD

**Issue by Skarfester** [Secretchronicles/TSC#599]
When starting a level with green shells in it, they appear green armadillos instead. Also, this armadillos didn't move, like if they are stuck. They can be hitted normally, though.
Red shells work fine.
On 2.0 worked fine.

**Comment by Skarfester** [comment]
You can use the levels on #600 to reproduce this bug.

**Comment by Skarfester** [comment]
I just found out that these armadillos react as a green shell. It doesn't hurt you; if you touch it then a green shell is kicked forward or, if you use the run button, you grab it.
It's like an image mismatch.

**Comment by Quintus** [comment]
I can reproduce this. I'm not exactly sure what causes this, though.
