### ISSUE TITLE
Point labels from levels remain in overworld map

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#605]
If you complete a level and have any point indicators floating on the screen, they will continue displaying in the overworld map and will not go away until you enter a level again.

Steps to reproduce:
* Start the game and proceed to the end of level 1.
* Grab some jewels so that point labels show up.
* Exit the level quickly before the point labels disappear
* You will enter the overworld map.  Notice that the point labels are still present and do not disappear.
* Enter level 2.  The labels will quickly disappear.

Observe the 100 and two 5's (slightly faded) in this picture:

![pointdrawingbug](https://cloud.githubusercontent.com/assets/6478551/22401511/6ca9ad82-e59b-11e6-9b47-c0e2e8425a60.png)

**Comment by datahead8888** [comment]
Update - I added a picture

**Comment by Quintus** [comment]
The overworld map is missing an update of the HUD in general it appears. Open the editor with F8 and hover over some element. You will see that the HUD notice on the element's name never disappears as it should.

**Comment by Quintus** [comment]
(the points shown when you hit an enemy are also drawn via the HUD, which might be a little counterintuitive)
