### ISSUE TITLE
Saving on overworld is broken

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#607]
Saving on an overworld produces a garbage savegame file where worlds are saved multiple times into the XML. Loading the savegame causes access information to be lost.

To reproduce:

1. Start a new game by selecting "World 1"
2. Play 3 levels
3. On the overworld, save the game.
4. Quit TSC
5. Start TSC, load the savegame you just created
6. Observe that only lvl_1 is accessible on the world map of "World 1".

Also, take a look at the generated XML for the savegame. It contains all worlds twice.

Observed on `devel` on 3d9a10ca8a04c59cf2b3d58ae67f1b28ce71fb7c.

Valete,
Quintus

**Comment by kirbyfan64** [comment]
Can this be closed now?

**Comment by Quintus** [comment]
Am 25. Januar 2018 um 23:30 Uhr +0000 schrieb Ryan Gonzalez:
> Can this be closed now?

Did you try to reproduce? Given the commit message of the referenced
commit, it doesn't appear fixed to me.

-- 
Blog: https://mg.guelker.eu
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by kirbyfan64** [comment]
Ahh, thought it was marked as closing this issue; I didn't realize it was just referencing it.

**Comment by Quintus** [comment]
Problem is confirmed to still exist.

**Comment by Quintus** [comment]
Today, I can't reproduce the problem anymore. It might be that the
work on #632 fixed this as well. I'll close this as fixed thus.
