### ISSUE TITLE
I can't find the "Exit" in the control Keyboard list :/

### ISSUE THREAD

**Issue by Moewsaleh** [Secretchronicles/TSC#613]
Hello , 

When i go to Keyboard under control section , i can't find the Exit door to set.

So when i finish the level and arrive to the exit door there is no key work :/ 

why is that

**Comment by kirbyfan64** [comment]
I think you just press the Up key in order to enter doors.

**Comment by kirbyfan64** [comment]
@Moewsaleh Was that all?
