### ISSUE TITLE
AppImages!

### ISSUE THREAD

**Issue by refi64** [Secretchronicles/TSC#614]
I've seen a *lot* of issues here related to dependency hell, e.g. *oh crud, TSC wants CEGUI 0.8.99127, but I have a slightly different version and need to recompile the whole thing from source*.

AppImages have quickly been becoming a stable of Linux GUI applications. The average user won't need to know how to build code; they just run the AppImage, and *BAM* it magically works.

**Comment by sydneyjd** [comment]
I feel that is it not a bad idea for automated builds, or even temporary stable builds. 
It never hurt to have the option, we just have to do it. I'm not sure if it would currently be worth the effort, due to our team size, but that is not up to me.

My 2 cents,
-Sydney

**Comment by kirbyfan64** [comment]
Automated builds are pretty easy with Travis... RPCS3 makes automated AppImage builds.

**Comment by Quintus** [comment]
Couldn't we just provide a build option to link TSC completely
statically? This seams easier to integrate into the existing build
process and has the same result. For Windows, this is done already
anyway.

As such, the idea is not bad, as long as dynamically linked builds are
still possible, because that's what will allow TSC to be included in
distro repositories. Not everyone wants to install software outside
distro repos; Linux is not Windows after all.

-- 
Blog: https://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by datahead8888** [comment]
> I've seen a lot of issues here related to dependency hell, e.g. oh crud, TSC wants CEGUI 0.8.99127, but I have a slightly different version and need to recompile the whole thing from source.

This sort of thing was a bit of a deal breaker (when programming on Windows) for whether or not someone in IRC would develop for TSC recently.  Making TSC easier to build (and able to build on more platforms) would really help bring in more developers.

I see some references online to AppImages being used for Windows.

> Couldn't we just provide a build option to link TSC completely statically?

How much code and/or configuration would it take to add the AppImages setup?  Would it be possible to make AppImages work through an extra commandline option?

Quintus has a valid point, but I also agree with the philosophy of making things as easy as possible for people less comfortable with the command line and/or scripting.  This is one of those things that gets more people using Linux and open source software in general.  Adding the build option Quintus suggested, though, probably should be done either way eventually.

**Comment by kirbyfan64** [comment]
FWIW I've found statically linking stuff on Linux in general to be a can of worms, especially anything that needs to include Mesa/GL libraries (which aren't available statically in many distros).

AppImages are usually built by taking an already-built version of TSC, setting up the source tree, "installing" to a local directory, and then running the build tool on the installed files to package them.

You can see an example here (note this uses a Qt-only deployment script): https://github.com/RPCS3/rpcs3/blob/master/.travis.yml

**Comment by Quintus** [comment]
While I do think that containerisation has inherent security problems
due to non-upgradability of dependencies and effectively proxying all
the security burden onto the issuer of the container (who may become
unavailable), I think the impact this has on a desktop game like TSC is
small. Static linking suffers from the same problem, though not in the
same extent.

I'm just throwing out some thoughts. I'm not against any specific
approach, and don't have the time to think about it much. All I want is
that the decision is made after some consideration and not just "because
possible".

-- 
Blog: https://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by kirbyfan64** [comment]
> All I want is that the decision is made after some consideration and not just "because possible".

I wish people thought this when picking JavaScript frameworks...

FWIW I personally think AppImages would be great for TSC because:

- One file to download. A non-tech-savvy user that somehow ended up with Linux doesn't need to follow obscure directions.
- No dependency hell.
- AppImages can automatically create .desktop files on first launch, so it's almost like an installed program.
- etc.

**Comment by datahead8888** [comment]
> FWIW I personally think AppImages would be great for TSC because

How easy would it be for a programmer to take an AppImages build and start developing with it?  Programmers also like to save time and effort :)  Making things easier might bring more programmers on board, especially if it made Windows builds easier (something we've been weak on).

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

**Comment by xet7** [comment]
How this is different from FlatPak? There's talk about it at:
https://smcv.pseudorandom.co.uk/2017/flatpak_and_debian/

**Comment by kirbyfan64** [comment]
Flatpak still requires an installation of sorts, as well as installing Flatpak itself. AppImages literally just require you to download and run it, almost like a Windows portable exe file.

**Comment by datahead8888** [comment]
Someone recently posted this comment on a video I had made of TSC:

> Thats great. i am no linux dunmmy, but after 3 hours of fighting major dependency problems in ubuntu 16.04LTS,.. I had to give up trying to install it!. this is after pulling hair out and attempting to install all the recomended dependencies. My opinion is that it is just too difficult for the average linux user to get this thing going. I will find a different game to play that is easier to install.﻿

I think making TSC easier to build and install is a great idea :)

In the meantime, I will have to point him to our forum.

Reference:
https://www.youtube.com/watch?v=4FmyN4mJ5ls&lc=z22wdpzrdvnqfv0khacdp434p35xwqbzfzykc2etatlw03c010c

**Comment by PrzemekSkw** [comment]
Finally with my friend we have made working flatpak from windows version:
[https://mega.nz/#F!8GwlXRIY!cRKXA8GTAqeeDeEbs5Ur1A](url)
Just unzip, give permission to all files, then run ./install.sh and ./run.sh.

**Comment by kirbyfan64** [comment]
Status update for AppImages: I have no clue. For some reason, on the built images, SFML is crashing. I'm not sure if this is because of my window manager, or maybe a bug in Wayland...

**Comment by probonopd** [comment]
Can you build on Ubuntu 14.04 and upload the (crashing) AppImage? Then I could have a look at it.

**Comment by kirbyfan64** [comment]
@probonopd [Here you go.](https://upspin.refi64.com/rymg19@gmail.com/pub/tsc-appimage/TSC-2.1.0-dev-387713c245a7b13afab7fff49e243c2836b8b849.glibc2.14-x86_64.AppImage)

**Comment by probonopd** [comment]
It appears to be launching for me on Xubuntu 16.04. Can you describe the steps to reproduce the crash?

There are some files bundled in the AppImage which are known to cause issues and should be removed. You  can do this by:

```
sudo mount TSC-2.1.0-dev-387713c245a7b13afab7fff49e243c2836b8b849.glibc2.14-x86_64.AppImage /mnt/
sudo cp -r /mnt/ TSC
sudo chown -R $USER TSC/
sudo umount /mnt 
cd TSC/
wget https://raw.githubusercontent.com/AppImage/AppImages/master/functions.sh
. functions.sh 
delete_blacklisted 
./AppRun 

# The files deleted are:
# './usr/lib/x86_64-linux-gnu/mesa/libGL.so.1'
# './usr/lib/x86_64-linux-gnu/libdrm.so.2'
# './usr/lib/x86_64-linux-gnu/libxcb.so.1'
# './usr/lib/x86_64-linux-gnu/libX11.so.6'
# './usr/lib/x86_64-linux-gnu/libICE.so.6'
# './usr/lib/x86_64-linux-gnu/libSM.so.6'
# './usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0'
```

Please see if this makes any difference.

**Comment by kirbyfan64** [comment]
@probonopd IT WORKS!! Thanks!!

**Comment by xet7** [comment]
@kirbyfan64 

I tried to run travis.sh on alexandria server. After building, I did not find AppImage file. Where does build script save it? Or does that script only work at travis? Can script be modified to run outside of travis? Where can I download travis builds?

**Comment by pirate486743186** [comment]
consider using openSUSE Build Service for the appimage
https://build.opensuse.org/

It can directly pull from github and the appimages it makes are upgradable with appimageupdate https://github.com/AppImage/AppImageUpdate

**Comment by refi64** [comment]
So some corrections, since this issue was created I've largely moved into the Flatpak camp, since they're a lot easier to maintain (no CentOS 6 or manual update integration), there's a manifest on master.
