### ISSUE TITLE
When will be working on linux?

### ISSUE THREAD

**Issue by PrzemekSkw** [Secretchronicles/TSC#615]
TSC and SMC fails to install on any linux distro because of cegui 0.7. Will be available some fix for that?

**Comment by kirbyfan64** [comment]
The master branch has already been ported to CEGUI 0.8; there just isn't quite a release yet. (FWIW I use it from Linux, and it works fine.)

My *personal* ambition is to make AppImages work, so that in future releases, Linux users will just download and run the AppImage without any trouble.

**Comment by PrzemekSkw** [comment]
Appimage will be great, it will also great if someone will use that master branch in aur repository :) I will wait than. Thanks for answer.
