### ISSUE TITLE
Build fails on wrong comparison

### ISSUE THREAD

**Issue by rffontenelle** [Secretchronicles/TSC#617]
Build fails with `ISO C++ forbids comparison between pointer and integer [-fpermissive]`, as can be seen in the below output:
> libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../../../cegui/include -I../../../../cegui/include -I../../../../cegui/include/XMLParserModules/TinyXMLParser -DCEGUI_STATIC -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -MT libCEGUITinyXMLParser_la-tinyxmlparser.lo -MD -MP -MF .deps/libCEGUITinyXMLParser_la-tinyxmlparser.Tpo -c ceguitinyxml/tinyxmlparser.cpp -o libCEGUITinyXMLParser_la-tinyxmlparser.o
CEGUITinyXMLParser.cpp: In member function 'void CEGUI::TinyXMLDocument::processElement(const CEGUITinyXML::TiXmlElement*)':
CEGUITinyXMLParser.cpp:148:53: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
                 if (childNode->ToText()->Value() != '\0')
                                                     ^~~~
make[7]: *** [Makefile:462: libCEGUITinyXMLParser_la-CEGUITinyXMLParser.lo] Error 1

**Environment:**
Distro: Arch Linux 64-bit
Packages: tsc 2.0.0, gcc 7.2.0

**Files:**
* [tsc-2.0.0-1-x86_64-build.log.txt](https://github.com/Secretchronicles/TSC/files/1324165/tsc-2.0.0-1-x86_64-build.log.txt)
* [tsc-2.0.0-1-x86_64-package.log.txt](https://github.com/Secretchronicles/TSC/files/1324173/tsc-2.0.0-1-x86_64-package.log.txt)

**Comment by Quintus** [comment]
Try compiling the `devel` branch instead of stable 2.0.0. The problem should be fixed there.

**Comment by rffontenelle** [comment]
Sorry for the delayed answer, but I'm having some trouble on building `cegui`. As soon as solve this, I'll continue to try compiling the devel branch and update the info in here.

**Comment by PrzemekSkw** [comment]
@Quintus can You explain how to buil devel branch ? there is no such thing in AUR.

**Comment by rffontenelle** [comment]
@PrzemekSkw, by "`devel` branch" Quintus means a branch named `devel` from TSC's Git repository. This is an equivalent of building a `-git` package in AUR. His idea is to double check if the problem we're having in the 2.0.0 release was already fixed in a non-released version of TSC. But, as I mentioned above, [cegui](https://aur.archlinux.org/packages/cegui/) is a dependency of tsc and is broken in AUR, so that's a blocker.

**Comment by Quintus** [comment]
TSC's CEGUI support has been upgraded in `devel`. While stable 2.0.0 depends on CEGUI <= 0.7.9, the version in `devel` ought to work with any recent release of CEGUI (and even requires CEGUI >= 0.8.5). There is an [INSTALL.md](https://github.com/Secretchronicles/TSC/blob/devel/INSTALL.md) document that describes how to build TSC from `devel`, but it assumes you have CEGUI installed.

TSC does not depend on CEGUI's NullRenderer anymore. I have personally phased this silly dependency out of the codebase. Any normal CEGUI build configuration should suffice.

**Comment by PrzemekSkw** [comment]
@Quintus  Sory but I don't understand, how I can build devel version if it assumes that I have cegui installed? if cegui is broken and I can't install it. I also try with that INSTALL.md and have that error:
`cmake -DCMAKE_INSTALL_PREFIX=/home/lusia/Pobrane/TSC ..
-- Found SFML .. in /usr/include
CMake Error at CMakeLists.txt:120 (find_package):
  By not providing "FindCEGUI.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CEGUI", but
  CMake did not find one.

  Could not find a package configuration file provided by "CEGUI" with any of
  the following names:

    CEGUIConfig.cmake
    cegui-config.cmake

  Add the installation prefix of "CEGUI" to CMAKE_PREFIX_PATH or set
  "CEGUI_DIR" to a directory containing one of the above files.  If "CEGUI"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/lusia/TSC/build/CMakeFiles/CMakeOutput.log".
`

**Comment by Quintus** [comment]
> how I can build devel version if it assumes that I have cegui installed? if cegui is broken and I can't install it.

Yes. You need to fix your CEGUI installation first. And please don't hijack this issue, open a new one for your problem, in which you please also include the output of `git log -n1` in your copy of the TSC repository so I can know what you actually use.

**Comment by PrzemekSkw** [comment]
Thanks for You help, I will fight with that cegui then.

**Comment by rffontenelle** [comment]
@PrzemekSkw: for what is worth, here is the bug report in CEGUI: https://bitbucket.org/cegui/cegui/issues/1153/undeclared-uchar-and-char16_t-types

**Comment by PrzemekSkw** [comment]
@rffontenelle Thank You very much for that, maybe they will fix that :)

**Comment by Quintus** [comment]
Appears to not be relevant anymore. Closing.
