### ISSUE TITLE
TSC 2.1.0 requires a newer version of libboost-filesystem unavailable on Ubuntu 16.04

### ISSUE THREAD

**Issue by WPFilmmaker** [Secretchronicles/TSC#624]
As per title when I try to install TSC 2.1.0+git20160813-1 I get required libboost-filesystem 1.61.0 but Ubuntu 16.04 ships only 11.58.0. Is there any way you can make TSC 2.1.0 support Ubuntu 16.04 as well? It will be supported until 2021 and it would be nice to have TSC running on it.

**Comment by xet7** [comment]
It could be possible to run TSC game itself on Ubuntu 16.04 with upcoming AppImage #614 but actual development requires Ubuntu 16.10 or newer, or other distro with new enough dependencies.

**Comment by WPFilmmaker** [comment]
@xet7 Thanks for the answer! AppImage would be great. I will definitively provide feedbacks once I can run the game :)
