### ISSUE TITLE
installation error : dependency is not satisfiable libboost-filesystem1.61.0

### ISSUE THREAD

**Issue by vikashiiitdm** [Secretchronicles/TSC#625]
i already have compiled boost 1.66 from source. This happens when i am trying to install the .deb file. 
Can you, please, help?

**Comment by Quintus** [comment]
A debian package can only specify dependencies on debian packages. Your
package manager does not know about your installed-from-source boost, so
it says it's not available.

You'll either:

1) need to persuade your package manager to ignore
   dependencies when installing that package (bad idea,
   but probably easiest),

2) install boost as a debian package (best variant), or

3) compile TSC from source (may be complicated). When you do that,
   please compile TSC from the master branch and not release 2.0.0, which
   is out of date so much that it's going to give you problems.

Greetings
Marvin

-- 
Blog: https://mg.guelker.eu
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by Quintus** [comment]
This isn't a bug anyway, it has nothing to do on the tracker. Questions like this should go to the [tsc-users mailinglist](https://lists.secretchronicles.org/hyperkitty/list/tsc-users@lists.secretchronicles.org/).
