### ISSUE TITLE
Title Theme Music

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#628]
Since Jobromedia left us without a clue on the license of his great music work, we now still have no title music.

I just listened again to the awesome music artwork from #222, but that's a character-specific theme music and probably doesn't make for a good title theme. So, here's a task for a new theme playing on the title screen.

Please submit!

**Comment by kirbyfan64** [comment]
Any particular themes you're going for?

**Comment by Quintus** [comment]
Maybe I should have clarified. This ticket is about the music that plays on the title screen, i.e., the "title theme". Maybe that wasn't clear from what I wrote above. The theme could be re-used at certain story-relevant points in the game, though they'll probably often have the theme of the character playing. It may thus happen that the music is actually only listenable to on the title screen.

Regarding the exact musical theme, I'm open for suggestions (which is a nice saying for "I have no idea"). What should be considered is that this is the first thing a new player hears when he opens the game. Currently, the hyper_1.ogg music is played, which is not optimal because for one, hyper_1 doesn't meet our licensing requirements (it's an old GPLed music from SMC), and for the other, it's a pretty generic music that hasn't been created with our story plans in mind. I admit, maybe we should finally resolve the story question (#68) first. I may later today post there.

kirbyfan64, I'm a programmer only, and as Bugsbane once said, programmers are bad at keeping style consistent in anything other than code. I can't but leave it to you as the only active musician in TSC to decide what the musical style of the game should be. See it as creative liberty. Maybe you want to review existing music to see if you can make out some common style among them, or if not, liberally delete unfitting music. There's really no other way to get things to fit one another. Bugsbane has wanted to do the same with the graphics, and I really think that it's a good idea to get consistent.

**Comment by refi64** [comment]
well I forgot about this for a long time but I've had it on my mind for a few weeks now, if I do nothing else over Christmas break I *will* finish this.

**Comment by Quintus** [comment]
Very kind of you, and it is appreciated. Thank you!

**Comment by datahead8888** [comment]
Submission:
https://raw.githubusercontent.com/Secretchronicles/TSC/devel/tsc/data/music/story/theme_2.ogg

**Comment by Quintus** [comment]
Indeed. We simply forgot to close this ticket.
