### ISSUE TITLE
Any new binary releases soon ?

### ISSUE THREAD

**Issue by anselal** [Secretchronicles/TSC#629]
Last precompiled release is 3 years old !!!

**Comment by xet7** [comment]
Latest VirtualBox appliance release is 2017-12-10:
https://secretchronicles.org/en/news/2017/12/10/virtualbox-appliance-available/

AppImage version #614 will be available soon, when I have configured Travis to upload builds to server. AppImage version itself already works.

**Comment by Quintus** [comment]
It's not an easy question as you might think. xet7 has correctly pointed
out that there are some precompiled development snapshots flying around
in various formats, but there is not currently a stable release. The
current "devel" branch contains the upcoming 2.1.0 release, but you'll
need to compile it from source and it isn't ready yet.

2.1.0 already contains a number of grave changes in our dependencies
(CEGUI upgraded, SDL out and SFML in). These changes have introduced a
number of bugs that need fixing, and, you know, we're all just working
in our free time on the game, which basically boils down to a few days
in a year.

Meanwhile, I have started a completely new repository for TSC 3, but
that won't be ready before 2.1.0 most likely. The old TSC2 codebase was
inherited from SMC, and it is horrible enough to warrant this decision.

What I want to say is that TSC is very well alive. A team of about 3
people is actively working on it, but the size of the game in relation
to the available amount of free time prevents any kind of fast
releases.

It is kirbyfan who manages the 2.1.0 development process, so any
definite statement needs to come from him. If I may give my unqualified
opinion, I wouldn't expect a 2.1.0 release before this year's Christmas.
If you want to help accelerate the process, we're always eagerly looking
for new contributors.

-- 
Blog: https://mg.guelker.eu
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by Quintus** [comment]
General discussion on TSC does not belong onto the tracker. Development-related general discussion should go to the [tsc-devel](https://lists.secretchronicles.org/hyperkitty/list/tsc-devel@lists.secretchronicles.org/) mailinglist.
