### ISSUE TITLE
I build an packages for Ubuntu 18.04 :) 

### ISSUE THREAD

**Issue by boospy** [Secretchronicles/TSC#637]
Hello all, 

and thanks for the really nice game. For easy installation i build a packages for Ubuntu 18.04. It can easy installed from us [Repository](https://apt.iteas.at/):

```
apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 2FAB19E7CCB7F415
echo "deb https://apt.iteas.at/iteas bionic main" > /etc/apt/sources.list.d/iteas.list
apt update
apt install tsc
```
Have Fun! :+1:

**Comment by boospy** [comment]
Yes, with some notifications cmake works.

**Comment by xet7** [comment]
@boospy 

What commands did you run to build package?

**Comment by boospy** [comment]
```
git submodule init
git submodule update
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=~/tsc ..
make -j40
make install 
```

**Comment by xet7** [comment]
@boospy 

AFAIK those commands only build and install TSC.

How did you build .deb package? With what commands?

**Comment by boospy** [comment]
> How did you build .deb package? With what commands?

Nothing... i'am not a developer. After make install i copy all the content in  my packagebuilddirectory and build the package manually with dpkg.

**Comment by xet7** [comment]
@boospy 

How do you build it manually? What you copy where? What is the directory structure? And dpkg commands?

**Comment by boospy** [comment]
Install the package and you see the structure. 

> dpkg -b tsc-paketbau /mnt/Downloads/tsc_2.1.0+git20180909-1alpha_amd64.deb

**Comment by Quintus** [comment]
It surely looks nice. I don't have the time to look at it in detail
right now, but be sure that it is appreciated. Did you take advantage of
the work in the abandoned PR #448?

Which TSC branch is your package based on?

-- 
Blog: https://mg.guelker.eu
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by boospy** [comment]
This is the actually devbranche here from git. 2.1dev. Thanks for #448 maybe with this infos it is easier to build packages in the future.

**Comment by Quintus** [comment]
Hi,

so, now I have a little more time than yesterday. This looks
promising. @xet7, would you mind to test if the package properly works
on a clean 18.04 system (e.g. by testing via a VM)?

@boospy, we currently have the problem that we have no people who build
this kind of packages for Linux distributions. Do you think you could
follow TSC development and keep building packages as the development
progresses? If so, we should move your APT repository over to
secretchronicles.org and officially endorse it as a means to get a
current copy of TSC. We can surely arrange it to give you the required
access to alexandria (our server).

Marvin

-- 
Blog: https://mg.guelker.eu
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by boospy** [comment]
Hi, 

i've tested the package on an Xubuntu 18.04 plain installation on KVM-Spice. The Game is working fine. 
I can help to build packages for Ubuntu's, because we need the packages in our customers schools too ;) 
I can not promise how much time I will have for this, but I will do my best.

If future bugs with the packages exists someone must tag me here on git. Or is #448 farther the right place?

Mario

**Comment by Quintus** [comment]
Am 16. September 2018 um 11:40 Uhr -0700 schrieb Mario Loderer:
> I can help to build packages for Ubuntu's, because we need the packages in our customers schools too ;) 
> I can not promise how much time I will have for this, but I will do my
> best.

That's what we're all doing here. Everyone of us here considers TSC as a
free-time project, which naturally means that there's only a limited
slot of time available.

The only request I have is that if you decide to permanently cease
creation of the packages, you should *please* notify us of that.

> If future bugs with the packages exists someone must tag me here on
> git. Or is #448 farther the right place?

Please don't write anything to #448, because that PR is closed and
should not be hijacked. For anything that is not related to TSC's code
we have a mailing list/web forum available which you should consider
subscribing to. The mailing list and forum are mirrored, so you can use
whatever you prefer.

* Mailing list: https://lists.secretchronicles.org/postorius/lists/tsc-devel.lists.secretchronicles.org/
* Web forum: https://lists.secretchronicles.org/hyperkitty/list/tsc-devel@lists.secretchronicles.org/

The mailing list is quite low traffic and has the advantage of
delivering any relevant discussions directly to your mail inbox.

Finally, if you like the game and like to have occasional chats on it,
feel free to join our IRC channel #secretchronicles on
chat.freenode.net. Someone from the team usually hangs around there.

As for the GitHub tracker, I'll need to discuss with the rest of the TSC
team. We can add you to the Secretchronicles GitHub organisation (and by
extension, to the TSC team), which would make it possible to assign
tickets to you on the tracker in case someone reports them. It would
also better reflect the access to something below the
secretchronicles.org domain.

Marvin

-- 
Blog: https://mg.guelker.eu
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by Quintus** [comment]
Please apologise that we're a little slow. It appears that nobody is opposed to incorporating your efforts into our infrastructure. Please subscribe to our mailinglist and discuss the details of building packages with @sydneyjd. He'll grant you the required access or set up the programs that you need. You will also receive an invitation to our GitHub organisation.

**Comment by Quintus** [comment]
@sydneyjd @boospy So, what's the state of this?

**Comment by sydneyjd** [comment]
@boospy Hey! 
When you get time to build new packages,please feel free to contact me and I will help you set them up and host them officially on Alexandria(Our Server). We would appreciate being able to host them, and will officially endorse them if we migrate the APT repository's for the packages to Alexandria. Let me know if I am able to help you in any way.

-Sydney

**Comment by Quintus** [comment]
@boospy @sydneyjd  Status of this? I want to get the package onto the website quickly.

**Comment by boospy** [comment]
I will build new packages this week.

**Comment by boospy** [comment]
I've build one new package. Same process like the last package. But i can't start the game. Very strange path is there. 
```
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::status: Permission denied: "/root/tsc/share/tsc/packages"
zsh: abort      tsc
```

**Comment by kirbyfan64** [comment]
@boospy Check your CMAKE_INSTALL_PREFIX setting.

**Comment by boospy** [comment]
No it works. New packages on https://apt.iteas.at available. 
@sydneyjd  feel free to contact me for migrate the package on your Alexandria too.

**Comment by sydneyjd** [comment]
Thanks Boospy, the package looks and works great! Now we just have to get this pull request merged and it will be publicly listed and hosted on the Secretchronicles server. https://github.com/Secretchronicles/main-website/pull/33
We would appreciate it if you would possibly consider maintaining this package for Ubuntu for a decent length of time, and if you are able to do so we may create a custom apt repository just for the game. Please keep us posted on what you plan to do. Thanks so much!

**Comment by boospy** [comment]
Yes i maintaining this package for Ubuntu for a longer time (only for LTS), because we use TSC @our Customers in schools for the children. They love the game. :)

**Comment by Quintus** [comment]
Quite interesting use of TSC. We are always glad to hear it's being used! And thank you for offering maintenance of the .deb package. LTS only is absolutely okay.

As you're appearently an active user of the game, let me point out that TSC is in need of new levels for the upcoming 2.1.0 release. As of now, the level set between 2.0.0 and 2.1.0 is not exactly different. I think I can speak for the entire TSC team when I say that it would be very nice if you took the time to read through [the most recent story proposal](https://github.com/Secretchronicles/documents/raw/master/gd/documents/pdf/18-001.pdf) and try building one or two of the possible levels mentioned in that proposal. Give the current state of the project, I don't expect any major changes to the story described in that proposal, though you're of course welcome to provide input on the story question. It would be very nice if you could hang around in our IRC channel `#secretchronicles` on chat.freenode.net on a more or less regular base (given you're already a TSC team member anyway).

Once enough levels for the new story have been crafted, I expect them to take over the primary campaign from the current one, which is effectively just a random collection of levels we as devs found nice at some point in time. They have no storyline leading through them.

**Comment by pirate486743186** [comment]
consider using openSUSE Build Service
https://build.opensuse.org/

it will be a normal repo.
their system can build for other distros too and appimages.
it can pull code directly from github.

**Comment by Quintus** [comment]
@pirate486743186 Please don't hijack threads with only tangentially related suggestions. It looks like you want to make a more generic suggestion as you already posted that in #614. Please create a new ticket for the topic.

**Comment by Quintus** [comment]
On the topic of this thread, the Ubuntu package has already been [pushed to the website](https://secretchronicles.org/en/news/2019/03/10/Ubuntu-18/). @boospy you might want to close the ticket as resolved. For uploading new packages, it's probably sufficient if you ping sydney, refi, or me.
