### ISSUE TITLE
Service Announcement: Server outage

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#649]
Hi everyone,

since yesterday our sponsored project server, alexandria.secretchronicles.org, is down. We are in contact with our server sponsor to resolve the problem, but as of now, this means:

* The mailinglist is dysfunctional
* The website secretchronicles.org is unavailable
* The IRC chatlogs are down
* The IRC bot `furbot` is unavailable

This ticket is to make everybody aware as it's not possible currently to announce this via the usual means (mailinglist). The most recent developments can be followed in our IRC channel `#secretchronicles` on `chat.freenode.net`. As no chatlogs are available as of now, you need to join the channel.

@sydneyjd is working on the backups, @xet7 and me are busy with getting the server back up and running. I will close this ticket once things return to normal.

I'm sorry and apologise for the inconvenience.

--quintus

/cc @datahead8888 @kirbyfan64 @boospy

**Comment by kirbyfan64** [comment]
Do we know what happened yet?

**Comment by datahead8888** [comment]
If it turns out to be a downage issue, we might ask if we're on any support email lists.

**Comment by Quintus** [comment]
We're working with our server sponsor to get things resolved. First-Root
has offered to upgrade us to a KVM server meanwhile.

-- 
Blog: https://mg.guelker.eu

**Comment by Quintus** [comment]
We have moved to a server provided by the Wekan project now. All services are up again.
