### ISSUE TITLE
[minor] rename levels, to appear in order

### ISSUE THREAD

**Issue by pirate486743186** [Secretchronicles/TSC#651]
in dev mode, rename the levels, so that the alphanumeric order corresponds to the real order. For example instead of lvl_1, lvl_10, lvl_2

**Comment by Quintus** [comment]
This can cause compatibility problems. If a user created levels with exits to such levels or worlds using them, they would break on the rename.

**Comment by pirate486743186** [comment]
Well.... you are right.... :D
