### ISSUE TITLE
New Version of DEB-Packages for 18.04 now installable

### ISSUE THREAD

**Issue by boospy** [Secretchronicles/TSC#664]
Hello all, 

i build an actual version of TSC: 2.1.0+git20191015-alpha4 Commit: 0b1f261e

https://apt.iteas.at

Best Regards :)

**Comment by Quintus** [comment]
Thanks! We shall upload it to the server.

cc @sydneyjd

-- 
Blog: https://mg.guelker.eu

**Comment by sydneyjd** [comment]
Done, just need to check and merge https://github.com/Secretchronicles/main-website/pull/37.

-Sydney

**Comment by sydneyjd** [comment]
Closing, as I merged pull request almost a month ago.
