### ISSUE TITLE
Translatable level editor Menu/Items/Select and rest of Status Bar

### ISSUE THREAD

**Issue by xet7** [Secretchronicles/TSC#667]
Hi,
could following be made translatable:

## Level editor left
- [ ] Menu
- [ ] Items
- [ ] Select

## Level editor status bar
- [ ] Some texts that are still In English, like Brick Yellow in desert_ruins level

**Comment by Quintus** [comment]
Am 15. November 2019 um 23:25 Uhr -0800 schrieb Lauri Ojansivu:
> - [ ] Menu
> - [ ] Items
> - [ ] Select

These should be doable.

> - [ ] Some texts that are still In English, like Brick Yellow in
> desert_ruins level

This is not translatable. It's the file name of the sprite's graphic.

-- 
Blog: https://mg.guelker.eu

**Comment by Quintus** [comment]
Actually, it looks like I can make the editor's left menu mostly translatable with a small trick (unused string values that get picked up by xgettext(1)).
