### ISSUE TITLE
Make title menu translatable

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#669]
Currently, the title screen menu (also known as the main menu) is not translatable, because it's entirely made up of images. Making it translatable means replacing the images by native CEGUI text.

I have done some work on this in the `translatable-main-menu` branch, but this turns out to be very laborous due to a number of problems:

* CEGUI does not allow to draw a border around glyphs. This can only be imitated by placing a slightly larger version of the text label behind the actual label.
* CEGUI does not support the glossy 3D effect we have on the letters at all.
* CEGUI does not support the glowing effect natively. It can probably be imitiated by fiddling with the `TextColours` property, but this requires completely manual calculation of all colour components and thus is lots of work.
* CEGUI does not support zooming. The grow/shrink effect that signals the selection currently cannot be implemented with CEGUI thus. Also, CEGUI's font support is clunky at best. It's not possible to just increase the font size. Each and every font size needs a whole new XML config file for CEGUI (likewise for bold, italic, etc.).
* CEGUI supports images inside `StaticText` windows, but they look crappy when compared to the images currently shown next to a selected menu item.

That being said, all of this is probably demanding much from a GUI system. I doubt there's any lightweight GUI system that would allow all of this. The other alternative to implementing the menu with CEGUI is to stay with the pictures, but develop them into a real bitmap font, i.e. instead of complete pictures for each menu item we would need pictures for every letter in all alphabets TSC may ever be translated into. This does not sound doable either, not to mention we don't even have an artist who could do that.

Third option: Do away with our current title menu and implement it entirely differently in a way that does not require all these fancy effects.

In total, I don't think I am going to touch the main menu for 2.1.0 any further.

Ideas welcome. /cc @xet7 (to make him aware of this problem)

**Comment by xet7** [comment]
Main menu is not so important currently, because those English words are so familiar to most people, and with those English ones it's also easy enough to navigate to language change options. Making those translatable wound need too much work.

Level Editor Menu/Items/Select #667 is more important, because it's easier to change.

**Comment by Quintus** [comment]
I agree with you, but that it's not as important as the level editor's menu does not mean that it wouldn't be nice to have. Thus this ticket should stay open.

**Comment by datahead8888** [comment]
We should probably eventually move toward having our own effects/style for the menu in order to be distinct from SMC, which can work with the idea of being translatable.  We could look to OpenGL for additional effects, though we will have issues with pixelation if we just enlarge images for zooming.

**Comment by Quintus** [comment]
> We should probably eventually move toward having our own effects/style for the menu in order to be distinct from SMC, which can work with the idea of being translatable

I agree. These colourful menu items don't fit the more serious approach our game title follows. Changing the main menu to use our own style can be combined with making it translatable. I am going to open a new ticket for that and close this one.

**Comment by Quintus** [comment]
Superseded by #676.
