### ISSUE TITLE
Error CMAKE: Missing tinyclipboard and pod-parser

### ISSUE THREAD

**Issue by penguin21** [Secretchronicles/TSC#677]
Hi, I have problems in the cmake when trying to compile the game, which says that there are no tinyclipboard and pod-parser dependencies. Please, can you fix this?

Code Log:
```
fatal: not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
fatal: not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1")
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Searching for SFML audio library
--   found: /usr/lib/x86_64-linux-gnu/libsfml-audio.so
-- Searching for SFML graphics library
--   found: /usr/lib/x86_64-linux-gnu/libsfml-graphics.so
-- Searching for SFML window library
--   found: /usr/lib/x86_64-linux-gnu/libsfml-window.so
-- Searching for SFML system library
--   found: /usr/lib/x86_64-linux-gnu/libsfml-system.so
-- Found SFML: /usr/include/SFML
-- Searching for Base CEGUI library
--   found: /usr/lib/libCEGUIBase-0.so
-- Searching for CoreWindowRendererSet CEGUI library
--   found: /usr/lib/cegui-0.8/libCEGUICoreWindowRendererSet.so
-- Searching for DevILImageCodec CEGUI library
--   found: /usr/lib/cegui-0.8/libCEGUIDevILImageCodec.so
-- Searching for LibXMLParser CEGUI library
--   found: /usr/lib/cegui-0.8/libCEGUILibXMLParser.so
-- Searching for OpenGLRenderer CEGUI library
--   found: /usr/lib/libCEGUIOpenGLRenderer-0.so
-- Found CEGUI: /usr/include/cegui-0.8.7
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.34")
-- Found PCRE: /usr/include
-- Found LibXmlPP: /usr/lib/x86_64-linux-gnu/libxml++-2.6.so (found suitable version "2.40.1", minimum required is "2.6")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   filesystem
--   chrono
--   thread
--   system
--   date_time
--   atomic
-- Building tinyclipboard statically
-- Building pod-cpp statically
-- Scripting engine enabled: building mruby statically
-- Found BISON: /usr/bin/bison (found version "3.0.4")
-- Found Ruby: /usr/bin/ruby
-- --------------- Build info summary ----------------
-- TSC version:    2.1.1dev
-- Build type:     Debug
-- --------------- Configuration summary -------------
-- Enable native language support:    ON
-- Enable the scripting API docs:     ON
-- Use system-provided tinyclipboard: OFF
-- Use system-provided pod-cpp:       OFF
-- Use system-provided mruby:         OFF
-- --------------- Path configuration -----------------
-- Install prefix:        /mnt/c/Users/pepes/Documents/TSC-devel/tsc/tsc
-- Binary directory:      bin
-- Shared data directory: share
-- Manpage directory:     share/man
-- (relative pathes are relative to the install prefix;
-- the directory /tsc will be appended to the shared
-- data directory indicated above.)
-- ----------------------------------------------------
-- Configuring done
CMake Error at cmake/modules/ProvideTinyclipboard.cmake:7 (add_library):
  Cannot find source file:

    /mnt/c/Users/pepes/Documents/TSC-devel/tinyclipboard/src/tinyclipboard.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  CMakeLists.txt:125 (include)


CMake Error at cmake/modules/ProvidePodParser.cmake:7 (add_library):
  Cannot find source file:

    /mnt/c/Users/pepes/Documents/TSC-devel/pod-parser/pod.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  CMakeLists.txt:126 (include)


CMake Error: Cannot determine link language for target "tinyclipboard".
CMake Error: CMake can not determine linker language for target: tinyclipboard
CMake Error: Cannot determine link language for target "podparser".
CMake Error: CMake can not determine linker language for target: podparser
-- Generating done
-- Build files have been written to: /mnt/c/Users/pepes/Documents/TSC-devel/tsc/build
Scanning dependencies of target pofiles_1
[  0%] Generating de.gmo
[  1%] Generating el.gmo
[  1%] Generating es.gmo
[  2%] Generating fi_FI.gmo
[  2%] Generating fr.gmo
[  3%] Generating hu.gmo
[  3%] Generating it.gmo
[  4%] Generating nl.gmo
[  4%] Generating nn.gmo
[  5%] Generating pl.gmo
[  5%] Generating pt_BR.gmo
[  6%] Generating ru.gmo
[  6%] Generating tr.gmo
[  7%] Generating zh_TW.gmo
[  7%] Built target pofiles_1
Scanning dependencies of target tinyclipboard
make[2]: *** No rule to make target 'CMakeFiles/tinyclipboard.dir/build'.  Stop.
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/tinyclipboard.dir/all' failed
make[1]: *** [CMakeFiles/tinyclipboard.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
[  7%] Built target pofiles_1
make[2]: *** No rule to make target 'CMakeFiles/tinyclipboard.dir/build'.  Stop.
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/tinyclipboard.dir/all' failed
make[1]: *** [CMakeFiles/tinyclipboard.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
You can now run TSC with ./run-tsc.sh
```

**Comment by Quintus** [comment]
You need to run

  $ git submodule init
  $ git submodule update

before you start the compilation process. TSC uses Git submodules.
Please execute those commands, wipe the build directory, and then retry
the compilation.

  -quintus

-- 
Blog: https://mg.guelker.eu

**Comment by penguin21** [comment]
In the makefile disable the docs scripts,
but I was not allowed to download those gits for example the podparser entered the page and I get that there is no git page.
https://git.guelker.eu/pod-cpp/

**Comment by Quintus** [comment]
Am 12. Februar 2020 um 03:59 Uhr -0800 schrieb penguin21:
>In the makefile disable the docs scripts,
>but I was not allowed to download those gits for example the podparser entered the page and I get that there is no git page.
>https://git.guelker.eu/pod-cpp/

This won't work -- there's no HTTPS serve for this server. You need 
to use the git:// URL:

  $ git clone git://git.guelker.eu/pod-cpp.git
  Cloning into 'pod-cpp'...
  remote: Objekte aufzählen: 135, Fertig.
  remote: Zähle Objekte: 100% (135/135), Fertig.
  remote: Komprimiere Objekte: 100% (134/134), Fertig.
  remote: Gesamt 135 (Delta 66), Wiederverwendet 0 (Delta 0)
  Receiving objects: 100% (135/135), 39.84 KiB | 627.00 KiB/s, done.
  Resolving deltas: 100% (66/66), done.

Likewise for tinyclipboard. It would certainly be easier if you just 
used $ git submodule as documented rather than trying to do it manually. 
The submodules are set up to use the correct URLs.

If you don't want the script docs, disable them by passing 
`-DENABLE_SCRIPT_DOCS=OFF` to CMake. It won't help you, though, because 
tinyclipboard has nothing to do with the docs and is a required 
dependency of TSC.

  -quintus

-- 
Blog: https://mg.guelker.eu

**Comment by penguin21** [comment]
I start ubuntu to compile it for windows, and I get this.

```
pepe@pepe-PepePC:~/tsc-cross/mxe$ make boost libxml++ glew cegui libpn
[using autodetected 6 job(s)]
[check requirements]
Missing requirement: openssl

Please have a look at "index.html" to ensure
that your system meets all requirements.

make: *** [Makefile:371: /home/pepe/tsc-cross/mxe/usr/installed/check-requirements] Error 1
```

Already having the openssl installed

**Comment by xet7** [comment]
@penguin21 

# Linux

For Ubuntu 18.04 and Linux Mint and newer, TSC is compiled and run this way, running these commands in Linux:
```
git clone https://github.com/Secretchronicles/TSC.git
cd TSC
./install-build-dependencies.sh
./build-tsc.sh
./run-tsc.sh
```
Here in build.txt is how .deb packages have been made:
https://ftp.secretchronicles.org/build-deb/

# Windows

Windows installer packages are created in Windows using MSYS2:
https://github.com/Secretchronicles/TSC/blob/devel/INSTALL.md#vii-compiling-on-windows-with-msys2

**Comment by Quintus** [comment]
Crosscompilation from Linux to Windows is not supported anymore since 
quite a while. The INSTALL.md file was outdated in this regard. I have 
removed this outdated piece of documentation with commit 
a64678c1ba5e2a3e07f6c3441a58472753e4cefe. If you want to compile for 
Windows, you need to do it on Windows itself using MSYS2. The native 
compilation instructions for Windows in INSTALL.md should be correct 
(@xet7: Could you please re-check they're correct, and if not, update 
them?)

For compilation on Linuxes, INSTALL.md is otherwise correct and can be 
followed (you probably missed the `--recursive` option passed to `git 
pull`, which is the same as executing `git submodule init && git 
submodule update` after download). In addition to this, xet7 provides 
the build scripts he mentioned in his comment that fully automate the 
entire process if you want to be lazy.

@xet7: There is an error in the dependencies install script. Since we 
switched to `scrdg` for the scripting API documentation, any 
dependencies on RubyGems were dropped. You can safely remove that line 
from your script. Only ruby itself (including rake) are now needed 
still, for compiling mruby, and those two are provided by the ruby-full 
package.

@penguin21: I assume that you now managed to get copies of pod-cpp and 
tinyclipboard?

  -quintus

Am 12. Februar 2020 um 12:33 Uhr -0800 schrieb penguin21:
>I start ubuntu to compile it for windows, and I get this.
>
>```
>pepe@pepe-PepePC:~/tsc-cross/mxe$ make boost libxml++ glew cegui libpn
>[using autodetected 6 job(s)]
>[check requirements]
>Missing requirement: openssl
>
>Please have a look at "index.html" to ensure
>that your system meets all requirements.
>
>make: *** [Makefile:371: /home/pepe/tsc-cross/mxe/usr/installed/check-requirements] Error 1
>```
>
>Already having the openssl installed
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Secretchronicles/TSC/issues/677#issuecomment-585404493

-- 
Blog: https://mg.guelker.eu

**Comment by Quintus** [comment]
>you probably missed the `--recursive` option passed to `git pull`

git pull -> git clone

Please excuse the typographic error.

  -quintus

-- 
Blog: https://mg.guelker.eu

**Comment by penguin21** [comment]
The cmake command does not exist in the msys. What do I do now?

```
$ cmake -G "MSYS Makefiles" ..
-bash: cmake: no se encontró la orden

```

**Comment by xet7** [comment]
@penguin21 

Try:
```
pacman -S cmake
```

**Comment by penguin21** [comment]
And now to try this command:

```
Pepe@DESKTOP-A6GIOH6 MSYS ~/TSC/tsc/build
$ cmake -G "MSYS Makefiles" ..
CMake Error: Could not create named generator MSYS Makefiles

Generators
* Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
```

Edit:
In the name of the generator I put Unix Generator instead of MSYS Makefiles and I get this:

```
Pepe@DESKTOP-A6GIOH6 MSYS ~/TSC/tsc/build
$ cmake -G "Unix Makefiles" ..
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:19 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:19 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/Pepe/TSC/tsc/build/CMakeFiles/CMakeOutput.log".
See also "/home/Pepe/TSC/tsc/build/CMakeFiles/CMakeError.log".
```

**Comment by xet7** [comment]
@penguin21 

You need to install all dependencies for 32bit and 64bit builds.

**Comment by penguin21** [comment]
> @penguin21
> 
> You need to install all dependencies for 32bit and 64bit builds.

What dependencies did I all use these two commands:
```
pacman -S --needed git base-devel bison ruby mingw-w64-x86_64-{toolchain,extra-cmake-modules,ruby,cegui,sfml,libxml++2.6,gperf}
pacman -S --needed git base-devel bison ruby mingw-w64-i686-{toolchain,extra-cmake-modules,ruby,cegui,sfml,libxml++2.6,gperf}
```

And when I give it again the command gives me the same error again.

**Comment by xet7** [comment]
You also need all other optional and gui deps:
```
pacman -S --needed mingw-w64-x86_64-{doxygen,graphviz,nsis}
pacman -S --needed mingw-w64-i686-{doxygen,graphviz,nsis,minizip-git}
pacman -S mingw-w64-x86_64-qt5
```

**Comment by penguin21** [comment]
> You also need all other optional and gui deps:
> 
> ```
> pacman -S --needed mingw-w64-x86_64-{doxygen,graphviz,nsis}
> pacman -S --needed mingw-w64-i686-{doxygen,graphviz,nsis,minizip-git}
> pacman -S mingw-w64-x86_64-qt5
> ```

I have all the dependencies and nothing. The same mistake.
I don't know what happens to line 19 if it's okay and the directory `cmake/modules` is there

**Comment by xet7** [comment]
@penguin21 

If you have something old in build directory, you need to delete those, and then generate Makefiles etc again:
```
cd TSC/tsc/build
rm -rf *
```

**Comment by penguin21** [comment]
Update: DW, I was the dumbest man I am had to have run `mingw64.exe` instead of `msys2.exe` and have done the cmake from there.
The install.md file said it but it did not literally say it is like saying run `cmd.exe` for example.

Still not working, the problem is that the CMAKE_C_COMPILER generator does not exist.
Please look for a way to get that error removed.

**Comment by xet7** [comment]
1. MSYS2 should be downloaded from https://www.msys2.org , with filename msys2-x86_64-20190524.exe .

2. In Windows Start menu click MSYS2 64bit / MSYS2 MinGW 64bit.

3. Then using that MSYS2 shell, you need to delete TSC repo, because you probably cloned it with non-MSYS git that does not work when building TSC:
```
rm -rf TSC
```
4. Install all dependencies.

5. Clone repo and create build directory:
```
git clone https://github.com/Secretchronicles/TSC.git
cd TSC/tsc
mkdir build
cd build
```
6. Generate makefiles etc build package.

7. Copy setup package to your Downloads directory:
```
cp *.exe c:/Users/YOURUSERNAME/Downloads/
```
8. For 32bit version of TSC, at build directory do `rm -rf *`

9. In Windows Start menu click MSYS2 64bit / MSYS2 MinGW 32bit.

10. Do steps 6-7 from above.

**Comment by xet7** [comment]
When I tried steps above on Windows 10, it did create installer file `TSC-2.1.0-win64.exe` to build directory, and that installer works.

**Comment by xet7** [comment]
I used all those steps of generating makefiles etc and `make package`, but not `make install` because I did not need to install game directly. I only wanted to create installer package.
