### ISSUE TITLE
Ubuntu package issue

### ISSUE THREAD

**Issue by agrr** [Secretchronicles/TSC#683]
Hello,

tried to install version 2.1.0 RC2 on Ubuntu 20.04 with the suggested command:
``
sudo apt install ./TSC-2.1.0+packagename.deb
``
and there's a missing dependency: libboost-chrono1.71

After manually installing that package the game runs correctly, you should add the dependency at the package metadata level so that apt installer can pick it up.

Thanks

**Comment by Quintus** [comment]
Thank you for finding this!

/cc @xet7
