### ISSUE TITLE
Reset Progress Message Box Does Not Respond to Game Controller Input

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#686]
Play a level individually using the game controller.
Finish the level.
You will return to the level selection menu.
Use the game controller to start the same level.
You will see a dialog about resetting your progress (which probably should not display at this point).
You cannot exit the dialog with the game controller.  You must either use the mouse or the keyboard.

**Comment by datahead8888** [comment]
It may be a bug, but it requires some discussion, as this is a level editing anomaly.

**Comment by Quintus** [comment]
I have reproduced and fixed the problem. This was the first time since ages that I played TSC with a gamepad.

**Comment by datahead8888** [comment]
Thanks for fixing this - it's good to see the game controller able to control everything.
If I see any more related bugs, I'll file new issues for another release.
