### ISSUE TITLE
License for artistic content

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#69]
Currently, artistic contributions to SMC underly a [quite broad license](http://www.secretmaryo.org/wiki/index.php?title=Legal_Notice_for_Contributions):

> Sending any contributions (else if explicitly described not as such) for this game on the Forum/Wiki/E-Mail is a tacit acceptance of the fact that you allow the Project Leader complete copyright. You maintain your own full rights to the contributions, and may continue to do whatever you wish to do with them.

For future contributions, I suggest to switch to a [creative commons license](https://creativecommons.org/licenses/), preferably [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).

Note this does *not* affect existing artistic material. That would remain under the existing license, although the old broad license might allow "the project leader" to relicense the work (due to the "complete copyright" clause). I don’t want to test this out, so I’d just say existing works stay under the old license, and new artistic works goes under CC-BY-SA.

Note that it is possible to license the graphics differently from the sourcecode, there is no requirement to have them GPL too (which would require publishing source files and the like of graphics, sounds, etc.). For a lengthy explanation on this, see [this forum thread](http://www.secretmaryo.org/phpBB3/viewtopic.php?f=1&t=9953).

Vale,
Quintus

**Comment by Bugsbane** [comment]
I'm fine with any of my assets being under CC-BY 4.0

**Comment by Quintus** [comment]
I am unsure why this issue is open still. We have settled on CC-BY 4.0 for quite a long time already. Closing.
