### ISSUE TITLE
Portable version [feature request]

### ISSUE THREAD

**Issue by donno2048** [Secretchronicles/TSC#692]

**Comment by xet7** [comment]
@donno2048 

For what operating system?

**Comment by donno2048** [comment]
Windows 10, oops...

**Comment by xet7** [comment]
@donno2048 

I think you can create portable version yourself this way:
1) Install TSC
2) Copy directory `C:\Program Files\TSC` to your USB stick
3) On another computer, insert USB stick
4) Run TSC directly from `TSC/bin/tsc.exe`

**Comment by xet7** [comment]
@donno2048 

Does it work with that way described above?

**Comment by donno2048** [comment]
Oh, so there is no additional installation?
I thought there is because there was no portable download on the site...
my mistake

**Comment by xet7** [comment]
I think installer is only for getting TSC icon to Start menu. For portable version, icon at Start menu is not required.

**Comment by donno2048** [comment]
Thanks!
