### ISSUE TITLE
mruby build fails

### ISSUE THREAD

**Issue by rezso** [Secretchronicles/TSC#694]
The build fails with https://github.com/mruby/mruby/commit/a639a39883f95365e8f336cd4770c06f3d9aa87a:

FAILED: CMakeFiles/tsc.dir/src/audio/random_sound.cpp.o 
/usr/lib/ccache/c++ -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -I. -I/usr/include/SFML -I/usr/include/libxml++-3.0 -I/usr/include/glibmm-2.4 -I/usr/lib/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libxml++-3.0/include -I../../tinyclipboard/include -I../../pod-parser -I/usr/include/cegui-0 -I../../mruby/mruby/include -O2 -DNDEBUG -Wall -Wno-deprecated-declarations -std=c++11 -MD -MT CMakeFiles/tsc.dir/src/audio/random_sound.cpp.o -MF CMakeFiles/tsc.dir/src/audio/random_sound.cpp.o.d -o CMakeFiles/tsc.dir/src/audio/random_sound.cpp.o -c ../src/audio/random_sound.cpp
In file included from ../../mruby/mruby/include/mruby/presym.h:15,
                 from ../../mruby/mruby/include/mruby.h:1412,
                 from ../src/audio/../audio/../core/global_basic.hpp:133,
                 from ../src/audio/../audio/random_sound.hpp:20,
                 from ../src/audio/random_sound.cpp:17:
../../mruby/mruby/include/mruby/presym/enable.h:15:11: fatal error: mruby/presym.inc: No such file or directory
   15 | # include <mruby/presym.inc>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
[31/198] Building CXX object CMakeFiles/tsc.dir/src/audio/audio.cpp.o
FAILED: CMakeFiles/tsc.dir/src/audio/audio.cpp.o 
/usr/lib/ccache/c++ -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -I. -I/usr/include/SFML -I/usr/include/libxml++-3.0 -I/usr/include/glibmm-2.4 -I/usr/lib/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libxml++-3.0/include -I../../tinyclipboard/include -I../../pod-parser -I/usr/include/cegui-0 -I../../mruby/mruby/include -O2 -DNDEBUG -Wall -Wno-deprecated-declarations -std=c++11 -MD -MT CMakeFiles/tsc.dir/src/audio/audio.cpp.o -MF CMakeFiles/tsc.dir/src/audio/audio.cpp.o.d -o CMakeFiles/tsc.dir/src/audio/audio.cpp.o -c ../src/audio/audio.cpp
In file included from ../../mruby/mruby/include/mruby/presym.h:15,
                 from ../../mruby/mruby/include/mruby.h:1412,
                 from ../src/audio/../audio/../core/global_basic.hpp:133,
                 from ../src/audio/../audio/audio.hpp:22,
                 from ../src/audio/audio.cpp:17:
../../mruby/mruby/include/mruby/presym/enable.h:15:11: fatal error: mruby/presym.inc: No such file or directory
   15 | # include <mruby/presym.inc>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
[32/198] Building CXX object CMakeFiles/tsc.dir/src/audio/sound_manager.cpp.o
FAILED: CMakeFiles/tsc.dir/src/audio/sound_manager.cpp.o 
/usr/lib/ccache/c++ -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -I. -I/usr/include/SFML -I/usr/include/libxml++-3.0 -I/usr/include/glibmm-2.4 -I/usr/lib/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libxml++-3.0/include -I../../tinyclipboard/include -I../../pod-parser -I/usr/include/cegui-0 -I../../mruby/mruby/include -O2 -DNDEBUG -Wall -Wno-deprecated-declarations -std=c++11 -MD -MT CMakeFiles/tsc.dir/src/audio/sound_manager.cpp.o -MF CMakeFiles/tsc.dir/src/audio/sound_manager.cpp.o.d -o CMakeFiles/tsc.dir/src/audio/sound_manager.cpp.o -c ../src/audio/sound_manager.cpp
In file included from ../../mruby/mruby/include/mruby/presym.h:15,
                 from ../../mruby/mruby/include/mruby.h:1412,
                 from ../src/audio/../core/../core/global_basic.hpp:133,
                 from ../src/audio/../core/property_helper.hpp:20,
                 from ../src/audio/sound_manager.cpp:17:
../../mruby/mruby/include/mruby/presym/enable.h:15:11: fatal error: mruby/presym.inc: No such file or directory
   15 | # include <mruby/presym.inc>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
[33/198] Building CXX object CMakeFiles/tsc.dir/src/campaign/campaign_loader.cpp.o
FAILED: CMakeFiles/tsc.dir/src/campaign/campaign_loader.cpp.o 
/usr/lib/ccache/c++ -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -I. -I/usr/include/SFML -I/usr/include/libxml++-3.0 -I/usr/include/glibmm-2.4 -I/usr/lib/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libxml++-3.0/include -I../../tinyclipboard/include -I../../pod-parser -I/usr/include/cegui-0 -I../../mruby/mruby/include -O2 -DNDEBUG -Wall -Wno-deprecated-declarations -std=c++11 -MD -MT CMakeFiles/tsc.dir/src/campaign/campaign_loader.cpp.o -MF CMakeFiles/tsc.dir/src/campaign/campaign_loader.cpp.o.d -o CMakeFiles/tsc.dir/src/campaign/campaign_loader.cpp.o -c ../src/campaign/campaign_loader.cpp
In file included from ../../mruby/mruby/include/mruby/presym.h:15,
                 from ../../mruby/mruby/include/mruby.h:1412,
                 from ../src/campaign/../core/global_basic.hpp:133,
                 from ../src/campaign/../core/global_game.hpp:19,
                 from ../src/campaign/campaign_loader.hpp:18,
                 from ../src/campaign/campaign_loader.cpp:16:
../../mruby/mruby/include/mruby/presym/enable.h:15:11: fatal error: mruby/presym.inc: No such file or directory
   15 | # include <mruby/presym.inc>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.

With previously used mruby (https://github.com/mruby/mruby/commit/1c09046):

FAILED: mruby-prefix/src/mruby-stamp/mruby-build mruby/build/host/lib/libmruby.a mruby/build/host/lib/libmruby_core.a 
cd /var/uhubuild/work/compile/tsc/build/mruby && ./minirake MRUBY_CONFIG=/var/uhubuild/work/compile/tsc/mruby_tsc_build_config.rb TSC_BUILD_TYPE=\"Release\" && /usr/bin/cmake -E touch /var/uhubuild/work/compile/tsc/build/mruby-prefix/src/mruby-stamp/mruby-build
(in /var/uhubuild/work/compile/tsc/build/mruby)
rake aborted!
wrong number of arguments (given 2, expected 1)
Rakefile:40:in `<top (required)>'

Maybe this caused by the ruby 3.0.0 on the system?

**Comment by xet7** [comment]
@rezso 

What operating system version you are using?

Did you use scripts at TSC repo root directory to install dependencies and then build TSC ?

**Comment by rezso** [comment]
Okay, with https://github.com/mruby/mruby/commit/1a9bdfcde5fd7c91e756747ba0565f29385115a7 (release 2.1.2) the build works fine :)

My "script" for build:

if [ -d .git ]; then
    git submodule update --init --recursive
else
    git clone https://github.com/Secretchronicles/tinyclipboard.git tinyclipboard
    git clone https://github.com/Secretchronicles/pod-parser.git pod-parser
    git clone https://github.com/mruby/mruby.git mruby/mruby
    cd mruby/mruby
    git checkout 1a9bdfc
    cd ../../
fi

cd tsc
ub_compile \
	-DUSE_LIBXMLPP3=ON
	
(the ub_compile is a helper script, wich is calls cmake with some default options:  -GNinja  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/usr" )

**Comment by Quintus** [comment]
Errm, we ship mruby in a submodule ourselves. If you use any other version of mruby, you're on your own -- we cannot officially support this. To get a copy of TSC's repository with all submodules checked out, simply use

~~~~
$ git clone --recursive git://github.com/Secretchronicles/TSC.git
~~~~

This will pull in all submodules and there is no need to issue any other Git commands. Please refer to [our INSTALL.md file](https://github.com/Secretchronicles/TSC/blob/devel/INSTALL.md#iv-installing-from-git).

Closing.

**Comment by rezso** [comment]
Just three notes:
1. I compile TSC from release tarball. In this case the recursive git clone from the TSC source not works, because the release tarball not contains the .git directory.
2. My 3 git clone commands is equal with recursive clone.
3. recursive clone will download dependencies with the latest commit. I tried this in first run, the .gitmodules or  your source tree on this repo doesn't contains any recommended commit hash (like with pod-parser and tinyclipboard), so I must try to find the working commit.
But I compiled TSC now, so not a big problem...

**Comment by Quintus** [comment]
Am 14. Januar 2021 um 10:37 Uhr -0800 schrieb rezso:
> Just three notes:
> 1. I compile TSC from release tarball. In this case the recursive git clone from the TSC source not works, because the release tarball not contains the .git directory.

The release tarball does not need the .git directory because it
contains a complete checkout of mruby (and the other git submodules).
If you compile from the release tarball, no Git command is needed at
all.

> 2. My 3 git clone commands is equal with recursive clone.

With this you're actually right. I apologise; I just saw that you
linked to a specific commit of mruby and inferred you want to use that
one instead of our targetted one.

> 3. recursive clone will download dependencies with the latest
>    commit. I tried this in first run, the .gitmodules or your source
>    tree on this repo doesn't contains any recommended commit hash
>    (like with pod-parser and tinyclipboard), so I must try to find
>    the working commit.

I am not sure what you mean. See:

    $ git log -n1 mruby/mruby/
    commit 513c43799ad932b044bb2a4d2d367fd052b7b7e7
    Author: Marvin Gülker <m-guelker@phoenixmail.de>
    Date:   Sun Mar 10 19:46:28 2019 +0100

        Update mruby to 2.0.0.

        Note: Any level that uses TSC.require crashes with this commit.

Commit 513c43799ad932b044bb2a4d2d367fd052b7b7e7 sets several commit
hashes for subprojects. And as far as I know, recursive cloning should
honour that recorded hash, unless you changed something in your Git
configuration to not do that.

  -quintus

-- 
Dipl.-Jur. M. Gülker | https://mg.guelker.eu | PGP: Siehe Webseite
Passau, Deutschland  | kontakt@guelker.eu    | O<

**Comment by Quintus** [comment]
~~~~
[0 09:05:37 quintus@atlantis] ~/tmp
$ git clone --recursive git://github.com/Secretchronicles/TSC.git
Cloning into 'TSC'...
remote: Enumerating objects: 670, done.
remote: Counting objects: 100% (670/670), done.
remote: Compressing objects: 100% (562/562), done.
remote: Total 37344 (delta 318), reused 237 (delta 107), pack-reused 36674
Receiving objects: 100% (37344/37344), 444.14 MiB | 5.78 MiB/s, done.
Resolving deltas: 100% (25276/25276), done.
Checking out files: 100% (3440/3440), done.
Submodule 'flatpak/shared-modules' (https://github.com/flathub/shared-modules) registered for path 'flatpak/shared-modules'
Submodule 'mruby/mruby' (https://github.com/mruby/mruby.git) registered for path 'mruby/mruby'
Submodule 'pod-parser' (git://git.guelker.eu/pod-cpp.git) registered for path 'pod-parser'
Submodule 'tinyclipboard' (git://git.guelker.eu/tinyclipboard.git) registered for path 'tinyclipboard'
Cloning into '/home/quintus/tmp/TSC/flatpak/shared-modules'...
remote: Enumerating objects: 2, done.        
remote: Counting objects: 100% (2/2), done.        
remote: Compressing objects: 100% (2/2), done.        
remote: Total 757 (delta 0), reused 1 (delta 0), pack-reused 755        
Receiving objects: 100% (757/757), 156.49 KiB | 643.00 KiB/s, done.
Resolving deltas: 100% (391/391), done.
Cloning into '/home/quintus/tmp/TSC/tinyclipboard'...
remote: Objekte aufzählen: 48, Fertig.        
remote: Zähle Objekte: 100% (48/48), Fertig.        
remote: Komprimiere Objekte: 100% (42/42), Fertig.        
remote: Gesamt 48 (Delta 17), Wiederverwendet 0 (Delta 0)        
Receiving objects: 100% (48/48), 34.70 KiB | 1.08 MiB/s, done.
Resolving deltas: 100% (17/17), done.
Cloning into '/home/quintus/tmp/TSC/mruby/mruby'...
remote: Enumerating objects: 99, done.        
remote: Counting objects: 100% (99/99), done.        
remote: Compressing objects: 100% (65/65), done.        
remote: Total 60537 (delta 45), reused 60 (delta 26), pack-reused 60438        
Receiving objects: 100% (60537/60537), 15.65 MiB | 5.17 MiB/s, done.
Resolving deltas: 100% (37992/37992), done.
Cloning into '/home/quintus/tmp/TSC/pod-parser'...
remote: Objekte aufzählen: 135, Fertig.        
remote: Zähle Objekte: 100% (135/135), Fertig.        
remote: Komprimiere Objekte: 100% (134/134), Fertig.        
remote: Gesamt 135 (Delta 66), Wiederverwendet 0 (Delta 0)        
Receiving objects: 100% (135/135), 39.07 KiB | 563.00 KiB/s, done.
Resolving deltas: 100% (66/66), done.
Submodule path 'flatpak/shared-modules': checked out '27e7d67b60a30ffd2b807a4f3eb3f65b0e9df953'
Submodule path 'mruby/mruby': checked out '1c09046c13fc0a763583c6da0f1d350f6c41c4ca'
Submodule path 'pod-parser': checked out 'cea6b81c0635650ac1429b7d16892c1d12c35b72'
Submodule path 'tinyclipboard': checked out 'f38151e8f5143f5005ee8568d1de33f6365424e5'
~~~~

Note the last few lines. Which is exactly what it is supposed to check out. For mruby, it's commit `1c09046c13fc0a763583c6da0f1d350f6c41c4ca`. Which matches what I have on my local machine for TSC and what Git says has been recorded with TSC commit 513c43799ad932b044bb2a4d2d367fd052b7b7e7:

~~~~
$ git show 513c43799ad932b044bb2a4d2d367fd052b7b7e7 | grep -A 7 -- "--- a/mruby/mruby"
--- a/mruby/mruby
+++ b/mruby/mruby
@@ -1 +1 @@
-Subproject commit 023070a6396233974785a8fd5735b9380a884f27
+Subproject commit 1c09046c13fc0a763583c6da0f1d350f6c41c4ca
diff --git a/tsc/mruby_tsc_build_config.rb b/tsc/mruby_tsc_build_config.rb
index 89036831..5b4fcb9f 100644
--- a/tsc/mruby_tsc_build_config.rb
~~~~

Note: I've just pushed to the `devel` branch to revert a workaround we had while my personal Git server was down. But that hasn't changed anything with regard to the commit hashes and specifically mruby was not affected at all.

  -quintus
