### ISSUE TITLE
Missing releases

### ISSUE THREAD

**Issue by jhonny-oliveira** [Secretchronicles/TSC#700]
Hi!

It seems the latest releases went missing (release tab), could you please recreate them? I'm packaging TSC for Ubuntu and my watch file relies on the releases to detect new versions. I need at least the last release.

Thank you!
Jhonny Oliveira
https://xtradeb.net

**Comment by Quintus** [comment]
As far as I know, we have never used GitHub's release facility, so it's not the case that something "went" missing; it was never there. The releases are officially available from https://secretchronicles.org/en/download/ or alternatively from the Git checkout via tags. You can see the tags on GitHub here: https://github.com/Secretchronicles/TSC/tags

I don’t feel particularly drawn towards using a platform's functionality for something that we have a RSS-enabled blog for; it creates additional work and needs to be kept in sync. But I see how it is useful to you and unless @xet7 objects I think we can add it. The *official* source will however remain secretchronicles.org.

**Comment by jhonny-oliveira** [comment]
I'm quite sure it was there, otherwise I would have not been able to use it. Maybe, it was being generated automatically.
No matter, I will use the official source from now on.

Thank you!

**Comment by xet7** [comment]
@jhonny-oliveira 

For current packages, there is no automatic builds. When there are major updates, I build manually on each OS and CPU with these build scripts https://ftp.secretchronicles.org/build-deb/ with Release build option, similar to these commands:

```
git clone https://github.com/Secretchronicles/TSC
cd TSC
./install-build-dependencies.sh
./build-tsc.sh
```

Some more build info at https://github.com/Secretchronicles/TSC/blob/devel/INSTALL.md

Currently Flatpak is not tested or published to FlatHub yet.
