### ISSUE TITLE
publishing pkgbuild

### ISSUE THREAD

**Issue by somebody1234** [Secretchronicles/TSC#701]
given that there's an arch linux pkgbuild in-tree it'd be nice if there was, say, a github action that published it to the AUR every time it's updated

**Comment by xet7** [comment]
@somebody1234 

Currently all builds are done manually at each platform.

Does github actions support building for AUR and other platforms? Is there some example actions somewhere?

**Comment by xet7** [comment]
@somebody1234 

Where is that arch linux pkgbuild? URL? Because I don't know, I have newer used Arch Linux, and I have never built any Arch Linux packages.

**Comment by somebody1234** [comment]
@xet7 aur doesn't require building - the pkgbuild is essentially an install script. it is [here](https://github.com/Secretchronicles/TSC/blob/devel/tsc/extras/archlinux/PKGBUILD)

**Comment by somebody1234** [comment]
but to be fair, it's worth noting it doesn't seem to work for me - it's missing cegui as a dependency, but also it seems to require the `CEGUI_USE_EXPAT` flag which is enabled in neither the version currently on the AUR, nor the version here

(current `cegui` for arch seems to be missing libxml completely for some reason)

**Comment by xet7** [comment]
That pkgbuild has old link, ftp server is not active anymore. Current releases are here:
https://ftp.secretchronicles.org/releases/

**Comment by xet7** [comment]
I have built packages only for those platforms where all dependencies exists.

**Comment by somebody1234** [comment]
good catch... very odd considering it seems to have been last updated this year (in contrast to the one on the AUR which was last updated in 2018 yet uses the correct https server)

**Comment by somebody1234** [comment]
(and again note that the PKGBUILD is an install script, not a package, so it does not require building. and i believe all the dependencies exist; when i said `cegui` is missing as a dependency i meant it's not listed in the PKGBUILD as a dependency.)

**Comment by xet7** [comment]
I think current way to build separate packages for each distro release is too much. Sometime I'll maybe figure out how to publish AppImage or Flatpak.

**Comment by xet7** [comment]
Or Snap

**Comment by somebody1234** [comment]
however i did try building it and now there's a small issue:
```
rake aborted!
wrong number of arguments (given 2, expected 1)
```

not that important though... i can just try debugging this one myself

**Comment by somebody1234** [comment]
as for appimage/flatpak/snap... i feel like those may not be ideal given that they generally have sandboxing which is kinda weird?

i believe quite a lot of places build for some kind of generic linux target. not quite sure how they do that though

**Comment by xet7** [comment]
## Building for Linux

On supported Linux platforms building does work like this, for creating local debug build:
```
git clone https://github.com/Secretchronicles/TSC

cd TSC

./install-build-dependencies.sh

./build-tsc.sh
```
For releases, it uses compiler flag `Release` and other file paths, with these build scripts https://ftp.secretchronicles.org/build-deb/

## Building for Windows

https://github.com/Secretchronicles/TSC/blob/devel/INSTALL.md#vi-compiling-on-windows-with-msys2

## Building for Mac

Building only works on old macOS version where all dependencies exist, and there is a lot of manual steps, I have not gone through all steps yet. There is contributors prebuild binary maybe available, but because I have not built package myself yet, I can not include it at official TSC website yet:

https://github.com/Secretchronicles/TSC/issues/691

**Comment by somebody1234** [comment]
if this is in reply to the "building for some kind of generic linux target" part, no i meant they somehow produce a generic binary. maybe they're just ("just") statically linked

**Comment by xet7** [comment]
That generic binary target most likely is AppImage, that is one executeable file.

**Comment by xet7** [comment]
One AppImage works on most Linux distros on one CPU type, like amd64. It needs separate binary for other CPU, like arm64.

AFAIK Linux does not yet have multiarch binary package possibility like macOS does.

**Comment by somebody1234** [comment]
hmm... yea my bad - seems like most of the packages that provide generic linux releases seem to be in rust (which seems to be statically linked by default, which would explain it)

**Comment by somebody1234** [comment]
as for multiarch... not like there's any benefit tbh. i'd imagine you'd pretty much need twice the amount of code since the instruction sets are completely different... at which point it's probably easier to just make two separate binaries

**Comment by xet7** [comment]
@somebody1234 

Statically linking means, that all required libraries (like .so or .dll) and optionally all other files (like images, music, etc) are included in the same executeable file, and are loaded from that file when executing app.

Files could be appended to:

a) After end of executeable file

b) Archived to .zip file that is appended  to end of executeable file.

That executeable file can be coded for example with:

a) C like https://github.com/jart/cosmopolitan that can build console/web one binary that works at all x64 OS like Windows/Linux/macOS/FreeBSD/NetBSD/OpenBSD. But it does not yet work for graphical OpenGL apps like TSC. This is only one where same binary works at many OS.

b) C++ , like TSC

c) Rust

d) Python, where with Pop https://gitlab.com/saltstack/pop/pop one executeable file has Python, interpreted .py files etc

e) Tcl, where there is CPU/OS specific executeable tclkit built at http://kitcreator.rkeene.org/kitcreator , and then `app.kit` file that is like .zip file, those can be run separately like `tclkit-amd64.exe app.kit` and `tclkit-arm64.exe app.kit` or combined to one `app-amd64.exe` file. That `app.kit` archive also includes all .dll/.so files for each CPU platform, Tcl executeable binary, all .tcl textfiles that are interpreted on the fly, images, sounds, etc, can also have GUI made with Tk.

Multiarch would be huge win. Already Cosmopolitan can make same x64 executeable work on many OS. It is missing GUI (although webserver is possible for GUI), and multiarch. Having additionally GUI and multiarch added to same executeable would mean, that same executeable would work at any OS and any CPU, with only one download. Same executeable would contain:
- all CPU-specific executeables
- once all images, music, and other files

Downloads having only one file would be such a huge win, I would like to find out is it possible.

**Comment by Quintus** [comment]
There is a [tsc package on the AUR](https://aur.archlinux.org/packages/tsc/), but it is not maintained by anyone of us AFAIK. It's unofficial and that there is a PKGBUILD in the repository is a reminiscence of me using ArchLinux several years ago. It should be removed entirely.
