### ISSUE TITLE
debian 11 deb, missing dependency

### ISSUE THREAD

**Issue by ghost** [Secretchronicles/TSC#703]
it is missing this dependency `libboost-chrono1.74.0`

**Comment by ghost** [comment]
Probably the real flaw, is that it's the wrong version, it sais it's the dev version, but the file was labeled 2.1.0 .
```
This is The Secret Chronicles of Dr. M. version 2.1.1-dev.
 --- This is a DEVELOPMENT built! It may eat your hamster! ---
It was compiled from commit fa110e4.
```

it's indeed the file with sha256 142dbea3abee8f494e98d21d3fd84bf86ce24ea022521853a27e2057aadaffa3

**Comment by Quintus** [comment]
The deb file is made by @xet7, so I'll assign this to him.

**Comment by xet7** [comment]
@pirate486743186 @Quintus 

I have updated most Debian bullseye .deb packages today 04.09.2022 (2022-09-04):
- amd64
- i386
- arm64
- s390x

This link shows newest at top:
https://ftp.secretchronicles.org/releases/?sort=time&order=desc

I will later add ppc64le, and also Ubuntu 22.04 and Raspberry Pi OS packages, etc.

**Comment by xet7** [comment]
I will also later update website with those new md5 and sha256 hashes, that are already here:
https://ftp.secretchronicles.org/releases/?sort=time&order=desc

**Comment by xet7** [comment]
Released.

News In English:
https://secretchronicles.org/en/news/2022/09/04/tsc-for-jammy-and-bullseye-many-cpu-platforms-available/

News In Finnish:
https://secretchronicles.org/fi/news/2022/09/04/tsc-for-jammy-and-bullseye-many-cpu-platforms-available/
