### ISSUE TITLE
makedeb and mpr

### ISSUE THREAD

**Issue by ghost** [Secretchronicles/TSC#704]
there's makedeb, a fork of makepkg for deb packages and mpr, the equivalent of the AUR for PKGBUILTs for deb.

You might want to be the maintainers of a tsc PKGBUILD there.

makedeb https://docs.makedeb.org/installing/apt-repository/
mpr https://mpr.makedeb.org/

**Comment by Quintus** [comment]
Like I said in #705, we cannot support all possible third party tools. This places additional burden on us, so unless a volunteer appears to maintain such a file, I see no way to get this into TSC. Working with the code is enough work already.

Once upon a time, there was a TSC PKBUILD for the AUR, but it seems that TSC is not listed in the AUR anymore. Appearently the maintainer gave it up.

**Comment by ghost** [comment]
I was thinking that maybe @xet7 would be interested.
