### ISSUE TITLE
get-deb

### ISSUE THREAD

**Issue by ghost** [Secretchronicles/TSC#705]
get-deb is an apt-get like cli application, in order to search and install debs.
https://github.com/wimpysworld/deb-get

If you publish standard github releases, it will be very easy to have and maintain tsc in deb-get application list.

**Comment by Quintus** [comment]
We cannot support all possible 3rd party tools out there. I would rather see TSC being included into official Linux repositories.

**Comment by ghost** [comment]
What you need to do for this, it's simply to make github deb releases( github api) and don't change the format so that it can scrape the version number. The tool, has a function for github releases. If that ever breaks, the deb-get project will fix it. It will be harder to try and scrape the website (regex fun).

All that this tool does, is fetch the debs that upstream is providing. You just need to keep your releases easy for a dumb script to scrape. Don't change the format.... You already provide debs....

It should look like this:
https://github.com/vladimiry/ElectronMail/releases
