### ISSUE TITLE
Compiling fails with boost-1.85 (Linux / Gentoo)

### ISSUE THREAD

**Issue by bell07** [Secretchronicles/TSC#711]
Updated boost on my System to boost-1.85 and tried to recompile TSC for new library version.

The build fails with 
`
fatal error: boost/filesystem/convenience.hpp: No such file or directory`

Found next info in https://www.boost.org/users/history/version_1_85_0.html

> Removed APIs that were previously declared deprecated. In particular, path and recursive_directory_iterator member functions, is_regular, copy_directory, symbolic_link_exists, complete, copy_option, symlink_option, as well as boost/filesystem/convenience.hpp and boost/filesystem/path_traits.hpp headers were removed. Possible replacements for the removed components are mentioned in the documentation. 

Please update the sources for the new boost version

**Comment by Quintus** [comment]
Problem has been fixed. Please try again.

**Comment by bell07** [comment]
Confirm the fix solves my issue
